-- ==============================================================
-- Generated by Vitis HLS v2023.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject_relu_ap_fixed_32_6_5_3_0_ap_fixed_32_6_5_3_0_relu_config3_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    p_read : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read1 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read2 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read3 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read4 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read5 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read6 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read7 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read8 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read9 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read10 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read11 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read12 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read13 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read14 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read15 : IN STD_LOGIC_VECTOR (31 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (30 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (30 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (30 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (30 downto 0);
    ap_return_4 : OUT STD_LOGIC_VECTOR (30 downto 0);
    ap_return_5 : OUT STD_LOGIC_VECTOR (30 downto 0);
    ap_return_6 : OUT STD_LOGIC_VECTOR (30 downto 0);
    ap_return_7 : OUT STD_LOGIC_VECTOR (30 downto 0);
    ap_return_8 : OUT STD_LOGIC_VECTOR (30 downto 0);
    ap_return_9 : OUT STD_LOGIC_VECTOR (30 downto 0);
    ap_return_10 : OUT STD_LOGIC_VECTOR (30 downto 0);
    ap_return_11 : OUT STD_LOGIC_VECTOR (30 downto 0);
    ap_return_12 : OUT STD_LOGIC_VECTOR (30 downto 0);
    ap_return_13 : OUT STD_LOGIC_VECTOR (30 downto 0);
    ap_return_14 : OUT STD_LOGIC_VECTOR (30 downto 0);
    ap_return_15 : OUT STD_LOGIC_VECTOR (30 downto 0) );
end;


architecture behav of myproject_relu_ap_fixed_32_6_5_3_0_ap_fixed_32_6_5_3_0_relu_config3_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal p_read_65_reg_494 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal p_read_66_reg_499 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_read_67_reg_504 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_read_68_reg_509 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_read_69_reg_514 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_read1026_reg_519 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_read925_reg_524 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_read824_reg_529 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_read723_reg_534 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_read622_reg_539 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_read521_reg_544 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_read420_reg_549 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_read319_reg_554 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_read218_reg_559 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_read117_reg_564 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_read16_reg_569 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln42_fu_142_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal trunc_ln42_reg_574 : STD_LOGIC_VECTOR (30 downto 0);
    signal trunc_ln42_1_fu_146_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal trunc_ln42_1_reg_579 : STD_LOGIC_VECTOR (30 downto 0);
    signal trunc_ln42_2_fu_150_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal trunc_ln42_2_reg_584 : STD_LOGIC_VECTOR (30 downto 0);
    signal trunc_ln42_3_fu_154_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal trunc_ln42_3_reg_589 : STD_LOGIC_VECTOR (30 downto 0);
    signal trunc_ln42_4_fu_158_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal trunc_ln42_4_reg_594 : STD_LOGIC_VECTOR (30 downto 0);
    signal trunc_ln42_5_fu_162_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal trunc_ln42_5_reg_599 : STD_LOGIC_VECTOR (30 downto 0);
    signal trunc_ln42_6_fu_166_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal trunc_ln42_6_reg_604 : STD_LOGIC_VECTOR (30 downto 0);
    signal trunc_ln42_7_fu_170_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal trunc_ln42_7_reg_609 : STD_LOGIC_VECTOR (30 downto 0);
    signal trunc_ln42_8_fu_174_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal trunc_ln42_8_reg_614 : STD_LOGIC_VECTOR (30 downto 0);
    signal trunc_ln42_9_fu_178_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal trunc_ln42_9_reg_619 : STD_LOGIC_VECTOR (30 downto 0);
    signal trunc_ln42_10_fu_182_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal trunc_ln42_10_reg_624 : STD_LOGIC_VECTOR (30 downto 0);
    signal trunc_ln42_11_fu_186_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal trunc_ln42_11_reg_629 : STD_LOGIC_VECTOR (30 downto 0);
    signal trunc_ln42_12_fu_190_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal trunc_ln42_12_reg_634 : STD_LOGIC_VECTOR (30 downto 0);
    signal trunc_ln42_13_fu_194_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal trunc_ln42_13_reg_639 : STD_LOGIC_VECTOR (30 downto 0);
    signal trunc_ln42_14_fu_198_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal trunc_ln42_14_reg_644 : STD_LOGIC_VECTOR (30 downto 0);
    signal trunc_ln42_15_fu_202_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal trunc_ln42_15_reg_649 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal icmp_ln45_fu_206_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln45_1_fu_218_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln45_2_fu_230_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln45_3_fu_242_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln45_4_fu_254_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln45_5_fu_266_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln45_6_fu_278_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln45_7_fu_290_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln45_8_fu_302_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln45_9_fu_314_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln45_10_fu_326_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln45_11_fu_338_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln45_12_fu_350_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln45_13_fu_362_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln45_14_fu_374_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln45_15_fu_386_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal datareg_fu_211_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal datareg_1_fu_223_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal datareg_2_fu_235_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal datareg_3_fu_247_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal datareg_4_fu_259_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal datareg_5_fu_271_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal datareg_6_fu_283_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal datareg_7_fu_295_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal datareg_8_fu_307_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal datareg_9_fu_319_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal datareg_10_fu_331_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal datareg_11_fu_343_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal datareg_12_fu_355_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal datareg_13_fu_367_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal datareg_14_fu_379_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal datareg_15_fu_391_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_return_0_preg : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    signal ap_return_1_preg : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    signal ap_return_2_preg : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    signal ap_return_3_preg : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    signal ap_return_4_preg : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    signal ap_return_5_preg : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    signal ap_return_6_preg : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    signal ap_return_7_preg : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    signal ap_return_8_preg : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    signal ap_return_9_preg : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    signal ap_return_10_preg : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    signal ap_return_11_preg : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    signal ap_return_12_preg : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    signal ap_return_13_preg : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    signal ap_return_14_preg : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    signal ap_return_15_preg : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_idle_pp0_0to0 : STD_LOGIC;
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start;
                end if; 
            end if;
        end if;
    end process;


    ap_return_0_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_0_preg <= ap_const_lv31_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_return_0_preg <= datareg_fu_211_p3;
                end if; 
            end if;
        end if;
    end process;


    ap_return_10_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_10_preg <= ap_const_lv31_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_return_10_preg <= datareg_10_fu_331_p3;
                end if; 
            end if;
        end if;
    end process;


    ap_return_11_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_11_preg <= ap_const_lv31_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_return_11_preg <= datareg_11_fu_343_p3;
                end if; 
            end if;
        end if;
    end process;


    ap_return_12_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_12_preg <= ap_const_lv31_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_return_12_preg <= datareg_12_fu_355_p3;
                end if; 
            end if;
        end if;
    end process;


    ap_return_13_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_13_preg <= ap_const_lv31_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_return_13_preg <= datareg_13_fu_367_p3;
                end if; 
            end if;
        end if;
    end process;


    ap_return_14_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_14_preg <= ap_const_lv31_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_return_14_preg <= datareg_14_fu_379_p3;
                end if; 
            end if;
        end if;
    end process;


    ap_return_15_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_15_preg <= ap_const_lv31_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_return_15_preg <= datareg_15_fu_391_p3;
                end if; 
            end if;
        end if;
    end process;


    ap_return_1_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_1_preg <= ap_const_lv31_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_return_1_preg <= datareg_1_fu_223_p3;
                end if; 
            end if;
        end if;
    end process;


    ap_return_2_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_2_preg <= ap_const_lv31_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_return_2_preg <= datareg_2_fu_235_p3;
                end if; 
            end if;
        end if;
    end process;


    ap_return_3_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_3_preg <= ap_const_lv31_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_return_3_preg <= datareg_3_fu_247_p3;
                end if; 
            end if;
        end if;
    end process;


    ap_return_4_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_4_preg <= ap_const_lv31_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_return_4_preg <= datareg_4_fu_259_p3;
                end if; 
            end if;
        end if;
    end process;


    ap_return_5_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_5_preg <= ap_const_lv31_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_return_5_preg <= datareg_5_fu_271_p3;
                end if; 
            end if;
        end if;
    end process;


    ap_return_6_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_6_preg <= ap_const_lv31_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_return_6_preg <= datareg_6_fu_283_p3;
                end if; 
            end if;
        end if;
    end process;


    ap_return_7_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_7_preg <= ap_const_lv31_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_return_7_preg <= datareg_7_fu_295_p3;
                end if; 
            end if;
        end if;
    end process;


    ap_return_8_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_8_preg <= ap_const_lv31_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_return_8_preg <= datareg_8_fu_307_p3;
                end if; 
            end if;
        end if;
    end process;


    ap_return_9_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_9_preg <= ap_const_lv31_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_return_9_preg <= datareg_9_fu_319_p3;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                p_read1026_reg_519 <= p_read10;
                p_read117_reg_564 <= p_read1;
                p_read16_reg_569 <= p_read;
                p_read218_reg_559 <= p_read2;
                p_read319_reg_554 <= p_read3;
                p_read420_reg_549 <= p_read4;
                p_read521_reg_544 <= p_read5;
                p_read622_reg_539 <= p_read6;
                p_read723_reg_534 <= p_read7;
                p_read824_reg_529 <= p_read8;
                p_read925_reg_524 <= p_read9;
                p_read_65_reg_494 <= p_read15;
                p_read_66_reg_499 <= p_read14;
                p_read_67_reg_504 <= p_read13;
                p_read_68_reg_509 <= p_read12;
                p_read_69_reg_514 <= p_read11;
                trunc_ln42_10_reg_624 <= trunc_ln42_10_fu_182_p1;
                trunc_ln42_11_reg_629 <= trunc_ln42_11_fu_186_p1;
                trunc_ln42_12_reg_634 <= trunc_ln42_12_fu_190_p1;
                trunc_ln42_13_reg_639 <= trunc_ln42_13_fu_194_p1;
                trunc_ln42_14_reg_644 <= trunc_ln42_14_fu_198_p1;
                trunc_ln42_15_reg_649 <= trunc_ln42_15_fu_202_p1;
                trunc_ln42_1_reg_579 <= trunc_ln42_1_fu_146_p1;
                trunc_ln42_2_reg_584 <= trunc_ln42_2_fu_150_p1;
                trunc_ln42_3_reg_589 <= trunc_ln42_3_fu_154_p1;
                trunc_ln42_4_reg_594 <= trunc_ln42_4_fu_158_p1;
                trunc_ln42_5_reg_599 <= trunc_ln42_5_fu_162_p1;
                trunc_ln42_6_reg_604 <= trunc_ln42_6_fu_166_p1;
                trunc_ln42_7_reg_609 <= trunc_ln42_7_fu_170_p1;
                trunc_ln42_8_reg_614 <= trunc_ln42_8_fu_174_p1;
                trunc_ln42_9_reg_619 <= trunc_ln42_9_fu_178_p1;
                trunc_ln42_reg_574 <= trunc_ln42_fu_142_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_reset_idle_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_done_reg = ap_const_logic_1) or ((ap_done_reg = ap_const_logic_1) and (ap_start = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_done_reg = ap_const_logic_1) or ((ap_done_reg = ap_const_logic_1) and (ap_start = ap_const_logic_1)));
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_done_reg)
    begin
                ap_block_state1_pp0_stage0_iter0 <= (ap_done_reg = ap_const_logic_1);
    end process;

        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_done_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_done_reg, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start;

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_idle_pp0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to0_assign_proc : process(ap_enable_reg_pp0_iter0)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_0)) then 
            ap_idle_pp0_0to0 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_reset_idle_pp0_assign_proc : process(ap_start, ap_idle_pp0_0to0)
    begin
        if (((ap_idle_pp0_0to0 = ap_const_logic_1) and (ap_start = ap_const_logic_0))) then 
            ap_reset_idle_pp0 <= ap_const_logic_1;
        else 
            ap_reset_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_return_0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, datareg_fu_211_p3, ap_return_0_preg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_return_0 <= datareg_fu_211_p3;
        else 
            ap_return_0 <= ap_return_0_preg;
        end if; 
    end process;


    ap_return_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, datareg_1_fu_223_p3, ap_return_1_preg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_return_1 <= datareg_1_fu_223_p3;
        else 
            ap_return_1 <= ap_return_1_preg;
        end if; 
    end process;


    ap_return_10_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, datareg_10_fu_331_p3, ap_return_10_preg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_return_10 <= datareg_10_fu_331_p3;
        else 
            ap_return_10 <= ap_return_10_preg;
        end if; 
    end process;


    ap_return_11_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, datareg_11_fu_343_p3, ap_return_11_preg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_return_11 <= datareg_11_fu_343_p3;
        else 
            ap_return_11 <= ap_return_11_preg;
        end if; 
    end process;


    ap_return_12_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, datareg_12_fu_355_p3, ap_return_12_preg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_return_12 <= datareg_12_fu_355_p3;
        else 
            ap_return_12 <= ap_return_12_preg;
        end if; 
    end process;


    ap_return_13_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, datareg_13_fu_367_p3, ap_return_13_preg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_return_13 <= datareg_13_fu_367_p3;
        else 
            ap_return_13 <= ap_return_13_preg;
        end if; 
    end process;


    ap_return_14_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, datareg_14_fu_379_p3, ap_return_14_preg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_return_14 <= datareg_14_fu_379_p3;
        else 
            ap_return_14 <= ap_return_14_preg;
        end if; 
    end process;


    ap_return_15_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, datareg_15_fu_391_p3, ap_return_15_preg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_return_15 <= datareg_15_fu_391_p3;
        else 
            ap_return_15 <= ap_return_15_preg;
        end if; 
    end process;


    ap_return_2_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, datareg_2_fu_235_p3, ap_return_2_preg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_return_2 <= datareg_2_fu_235_p3;
        else 
            ap_return_2 <= ap_return_2_preg;
        end if; 
    end process;


    ap_return_3_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, datareg_3_fu_247_p3, ap_return_3_preg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_return_3 <= datareg_3_fu_247_p3;
        else 
            ap_return_3 <= ap_return_3_preg;
        end if; 
    end process;


    ap_return_4_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, datareg_4_fu_259_p3, ap_return_4_preg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_return_4 <= datareg_4_fu_259_p3;
        else 
            ap_return_4 <= ap_return_4_preg;
        end if; 
    end process;


    ap_return_5_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, datareg_5_fu_271_p3, ap_return_5_preg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_return_5 <= datareg_5_fu_271_p3;
        else 
            ap_return_5 <= ap_return_5_preg;
        end if; 
    end process;


    ap_return_6_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, datareg_6_fu_283_p3, ap_return_6_preg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_return_6 <= datareg_6_fu_283_p3;
        else 
            ap_return_6 <= ap_return_6_preg;
        end if; 
    end process;


    ap_return_7_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, datareg_7_fu_295_p3, ap_return_7_preg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_return_7 <= datareg_7_fu_295_p3;
        else 
            ap_return_7 <= ap_return_7_preg;
        end if; 
    end process;


    ap_return_8_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, datareg_8_fu_307_p3, ap_return_8_preg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_return_8 <= datareg_8_fu_307_p3;
        else 
            ap_return_8 <= ap_return_8_preg;
        end if; 
    end process;


    ap_return_9_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, datareg_9_fu_319_p3, ap_return_9_preg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_return_9 <= datareg_9_fu_319_p3;
        else 
            ap_return_9 <= ap_return_9_preg;
        end if; 
    end process;

    datareg_10_fu_331_p3 <= 
        trunc_ln42_10_reg_624 when (icmp_ln45_10_fu_326_p2(0) = '1') else 
        ap_const_lv31_0;
    datareg_11_fu_343_p3 <= 
        trunc_ln42_11_reg_629 when (icmp_ln45_11_fu_338_p2(0) = '1') else 
        ap_const_lv31_0;
    datareg_12_fu_355_p3 <= 
        trunc_ln42_12_reg_634 when (icmp_ln45_12_fu_350_p2(0) = '1') else 
        ap_const_lv31_0;
    datareg_13_fu_367_p3 <= 
        trunc_ln42_13_reg_639 when (icmp_ln45_13_fu_362_p2(0) = '1') else 
        ap_const_lv31_0;
    datareg_14_fu_379_p3 <= 
        trunc_ln42_14_reg_644 when (icmp_ln45_14_fu_374_p2(0) = '1') else 
        ap_const_lv31_0;
    datareg_15_fu_391_p3 <= 
        trunc_ln42_15_reg_649 when (icmp_ln45_15_fu_386_p2(0) = '1') else 
        ap_const_lv31_0;
    datareg_1_fu_223_p3 <= 
        trunc_ln42_1_reg_579 when (icmp_ln45_1_fu_218_p2(0) = '1') else 
        ap_const_lv31_0;
    datareg_2_fu_235_p3 <= 
        trunc_ln42_2_reg_584 when (icmp_ln45_2_fu_230_p2(0) = '1') else 
        ap_const_lv31_0;
    datareg_3_fu_247_p3 <= 
        trunc_ln42_3_reg_589 when (icmp_ln45_3_fu_242_p2(0) = '1') else 
        ap_const_lv31_0;
    datareg_4_fu_259_p3 <= 
        trunc_ln42_4_reg_594 when (icmp_ln45_4_fu_254_p2(0) = '1') else 
        ap_const_lv31_0;
    datareg_5_fu_271_p3 <= 
        trunc_ln42_5_reg_599 when (icmp_ln45_5_fu_266_p2(0) = '1') else 
        ap_const_lv31_0;
    datareg_6_fu_283_p3 <= 
        trunc_ln42_6_reg_604 when (icmp_ln45_6_fu_278_p2(0) = '1') else 
        ap_const_lv31_0;
    datareg_7_fu_295_p3 <= 
        trunc_ln42_7_reg_609 when (icmp_ln45_7_fu_290_p2(0) = '1') else 
        ap_const_lv31_0;
    datareg_8_fu_307_p3 <= 
        trunc_ln42_8_reg_614 when (icmp_ln45_8_fu_302_p2(0) = '1') else 
        ap_const_lv31_0;
    datareg_9_fu_319_p3 <= 
        trunc_ln42_9_reg_619 when (icmp_ln45_9_fu_314_p2(0) = '1') else 
        ap_const_lv31_0;
    datareg_fu_211_p3 <= 
        trunc_ln42_reg_574 when (icmp_ln45_fu_206_p2(0) = '1') else 
        ap_const_lv31_0;
    icmp_ln45_10_fu_326_p2 <= "1" when (signed(p_read1026_reg_519) > signed(ap_const_lv32_0)) else "0";
    icmp_ln45_11_fu_338_p2 <= "1" when (signed(p_read_69_reg_514) > signed(ap_const_lv32_0)) else "0";
    icmp_ln45_12_fu_350_p2 <= "1" when (signed(p_read_68_reg_509) > signed(ap_const_lv32_0)) else "0";
    icmp_ln45_13_fu_362_p2 <= "1" when (signed(p_read_67_reg_504) > signed(ap_const_lv32_0)) else "0";
    icmp_ln45_14_fu_374_p2 <= "1" when (signed(p_read_66_reg_499) > signed(ap_const_lv32_0)) else "0";
    icmp_ln45_15_fu_386_p2 <= "1" when (signed(p_read_65_reg_494) > signed(ap_const_lv32_0)) else "0";
    icmp_ln45_1_fu_218_p2 <= "1" when (signed(p_read117_reg_564) > signed(ap_const_lv32_0)) else "0";
    icmp_ln45_2_fu_230_p2 <= "1" when (signed(p_read218_reg_559) > signed(ap_const_lv32_0)) else "0";
    icmp_ln45_3_fu_242_p2 <= "1" when (signed(p_read319_reg_554) > signed(ap_const_lv32_0)) else "0";
    icmp_ln45_4_fu_254_p2 <= "1" when (signed(p_read420_reg_549) > signed(ap_const_lv32_0)) else "0";
    icmp_ln45_5_fu_266_p2 <= "1" when (signed(p_read521_reg_544) > signed(ap_const_lv32_0)) else "0";
    icmp_ln45_6_fu_278_p2 <= "1" when (signed(p_read622_reg_539) > signed(ap_const_lv32_0)) else "0";
    icmp_ln45_7_fu_290_p2 <= "1" when (signed(p_read723_reg_534) > signed(ap_const_lv32_0)) else "0";
    icmp_ln45_8_fu_302_p2 <= "1" when (signed(p_read824_reg_529) > signed(ap_const_lv32_0)) else "0";
    icmp_ln45_9_fu_314_p2 <= "1" when (signed(p_read925_reg_524) > signed(ap_const_lv32_0)) else "0";
    icmp_ln45_fu_206_p2 <= "1" when (signed(p_read16_reg_569) > signed(ap_const_lv32_0)) else "0";
    trunc_ln42_10_fu_182_p1 <= p_read10(31 - 1 downto 0);
    trunc_ln42_11_fu_186_p1 <= p_read11(31 - 1 downto 0);
    trunc_ln42_12_fu_190_p1 <= p_read12(31 - 1 downto 0);
    trunc_ln42_13_fu_194_p1 <= p_read13(31 - 1 downto 0);
    trunc_ln42_14_fu_198_p1 <= p_read14(31 - 1 downto 0);
    trunc_ln42_15_fu_202_p1 <= p_read15(31 - 1 downto 0);
    trunc_ln42_1_fu_146_p1 <= p_read1(31 - 1 downto 0);
    trunc_ln42_2_fu_150_p1 <= p_read2(31 - 1 downto 0);
    trunc_ln42_3_fu_154_p1 <= p_read3(31 - 1 downto 0);
    trunc_ln42_4_fu_158_p1 <= p_read4(31 - 1 downto 0);
    trunc_ln42_5_fu_162_p1 <= p_read5(31 - 1 downto 0);
    trunc_ln42_6_fu_166_p1 <= p_read6(31 - 1 downto 0);
    trunc_ln42_7_fu_170_p1 <= p_read7(31 - 1 downto 0);
    trunc_ln42_8_fu_174_p1 <= p_read8(31 - 1 downto 0);
    trunc_ln42_9_fu_178_p1 <= p_read9(31 - 1 downto 0);
    trunc_ln42_fu_142_p1 <= p_read(31 - 1 downto 0);
end behav;
