-- ==============================================================
-- Generated by Vitis HLS v2023.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity myproject_dense_resource_ap_fixed_32_6_5_3_0_ap_fixed_32_6_5_3_0_config4_s_outidx_ROM_AdEe is 
    generic(
             DataWidth     : integer := 3; 
             AddressWidth     : integer := 7; 
             AddressRange    : integer := 128
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of myproject_dense_resource_ap_fixed_32_6_5_3_0_ap_fixed_32_6_5_3_0_config4_s_outidx_ROM_AdEe is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "000", 1 => "000", 2 => "000", 3 => "000", 
    4 => "000", 5 => "000", 6 => "000", 7 => "000", 
    8 => "000", 9 => "000", 10 => "000", 11 => "000", 
    12 => "000", 13 => "000", 14 => "000", 15 => "000", 
    16 => "001", 17 => "001", 18 => "001", 19 => "001", 
    20 => "001", 21 => "001", 22 => "001", 23 => "001", 
    24 => "001", 25 => "001", 26 => "001", 27 => "001", 
    28 => "001", 29 => "001", 30 => "001", 31 => "001", 
    32 => "010", 33 => "010", 34 => "010", 35 => "010", 
    36 => "010", 37 => "010", 38 => "010", 39 => "010", 
    40 => "010", 41 => "010", 42 => "010", 43 => "010", 
    44 => "010", 45 => "010", 46 => "010", 47 => "010", 
    48 => "011", 49 => "011", 50 => "011", 51 => "011", 
    52 => "011", 53 => "011", 54 => "011", 55 => "011", 
    56 => "011", 57 => "011", 58 => "011", 59 => "011", 
    60 => "011", 61 => "011", 62 => "011", 63 => "011", 
    64 => "100", 65 => "100", 66 => "100", 67 => "100", 
    68 => "100", 69 => "100", 70 => "100", 71 => "100", 
    72 => "100", 73 => "100", 74 => "100", 75 => "100", 
    76 => "100", 77 => "100", 78 => "100", 79 => "100", 
    80 => "101", 81 => "101", 82 => "101", 83 => "101", 
    84 => "101", 85 => "101", 86 => "101", 87 => "101", 
    88 => "101", 89 => "101", 90 => "101", 91 => "101", 
    92 => "101", 93 => "101", 94 => "101", 95 => "101", 
    96 => "110", 97 => "110", 98 => "110", 99 => "110", 
    100 => "110", 101 => "110", 102 => "110", 103 => "110", 
    104 => "110", 105 => "110", 106 => "110", 107 => "110", 
    108 => "110", 109 => "110", 110 => "110", 111 => "110", 
    112 => "111", 113 => "111", 114 => "111", 115 => "111", 
    116 => "111", 117 => "111", 118 => "111", 119 => "111", 
    120 => "111", 121 => "111", 122 => "111", 123 => "111", 
    124 => "111", 125 => "111", 126 => "111", 127 => "111");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

