-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- --------------------------------------------------------------------------------
-- Tool Version: Vivado v.2025.1 (win64) Build 6140274 Thu May 22 00:12:29 MDT 2025
-- Date        : Mon Dec 15 00:50:54 2025
-- Host        : Unlucky running 64-bit major release  (build 9200)
-- Command     : write_vhdl -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix
--               decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ bd_0_hls_inst_0_stub.vhdl
-- Design      : bd_0_hls_inst_0
-- Purpose     : Stub declaration of top-level module interface
-- Device      : xc7z020clg400-1
-- --------------------------------------------------------------------------------
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix is
  Port ( 
    input_data_0_ce0 : out STD_LOGIC;
    input_data_0_we0 : out STD_LOGIC;
    input_data_0_ce1 : out STD_LOGIC;
    input_data_0_we1 : out STD_LOGIC;
    input_data_1_ce0 : out STD_LOGIC;
    input_data_1_we0 : out STD_LOGIC;
    input_data_1_ce1 : out STD_LOGIC;
    input_data_1_we1 : out STD_LOGIC;
    input_data_2_ce0 : out STD_LOGIC;
    input_data_2_we0 : out STD_LOGIC;
    input_data_2_ce1 : out STD_LOGIC;
    input_data_2_we1 : out STD_LOGIC;
    input_data_3_ce0 : out STD_LOGIC;
    input_data_3_we0 : out STD_LOGIC;
    input_data_3_ce1 : out STD_LOGIC;
    input_data_3_we1 : out STD_LOGIC;
    input_data_4_ce0 : out STD_LOGIC;
    input_data_4_we0 : out STD_LOGIC;
    input_data_4_ce1 : out STD_LOGIC;
    input_data_4_we1 : out STD_LOGIC;
    input_data_5_ce0 : out STD_LOGIC;
    input_data_5_we0 : out STD_LOGIC;
    input_data_5_ce1 : out STD_LOGIC;
    input_data_5_we1 : out STD_LOGIC;
    input_data_6_ce0 : out STD_LOGIC;
    input_data_6_we0 : out STD_LOGIC;
    input_data_6_ce1 : out STD_LOGIC;
    input_data_6_we1 : out STD_LOGIC;
    input_data_7_ce0 : out STD_LOGIC;
    input_data_7_we0 : out STD_LOGIC;
    input_data_7_ce1 : out STD_LOGIC;
    input_data_7_we1 : out STD_LOGIC;
    output_data_0_ce0 : out STD_LOGIC;
    output_data_0_we0 : out STD_LOGIC;
    output_data_0_ce1 : out STD_LOGIC;
    output_data_0_we1 : out STD_LOGIC;
    output_data_1_ce0 : out STD_LOGIC;
    output_data_1_we0 : out STD_LOGIC;
    output_data_1_ce1 : out STD_LOGIC;
    output_data_1_we1 : out STD_LOGIC;
    output_data_2_ce0 : out STD_LOGIC;
    output_data_2_we0 : out STD_LOGIC;
    output_data_2_ce1 : out STD_LOGIC;
    output_data_2_we1 : out STD_LOGIC;
    output_data_3_ce0 : out STD_LOGIC;
    output_data_3_we0 : out STD_LOGIC;
    output_data_3_ce1 : out STD_LOGIC;
    output_data_3_we1 : out STD_LOGIC;
    output_data_4_ce0 : out STD_LOGIC;
    output_data_4_we0 : out STD_LOGIC;
    output_data_4_ce1 : out STD_LOGIC;
    output_data_4_we1 : out STD_LOGIC;
    output_data_5_ce0 : out STD_LOGIC;
    output_data_5_we0 : out STD_LOGIC;
    output_data_5_ce1 : out STD_LOGIC;
    output_data_5_we1 : out STD_LOGIC;
    output_data_6_ce0 : out STD_LOGIC;
    output_data_6_we0 : out STD_LOGIC;
    output_data_6_ce1 : out STD_LOGIC;
    output_data_6_we1 : out STD_LOGIC;
    output_data_7_ce0 : out STD_LOGIC;
    output_data_7_we0 : out STD_LOGIC;
    output_data_7_ce1 : out STD_LOGIC;
    output_data_7_we1 : out STD_LOGIC;
    input_data_0_address0 : out STD_LOGIC_VECTOR ( 2 downto 0 );
    input_data_0_d0 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    input_data_0_q0 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    input_data_0_address1 : out STD_LOGIC_VECTOR ( 2 downto 0 );
    input_data_0_d1 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    input_data_0_q1 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    input_data_1_address0 : out STD_LOGIC_VECTOR ( 2 downto 0 );
    input_data_1_d0 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    input_data_1_q0 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    input_data_1_address1 : out STD_LOGIC_VECTOR ( 2 downto 0 );
    input_data_1_d1 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    input_data_1_q1 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    input_data_2_address0 : out STD_LOGIC_VECTOR ( 2 downto 0 );
    input_data_2_d0 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    input_data_2_q0 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    input_data_2_address1 : out STD_LOGIC_VECTOR ( 2 downto 0 );
    input_data_2_d1 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    input_data_2_q1 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    input_data_3_address0 : out STD_LOGIC_VECTOR ( 2 downto 0 );
    input_data_3_d0 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    input_data_3_q0 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    input_data_3_address1 : out STD_LOGIC_VECTOR ( 2 downto 0 );
    input_data_3_d1 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    input_data_3_q1 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    input_data_4_address0 : out STD_LOGIC_VECTOR ( 2 downto 0 );
    input_data_4_d0 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    input_data_4_q0 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    input_data_4_address1 : out STD_LOGIC_VECTOR ( 2 downto 0 );
    input_data_4_d1 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    input_data_4_q1 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    input_data_5_address0 : out STD_LOGIC_VECTOR ( 2 downto 0 );
    input_data_5_d0 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    input_data_5_q0 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    input_data_5_address1 : out STD_LOGIC_VECTOR ( 2 downto 0 );
    input_data_5_d1 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    input_data_5_q1 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    input_data_6_address0 : out STD_LOGIC_VECTOR ( 2 downto 0 );
    input_data_6_d0 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    input_data_6_q0 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    input_data_6_address1 : out STD_LOGIC_VECTOR ( 2 downto 0 );
    input_data_6_d1 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    input_data_6_q1 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    input_data_7_address0 : out STD_LOGIC_VECTOR ( 2 downto 0 );
    input_data_7_d0 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    input_data_7_q0 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    input_data_7_address1 : out STD_LOGIC_VECTOR ( 2 downto 0 );
    input_data_7_d1 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    input_data_7_q1 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    output_data_0_address0 : out STD_LOGIC_VECTOR ( 2 downto 0 );
    output_data_0_d0 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    output_data_0_q0 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    output_data_0_address1 : out STD_LOGIC_VECTOR ( 2 downto 0 );
    output_data_0_d1 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    output_data_0_q1 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    output_data_1_address0 : out STD_LOGIC_VECTOR ( 2 downto 0 );
    output_data_1_d0 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    output_data_1_q0 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    output_data_1_address1 : out STD_LOGIC_VECTOR ( 2 downto 0 );
    output_data_1_d1 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    output_data_1_q1 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    output_data_2_address0 : out STD_LOGIC_VECTOR ( 2 downto 0 );
    output_data_2_d0 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    output_data_2_q0 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    output_data_2_address1 : out STD_LOGIC_VECTOR ( 2 downto 0 );
    output_data_2_d1 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    output_data_2_q1 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    output_data_3_address0 : out STD_LOGIC_VECTOR ( 2 downto 0 );
    output_data_3_d0 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    output_data_3_q0 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    output_data_3_address1 : out STD_LOGIC_VECTOR ( 2 downto 0 );
    output_data_3_d1 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    output_data_3_q1 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    output_data_4_address0 : out STD_LOGIC_VECTOR ( 2 downto 0 );
    output_data_4_d0 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    output_data_4_q0 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    output_data_4_address1 : out STD_LOGIC_VECTOR ( 2 downto 0 );
    output_data_4_d1 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    output_data_4_q1 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    output_data_5_address0 : out STD_LOGIC_VECTOR ( 2 downto 0 );
    output_data_5_d0 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    output_data_5_q0 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    output_data_5_address1 : out STD_LOGIC_VECTOR ( 2 downto 0 );
    output_data_5_d1 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    output_data_5_q1 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    output_data_6_address0 : out STD_LOGIC_VECTOR ( 2 downto 0 );
    output_data_6_d0 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    output_data_6_q0 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    output_data_6_address1 : out STD_LOGIC_VECTOR ( 2 downto 0 );
    output_data_6_d1 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    output_data_6_q1 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    output_data_7_address0 : out STD_LOGIC_VECTOR ( 2 downto 0 );
    output_data_7_d0 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    output_data_7_q0 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    output_data_7_address1 : out STD_LOGIC_VECTOR ( 2 downto 0 );
    output_data_7_d1 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    output_data_7_q1 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    ap_clk : in STD_LOGIC;
    ap_rst : in STD_LOGIC;
    ap_done : out STD_LOGIC;
    ap_idle : out STD_LOGIC;
    ap_ready : out STD_LOGIC;
    ap_start : in STD_LOGIC
  );

  attribute CHECK_LICENSE_TYPE : string;
  attribute CHECK_LICENSE_TYPE of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is "bd_0_hls_inst_0,tiny_autoencoder,{}";
  attribute CORE_GENERATION_INFO : string;
  attribute CORE_GENERATION_INFO of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is "bd_0_hls_inst_0,tiny_autoencoder,{x_ipProduct=Vivado 2025.1,x_ipVendor=xilinx.com,x_ipLibrary=hls,x_ipName=tiny_autoencoder,x_ipVersion=1.0,x_ipCoreRevision=2114391765,x_ipLanguage=VERILOG,x_ipSimLanguage=MIXED}";
  attribute DowngradeIPIdentifiedWarnings : string;
  attribute DowngradeIPIdentifiedWarnings of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is "yes";
  attribute IP_DEFINITION_SOURCE : string;
  attribute IP_DEFINITION_SOURCE of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is "HLS";
  attribute hls_module : string;
  attribute hls_module of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is "yes";
end decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix;

architecture stub of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix is
  attribute syn_black_box : boolean;
  attribute black_box_pad_pin : string;
  attribute syn_black_box of stub : architecture is true;
  attribute black_box_pad_pin of stub : architecture is "input_data_0_ce0,input_data_0_we0,input_data_0_ce1,input_data_0_we1,input_data_1_ce0,input_data_1_we0,input_data_1_ce1,input_data_1_we1,input_data_2_ce0,input_data_2_we0,input_data_2_ce1,input_data_2_we1,input_data_3_ce0,input_data_3_we0,input_data_3_ce1,input_data_3_we1,input_data_4_ce0,input_data_4_we0,input_data_4_ce1,input_data_4_we1,input_data_5_ce0,input_data_5_we0,input_data_5_ce1,input_data_5_we1,input_data_6_ce0,input_data_6_we0,input_data_6_ce1,input_data_6_we1,input_data_7_ce0,input_data_7_we0,input_data_7_ce1,input_data_7_we1,output_data_0_ce0,output_data_0_we0,output_data_0_ce1,output_data_0_we1,output_data_1_ce0,output_data_1_we0,output_data_1_ce1,output_data_1_we1,output_data_2_ce0,output_data_2_we0,output_data_2_ce1,output_data_2_we1,output_data_3_ce0,output_data_3_we0,output_data_3_ce1,output_data_3_we1,output_data_4_ce0,output_data_4_we0,output_data_4_ce1,output_data_4_we1,output_data_5_ce0,output_data_5_we0,output_data_5_ce1,output_data_5_we1,output_data_6_ce0,output_data_6_we0,output_data_6_ce1,output_data_6_we1,output_data_7_ce0,output_data_7_we0,output_data_7_ce1,output_data_7_we1,input_data_0_address0[2:0],input_data_0_d0[15:0],input_data_0_q0[15:0],input_data_0_address1[2:0],input_data_0_d1[15:0],input_data_0_q1[15:0],input_data_1_address0[2:0],input_data_1_d0[15:0],input_data_1_q0[15:0],input_data_1_address1[2:0],input_data_1_d1[15:0],input_data_1_q1[15:0],input_data_2_address0[2:0],input_data_2_d0[15:0],input_data_2_q0[15:0],input_data_2_address1[2:0],input_data_2_d1[15:0],input_data_2_q1[15:0],input_data_3_address0[2:0],input_data_3_d0[15:0],input_data_3_q0[15:0],input_data_3_address1[2:0],input_data_3_d1[15:0],input_data_3_q1[15:0],input_data_4_address0[2:0],input_data_4_d0[15:0],input_data_4_q0[15:0],input_data_4_address1[2:0],input_data_4_d1[15:0],input_data_4_q1[15:0],input_data_5_address0[2:0],input_data_5_d0[15:0],input_data_5_q0[15:0],input_data_5_address1[2:0],input_data_5_d1[15:0],input_data_5_q1[15:0],input_data_6_address0[2:0],input_data_6_d0[15:0],input_data_6_q0[15:0],input_data_6_address1[2:0],input_data_6_d1[15:0],input_data_6_q1[15:0],input_data_7_address0[2:0],input_data_7_d0[15:0],input_data_7_q0[15:0],input_data_7_address1[2:0],input_data_7_d1[15:0],input_data_7_q1[15:0],output_data_0_address0[2:0],output_data_0_d0[15:0],output_data_0_q0[15:0],output_data_0_address1[2:0],output_data_0_d1[15:0],output_data_0_q1[15:0],output_data_1_address0[2:0],output_data_1_d0[15:0],output_data_1_q0[15:0],output_data_1_address1[2:0],output_data_1_d1[15:0],output_data_1_q1[15:0],output_data_2_address0[2:0],output_data_2_d0[15:0],output_data_2_q0[15:0],output_data_2_address1[2:0],output_data_2_d1[15:0],output_data_2_q1[15:0],output_data_3_address0[2:0],output_data_3_d0[15:0],output_data_3_q0[15:0],output_data_3_address1[2:0],output_data_3_d1[15:0],output_data_3_q1[15:0],output_data_4_address0[2:0],output_data_4_d0[15:0],output_data_4_q0[15:0],output_data_4_address1[2:0],output_data_4_d1[15:0],output_data_4_q1[15:0],output_data_5_address0[2:0],output_data_5_d0[15:0],output_data_5_q0[15:0],output_data_5_address1[2:0],output_data_5_d1[15:0],output_data_5_q1[15:0],output_data_6_address0[2:0],output_data_6_d0[15:0],output_data_6_q0[15:0],output_data_6_address1[2:0],output_data_6_d1[15:0],output_data_6_q1[15:0],output_data_7_address0[2:0],output_data_7_d0[15:0],output_data_7_q0[15:0],output_data_7_address1[2:0],output_data_7_d1[15:0],output_data_7_q1[15:0],ap_clk,ap_rst,ap_done,ap_idle,ap_ready,ap_start";
  attribute X_INTERFACE_INFO : string;
  attribute X_INTERFACE_INFO of input_data_0_address0 : signal is "xilinx.com:signal:data:1.0 input_data_0_address0 DATA";
  attribute X_INTERFACE_MODE : string;
  attribute X_INTERFACE_MODE of input_data_0_address0 : signal is "master";
  attribute X_INTERFACE_PARAMETER : string;
  attribute X_INTERFACE_PARAMETER of input_data_0_address0 : signal is "XIL_INTERFACENAME input_data_0_address0, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of input_data_0_d0 : signal is "xilinx.com:signal:data:1.0 input_data_0_d0 DATA";
  attribute X_INTERFACE_MODE of input_data_0_d0 : signal is "master";
  attribute X_INTERFACE_PARAMETER of input_data_0_d0 : signal is "XIL_INTERFACENAME input_data_0_d0, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of input_data_0_q0 : signal is "xilinx.com:signal:data:1.0 input_data_0_q0 DATA";
  attribute X_INTERFACE_MODE of input_data_0_q0 : signal is "slave";
  attribute X_INTERFACE_PARAMETER of input_data_0_q0 : signal is "XIL_INTERFACENAME input_data_0_q0, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of input_data_0_address1 : signal is "xilinx.com:signal:data:1.0 input_data_0_address1 DATA";
  attribute X_INTERFACE_MODE of input_data_0_address1 : signal is "master";
  attribute X_INTERFACE_PARAMETER of input_data_0_address1 : signal is "XIL_INTERFACENAME input_data_0_address1, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of input_data_0_d1 : signal is "xilinx.com:signal:data:1.0 input_data_0_d1 DATA";
  attribute X_INTERFACE_MODE of input_data_0_d1 : signal is "master";
  attribute X_INTERFACE_PARAMETER of input_data_0_d1 : signal is "XIL_INTERFACENAME input_data_0_d1, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of input_data_0_q1 : signal is "xilinx.com:signal:data:1.0 input_data_0_q1 DATA";
  attribute X_INTERFACE_MODE of input_data_0_q1 : signal is "slave";
  attribute X_INTERFACE_PARAMETER of input_data_0_q1 : signal is "XIL_INTERFACENAME input_data_0_q1, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of input_data_1_address0 : signal is "xilinx.com:signal:data:1.0 input_data_1_address0 DATA";
  attribute X_INTERFACE_MODE of input_data_1_address0 : signal is "master";
  attribute X_INTERFACE_PARAMETER of input_data_1_address0 : signal is "XIL_INTERFACENAME input_data_1_address0, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of input_data_1_d0 : signal is "xilinx.com:signal:data:1.0 input_data_1_d0 DATA";
  attribute X_INTERFACE_MODE of input_data_1_d0 : signal is "master";
  attribute X_INTERFACE_PARAMETER of input_data_1_d0 : signal is "XIL_INTERFACENAME input_data_1_d0, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of input_data_1_q0 : signal is "xilinx.com:signal:data:1.0 input_data_1_q0 DATA";
  attribute X_INTERFACE_MODE of input_data_1_q0 : signal is "slave";
  attribute X_INTERFACE_PARAMETER of input_data_1_q0 : signal is "XIL_INTERFACENAME input_data_1_q0, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of input_data_1_address1 : signal is "xilinx.com:signal:data:1.0 input_data_1_address1 DATA";
  attribute X_INTERFACE_MODE of input_data_1_address1 : signal is "master";
  attribute X_INTERFACE_PARAMETER of input_data_1_address1 : signal is "XIL_INTERFACENAME input_data_1_address1, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of input_data_1_d1 : signal is "xilinx.com:signal:data:1.0 input_data_1_d1 DATA";
  attribute X_INTERFACE_MODE of input_data_1_d1 : signal is "master";
  attribute X_INTERFACE_PARAMETER of input_data_1_d1 : signal is "XIL_INTERFACENAME input_data_1_d1, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of input_data_1_q1 : signal is "xilinx.com:signal:data:1.0 input_data_1_q1 DATA";
  attribute X_INTERFACE_MODE of input_data_1_q1 : signal is "slave";
  attribute X_INTERFACE_PARAMETER of input_data_1_q1 : signal is "XIL_INTERFACENAME input_data_1_q1, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of input_data_2_address0 : signal is "xilinx.com:signal:data:1.0 input_data_2_address0 DATA";
  attribute X_INTERFACE_MODE of input_data_2_address0 : signal is "master";
  attribute X_INTERFACE_PARAMETER of input_data_2_address0 : signal is "XIL_INTERFACENAME input_data_2_address0, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of input_data_2_d0 : signal is "xilinx.com:signal:data:1.0 input_data_2_d0 DATA";
  attribute X_INTERFACE_MODE of input_data_2_d0 : signal is "master";
  attribute X_INTERFACE_PARAMETER of input_data_2_d0 : signal is "XIL_INTERFACENAME input_data_2_d0, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of input_data_2_q0 : signal is "xilinx.com:signal:data:1.0 input_data_2_q0 DATA";
  attribute X_INTERFACE_MODE of input_data_2_q0 : signal is "slave";
  attribute X_INTERFACE_PARAMETER of input_data_2_q0 : signal is "XIL_INTERFACENAME input_data_2_q0, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of input_data_2_address1 : signal is "xilinx.com:signal:data:1.0 input_data_2_address1 DATA";
  attribute X_INTERFACE_MODE of input_data_2_address1 : signal is "master";
  attribute X_INTERFACE_PARAMETER of input_data_2_address1 : signal is "XIL_INTERFACENAME input_data_2_address1, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of input_data_2_d1 : signal is "xilinx.com:signal:data:1.0 input_data_2_d1 DATA";
  attribute X_INTERFACE_MODE of input_data_2_d1 : signal is "master";
  attribute X_INTERFACE_PARAMETER of input_data_2_d1 : signal is "XIL_INTERFACENAME input_data_2_d1, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of input_data_2_q1 : signal is "xilinx.com:signal:data:1.0 input_data_2_q1 DATA";
  attribute X_INTERFACE_MODE of input_data_2_q1 : signal is "slave";
  attribute X_INTERFACE_PARAMETER of input_data_2_q1 : signal is "XIL_INTERFACENAME input_data_2_q1, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of input_data_3_address0 : signal is "xilinx.com:signal:data:1.0 input_data_3_address0 DATA";
  attribute X_INTERFACE_MODE of input_data_3_address0 : signal is "master";
  attribute X_INTERFACE_PARAMETER of input_data_3_address0 : signal is "XIL_INTERFACENAME input_data_3_address0, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of input_data_3_d0 : signal is "xilinx.com:signal:data:1.0 input_data_3_d0 DATA";
  attribute X_INTERFACE_MODE of input_data_3_d0 : signal is "master";
  attribute X_INTERFACE_PARAMETER of input_data_3_d0 : signal is "XIL_INTERFACENAME input_data_3_d0, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of input_data_3_q0 : signal is "xilinx.com:signal:data:1.0 input_data_3_q0 DATA";
  attribute X_INTERFACE_MODE of input_data_3_q0 : signal is "slave";
  attribute X_INTERFACE_PARAMETER of input_data_3_q0 : signal is "XIL_INTERFACENAME input_data_3_q0, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of input_data_3_address1 : signal is "xilinx.com:signal:data:1.0 input_data_3_address1 DATA";
  attribute X_INTERFACE_MODE of input_data_3_address1 : signal is "master";
  attribute X_INTERFACE_PARAMETER of input_data_3_address1 : signal is "XIL_INTERFACENAME input_data_3_address1, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of input_data_3_d1 : signal is "xilinx.com:signal:data:1.0 input_data_3_d1 DATA";
  attribute X_INTERFACE_MODE of input_data_3_d1 : signal is "master";
  attribute X_INTERFACE_PARAMETER of input_data_3_d1 : signal is "XIL_INTERFACENAME input_data_3_d1, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of input_data_3_q1 : signal is "xilinx.com:signal:data:1.0 input_data_3_q1 DATA";
  attribute X_INTERFACE_MODE of input_data_3_q1 : signal is "slave";
  attribute X_INTERFACE_PARAMETER of input_data_3_q1 : signal is "XIL_INTERFACENAME input_data_3_q1, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of input_data_4_address0 : signal is "xilinx.com:signal:data:1.0 input_data_4_address0 DATA";
  attribute X_INTERFACE_MODE of input_data_4_address0 : signal is "master";
  attribute X_INTERFACE_PARAMETER of input_data_4_address0 : signal is "XIL_INTERFACENAME input_data_4_address0, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of input_data_4_d0 : signal is "xilinx.com:signal:data:1.0 input_data_4_d0 DATA";
  attribute X_INTERFACE_MODE of input_data_4_d0 : signal is "master";
  attribute X_INTERFACE_PARAMETER of input_data_4_d0 : signal is "XIL_INTERFACENAME input_data_4_d0, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of input_data_4_q0 : signal is "xilinx.com:signal:data:1.0 input_data_4_q0 DATA";
  attribute X_INTERFACE_MODE of input_data_4_q0 : signal is "slave";
  attribute X_INTERFACE_PARAMETER of input_data_4_q0 : signal is "XIL_INTERFACENAME input_data_4_q0, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of input_data_4_address1 : signal is "xilinx.com:signal:data:1.0 input_data_4_address1 DATA";
  attribute X_INTERFACE_MODE of input_data_4_address1 : signal is "master";
  attribute X_INTERFACE_PARAMETER of input_data_4_address1 : signal is "XIL_INTERFACENAME input_data_4_address1, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of input_data_4_d1 : signal is "xilinx.com:signal:data:1.0 input_data_4_d1 DATA";
  attribute X_INTERFACE_MODE of input_data_4_d1 : signal is "master";
  attribute X_INTERFACE_PARAMETER of input_data_4_d1 : signal is "XIL_INTERFACENAME input_data_4_d1, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of input_data_4_q1 : signal is "xilinx.com:signal:data:1.0 input_data_4_q1 DATA";
  attribute X_INTERFACE_MODE of input_data_4_q1 : signal is "slave";
  attribute X_INTERFACE_PARAMETER of input_data_4_q1 : signal is "XIL_INTERFACENAME input_data_4_q1, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of input_data_5_address0 : signal is "xilinx.com:signal:data:1.0 input_data_5_address0 DATA";
  attribute X_INTERFACE_MODE of input_data_5_address0 : signal is "master";
  attribute X_INTERFACE_PARAMETER of input_data_5_address0 : signal is "XIL_INTERFACENAME input_data_5_address0, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of input_data_5_d0 : signal is "xilinx.com:signal:data:1.0 input_data_5_d0 DATA";
  attribute X_INTERFACE_MODE of input_data_5_d0 : signal is "master";
  attribute X_INTERFACE_PARAMETER of input_data_5_d0 : signal is "XIL_INTERFACENAME input_data_5_d0, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of input_data_5_q0 : signal is "xilinx.com:signal:data:1.0 input_data_5_q0 DATA";
  attribute X_INTERFACE_MODE of input_data_5_q0 : signal is "slave";
  attribute X_INTERFACE_PARAMETER of input_data_5_q0 : signal is "XIL_INTERFACENAME input_data_5_q0, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of input_data_5_address1 : signal is "xilinx.com:signal:data:1.0 input_data_5_address1 DATA";
  attribute X_INTERFACE_MODE of input_data_5_address1 : signal is "master";
  attribute X_INTERFACE_PARAMETER of input_data_5_address1 : signal is "XIL_INTERFACENAME input_data_5_address1, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of input_data_5_d1 : signal is "xilinx.com:signal:data:1.0 input_data_5_d1 DATA";
  attribute X_INTERFACE_MODE of input_data_5_d1 : signal is "master";
  attribute X_INTERFACE_PARAMETER of input_data_5_d1 : signal is "XIL_INTERFACENAME input_data_5_d1, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of input_data_5_q1 : signal is "xilinx.com:signal:data:1.0 input_data_5_q1 DATA";
  attribute X_INTERFACE_MODE of input_data_5_q1 : signal is "slave";
  attribute X_INTERFACE_PARAMETER of input_data_5_q1 : signal is "XIL_INTERFACENAME input_data_5_q1, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of input_data_6_address0 : signal is "xilinx.com:signal:data:1.0 input_data_6_address0 DATA";
  attribute X_INTERFACE_MODE of input_data_6_address0 : signal is "master";
  attribute X_INTERFACE_PARAMETER of input_data_6_address0 : signal is "XIL_INTERFACENAME input_data_6_address0, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of input_data_6_d0 : signal is "xilinx.com:signal:data:1.0 input_data_6_d0 DATA";
  attribute X_INTERFACE_MODE of input_data_6_d0 : signal is "master";
  attribute X_INTERFACE_PARAMETER of input_data_6_d0 : signal is "XIL_INTERFACENAME input_data_6_d0, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of input_data_6_q0 : signal is "xilinx.com:signal:data:1.0 input_data_6_q0 DATA";
  attribute X_INTERFACE_MODE of input_data_6_q0 : signal is "slave";
  attribute X_INTERFACE_PARAMETER of input_data_6_q0 : signal is "XIL_INTERFACENAME input_data_6_q0, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of input_data_6_address1 : signal is "xilinx.com:signal:data:1.0 input_data_6_address1 DATA";
  attribute X_INTERFACE_MODE of input_data_6_address1 : signal is "master";
  attribute X_INTERFACE_PARAMETER of input_data_6_address1 : signal is "XIL_INTERFACENAME input_data_6_address1, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of input_data_6_d1 : signal is "xilinx.com:signal:data:1.0 input_data_6_d1 DATA";
  attribute X_INTERFACE_MODE of input_data_6_d1 : signal is "master";
  attribute X_INTERFACE_PARAMETER of input_data_6_d1 : signal is "XIL_INTERFACENAME input_data_6_d1, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of input_data_6_q1 : signal is "xilinx.com:signal:data:1.0 input_data_6_q1 DATA";
  attribute X_INTERFACE_MODE of input_data_6_q1 : signal is "slave";
  attribute X_INTERFACE_PARAMETER of input_data_6_q1 : signal is "XIL_INTERFACENAME input_data_6_q1, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of input_data_7_address0 : signal is "xilinx.com:signal:data:1.0 input_data_7_address0 DATA";
  attribute X_INTERFACE_MODE of input_data_7_address0 : signal is "master";
  attribute X_INTERFACE_PARAMETER of input_data_7_address0 : signal is "XIL_INTERFACENAME input_data_7_address0, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of input_data_7_d0 : signal is "xilinx.com:signal:data:1.0 input_data_7_d0 DATA";
  attribute X_INTERFACE_MODE of input_data_7_d0 : signal is "master";
  attribute X_INTERFACE_PARAMETER of input_data_7_d0 : signal is "XIL_INTERFACENAME input_data_7_d0, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of input_data_7_q0 : signal is "xilinx.com:signal:data:1.0 input_data_7_q0 DATA";
  attribute X_INTERFACE_MODE of input_data_7_q0 : signal is "slave";
  attribute X_INTERFACE_PARAMETER of input_data_7_q0 : signal is "XIL_INTERFACENAME input_data_7_q0, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of input_data_7_address1 : signal is "xilinx.com:signal:data:1.0 input_data_7_address1 DATA";
  attribute X_INTERFACE_MODE of input_data_7_address1 : signal is "master";
  attribute X_INTERFACE_PARAMETER of input_data_7_address1 : signal is "XIL_INTERFACENAME input_data_7_address1, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of input_data_7_d1 : signal is "xilinx.com:signal:data:1.0 input_data_7_d1 DATA";
  attribute X_INTERFACE_MODE of input_data_7_d1 : signal is "master";
  attribute X_INTERFACE_PARAMETER of input_data_7_d1 : signal is "XIL_INTERFACENAME input_data_7_d1, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of input_data_7_q1 : signal is "xilinx.com:signal:data:1.0 input_data_7_q1 DATA";
  attribute X_INTERFACE_MODE of input_data_7_q1 : signal is "slave";
  attribute X_INTERFACE_PARAMETER of input_data_7_q1 : signal is "XIL_INTERFACENAME input_data_7_q1, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of output_data_0_address0 : signal is "xilinx.com:signal:data:1.0 output_data_0_address0 DATA";
  attribute X_INTERFACE_MODE of output_data_0_address0 : signal is "master";
  attribute X_INTERFACE_PARAMETER of output_data_0_address0 : signal is "XIL_INTERFACENAME output_data_0_address0, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of output_data_0_d0 : signal is "xilinx.com:signal:data:1.0 output_data_0_d0 DATA";
  attribute X_INTERFACE_MODE of output_data_0_d0 : signal is "master";
  attribute X_INTERFACE_PARAMETER of output_data_0_d0 : signal is "XIL_INTERFACENAME output_data_0_d0, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of output_data_0_q0 : signal is "xilinx.com:signal:data:1.0 output_data_0_q0 DATA";
  attribute X_INTERFACE_MODE of output_data_0_q0 : signal is "slave";
  attribute X_INTERFACE_PARAMETER of output_data_0_q0 : signal is "XIL_INTERFACENAME output_data_0_q0, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of output_data_0_address1 : signal is "xilinx.com:signal:data:1.0 output_data_0_address1 DATA";
  attribute X_INTERFACE_MODE of output_data_0_address1 : signal is "master";
  attribute X_INTERFACE_PARAMETER of output_data_0_address1 : signal is "XIL_INTERFACENAME output_data_0_address1, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of output_data_0_d1 : signal is "xilinx.com:signal:data:1.0 output_data_0_d1 DATA";
  attribute X_INTERFACE_MODE of output_data_0_d1 : signal is "master";
  attribute X_INTERFACE_PARAMETER of output_data_0_d1 : signal is "XIL_INTERFACENAME output_data_0_d1, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of output_data_0_q1 : signal is "xilinx.com:signal:data:1.0 output_data_0_q1 DATA";
  attribute X_INTERFACE_MODE of output_data_0_q1 : signal is "slave";
  attribute X_INTERFACE_PARAMETER of output_data_0_q1 : signal is "XIL_INTERFACENAME output_data_0_q1, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of output_data_1_address0 : signal is "xilinx.com:signal:data:1.0 output_data_1_address0 DATA";
  attribute X_INTERFACE_MODE of output_data_1_address0 : signal is "master";
  attribute X_INTERFACE_PARAMETER of output_data_1_address0 : signal is "XIL_INTERFACENAME output_data_1_address0, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of output_data_1_d0 : signal is "xilinx.com:signal:data:1.0 output_data_1_d0 DATA";
  attribute X_INTERFACE_MODE of output_data_1_d0 : signal is "master";
  attribute X_INTERFACE_PARAMETER of output_data_1_d0 : signal is "XIL_INTERFACENAME output_data_1_d0, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of output_data_1_q0 : signal is "xilinx.com:signal:data:1.0 output_data_1_q0 DATA";
  attribute X_INTERFACE_MODE of output_data_1_q0 : signal is "slave";
  attribute X_INTERFACE_PARAMETER of output_data_1_q0 : signal is "XIL_INTERFACENAME output_data_1_q0, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of output_data_1_address1 : signal is "xilinx.com:signal:data:1.0 output_data_1_address1 DATA";
  attribute X_INTERFACE_MODE of output_data_1_address1 : signal is "master";
  attribute X_INTERFACE_PARAMETER of output_data_1_address1 : signal is "XIL_INTERFACENAME output_data_1_address1, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of output_data_1_d1 : signal is "xilinx.com:signal:data:1.0 output_data_1_d1 DATA";
  attribute X_INTERFACE_MODE of output_data_1_d1 : signal is "master";
  attribute X_INTERFACE_PARAMETER of output_data_1_d1 : signal is "XIL_INTERFACENAME output_data_1_d1, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of output_data_1_q1 : signal is "xilinx.com:signal:data:1.0 output_data_1_q1 DATA";
  attribute X_INTERFACE_MODE of output_data_1_q1 : signal is "slave";
  attribute X_INTERFACE_PARAMETER of output_data_1_q1 : signal is "XIL_INTERFACENAME output_data_1_q1, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of output_data_2_address0 : signal is "xilinx.com:signal:data:1.0 output_data_2_address0 DATA";
  attribute X_INTERFACE_MODE of output_data_2_address0 : signal is "master";
  attribute X_INTERFACE_PARAMETER of output_data_2_address0 : signal is "XIL_INTERFACENAME output_data_2_address0, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of output_data_2_d0 : signal is "xilinx.com:signal:data:1.0 output_data_2_d0 DATA";
  attribute X_INTERFACE_MODE of output_data_2_d0 : signal is "master";
  attribute X_INTERFACE_PARAMETER of output_data_2_d0 : signal is "XIL_INTERFACENAME output_data_2_d0, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of output_data_2_q0 : signal is "xilinx.com:signal:data:1.0 output_data_2_q0 DATA";
  attribute X_INTERFACE_MODE of output_data_2_q0 : signal is "slave";
  attribute X_INTERFACE_PARAMETER of output_data_2_q0 : signal is "XIL_INTERFACENAME output_data_2_q0, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of output_data_2_address1 : signal is "xilinx.com:signal:data:1.0 output_data_2_address1 DATA";
  attribute X_INTERFACE_MODE of output_data_2_address1 : signal is "master";
  attribute X_INTERFACE_PARAMETER of output_data_2_address1 : signal is "XIL_INTERFACENAME output_data_2_address1, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of output_data_2_d1 : signal is "xilinx.com:signal:data:1.0 output_data_2_d1 DATA";
  attribute X_INTERFACE_MODE of output_data_2_d1 : signal is "master";
  attribute X_INTERFACE_PARAMETER of output_data_2_d1 : signal is "XIL_INTERFACENAME output_data_2_d1, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of output_data_2_q1 : signal is "xilinx.com:signal:data:1.0 output_data_2_q1 DATA";
  attribute X_INTERFACE_MODE of output_data_2_q1 : signal is "slave";
  attribute X_INTERFACE_PARAMETER of output_data_2_q1 : signal is "XIL_INTERFACENAME output_data_2_q1, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of output_data_3_address0 : signal is "xilinx.com:signal:data:1.0 output_data_3_address0 DATA";
  attribute X_INTERFACE_MODE of output_data_3_address0 : signal is "master";
  attribute X_INTERFACE_PARAMETER of output_data_3_address0 : signal is "XIL_INTERFACENAME output_data_3_address0, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of output_data_3_d0 : signal is "xilinx.com:signal:data:1.0 output_data_3_d0 DATA";
  attribute X_INTERFACE_MODE of output_data_3_d0 : signal is "master";
  attribute X_INTERFACE_PARAMETER of output_data_3_d0 : signal is "XIL_INTERFACENAME output_data_3_d0, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of output_data_3_q0 : signal is "xilinx.com:signal:data:1.0 output_data_3_q0 DATA";
  attribute X_INTERFACE_MODE of output_data_3_q0 : signal is "slave";
  attribute X_INTERFACE_PARAMETER of output_data_3_q0 : signal is "XIL_INTERFACENAME output_data_3_q0, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of output_data_3_address1 : signal is "xilinx.com:signal:data:1.0 output_data_3_address1 DATA";
  attribute X_INTERFACE_MODE of output_data_3_address1 : signal is "master";
  attribute X_INTERFACE_PARAMETER of output_data_3_address1 : signal is "XIL_INTERFACENAME output_data_3_address1, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of output_data_3_d1 : signal is "xilinx.com:signal:data:1.0 output_data_3_d1 DATA";
  attribute X_INTERFACE_MODE of output_data_3_d1 : signal is "master";
  attribute X_INTERFACE_PARAMETER of output_data_3_d1 : signal is "XIL_INTERFACENAME output_data_3_d1, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of output_data_3_q1 : signal is "xilinx.com:signal:data:1.0 output_data_3_q1 DATA";
  attribute X_INTERFACE_MODE of output_data_3_q1 : signal is "slave";
  attribute X_INTERFACE_PARAMETER of output_data_3_q1 : signal is "XIL_INTERFACENAME output_data_3_q1, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of output_data_4_address0 : signal is "xilinx.com:signal:data:1.0 output_data_4_address0 DATA";
  attribute X_INTERFACE_MODE of output_data_4_address0 : signal is "master";
  attribute X_INTERFACE_PARAMETER of output_data_4_address0 : signal is "XIL_INTERFACENAME output_data_4_address0, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of output_data_4_d0 : signal is "xilinx.com:signal:data:1.0 output_data_4_d0 DATA";
  attribute X_INTERFACE_MODE of output_data_4_d0 : signal is "master";
  attribute X_INTERFACE_PARAMETER of output_data_4_d0 : signal is "XIL_INTERFACENAME output_data_4_d0, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of output_data_4_q0 : signal is "xilinx.com:signal:data:1.0 output_data_4_q0 DATA";
  attribute X_INTERFACE_MODE of output_data_4_q0 : signal is "slave";
  attribute X_INTERFACE_PARAMETER of output_data_4_q0 : signal is "XIL_INTERFACENAME output_data_4_q0, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of output_data_4_address1 : signal is "xilinx.com:signal:data:1.0 output_data_4_address1 DATA";
  attribute X_INTERFACE_MODE of output_data_4_address1 : signal is "master";
  attribute X_INTERFACE_PARAMETER of output_data_4_address1 : signal is "XIL_INTERFACENAME output_data_4_address1, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of output_data_4_d1 : signal is "xilinx.com:signal:data:1.0 output_data_4_d1 DATA";
  attribute X_INTERFACE_MODE of output_data_4_d1 : signal is "master";
  attribute X_INTERFACE_PARAMETER of output_data_4_d1 : signal is "XIL_INTERFACENAME output_data_4_d1, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of output_data_4_q1 : signal is "xilinx.com:signal:data:1.0 output_data_4_q1 DATA";
  attribute X_INTERFACE_MODE of output_data_4_q1 : signal is "slave";
  attribute X_INTERFACE_PARAMETER of output_data_4_q1 : signal is "XIL_INTERFACENAME output_data_4_q1, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of output_data_5_address0 : signal is "xilinx.com:signal:data:1.0 output_data_5_address0 DATA";
  attribute X_INTERFACE_MODE of output_data_5_address0 : signal is "master";
  attribute X_INTERFACE_PARAMETER of output_data_5_address0 : signal is "XIL_INTERFACENAME output_data_5_address0, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of output_data_5_d0 : signal is "xilinx.com:signal:data:1.0 output_data_5_d0 DATA";
  attribute X_INTERFACE_MODE of output_data_5_d0 : signal is "master";
  attribute X_INTERFACE_PARAMETER of output_data_5_d0 : signal is "XIL_INTERFACENAME output_data_5_d0, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of output_data_5_q0 : signal is "xilinx.com:signal:data:1.0 output_data_5_q0 DATA";
  attribute X_INTERFACE_MODE of output_data_5_q0 : signal is "slave";
  attribute X_INTERFACE_PARAMETER of output_data_5_q0 : signal is "XIL_INTERFACENAME output_data_5_q0, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of output_data_5_address1 : signal is "xilinx.com:signal:data:1.0 output_data_5_address1 DATA";
  attribute X_INTERFACE_MODE of output_data_5_address1 : signal is "master";
  attribute X_INTERFACE_PARAMETER of output_data_5_address1 : signal is "XIL_INTERFACENAME output_data_5_address1, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of output_data_5_d1 : signal is "xilinx.com:signal:data:1.0 output_data_5_d1 DATA";
  attribute X_INTERFACE_MODE of output_data_5_d1 : signal is "master";
  attribute X_INTERFACE_PARAMETER of output_data_5_d1 : signal is "XIL_INTERFACENAME output_data_5_d1, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of output_data_5_q1 : signal is "xilinx.com:signal:data:1.0 output_data_5_q1 DATA";
  attribute X_INTERFACE_MODE of output_data_5_q1 : signal is "slave";
  attribute X_INTERFACE_PARAMETER of output_data_5_q1 : signal is "XIL_INTERFACENAME output_data_5_q1, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of output_data_6_address0 : signal is "xilinx.com:signal:data:1.0 output_data_6_address0 DATA";
  attribute X_INTERFACE_MODE of output_data_6_address0 : signal is "master";
  attribute X_INTERFACE_PARAMETER of output_data_6_address0 : signal is "XIL_INTERFACENAME output_data_6_address0, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of output_data_6_d0 : signal is "xilinx.com:signal:data:1.0 output_data_6_d0 DATA";
  attribute X_INTERFACE_MODE of output_data_6_d0 : signal is "master";
  attribute X_INTERFACE_PARAMETER of output_data_6_d0 : signal is "XIL_INTERFACENAME output_data_6_d0, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of output_data_6_q0 : signal is "xilinx.com:signal:data:1.0 output_data_6_q0 DATA";
  attribute X_INTERFACE_MODE of output_data_6_q0 : signal is "slave";
  attribute X_INTERFACE_PARAMETER of output_data_6_q0 : signal is "XIL_INTERFACENAME output_data_6_q0, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of output_data_6_address1 : signal is "xilinx.com:signal:data:1.0 output_data_6_address1 DATA";
  attribute X_INTERFACE_MODE of output_data_6_address1 : signal is "master";
  attribute X_INTERFACE_PARAMETER of output_data_6_address1 : signal is "XIL_INTERFACENAME output_data_6_address1, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of output_data_6_d1 : signal is "xilinx.com:signal:data:1.0 output_data_6_d1 DATA";
  attribute X_INTERFACE_MODE of output_data_6_d1 : signal is "master";
  attribute X_INTERFACE_PARAMETER of output_data_6_d1 : signal is "XIL_INTERFACENAME output_data_6_d1, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of output_data_6_q1 : signal is "xilinx.com:signal:data:1.0 output_data_6_q1 DATA";
  attribute X_INTERFACE_MODE of output_data_6_q1 : signal is "slave";
  attribute X_INTERFACE_PARAMETER of output_data_6_q1 : signal is "XIL_INTERFACENAME output_data_6_q1, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of output_data_7_address0 : signal is "xilinx.com:signal:data:1.0 output_data_7_address0 DATA";
  attribute X_INTERFACE_MODE of output_data_7_address0 : signal is "master";
  attribute X_INTERFACE_PARAMETER of output_data_7_address0 : signal is "XIL_INTERFACENAME output_data_7_address0, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of output_data_7_d0 : signal is "xilinx.com:signal:data:1.0 output_data_7_d0 DATA";
  attribute X_INTERFACE_MODE of output_data_7_d0 : signal is "master";
  attribute X_INTERFACE_PARAMETER of output_data_7_d0 : signal is "XIL_INTERFACENAME output_data_7_d0, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of output_data_7_q0 : signal is "xilinx.com:signal:data:1.0 output_data_7_q0 DATA";
  attribute X_INTERFACE_MODE of output_data_7_q0 : signal is "slave";
  attribute X_INTERFACE_PARAMETER of output_data_7_q0 : signal is "XIL_INTERFACENAME output_data_7_q0, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of output_data_7_address1 : signal is "xilinx.com:signal:data:1.0 output_data_7_address1 DATA";
  attribute X_INTERFACE_MODE of output_data_7_address1 : signal is "master";
  attribute X_INTERFACE_PARAMETER of output_data_7_address1 : signal is "XIL_INTERFACENAME output_data_7_address1, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of output_data_7_d1 : signal is "xilinx.com:signal:data:1.0 output_data_7_d1 DATA";
  attribute X_INTERFACE_MODE of output_data_7_d1 : signal is "master";
  attribute X_INTERFACE_PARAMETER of output_data_7_d1 : signal is "XIL_INTERFACENAME output_data_7_d1, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of output_data_7_q1 : signal is "xilinx.com:signal:data:1.0 output_data_7_q1 DATA";
  attribute X_INTERFACE_MODE of output_data_7_q1 : signal is "slave";
  attribute X_INTERFACE_PARAMETER of output_data_7_q1 : signal is "XIL_INTERFACENAME output_data_7_q1, LAYERED_METADATA undef";
  attribute X_INTERFACE_INFO of ap_clk : signal is "xilinx.com:signal:clock:1.0 ap_clk CLK";
  attribute X_INTERFACE_MODE of ap_clk : signal is "slave";
  attribute X_INTERFACE_PARAMETER of ap_clk : signal is "XIL_INTERFACENAME ap_clk, ASSOCIATED_RESET ap_rst, FREQ_HZ 100000000.0, FREQ_TOLERANCE_HZ 0, PHASE 0.0, CLK_DOMAIN bd_0_ap_clk_0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of ap_rst : signal is "xilinx.com:signal:reset:1.0 ap_rst RST";
  attribute X_INTERFACE_MODE of ap_rst : signal is "slave";
  attribute X_INTERFACE_PARAMETER of ap_rst : signal is "XIL_INTERFACENAME ap_rst, POLARITY ACTIVE_HIGH, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of ap_done : signal is "xilinx.com:interface:acc_handshake:1.0 ap_ctrl done";
  attribute X_INTERFACE_MODE of ap_done : signal is "slave";
  attribute X_INTERFACE_INFO of ap_idle : signal is "xilinx.com:interface:acc_handshake:1.0 ap_ctrl idle";
  attribute X_INTERFACE_INFO of ap_ready : signal is "xilinx.com:interface:acc_handshake:1.0 ap_ctrl ready";
  attribute X_INTERFACE_INFO of ap_start : signal is "xilinx.com:interface:acc_handshake:1.0 ap_ctrl start";
  attribute X_CORE_INFO : string;
  attribute X_CORE_INFO of stub : architecture is "tiny_autoencoder,Vivado 2025.1";
begin
end;
