// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        input_1_ap_vld,
        input_1,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_return_8,
        ap_return_9,
        ap_return_10,
        ap_return_11,
        ap_return_12,
        ap_return_13,
        ap_return_14,
        ap_return_15
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input   input_1_ap_vld;
input  [1023:0] input_1;
output  [15:0] ap_return_0;
output  [15:0] ap_return_1;
output  [15:0] ap_return_2;
output  [15:0] ap_return_3;
output  [15:0] ap_return_4;
output  [15:0] ap_return_5;
output  [15:0] ap_return_6;
output  [15:0] ap_return_7;
output  [15:0] ap_return_8;
output  [15:0] ap_return_9;
output  [15:0] ap_return_10;
output  [15:0] ap_return_11;
output  [15:0] ap_return_12;
output  [15:0] ap_return_13;
output  [15:0] ap_return_14;
output  [15:0] ap_return_15;

reg ap_idle;
reg[15:0] ap_return_0;
reg[15:0] ap_return_1;
reg[15:0] ap_return_2;
reg[15:0] ap_return_3;
reg[15:0] ap_return_4;
reg[15:0] ap_return_5;
reg[15:0] ap_return_6;
reg[15:0] ap_return_7;
reg[15:0] ap_return_8;
reg[15:0] ap_return_9;
reg[15:0] ap_return_10;
reg[15:0] ap_return_11;
reg[15:0] ap_return_12;
reg[15:0] ap_return_13;
reg[15:0] ap_return_14;
reg[15:0] ap_return_15;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
reg   [0:0] ap_phi_mux_do_init_phi_fu_360_p6;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln43_fu_734_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [3:0] w2_85_address0;
reg    w2_85_ce0;
wire   [1016:0] w2_85_q0;
reg    input_1_blk_n;
wire    ap_block_pp0_stage0;
reg   [0:0] do_init_reg_357;
reg    ap_block_pp0_stage0_11001;
reg   [3:0] w_index3_reg_385;
reg   [1023:0] input_1_load_phi_reg_398;
reg   [15:0] res_0_034_reg_411;
reg   [15:0] res_1_032_reg_425;
reg   [15:0] res_2_030_reg_439;
reg   [15:0] res_3_028_reg_453;
reg   [15:0] res_4_026_reg_467;
reg   [15:0] res_5_024_reg_481;
reg   [15:0] res_6_022_reg_495;
reg   [15:0] res_7_020_reg_509;
reg   [15:0] res_8_018_reg_523;
reg   [15:0] res_9_016_reg_537;
reg   [15:0] res_10_014_reg_551;
reg   [15:0] res_11_012_reg_565;
reg   [15:0] res_12_010_reg_579;
reg   [15:0] res_13_08_reg_593;
reg   [15:0] res_1445_06_reg_607;
reg   [15:0] res_15_04_reg_621;
wire   [15:0] a_fu_658_p1;
reg   [15:0] a_reg_3093;
wire   [15:0] a_1_fu_682_p1;
reg   [15:0] a_1_reg_3103;
wire   [15:0] a_2_fu_706_p1;
reg   [15:0] a_2_reg_3108;
wire  signed [15:0] a_3_fu_724_p1;
reg  signed [15:0] a_3_reg_3113;
wire   [3:0] w_index_fu_728_p2;
reg   [3:0] w_index_reg_3119;
reg   [0:0] icmp_ln43_reg_3124;
reg   [0:0] icmp_ln43_reg_3124_pp0_iter1_reg;
reg   [15:0] trunc_ln_reg_3128;
reg   [15:0] trunc_ln55_s_reg_3133;
reg   [15:0] trunc_ln55_63_reg_3138;
reg   [15:0] trunc_ln55_64_reg_3143;
reg   [15:0] trunc_ln55_65_reg_3148;
reg   [15:0] trunc_ln55_66_reg_3153;
reg   [15:0] trunc_ln55_67_reg_3158;
reg   [15:0] trunc_ln55_68_reg_3163;
reg   [15:0] trunc_ln55_69_reg_3168;
reg   [15:0] trunc_ln55_70_reg_3173;
reg   [15:0] trunc_ln55_71_reg_3178;
reg   [15:0] trunc_ln55_72_reg_3183;
reg   [15:0] trunc_ln55_73_reg_3188;
reg   [15:0] trunc_ln55_74_reg_3193;
reg   [15:0] trunc_ln55_75_reg_3198;
reg   [15:0] trunc_ln55_76_reg_3203;
reg   [15:0] trunc_ln55_77_reg_3208;
reg   [15:0] trunc_ln55_78_reg_3213;
reg   [15:0] trunc_ln55_79_reg_3218;
reg   [15:0] trunc_ln55_80_reg_3223;
reg   [15:0] trunc_ln55_81_reg_3228;
reg   [15:0] trunc_ln55_82_reg_3233;
reg   [15:0] trunc_ln55_83_reg_3238;
reg   [15:0] trunc_ln55_84_reg_3243;
reg   [15:0] trunc_ln55_85_reg_3248;
reg   [15:0] trunc_ln55_86_reg_3253;
reg   [15:0] trunc_ln55_87_reg_3258;
reg   [15:0] trunc_ln55_88_reg_3263;
reg   [15:0] trunc_ln55_89_reg_3268;
reg   [15:0] trunc_ln55_90_reg_3273;
reg   [15:0] trunc_ln55_91_reg_3278;
reg   [15:0] trunc_ln55_92_reg_3283;
reg   [15:0] trunc_ln55_93_reg_3288;
reg   [15:0] trunc_ln55_94_reg_3293;
reg   [15:0] trunc_ln55_95_reg_3298;
reg   [15:0] trunc_ln55_96_reg_3303;
reg   [15:0] trunc_ln55_97_reg_3308;
reg   [15:0] trunc_ln55_98_reg_3313;
reg   [15:0] trunc_ln55_99_reg_3318;
reg   [15:0] trunc_ln55_100_reg_3323;
reg   [15:0] trunc_ln55_101_reg_3328;
reg   [15:0] trunc_ln55_102_reg_3333;
reg   [15:0] trunc_ln55_103_reg_3338;
reg   [15:0] trunc_ln55_104_reg_3343;
reg   [15:0] trunc_ln55_105_reg_3348;
reg   [15:0] trunc_ln55_106_reg_3353;
reg   [15:0] trunc_ln55_107_reg_3358;
reg   [15:0] trunc_ln55_108_reg_3363;
reg   [15:0] trunc_ln55_109_reg_3368;
reg   [15:0] trunc_ln55_110_reg_3373;
reg   [15:0] trunc_ln55_111_reg_3378;
reg   [15:0] trunc_ln55_112_reg_3383;
reg   [15:0] trunc_ln55_113_reg_3388;
reg   [15:0] trunc_ln55_114_reg_3393;
reg   [15:0] trunc_ln55_115_reg_3398;
reg   [15:0] trunc_ln55_116_reg_3403;
reg   [15:0] trunc_ln55_117_reg_3408;
reg   [15:0] trunc_ln55_118_reg_3413;
reg   [15:0] trunc_ln55_119_reg_3418;
reg   [15:0] trunc_ln55_120_reg_3423;
reg   [15:0] trunc_ln55_121_reg_3428;
reg   [15:0] trunc_ln55_122_reg_3433;
reg   [15:0] trunc_ln55_123_reg_3438;
reg   [14:0] trunc_ln55_124_reg_3443;
wire   [15:0] add_ln55_66_fu_2683_p2;
wire   [15:0] add_ln55_70_fu_2703_p2;
wire   [15:0] add_ln55_74_fu_2723_p2;
wire   [15:0] add_ln55_78_fu_2743_p2;
wire   [15:0] add_ln55_82_fu_2763_p2;
wire   [15:0] add_ln55_86_fu_2783_p2;
wire   [15:0] add_ln55_90_fu_2803_p2;
wire   [15:0] add_ln55_94_fu_2823_p2;
wire   [15:0] add_ln55_98_fu_2843_p2;
wire   [15:0] add_ln55_102_fu_2863_p2;
wire   [15:0] add_ln55_106_fu_2883_p2;
wire   [15:0] add_ln55_110_fu_2903_p2;
wire   [15:0] add_ln55_114_fu_2923_p2;
wire   [15:0] add_ln55_118_fu_2943_p2;
wire   [15:0] add_ln55_122_fu_2963_p2;
wire   [15:0] add_ln55_126_fu_2987_p2;
wire    ap_loop_init;
reg   [3:0] ap_phi_mux_w_index3_phi_fu_388_p6;
reg   [1023:0] ap_phi_mux_input_1_load_phi_phi_fu_402_p4;
wire   [1023:0] ap_phi_reg_pp0_iter0_input_1_load_phi_reg_398;
reg   [15:0] ap_phi_mux_res_0_034_phi_fu_415_p6;
reg    ap_loop_init_pp0_iter1_reg;
reg    ap_loop_init_pp0_iter2_reg;
reg   [15:0] ap_phi_mux_res_1_032_phi_fu_429_p6;
reg   [15:0] ap_phi_mux_res_2_030_phi_fu_443_p6;
reg   [15:0] ap_phi_mux_res_3_028_phi_fu_457_p6;
reg   [15:0] ap_phi_mux_res_4_026_phi_fu_471_p6;
reg   [15:0] ap_phi_mux_res_5_024_phi_fu_485_p6;
reg   [15:0] ap_phi_mux_res_6_022_phi_fu_499_p6;
reg   [15:0] ap_phi_mux_res_7_020_phi_fu_513_p6;
reg   [15:0] ap_phi_mux_res_8_018_phi_fu_527_p6;
reg   [15:0] ap_phi_mux_res_9_016_phi_fu_541_p6;
reg   [15:0] ap_phi_mux_res_10_014_phi_fu_555_p6;
reg   [15:0] ap_phi_mux_res_11_012_phi_fu_569_p6;
reg   [15:0] ap_phi_mux_res_12_010_phi_fu_583_p6;
reg   [15:0] ap_phi_mux_res_13_08_phi_fu_597_p6;
reg   [15:0] ap_phi_mux_res_1445_06_phi_fu_611_p6;
reg   [15:0] ap_phi_mux_res_15_04_phi_fu_625_p6;
wire   [63:0] zext_ln43_fu_635_p1;
wire   [7:0] shl_ln_fu_640_p3;
wire   [1023:0] empty_fu_648_p1;
wire   [1023:0] empty_17_fu_652_p2;
wire  signed [8:0] add_ln56_cast_cast_fu_662_p4;
wire   [1023:0] empty_18_fu_672_p1;
wire   [1023:0] empty_19_fu_676_p2;
wire   [9:0] add_ln56_1_cast_cast_fu_686_p4;
wire   [1023:0] empty_20_fu_696_p1;
wire   [1023:0] empty_21_fu_700_p2;
wire  signed [9:0] add_ln56_2_cast_cast_cast_cast_cast_fu_710_p1;
wire   [1023:0] empty_22_fu_714_p1;
wire   [1023:0] empty_23_fu_718_p2;
wire  signed [15:0] w_fu_740_p1;
wire  signed [15:0] mul_ln55_fu_751_p1;
wire  signed [25:0] sext_ln73_63_fu_748_p1;
wire   [25:0] mul_ln55_fu_751_p2;
wire  signed [15:0] w_63_fu_767_p4;
wire  signed [15:0] mul_ln55_64_fu_784_p1;
wire  signed [25:0] sext_ln73_65_fu_781_p1;
wire   [25:0] mul_ln55_64_fu_784_p2;
wire  signed [15:0] w_64_fu_800_p4;
wire  signed [15:0] mul_ln55_65_fu_817_p1;
wire  signed [25:0] sext_ln73_67_fu_814_p1;
wire   [25:0] mul_ln55_65_fu_817_p2;
wire  signed [15:0] w_65_fu_833_p4;
wire  signed [15:0] mul_ln55_66_fu_853_p1;
wire  signed [25:0] sext_ln73_69_fu_847_p1;
wire   [25:0] mul_ln55_66_fu_853_p2;
wire  signed [15:0] w_66_fu_869_p4;
wire  signed [15:0] mul_ln55_67_fu_883_p1;
wire   [25:0] mul_ln55_67_fu_883_p2;
wire  signed [15:0] w_67_fu_899_p4;
wire  signed [15:0] mul_ln55_68_fu_913_p1;
wire   [25:0] mul_ln55_68_fu_913_p2;
wire  signed [15:0] w_68_fu_929_p4;
wire  signed [15:0] mul_ln55_69_fu_943_p1;
wire   [25:0] mul_ln55_69_fu_943_p2;
wire  signed [15:0] w_69_fu_959_p4;
wire  signed [15:0] mul_ln55_70_fu_973_p1;
wire   [25:0] mul_ln55_70_fu_973_p2;
wire  signed [15:0] w_70_fu_989_p4;
wire  signed [15:0] mul_ln55_71_fu_1003_p1;
wire   [25:0] mul_ln55_71_fu_1003_p2;
wire  signed [15:0] w_71_fu_1019_p4;
wire  signed [15:0] mul_ln55_72_fu_1033_p1;
wire   [25:0] mul_ln55_72_fu_1033_p2;
wire  signed [15:0] w_72_fu_1049_p4;
wire  signed [15:0] mul_ln55_73_fu_1063_p1;
wire   [25:0] mul_ln55_73_fu_1063_p2;
wire  signed [15:0] w_73_fu_1079_p4;
wire  signed [15:0] mul_ln55_74_fu_1093_p1;
wire   [25:0] mul_ln55_74_fu_1093_p2;
wire  signed [15:0] w_74_fu_1109_p4;
wire  signed [15:0] mul_ln55_75_fu_1123_p1;
wire   [25:0] mul_ln55_75_fu_1123_p2;
wire  signed [15:0] w_75_fu_1139_p4;
wire  signed [15:0] mul_ln55_76_fu_1153_p1;
wire   [25:0] mul_ln55_76_fu_1153_p2;
wire  signed [15:0] w_76_fu_1169_p4;
wire  signed [15:0] mul_ln55_77_fu_1183_p1;
wire   [25:0] mul_ln55_77_fu_1183_p2;
wire  signed [15:0] w_77_fu_1199_p4;
wire  signed [15:0] mul_ln55_78_fu_1213_p1;
wire   [25:0] mul_ln55_78_fu_1213_p2;
wire  signed [15:0] w_78_fu_1229_p4;
wire  signed [15:0] mul_ln55_79_fu_1243_p1;
wire   [25:0] mul_ln55_79_fu_1243_p2;
wire  signed [15:0] w_79_fu_1259_p4;
wire  signed [15:0] mul_ln55_80_fu_1273_p1;
wire   [25:0] mul_ln55_80_fu_1273_p2;
wire  signed [15:0] w_80_fu_1289_p4;
wire  signed [15:0] mul_ln55_81_fu_1303_p1;
wire   [25:0] mul_ln55_81_fu_1303_p2;
wire  signed [15:0] w_81_fu_1319_p4;
wire  signed [15:0] mul_ln55_82_fu_1333_p1;
wire   [25:0] mul_ln55_82_fu_1333_p2;
wire  signed [15:0] w_82_fu_1349_p4;
wire  signed [15:0] mul_ln55_83_fu_1363_p1;
wire   [25:0] mul_ln55_83_fu_1363_p2;
wire  signed [15:0] w_83_fu_1379_p4;
wire  signed [15:0] mul_ln55_84_fu_1393_p1;
wire   [25:0] mul_ln55_84_fu_1393_p2;
wire  signed [15:0] w_84_fu_1409_p4;
wire  signed [15:0] mul_ln55_85_fu_1423_p1;
wire   [25:0] mul_ln55_85_fu_1423_p2;
wire  signed [15:0] w_85_fu_1439_p4;
wire  signed [15:0] mul_ln55_86_fu_1453_p1;
wire   [25:0] mul_ln55_86_fu_1453_p2;
wire  signed [15:0] w_86_fu_1469_p4;
wire  signed [15:0] mul_ln55_87_fu_1483_p1;
wire   [25:0] mul_ln55_87_fu_1483_p2;
wire  signed [15:0] w_87_fu_1499_p4;
wire  signed [15:0] mul_ln55_88_fu_1513_p1;
wire   [25:0] mul_ln55_88_fu_1513_p2;
wire  signed [15:0] w_88_fu_1529_p4;
wire  signed [15:0] mul_ln55_89_fu_1543_p1;
wire   [25:0] mul_ln55_89_fu_1543_p2;
wire  signed [15:0] w_89_fu_1559_p4;
wire  signed [15:0] mul_ln55_90_fu_1573_p1;
wire   [25:0] mul_ln55_90_fu_1573_p2;
wire  signed [15:0] w_90_fu_1589_p4;
wire  signed [15:0] mul_ln55_91_fu_1603_p1;
wire   [25:0] mul_ln55_91_fu_1603_p2;
wire  signed [15:0] w_91_fu_1619_p4;
wire  signed [15:0] mul_ln55_92_fu_1633_p1;
wire   [25:0] mul_ln55_92_fu_1633_p2;
wire  signed [15:0] w_92_fu_1649_p4;
wire  signed [15:0] mul_ln55_93_fu_1663_p1;
wire   [25:0] mul_ln55_93_fu_1663_p2;
wire  signed [15:0] w_93_fu_1679_p4;
wire  signed [15:0] mul_ln55_94_fu_1693_p1;
wire   [25:0] mul_ln55_94_fu_1693_p2;
wire  signed [15:0] w_94_fu_1709_p4;
wire  signed [15:0] mul_ln55_95_fu_1723_p1;
wire   [25:0] mul_ln55_95_fu_1723_p2;
wire  signed [15:0] w_95_fu_1739_p4;
wire  signed [15:0] mul_ln55_96_fu_1753_p1;
wire   [25:0] mul_ln55_96_fu_1753_p2;
wire  signed [15:0] w_96_fu_1769_p4;
wire  signed [15:0] mul_ln55_97_fu_1783_p1;
wire   [25:0] mul_ln55_97_fu_1783_p2;
wire  signed [15:0] w_97_fu_1799_p4;
wire  signed [15:0] mul_ln55_98_fu_1813_p1;
wire   [25:0] mul_ln55_98_fu_1813_p2;
wire  signed [15:0] w_98_fu_1829_p4;
wire  signed [15:0] mul_ln55_99_fu_1843_p1;
wire   [25:0] mul_ln55_99_fu_1843_p2;
wire  signed [15:0] w_99_fu_1859_p4;
wire  signed [15:0] mul_ln55_100_fu_1873_p1;
wire   [25:0] mul_ln55_100_fu_1873_p2;
wire  signed [15:0] w_100_fu_1889_p4;
wire  signed [15:0] mul_ln55_101_fu_1903_p1;
wire   [25:0] mul_ln55_101_fu_1903_p2;
wire  signed [15:0] w_101_fu_1919_p4;
wire  signed [15:0] mul_ln55_102_fu_1933_p1;
wire   [25:0] mul_ln55_102_fu_1933_p2;
wire  signed [15:0] w_102_fu_1949_p4;
wire  signed [15:0] mul_ln55_103_fu_1963_p1;
wire   [25:0] mul_ln55_103_fu_1963_p2;
wire  signed [15:0] w_103_fu_1979_p4;
wire  signed [15:0] mul_ln55_104_fu_1993_p1;
wire   [25:0] mul_ln55_104_fu_1993_p2;
wire  signed [15:0] w_104_fu_2009_p4;
wire  signed [15:0] mul_ln55_105_fu_2023_p1;
wire   [25:0] mul_ln55_105_fu_2023_p2;
wire  signed [15:0] w_105_fu_2039_p4;
wire  signed [15:0] mul_ln55_106_fu_2053_p1;
wire   [25:0] mul_ln55_106_fu_2053_p2;
wire  signed [15:0] w_106_fu_2069_p4;
wire  signed [15:0] mul_ln55_107_fu_2083_p1;
wire   [25:0] mul_ln55_107_fu_2083_p2;
wire  signed [15:0] w_107_fu_2099_p4;
wire  signed [15:0] mul_ln55_108_fu_2113_p1;
wire   [25:0] mul_ln55_108_fu_2113_p2;
wire  signed [15:0] w_108_fu_2129_p4;
wire  signed [15:0] mul_ln55_109_fu_2143_p1;
wire   [25:0] mul_ln55_109_fu_2143_p2;
wire  signed [15:0] w_109_fu_2159_p4;
wire  signed [15:0] mul_ln55_110_fu_2173_p1;
wire   [25:0] mul_ln55_110_fu_2173_p2;
wire  signed [15:0] w_110_fu_2189_p4;
wire  signed [15:0] mul_ln55_111_fu_2203_p1;
wire   [25:0] mul_ln55_111_fu_2203_p2;
wire  signed [15:0] w_111_fu_2219_p4;
wire  signed [15:0] mul_ln55_112_fu_2233_p1;
wire   [25:0] mul_ln55_112_fu_2233_p2;
wire  signed [15:0] w_112_fu_2249_p4;
wire  signed [15:0] mul_ln55_113_fu_2263_p1;
wire   [25:0] mul_ln55_113_fu_2263_p2;
wire  signed [15:0] w_113_fu_2279_p4;
wire  signed [15:0] mul_ln55_114_fu_2293_p1;
wire   [25:0] mul_ln55_114_fu_2293_p2;
wire  signed [15:0] w_114_fu_2309_p4;
wire  signed [15:0] mul_ln55_115_fu_2323_p1;
wire   [25:0] mul_ln55_115_fu_2323_p2;
wire  signed [15:0] w_115_fu_2339_p4;
wire  signed [15:0] mul_ln55_116_fu_2353_p1;
wire   [25:0] mul_ln55_116_fu_2353_p2;
wire  signed [15:0] w_116_fu_2369_p4;
wire  signed [15:0] mul_ln55_117_fu_2383_p1;
wire   [25:0] mul_ln55_117_fu_2383_p2;
wire  signed [15:0] w_117_fu_2399_p4;
wire  signed [15:0] mul_ln55_118_fu_2413_p1;
wire   [25:0] mul_ln55_118_fu_2413_p2;
wire  signed [15:0] w_118_fu_2429_p4;
wire  signed [15:0] mul_ln55_119_fu_2443_p1;
wire   [25:0] mul_ln55_119_fu_2443_p2;
wire  signed [15:0] w_119_fu_2459_p4;
wire  signed [15:0] mul_ln55_120_fu_2473_p1;
wire   [25:0] mul_ln55_120_fu_2473_p2;
wire  signed [15:0] w_120_fu_2489_p4;
wire  signed [15:0] mul_ln55_121_fu_2503_p1;
wire   [25:0] mul_ln55_121_fu_2503_p2;
wire  signed [15:0] w_121_fu_2519_p4;
wire  signed [15:0] mul_ln55_122_fu_2533_p1;
wire   [25:0] mul_ln55_122_fu_2533_p2;
wire  signed [15:0] w_122_fu_2549_p4;
wire  signed [15:0] mul_ln55_123_fu_2563_p1;
wire   [25:0] mul_ln55_123_fu_2563_p2;
wire  signed [15:0] w_123_fu_2579_p4;
wire  signed [15:0] mul_ln55_124_fu_2593_p1;
wire   [25:0] mul_ln55_124_fu_2593_p2;
wire  signed [15:0] w_124_fu_2609_p4;
wire  signed [15:0] mul_ln55_125_fu_2623_p1;
wire   [25:0] mul_ln55_125_fu_2623_p2;
wire  signed [8:0] tmp_fu_2639_p4;
wire   [24:0] mul_ln55_126_fu_2653_p2;
wire   [15:0] add_ln55_64_fu_2673_p2;
wire   [15:0] add_ln55_fu_2669_p2;
wire   [15:0] add_ln55_65_fu_2677_p2;
wire   [15:0] add_ln55_68_fu_2693_p2;
wire   [15:0] add_ln55_67_fu_2689_p2;
wire   [15:0] add_ln55_69_fu_2697_p2;
wire   [15:0] add_ln55_72_fu_2713_p2;
wire   [15:0] add_ln55_71_fu_2709_p2;
wire   [15:0] add_ln55_73_fu_2717_p2;
wire   [15:0] add_ln55_76_fu_2733_p2;
wire   [15:0] add_ln55_75_fu_2729_p2;
wire   [15:0] add_ln55_77_fu_2737_p2;
wire   [15:0] add_ln55_80_fu_2753_p2;
wire   [15:0] add_ln55_79_fu_2749_p2;
wire   [15:0] add_ln55_81_fu_2757_p2;
wire   [15:0] add_ln55_84_fu_2773_p2;
wire   [15:0] add_ln55_83_fu_2769_p2;
wire   [15:0] add_ln55_85_fu_2777_p2;
wire   [15:0] add_ln55_88_fu_2793_p2;
wire   [15:0] add_ln55_87_fu_2789_p2;
wire   [15:0] add_ln55_89_fu_2797_p2;
wire   [15:0] add_ln55_92_fu_2813_p2;
wire   [15:0] add_ln55_91_fu_2809_p2;
wire   [15:0] add_ln55_93_fu_2817_p2;
wire   [15:0] add_ln55_96_fu_2833_p2;
wire   [15:0] add_ln55_95_fu_2829_p2;
wire   [15:0] add_ln55_97_fu_2837_p2;
wire   [15:0] add_ln55_100_fu_2853_p2;
wire   [15:0] add_ln55_99_fu_2849_p2;
wire   [15:0] add_ln55_101_fu_2857_p2;
wire   [15:0] add_ln55_104_fu_2873_p2;
wire   [15:0] add_ln55_103_fu_2869_p2;
wire   [15:0] add_ln55_105_fu_2877_p2;
wire   [15:0] add_ln55_108_fu_2893_p2;
wire   [15:0] add_ln55_107_fu_2889_p2;
wire   [15:0] add_ln55_109_fu_2897_p2;
wire   [15:0] add_ln55_112_fu_2913_p2;
wire   [15:0] add_ln55_111_fu_2909_p2;
wire   [15:0] add_ln55_113_fu_2917_p2;
wire   [15:0] add_ln55_116_fu_2933_p2;
wire   [15:0] add_ln55_115_fu_2929_p2;
wire   [15:0] add_ln55_117_fu_2937_p2;
wire   [15:0] add_ln55_120_fu_2953_p2;
wire   [15:0] add_ln55_119_fu_2949_p2;
wire   [15:0] add_ln55_121_fu_2957_p2;
wire  signed [15:0] sext_ln55_3_fu_2969_p1;
wire   [15:0] add_ln55_124_fu_2976_p2;
wire   [15:0] add_ln55_123_fu_2972_p2;
wire   [15:0] add_ln55_125_fu_2981_p2;
reg   [15:0] ap_return_0_preg;
reg   [15:0] ap_return_1_preg;
reg   [15:0] ap_return_2_preg;
reg   [15:0] ap_return_3_preg;
reg   [15:0] ap_return_4_preg;
reg   [15:0] ap_return_5_preg;
reg   [15:0] ap_return_6_preg;
reg   [15:0] ap_return_7_preg;
reg   [15:0] ap_return_8_preg;
reg   [15:0] ap_return_9_preg;
reg   [15:0] ap_return_10_preg;
reg   [15:0] ap_return_11_preg;
reg   [15:0] ap_return_12_preg;
reg   [15:0] ap_return_13_preg;
reg   [15:0] ap_return_14_preg;
reg   [15:0] ap_return_15_preg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to1;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_151;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_return_0_preg = 16'd0;
#0 ap_return_1_preg = 16'd0;
#0 ap_return_2_preg = 16'd0;
#0 ap_return_3_preg = 16'd0;
#0 ap_return_4_preg = 16'd0;
#0 ap_return_5_preg = 16'd0;
#0 ap_return_6_preg = 16'd0;
#0 ap_return_7_preg = 16'd0;
#0 ap_return_8_preg = 16'd0;
#0 ap_return_9_preg = 16'd0;
#0 ap_return_10_preg = 16'd0;
#0 ap_return_11_preg = 16'd0;
#0 ap_return_12_preg = 16'd0;
#0 ap_return_13_preg = 16'd0;
#0 ap_return_14_preg = 16'd0;
#0 ap_return_15_preg = 16'd0;
end

myproject_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s_w2_85_ROM_AUbkb #(
    .DataWidth( 1017 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
w2_85_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(w2_85_address0),
    .ce0(w2_85_ce0),
    .q0(w2_85_q0)
);

myproject_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
mul_16s_16s_26_1_1_U1(
    .din0(w_fu_740_p1),
    .din1(mul_ln55_fu_751_p1),
    .dout(mul_ln55_fu_751_p2)
);

myproject_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
mul_16s_16s_26_1_1_U2(
    .din0(w_63_fu_767_p4),
    .din1(mul_ln55_64_fu_784_p1),
    .dout(mul_ln55_64_fu_784_p2)
);

myproject_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
mul_16s_16s_26_1_1_U3(
    .din0(w_64_fu_800_p4),
    .din1(mul_ln55_65_fu_817_p1),
    .dout(mul_ln55_65_fu_817_p2)
);

myproject_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
mul_16s_16s_26_1_1_U4(
    .din0(w_65_fu_833_p4),
    .din1(mul_ln55_66_fu_853_p1),
    .dout(mul_ln55_66_fu_853_p2)
);

myproject_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
mul_16s_16s_26_1_1_U5(
    .din0(w_66_fu_869_p4),
    .din1(mul_ln55_67_fu_883_p1),
    .dout(mul_ln55_67_fu_883_p2)
);

myproject_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
mul_16s_16s_26_1_1_U6(
    .din0(w_67_fu_899_p4),
    .din1(mul_ln55_68_fu_913_p1),
    .dout(mul_ln55_68_fu_913_p2)
);

myproject_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
mul_16s_16s_26_1_1_U7(
    .din0(w_68_fu_929_p4),
    .din1(mul_ln55_69_fu_943_p1),
    .dout(mul_ln55_69_fu_943_p2)
);

myproject_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
mul_16s_16s_26_1_1_U8(
    .din0(w_69_fu_959_p4),
    .din1(mul_ln55_70_fu_973_p1),
    .dout(mul_ln55_70_fu_973_p2)
);

myproject_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
mul_16s_16s_26_1_1_U9(
    .din0(w_70_fu_989_p4),
    .din1(mul_ln55_71_fu_1003_p1),
    .dout(mul_ln55_71_fu_1003_p2)
);

myproject_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
mul_16s_16s_26_1_1_U10(
    .din0(w_71_fu_1019_p4),
    .din1(mul_ln55_72_fu_1033_p1),
    .dout(mul_ln55_72_fu_1033_p2)
);

myproject_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
mul_16s_16s_26_1_1_U11(
    .din0(w_72_fu_1049_p4),
    .din1(mul_ln55_73_fu_1063_p1),
    .dout(mul_ln55_73_fu_1063_p2)
);

myproject_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
mul_16s_16s_26_1_1_U12(
    .din0(w_73_fu_1079_p4),
    .din1(mul_ln55_74_fu_1093_p1),
    .dout(mul_ln55_74_fu_1093_p2)
);

myproject_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
mul_16s_16s_26_1_1_U13(
    .din0(w_74_fu_1109_p4),
    .din1(mul_ln55_75_fu_1123_p1),
    .dout(mul_ln55_75_fu_1123_p2)
);

myproject_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
mul_16s_16s_26_1_1_U14(
    .din0(w_75_fu_1139_p4),
    .din1(mul_ln55_76_fu_1153_p1),
    .dout(mul_ln55_76_fu_1153_p2)
);

myproject_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
mul_16s_16s_26_1_1_U15(
    .din0(w_76_fu_1169_p4),
    .din1(mul_ln55_77_fu_1183_p1),
    .dout(mul_ln55_77_fu_1183_p2)
);

myproject_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
mul_16s_16s_26_1_1_U16(
    .din0(w_77_fu_1199_p4),
    .din1(mul_ln55_78_fu_1213_p1),
    .dout(mul_ln55_78_fu_1213_p2)
);

myproject_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
mul_16s_16s_26_1_1_U17(
    .din0(w_78_fu_1229_p4),
    .din1(mul_ln55_79_fu_1243_p1),
    .dout(mul_ln55_79_fu_1243_p2)
);

myproject_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
mul_16s_16s_26_1_1_U18(
    .din0(w_79_fu_1259_p4),
    .din1(mul_ln55_80_fu_1273_p1),
    .dout(mul_ln55_80_fu_1273_p2)
);

myproject_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
mul_16s_16s_26_1_1_U19(
    .din0(w_80_fu_1289_p4),
    .din1(mul_ln55_81_fu_1303_p1),
    .dout(mul_ln55_81_fu_1303_p2)
);

myproject_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
mul_16s_16s_26_1_1_U20(
    .din0(w_81_fu_1319_p4),
    .din1(mul_ln55_82_fu_1333_p1),
    .dout(mul_ln55_82_fu_1333_p2)
);

myproject_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
mul_16s_16s_26_1_1_U21(
    .din0(w_82_fu_1349_p4),
    .din1(mul_ln55_83_fu_1363_p1),
    .dout(mul_ln55_83_fu_1363_p2)
);

myproject_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
mul_16s_16s_26_1_1_U22(
    .din0(w_83_fu_1379_p4),
    .din1(mul_ln55_84_fu_1393_p1),
    .dout(mul_ln55_84_fu_1393_p2)
);

myproject_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
mul_16s_16s_26_1_1_U23(
    .din0(w_84_fu_1409_p4),
    .din1(mul_ln55_85_fu_1423_p1),
    .dout(mul_ln55_85_fu_1423_p2)
);

myproject_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
mul_16s_16s_26_1_1_U24(
    .din0(w_85_fu_1439_p4),
    .din1(mul_ln55_86_fu_1453_p1),
    .dout(mul_ln55_86_fu_1453_p2)
);

myproject_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
mul_16s_16s_26_1_1_U25(
    .din0(w_86_fu_1469_p4),
    .din1(mul_ln55_87_fu_1483_p1),
    .dout(mul_ln55_87_fu_1483_p2)
);

myproject_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
mul_16s_16s_26_1_1_U26(
    .din0(w_87_fu_1499_p4),
    .din1(mul_ln55_88_fu_1513_p1),
    .dout(mul_ln55_88_fu_1513_p2)
);

myproject_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
mul_16s_16s_26_1_1_U27(
    .din0(w_88_fu_1529_p4),
    .din1(mul_ln55_89_fu_1543_p1),
    .dout(mul_ln55_89_fu_1543_p2)
);

myproject_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
mul_16s_16s_26_1_1_U28(
    .din0(w_89_fu_1559_p4),
    .din1(mul_ln55_90_fu_1573_p1),
    .dout(mul_ln55_90_fu_1573_p2)
);

myproject_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
mul_16s_16s_26_1_1_U29(
    .din0(w_90_fu_1589_p4),
    .din1(mul_ln55_91_fu_1603_p1),
    .dout(mul_ln55_91_fu_1603_p2)
);

myproject_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
mul_16s_16s_26_1_1_U30(
    .din0(w_91_fu_1619_p4),
    .din1(mul_ln55_92_fu_1633_p1),
    .dout(mul_ln55_92_fu_1633_p2)
);

myproject_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
mul_16s_16s_26_1_1_U31(
    .din0(w_92_fu_1649_p4),
    .din1(mul_ln55_93_fu_1663_p1),
    .dout(mul_ln55_93_fu_1663_p2)
);

myproject_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
mul_16s_16s_26_1_1_U32(
    .din0(w_93_fu_1679_p4),
    .din1(mul_ln55_94_fu_1693_p1),
    .dout(mul_ln55_94_fu_1693_p2)
);

myproject_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
mul_16s_16s_26_1_1_U33(
    .din0(w_94_fu_1709_p4),
    .din1(mul_ln55_95_fu_1723_p1),
    .dout(mul_ln55_95_fu_1723_p2)
);

myproject_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
mul_16s_16s_26_1_1_U34(
    .din0(w_95_fu_1739_p4),
    .din1(mul_ln55_96_fu_1753_p1),
    .dout(mul_ln55_96_fu_1753_p2)
);

myproject_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
mul_16s_16s_26_1_1_U35(
    .din0(w_96_fu_1769_p4),
    .din1(mul_ln55_97_fu_1783_p1),
    .dout(mul_ln55_97_fu_1783_p2)
);

myproject_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
mul_16s_16s_26_1_1_U36(
    .din0(w_97_fu_1799_p4),
    .din1(mul_ln55_98_fu_1813_p1),
    .dout(mul_ln55_98_fu_1813_p2)
);

myproject_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
mul_16s_16s_26_1_1_U37(
    .din0(w_98_fu_1829_p4),
    .din1(mul_ln55_99_fu_1843_p1),
    .dout(mul_ln55_99_fu_1843_p2)
);

myproject_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
mul_16s_16s_26_1_1_U38(
    .din0(w_99_fu_1859_p4),
    .din1(mul_ln55_100_fu_1873_p1),
    .dout(mul_ln55_100_fu_1873_p2)
);

myproject_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
mul_16s_16s_26_1_1_U39(
    .din0(w_100_fu_1889_p4),
    .din1(mul_ln55_101_fu_1903_p1),
    .dout(mul_ln55_101_fu_1903_p2)
);

myproject_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
mul_16s_16s_26_1_1_U40(
    .din0(w_101_fu_1919_p4),
    .din1(mul_ln55_102_fu_1933_p1),
    .dout(mul_ln55_102_fu_1933_p2)
);

myproject_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
mul_16s_16s_26_1_1_U41(
    .din0(w_102_fu_1949_p4),
    .din1(mul_ln55_103_fu_1963_p1),
    .dout(mul_ln55_103_fu_1963_p2)
);

myproject_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
mul_16s_16s_26_1_1_U42(
    .din0(w_103_fu_1979_p4),
    .din1(mul_ln55_104_fu_1993_p1),
    .dout(mul_ln55_104_fu_1993_p2)
);

myproject_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
mul_16s_16s_26_1_1_U43(
    .din0(w_104_fu_2009_p4),
    .din1(mul_ln55_105_fu_2023_p1),
    .dout(mul_ln55_105_fu_2023_p2)
);

myproject_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
mul_16s_16s_26_1_1_U44(
    .din0(w_105_fu_2039_p4),
    .din1(mul_ln55_106_fu_2053_p1),
    .dout(mul_ln55_106_fu_2053_p2)
);

myproject_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
mul_16s_16s_26_1_1_U45(
    .din0(w_106_fu_2069_p4),
    .din1(mul_ln55_107_fu_2083_p1),
    .dout(mul_ln55_107_fu_2083_p2)
);

myproject_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
mul_16s_16s_26_1_1_U46(
    .din0(w_107_fu_2099_p4),
    .din1(mul_ln55_108_fu_2113_p1),
    .dout(mul_ln55_108_fu_2113_p2)
);

myproject_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
mul_16s_16s_26_1_1_U47(
    .din0(w_108_fu_2129_p4),
    .din1(mul_ln55_109_fu_2143_p1),
    .dout(mul_ln55_109_fu_2143_p2)
);

myproject_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
mul_16s_16s_26_1_1_U48(
    .din0(w_109_fu_2159_p4),
    .din1(mul_ln55_110_fu_2173_p1),
    .dout(mul_ln55_110_fu_2173_p2)
);

myproject_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
mul_16s_16s_26_1_1_U49(
    .din0(w_110_fu_2189_p4),
    .din1(mul_ln55_111_fu_2203_p1),
    .dout(mul_ln55_111_fu_2203_p2)
);

myproject_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
mul_16s_16s_26_1_1_U50(
    .din0(w_111_fu_2219_p4),
    .din1(mul_ln55_112_fu_2233_p1),
    .dout(mul_ln55_112_fu_2233_p2)
);

myproject_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
mul_16s_16s_26_1_1_U51(
    .din0(w_112_fu_2249_p4),
    .din1(mul_ln55_113_fu_2263_p1),
    .dout(mul_ln55_113_fu_2263_p2)
);

myproject_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
mul_16s_16s_26_1_1_U52(
    .din0(w_113_fu_2279_p4),
    .din1(mul_ln55_114_fu_2293_p1),
    .dout(mul_ln55_114_fu_2293_p2)
);

myproject_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
mul_16s_16s_26_1_1_U53(
    .din0(w_114_fu_2309_p4),
    .din1(mul_ln55_115_fu_2323_p1),
    .dout(mul_ln55_115_fu_2323_p2)
);

myproject_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
mul_16s_16s_26_1_1_U54(
    .din0(w_115_fu_2339_p4),
    .din1(mul_ln55_116_fu_2353_p1),
    .dout(mul_ln55_116_fu_2353_p2)
);

myproject_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
mul_16s_16s_26_1_1_U55(
    .din0(w_116_fu_2369_p4),
    .din1(mul_ln55_117_fu_2383_p1),
    .dout(mul_ln55_117_fu_2383_p2)
);

myproject_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
mul_16s_16s_26_1_1_U56(
    .din0(w_117_fu_2399_p4),
    .din1(mul_ln55_118_fu_2413_p1),
    .dout(mul_ln55_118_fu_2413_p2)
);

myproject_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
mul_16s_16s_26_1_1_U57(
    .din0(w_118_fu_2429_p4),
    .din1(mul_ln55_119_fu_2443_p1),
    .dout(mul_ln55_119_fu_2443_p2)
);

myproject_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
mul_16s_16s_26_1_1_U58(
    .din0(w_119_fu_2459_p4),
    .din1(mul_ln55_120_fu_2473_p1),
    .dout(mul_ln55_120_fu_2473_p2)
);

myproject_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
mul_16s_16s_26_1_1_U59(
    .din0(w_120_fu_2489_p4),
    .din1(mul_ln55_121_fu_2503_p1),
    .dout(mul_ln55_121_fu_2503_p2)
);

myproject_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
mul_16s_16s_26_1_1_U60(
    .din0(w_121_fu_2519_p4),
    .din1(mul_ln55_122_fu_2533_p1),
    .dout(mul_ln55_122_fu_2533_p2)
);

myproject_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
mul_16s_16s_26_1_1_U61(
    .din0(w_122_fu_2549_p4),
    .din1(mul_ln55_123_fu_2563_p1),
    .dout(mul_ln55_123_fu_2563_p2)
);

myproject_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
mul_16s_16s_26_1_1_U62(
    .din0(w_123_fu_2579_p4),
    .din1(mul_ln55_124_fu_2593_p1),
    .dout(mul_ln55_124_fu_2593_p2)
);

myproject_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
mul_16s_16s_26_1_1_U63(
    .din0(w_124_fu_2609_p4),
    .din1(mul_ln55_125_fu_2623_p1),
    .dout(mul_ln55_125_fu_2623_p2)
);

myproject_mul_16s_9s_25_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 25 ))
mul_16s_9s_25_1_1_U64(
    .din0(a_3_reg_3113),
    .din1(tmp_fu_2639_p4),
    .dout(mul_ln55_126_fu_2653_p2)
);

myproject_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(ap_continue)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_0_preg <= 16'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln43_reg_3124_pp0_iter1_reg == 1'd1))) begin
            ap_return_0_preg <= add_ln55_66_fu_2683_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_10_preg <= 16'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln43_reg_3124_pp0_iter1_reg == 1'd1))) begin
            ap_return_10_preg <= add_ln55_106_fu_2883_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_11_preg <= 16'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln43_reg_3124_pp0_iter1_reg == 1'd1))) begin
            ap_return_11_preg <= add_ln55_110_fu_2903_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_12_preg <= 16'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln43_reg_3124_pp0_iter1_reg == 1'd1))) begin
            ap_return_12_preg <= add_ln55_114_fu_2923_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_13_preg <= 16'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln43_reg_3124_pp0_iter1_reg == 1'd1))) begin
            ap_return_13_preg <= add_ln55_118_fu_2943_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_14_preg <= 16'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln43_reg_3124_pp0_iter1_reg == 1'd1))) begin
            ap_return_14_preg <= add_ln55_122_fu_2963_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_15_preg <= 16'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln43_reg_3124_pp0_iter1_reg == 1'd1))) begin
            ap_return_15_preg <= add_ln55_126_fu_2987_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_1_preg <= 16'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln43_reg_3124_pp0_iter1_reg == 1'd1))) begin
            ap_return_1_preg <= add_ln55_70_fu_2703_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_2_preg <= 16'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln43_reg_3124_pp0_iter1_reg == 1'd1))) begin
            ap_return_2_preg <= add_ln55_74_fu_2723_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_3_preg <= 16'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln43_reg_3124_pp0_iter1_reg == 1'd1))) begin
            ap_return_3_preg <= add_ln55_78_fu_2743_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_4_preg <= 16'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln43_reg_3124_pp0_iter1_reg == 1'd1))) begin
            ap_return_4_preg <= add_ln55_82_fu_2763_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_5_preg <= 16'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln43_reg_3124_pp0_iter1_reg == 1'd1))) begin
            ap_return_5_preg <= add_ln55_86_fu_2783_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_6_preg <= 16'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln43_reg_3124_pp0_iter1_reg == 1'd1))) begin
            ap_return_6_preg <= add_ln55_90_fu_2803_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_7_preg <= 16'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln43_reg_3124_pp0_iter1_reg == 1'd1))) begin
            ap_return_7_preg <= add_ln55_94_fu_2823_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_8_preg <= 16'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln43_reg_3124_pp0_iter1_reg == 1'd1))) begin
            ap_return_8_preg <= add_ln55_98_fu_2843_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_9_preg <= 16'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln43_reg_3124_pp0_iter1_reg == 1'd1))) begin
            ap_return_9_preg <= add_ln55_102_fu_2863_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln43_reg_3124 == 1'd0))) begin
        do_init_reg_357 <= 1'd0;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln43_reg_3124 == 1'd1)) | ((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        do_init_reg_357 <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_151)) begin
        if ((ap_phi_mux_do_init_phi_fu_360_p6 == 1'd0)) begin
            input_1_load_phi_reg_398 <= input_1_load_phi_reg_398;
        end else if ((ap_phi_mux_do_init_phi_fu_360_p6 == 1'd1)) begin
            input_1_load_phi_reg_398 <= input_1;
        end else if (~(icmp_ln43_fu_734_p2 == 1'd1)) begin
            input_1_load_phi_reg_398 <= ap_phi_reg_pp0_iter0_input_1_load_phi_reg_398;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((icmp_ln43_reg_3124_pp0_iter1_reg == 1'd1)) begin
            res_0_034_reg_411 <= 16'd65512;
        end else if ((icmp_ln43_reg_3124_pp0_iter1_reg == 1'd0)) begin
            res_0_034_reg_411 <= add_ln55_66_fu_2683_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((icmp_ln43_reg_3124_pp0_iter1_reg == 1'd1)) begin
            res_10_014_reg_551 <= 16'd65507;
        end else if ((icmp_ln43_reg_3124_pp0_iter1_reg == 1'd0)) begin
            res_10_014_reg_551 <= add_ln55_106_fu_2883_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((icmp_ln43_reg_3124_pp0_iter1_reg == 1'd1)) begin
            res_11_012_reg_565 <= 16'd65513;
        end else if ((icmp_ln43_reg_3124_pp0_iter1_reg == 1'd0)) begin
            res_11_012_reg_565 <= add_ln55_110_fu_2903_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((icmp_ln43_reg_3124_pp0_iter1_reg == 1'd1)) begin
            res_12_010_reg_579 <= 16'd65530;
        end else if ((icmp_ln43_reg_3124_pp0_iter1_reg == 1'd0)) begin
            res_12_010_reg_579 <= add_ln55_114_fu_2923_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((icmp_ln43_reg_3124_pp0_iter1_reg == 1'd1)) begin
            res_13_08_reg_593 <= 16'd47;
        end else if ((icmp_ln43_reg_3124_pp0_iter1_reg == 1'd0)) begin
            res_13_08_reg_593 <= add_ln55_118_fu_2943_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((icmp_ln43_reg_3124_pp0_iter1_reg == 1'd1)) begin
            res_1445_06_reg_607 <= 16'd44;
        end else if ((icmp_ln43_reg_3124_pp0_iter1_reg == 1'd0)) begin
            res_1445_06_reg_607 <= add_ln55_122_fu_2963_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((icmp_ln43_reg_3124_pp0_iter1_reg == 1'd1)) begin
            res_15_04_reg_621 <= 16'd45;
        end else if ((icmp_ln43_reg_3124_pp0_iter1_reg == 1'd0)) begin
            res_15_04_reg_621 <= add_ln55_126_fu_2987_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((icmp_ln43_reg_3124_pp0_iter1_reg == 1'd1)) begin
            res_1_032_reg_425 <= 16'd46;
        end else if ((icmp_ln43_reg_3124_pp0_iter1_reg == 1'd0)) begin
            res_1_032_reg_425 <= add_ln55_70_fu_2703_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((icmp_ln43_reg_3124_pp0_iter1_reg == 1'd1)) begin
            res_2_030_reg_439 <= 16'd46;
        end else if ((icmp_ln43_reg_3124_pp0_iter1_reg == 1'd0)) begin
            res_2_030_reg_439 <= add_ln55_74_fu_2723_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((icmp_ln43_reg_3124_pp0_iter1_reg == 1'd1)) begin
            res_3_028_reg_453 <= 16'd9;
        end else if ((icmp_ln43_reg_3124_pp0_iter1_reg == 1'd0)) begin
            res_3_028_reg_453 <= add_ln55_78_fu_2743_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((icmp_ln43_reg_3124_pp0_iter1_reg == 1'd1)) begin
            res_4_026_reg_467 <= 16'd19;
        end else if ((icmp_ln43_reg_3124_pp0_iter1_reg == 1'd0)) begin
            res_4_026_reg_467 <= add_ln55_82_fu_2763_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((icmp_ln43_reg_3124_pp0_iter1_reg == 1'd1)) begin
            res_5_024_reg_481 <= 16'd65507;
        end else if ((icmp_ln43_reg_3124_pp0_iter1_reg == 1'd0)) begin
            res_5_024_reg_481 <= add_ln55_86_fu_2783_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((icmp_ln43_reg_3124_pp0_iter1_reg == 1'd1)) begin
            res_6_022_reg_495 <= 16'd46;
        end else if ((icmp_ln43_reg_3124_pp0_iter1_reg == 1'd0)) begin
            res_6_022_reg_495 <= add_ln55_90_fu_2803_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((icmp_ln43_reg_3124_pp0_iter1_reg == 1'd1)) begin
            res_7_020_reg_509 <= 16'd65508;
        end else if ((icmp_ln43_reg_3124_pp0_iter1_reg == 1'd0)) begin
            res_7_020_reg_509 <= add_ln55_94_fu_2823_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((icmp_ln43_reg_3124_pp0_iter1_reg == 1'd1)) begin
            res_8_018_reg_523 <= 16'd22;
        end else if ((icmp_ln43_reg_3124_pp0_iter1_reg == 1'd0)) begin
            res_8_018_reg_523 <= add_ln55_98_fu_2843_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((icmp_ln43_reg_3124_pp0_iter1_reg == 1'd1)) begin
            res_9_016_reg_537 <= 16'd65511;
        end else if ((icmp_ln43_reg_3124_pp0_iter1_reg == 1'd0)) begin
            res_9_016_reg_537 <= add_ln55_102_fu_2863_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln43_reg_3124 == 1'd0))) begin
        w_index3_reg_385 <= w_index_reg_3119;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln43_reg_3124 == 1'd1)) | ((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        w_index3_reg_385 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        a_1_reg_3103 <= a_1_fu_682_p1;
        a_2_reg_3108 <= a_2_fu_706_p1;
        a_3_reg_3113 <= a_3_fu_724_p1;
        a_reg_3093 <= a_fu_658_p1;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_init_pp0_iter1_reg <= ap_loop_init;
        ap_loop_init_pp0_iter2_reg <= ap_loop_init_pp0_iter1_reg;
        icmp_ln43_reg_3124 <= icmp_ln43_fu_734_p2;
        icmp_ln43_reg_3124_pp0_iter1_reg <= icmp_ln43_reg_3124;
        trunc_ln55_100_reg_3323 <= {{mul_ln55_102_fu_1933_p2[25:10]}};
        trunc_ln55_101_reg_3328 <= {{mul_ln55_103_fu_1963_p2[25:10]}};
        trunc_ln55_102_reg_3333 <= {{mul_ln55_104_fu_1993_p2[25:10]}};
        trunc_ln55_103_reg_3338 <= {{mul_ln55_105_fu_2023_p2[25:10]}};
        trunc_ln55_104_reg_3343 <= {{mul_ln55_106_fu_2053_p2[25:10]}};
        trunc_ln55_105_reg_3348 <= {{mul_ln55_107_fu_2083_p2[25:10]}};
        trunc_ln55_106_reg_3353 <= {{mul_ln55_108_fu_2113_p2[25:10]}};
        trunc_ln55_107_reg_3358 <= {{mul_ln55_109_fu_2143_p2[25:10]}};
        trunc_ln55_108_reg_3363 <= {{mul_ln55_110_fu_2173_p2[25:10]}};
        trunc_ln55_109_reg_3368 <= {{mul_ln55_111_fu_2203_p2[25:10]}};
        trunc_ln55_110_reg_3373 <= {{mul_ln55_112_fu_2233_p2[25:10]}};
        trunc_ln55_111_reg_3378 <= {{mul_ln55_113_fu_2263_p2[25:10]}};
        trunc_ln55_112_reg_3383 <= {{mul_ln55_114_fu_2293_p2[25:10]}};
        trunc_ln55_113_reg_3388 <= {{mul_ln55_115_fu_2323_p2[25:10]}};
        trunc_ln55_114_reg_3393 <= {{mul_ln55_116_fu_2353_p2[25:10]}};
        trunc_ln55_115_reg_3398 <= {{mul_ln55_117_fu_2383_p2[25:10]}};
        trunc_ln55_116_reg_3403 <= {{mul_ln55_118_fu_2413_p2[25:10]}};
        trunc_ln55_117_reg_3408 <= {{mul_ln55_119_fu_2443_p2[25:10]}};
        trunc_ln55_118_reg_3413 <= {{mul_ln55_120_fu_2473_p2[25:10]}};
        trunc_ln55_119_reg_3418 <= {{mul_ln55_121_fu_2503_p2[25:10]}};
        trunc_ln55_120_reg_3423 <= {{mul_ln55_122_fu_2533_p2[25:10]}};
        trunc_ln55_121_reg_3428 <= {{mul_ln55_123_fu_2563_p2[25:10]}};
        trunc_ln55_122_reg_3433 <= {{mul_ln55_124_fu_2593_p2[25:10]}};
        trunc_ln55_123_reg_3438 <= {{mul_ln55_125_fu_2623_p2[25:10]}};
        trunc_ln55_124_reg_3443 <= {{mul_ln55_126_fu_2653_p2[24:10]}};
        trunc_ln55_63_reg_3138 <= {{mul_ln55_65_fu_817_p2[25:10]}};
        trunc_ln55_64_reg_3143 <= {{mul_ln55_66_fu_853_p2[25:10]}};
        trunc_ln55_65_reg_3148 <= {{mul_ln55_67_fu_883_p2[25:10]}};
        trunc_ln55_66_reg_3153 <= {{mul_ln55_68_fu_913_p2[25:10]}};
        trunc_ln55_67_reg_3158 <= {{mul_ln55_69_fu_943_p2[25:10]}};
        trunc_ln55_68_reg_3163 <= {{mul_ln55_70_fu_973_p2[25:10]}};
        trunc_ln55_69_reg_3168 <= {{mul_ln55_71_fu_1003_p2[25:10]}};
        trunc_ln55_70_reg_3173 <= {{mul_ln55_72_fu_1033_p2[25:10]}};
        trunc_ln55_71_reg_3178 <= {{mul_ln55_73_fu_1063_p2[25:10]}};
        trunc_ln55_72_reg_3183 <= {{mul_ln55_74_fu_1093_p2[25:10]}};
        trunc_ln55_73_reg_3188 <= {{mul_ln55_75_fu_1123_p2[25:10]}};
        trunc_ln55_74_reg_3193 <= {{mul_ln55_76_fu_1153_p2[25:10]}};
        trunc_ln55_75_reg_3198 <= {{mul_ln55_77_fu_1183_p2[25:10]}};
        trunc_ln55_76_reg_3203 <= {{mul_ln55_78_fu_1213_p2[25:10]}};
        trunc_ln55_77_reg_3208 <= {{mul_ln55_79_fu_1243_p2[25:10]}};
        trunc_ln55_78_reg_3213 <= {{mul_ln55_80_fu_1273_p2[25:10]}};
        trunc_ln55_79_reg_3218 <= {{mul_ln55_81_fu_1303_p2[25:10]}};
        trunc_ln55_80_reg_3223 <= {{mul_ln55_82_fu_1333_p2[25:10]}};
        trunc_ln55_81_reg_3228 <= {{mul_ln55_83_fu_1363_p2[25:10]}};
        trunc_ln55_82_reg_3233 <= {{mul_ln55_84_fu_1393_p2[25:10]}};
        trunc_ln55_83_reg_3238 <= {{mul_ln55_85_fu_1423_p2[25:10]}};
        trunc_ln55_84_reg_3243 <= {{mul_ln55_86_fu_1453_p2[25:10]}};
        trunc_ln55_85_reg_3248 <= {{mul_ln55_87_fu_1483_p2[25:10]}};
        trunc_ln55_86_reg_3253 <= {{mul_ln55_88_fu_1513_p2[25:10]}};
        trunc_ln55_87_reg_3258 <= {{mul_ln55_89_fu_1543_p2[25:10]}};
        trunc_ln55_88_reg_3263 <= {{mul_ln55_90_fu_1573_p2[25:10]}};
        trunc_ln55_89_reg_3268 <= {{mul_ln55_91_fu_1603_p2[25:10]}};
        trunc_ln55_90_reg_3273 <= {{mul_ln55_92_fu_1633_p2[25:10]}};
        trunc_ln55_91_reg_3278 <= {{mul_ln55_93_fu_1663_p2[25:10]}};
        trunc_ln55_92_reg_3283 <= {{mul_ln55_94_fu_1693_p2[25:10]}};
        trunc_ln55_93_reg_3288 <= {{mul_ln55_95_fu_1723_p2[25:10]}};
        trunc_ln55_94_reg_3293 <= {{mul_ln55_96_fu_1753_p2[25:10]}};
        trunc_ln55_95_reg_3298 <= {{mul_ln55_97_fu_1783_p2[25:10]}};
        trunc_ln55_96_reg_3303 <= {{mul_ln55_98_fu_1813_p2[25:10]}};
        trunc_ln55_97_reg_3308 <= {{mul_ln55_99_fu_1843_p2[25:10]}};
        trunc_ln55_98_reg_3313 <= {{mul_ln55_100_fu_1873_p2[25:10]}};
        trunc_ln55_99_reg_3318 <= {{mul_ln55_101_fu_1903_p2[25:10]}};
        trunc_ln55_s_reg_3133 <= {{mul_ln55_64_fu_784_p2[25:10]}};
        trunc_ln_reg_3128 <= {{mul_ln55_fu_751_p2[25:10]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        w_index_reg_3119 <= w_index_fu_728_p2;
    end
end

always @ (*) begin
    if (((icmp_ln43_fu_734_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to1 = 1'b1;
    end else begin
        ap_idle_pp0_0to1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln43_reg_3124 == 1'd0))) begin
        ap_phi_mux_do_init_phi_fu_360_p6 = 1'd0;
    end else if ((((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln43_reg_3124 == 1'd1)) | ((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        ap_phi_mux_do_init_phi_fu_360_p6 = 1'd1;
    end else begin
        ap_phi_mux_do_init_phi_fu_360_p6 = do_init_reg_357;
    end
end

always @ (*) begin
    if ((ap_phi_mux_do_init_phi_fu_360_p6 == 1'd0)) begin
        ap_phi_mux_input_1_load_phi_phi_fu_402_p4 = input_1_load_phi_reg_398;
    end else if ((ap_phi_mux_do_init_phi_fu_360_p6 == 1'd1)) begin
        ap_phi_mux_input_1_load_phi_phi_fu_402_p4 = input_1;
    end else begin
        ap_phi_mux_input_1_load_phi_phi_fu_402_p4 = ap_phi_reg_pp0_iter0_input_1_load_phi_reg_398;
    end
end

always @ (*) begin
    if ((ap_loop_init_pp0_iter2_reg == 1'b1)) begin
        ap_phi_mux_res_0_034_phi_fu_415_p6 = 16'd65512;
    end else begin
        ap_phi_mux_res_0_034_phi_fu_415_p6 = res_0_034_reg_411;
    end
end

always @ (*) begin
    if ((ap_loop_init_pp0_iter2_reg == 1'b1)) begin
        ap_phi_mux_res_10_014_phi_fu_555_p6 = 16'd65507;
    end else begin
        ap_phi_mux_res_10_014_phi_fu_555_p6 = res_10_014_reg_551;
    end
end

always @ (*) begin
    if ((ap_loop_init_pp0_iter2_reg == 1'b1)) begin
        ap_phi_mux_res_11_012_phi_fu_569_p6 = 16'd65513;
    end else begin
        ap_phi_mux_res_11_012_phi_fu_569_p6 = res_11_012_reg_565;
    end
end

always @ (*) begin
    if ((ap_loop_init_pp0_iter2_reg == 1'b1)) begin
        ap_phi_mux_res_12_010_phi_fu_583_p6 = 16'd65530;
    end else begin
        ap_phi_mux_res_12_010_phi_fu_583_p6 = res_12_010_reg_579;
    end
end

always @ (*) begin
    if ((ap_loop_init_pp0_iter2_reg == 1'b1)) begin
        ap_phi_mux_res_13_08_phi_fu_597_p6 = 16'd47;
    end else begin
        ap_phi_mux_res_13_08_phi_fu_597_p6 = res_13_08_reg_593;
    end
end

always @ (*) begin
    if ((ap_loop_init_pp0_iter2_reg == 1'b1)) begin
        ap_phi_mux_res_1445_06_phi_fu_611_p6 = 16'd44;
    end else begin
        ap_phi_mux_res_1445_06_phi_fu_611_p6 = res_1445_06_reg_607;
    end
end

always @ (*) begin
    if ((ap_loop_init_pp0_iter2_reg == 1'b1)) begin
        ap_phi_mux_res_15_04_phi_fu_625_p6 = 16'd45;
    end else begin
        ap_phi_mux_res_15_04_phi_fu_625_p6 = res_15_04_reg_621;
    end
end

always @ (*) begin
    if ((ap_loop_init_pp0_iter2_reg == 1'b1)) begin
        ap_phi_mux_res_1_032_phi_fu_429_p6 = 16'd46;
    end else begin
        ap_phi_mux_res_1_032_phi_fu_429_p6 = res_1_032_reg_425;
    end
end

always @ (*) begin
    if ((ap_loop_init_pp0_iter2_reg == 1'b1)) begin
        ap_phi_mux_res_2_030_phi_fu_443_p6 = 16'd46;
    end else begin
        ap_phi_mux_res_2_030_phi_fu_443_p6 = res_2_030_reg_439;
    end
end

always @ (*) begin
    if ((ap_loop_init_pp0_iter2_reg == 1'b1)) begin
        ap_phi_mux_res_3_028_phi_fu_457_p6 = 16'd9;
    end else begin
        ap_phi_mux_res_3_028_phi_fu_457_p6 = res_3_028_reg_453;
    end
end

always @ (*) begin
    if ((ap_loop_init_pp0_iter2_reg == 1'b1)) begin
        ap_phi_mux_res_4_026_phi_fu_471_p6 = 16'd19;
    end else begin
        ap_phi_mux_res_4_026_phi_fu_471_p6 = res_4_026_reg_467;
    end
end

always @ (*) begin
    if ((ap_loop_init_pp0_iter2_reg == 1'b1)) begin
        ap_phi_mux_res_5_024_phi_fu_485_p6 = 16'd65507;
    end else begin
        ap_phi_mux_res_5_024_phi_fu_485_p6 = res_5_024_reg_481;
    end
end

always @ (*) begin
    if ((ap_loop_init_pp0_iter2_reg == 1'b1)) begin
        ap_phi_mux_res_6_022_phi_fu_499_p6 = 16'd46;
    end else begin
        ap_phi_mux_res_6_022_phi_fu_499_p6 = res_6_022_reg_495;
    end
end

always @ (*) begin
    if ((ap_loop_init_pp0_iter2_reg == 1'b1)) begin
        ap_phi_mux_res_7_020_phi_fu_513_p6 = 16'd65508;
    end else begin
        ap_phi_mux_res_7_020_phi_fu_513_p6 = res_7_020_reg_509;
    end
end

always @ (*) begin
    if ((ap_loop_init_pp0_iter2_reg == 1'b1)) begin
        ap_phi_mux_res_8_018_phi_fu_527_p6 = 16'd22;
    end else begin
        ap_phi_mux_res_8_018_phi_fu_527_p6 = res_8_018_reg_523;
    end
end

always @ (*) begin
    if ((ap_loop_init_pp0_iter2_reg == 1'b1)) begin
        ap_phi_mux_res_9_016_phi_fu_541_p6 = 16'd65511;
    end else begin
        ap_phi_mux_res_9_016_phi_fu_541_p6 = res_9_016_reg_537;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln43_reg_3124 == 1'd0))) begin
        ap_phi_mux_w_index3_phi_fu_388_p6 = w_index_reg_3119;
    end else if ((((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln43_reg_3124 == 1'd1)) | ((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        ap_phi_mux_w_index3_phi_fu_388_p6 = 4'd0;
    end else begin
        ap_phi_mux_w_index3_phi_fu_388_p6 = w_index3_reg_385;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0_0to1 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln43_reg_3124_pp0_iter1_reg == 1'd1))) begin
        ap_return_0 = add_ln55_66_fu_2683_p2;
    end else begin
        ap_return_0 = ap_return_0_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln43_reg_3124_pp0_iter1_reg == 1'd1))) begin
        ap_return_1 = add_ln55_70_fu_2703_p2;
    end else begin
        ap_return_1 = ap_return_1_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln43_reg_3124_pp0_iter1_reg == 1'd1))) begin
        ap_return_10 = add_ln55_106_fu_2883_p2;
    end else begin
        ap_return_10 = ap_return_10_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln43_reg_3124_pp0_iter1_reg == 1'd1))) begin
        ap_return_11 = add_ln55_110_fu_2903_p2;
    end else begin
        ap_return_11 = ap_return_11_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln43_reg_3124_pp0_iter1_reg == 1'd1))) begin
        ap_return_12 = add_ln55_114_fu_2923_p2;
    end else begin
        ap_return_12 = ap_return_12_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln43_reg_3124_pp0_iter1_reg == 1'd1))) begin
        ap_return_13 = add_ln55_118_fu_2943_p2;
    end else begin
        ap_return_13 = ap_return_13_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln43_reg_3124_pp0_iter1_reg == 1'd1))) begin
        ap_return_14 = add_ln55_122_fu_2963_p2;
    end else begin
        ap_return_14 = ap_return_14_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln43_reg_3124_pp0_iter1_reg == 1'd1))) begin
        ap_return_15 = add_ln55_126_fu_2987_p2;
    end else begin
        ap_return_15 = ap_return_15_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln43_reg_3124_pp0_iter1_reg == 1'd1))) begin
        ap_return_2 = add_ln55_74_fu_2723_p2;
    end else begin
        ap_return_2 = ap_return_2_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln43_reg_3124_pp0_iter1_reg == 1'd1))) begin
        ap_return_3 = add_ln55_78_fu_2743_p2;
    end else begin
        ap_return_3 = ap_return_3_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln43_reg_3124_pp0_iter1_reg == 1'd1))) begin
        ap_return_4 = add_ln55_82_fu_2763_p2;
    end else begin
        ap_return_4 = ap_return_4_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln43_reg_3124_pp0_iter1_reg == 1'd1))) begin
        ap_return_5 = add_ln55_86_fu_2783_p2;
    end else begin
        ap_return_5 = ap_return_5_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln43_reg_3124_pp0_iter1_reg == 1'd1))) begin
        ap_return_6 = add_ln55_90_fu_2803_p2;
    end else begin
        ap_return_6 = ap_return_6_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln43_reg_3124_pp0_iter1_reg == 1'd1))) begin
        ap_return_7 = add_ln55_94_fu_2823_p2;
    end else begin
        ap_return_7 = ap_return_7_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln43_reg_3124_pp0_iter1_reg == 1'd1))) begin
        ap_return_8 = add_ln55_98_fu_2843_p2;
    end else begin
        ap_return_8 = ap_return_8_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln43_reg_3124_pp0_iter1_reg == 1'd1))) begin
        ap_return_9 = add_ln55_102_fu_2863_p2;
    end else begin
        ap_return_9 = ap_return_9_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_done_reg == 1'b0) & (ap_phi_mux_do_init_phi_fu_360_p6 == 1'd1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_1_blk_n = input_1_ap_vld;
    end else begin
        input_1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        w2_85_ce0 = 1'b1;
    end else begin
        w2_85_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign a_1_fu_682_p1 = empty_19_fu_676_p2[15:0];

assign a_2_fu_706_p1 = empty_21_fu_700_p2[15:0];

assign a_3_fu_724_p1 = empty_23_fu_718_p2[15:0];

assign a_fu_658_p1 = empty_17_fu_652_p2[15:0];

assign add_ln55_100_fu_2853_p2 = (trunc_ln55_99_reg_3318 + trunc_ln55_100_reg_3323);

assign add_ln55_101_fu_2857_p2 = (add_ln55_100_fu_2853_p2 + add_ln55_99_fu_2849_p2);

assign add_ln55_102_fu_2863_p2 = (ap_phi_mux_res_9_016_phi_fu_541_p6 + add_ln55_101_fu_2857_p2);

assign add_ln55_103_fu_2869_p2 = (trunc_ln55_101_reg_3328 + trunc_ln55_102_reg_3333);

assign add_ln55_104_fu_2873_p2 = (trunc_ln55_103_reg_3338 + trunc_ln55_104_reg_3343);

assign add_ln55_105_fu_2877_p2 = (add_ln55_104_fu_2873_p2 + add_ln55_103_fu_2869_p2);

assign add_ln55_106_fu_2883_p2 = (ap_phi_mux_res_10_014_phi_fu_555_p6 + add_ln55_105_fu_2877_p2);

assign add_ln55_107_fu_2889_p2 = (trunc_ln55_105_reg_3348 + trunc_ln55_106_reg_3353);

assign add_ln55_108_fu_2893_p2 = (trunc_ln55_107_reg_3358 + trunc_ln55_108_reg_3363);

assign add_ln55_109_fu_2897_p2 = (add_ln55_108_fu_2893_p2 + add_ln55_107_fu_2889_p2);

assign add_ln55_110_fu_2903_p2 = (ap_phi_mux_res_11_012_phi_fu_569_p6 + add_ln55_109_fu_2897_p2);

assign add_ln55_111_fu_2909_p2 = (trunc_ln55_109_reg_3368 + trunc_ln55_110_reg_3373);

assign add_ln55_112_fu_2913_p2 = (trunc_ln55_111_reg_3378 + trunc_ln55_112_reg_3383);

assign add_ln55_113_fu_2917_p2 = (add_ln55_112_fu_2913_p2 + add_ln55_111_fu_2909_p2);

assign add_ln55_114_fu_2923_p2 = (ap_phi_mux_res_12_010_phi_fu_583_p6 + add_ln55_113_fu_2917_p2);

assign add_ln55_115_fu_2929_p2 = (trunc_ln55_113_reg_3388 + trunc_ln55_114_reg_3393);

assign add_ln55_116_fu_2933_p2 = (trunc_ln55_115_reg_3398 + trunc_ln55_116_reg_3403);

assign add_ln55_117_fu_2937_p2 = (add_ln55_116_fu_2933_p2 + add_ln55_115_fu_2929_p2);

assign add_ln55_118_fu_2943_p2 = (ap_phi_mux_res_13_08_phi_fu_597_p6 + add_ln55_117_fu_2937_p2);

assign add_ln55_119_fu_2949_p2 = (trunc_ln55_117_reg_3408 + trunc_ln55_118_reg_3413);

assign add_ln55_120_fu_2953_p2 = (trunc_ln55_119_reg_3418 + trunc_ln55_120_reg_3423);

assign add_ln55_121_fu_2957_p2 = (add_ln55_120_fu_2953_p2 + add_ln55_119_fu_2949_p2);

assign add_ln55_122_fu_2963_p2 = (ap_phi_mux_res_1445_06_phi_fu_611_p6 + add_ln55_121_fu_2957_p2);

assign add_ln55_123_fu_2972_p2 = (trunc_ln55_121_reg_3428 + trunc_ln55_122_reg_3433);

assign add_ln55_124_fu_2976_p2 = ($signed(trunc_ln55_123_reg_3438) + $signed(sext_ln55_3_fu_2969_p1));

assign add_ln55_125_fu_2981_p2 = (add_ln55_124_fu_2976_p2 + add_ln55_123_fu_2972_p2);

assign add_ln55_126_fu_2987_p2 = (ap_phi_mux_res_15_04_phi_fu_625_p6 + add_ln55_125_fu_2981_p2);

assign add_ln55_64_fu_2673_p2 = (trunc_ln55_63_reg_3138 + trunc_ln55_64_reg_3143);

assign add_ln55_65_fu_2677_p2 = (add_ln55_64_fu_2673_p2 + add_ln55_fu_2669_p2);

assign add_ln55_66_fu_2683_p2 = (ap_phi_mux_res_0_034_phi_fu_415_p6 + add_ln55_65_fu_2677_p2);

assign add_ln55_67_fu_2689_p2 = (trunc_ln55_65_reg_3148 + trunc_ln55_66_reg_3153);

assign add_ln55_68_fu_2693_p2 = (trunc_ln55_67_reg_3158 + trunc_ln55_68_reg_3163);

assign add_ln55_69_fu_2697_p2 = (add_ln55_68_fu_2693_p2 + add_ln55_67_fu_2689_p2);

assign add_ln55_70_fu_2703_p2 = (ap_phi_mux_res_1_032_phi_fu_429_p6 + add_ln55_69_fu_2697_p2);

assign add_ln55_71_fu_2709_p2 = (trunc_ln55_69_reg_3168 + trunc_ln55_70_reg_3173);

assign add_ln55_72_fu_2713_p2 = (trunc_ln55_71_reg_3178 + trunc_ln55_72_reg_3183);

assign add_ln55_73_fu_2717_p2 = (add_ln55_72_fu_2713_p2 + add_ln55_71_fu_2709_p2);

assign add_ln55_74_fu_2723_p2 = (ap_phi_mux_res_2_030_phi_fu_443_p6 + add_ln55_73_fu_2717_p2);

assign add_ln55_75_fu_2729_p2 = (trunc_ln55_73_reg_3188 + trunc_ln55_74_reg_3193);

assign add_ln55_76_fu_2733_p2 = (trunc_ln55_75_reg_3198 + trunc_ln55_76_reg_3203);

assign add_ln55_77_fu_2737_p2 = (add_ln55_76_fu_2733_p2 + add_ln55_75_fu_2729_p2);

assign add_ln55_78_fu_2743_p2 = (ap_phi_mux_res_3_028_phi_fu_457_p6 + add_ln55_77_fu_2737_p2);

assign add_ln55_79_fu_2749_p2 = (trunc_ln55_77_reg_3208 + trunc_ln55_78_reg_3213);

assign add_ln55_80_fu_2753_p2 = (trunc_ln55_79_reg_3218 + trunc_ln55_80_reg_3223);

assign add_ln55_81_fu_2757_p2 = (add_ln55_80_fu_2753_p2 + add_ln55_79_fu_2749_p2);

assign add_ln55_82_fu_2763_p2 = (ap_phi_mux_res_4_026_phi_fu_471_p6 + add_ln55_81_fu_2757_p2);

assign add_ln55_83_fu_2769_p2 = (trunc_ln55_81_reg_3228 + trunc_ln55_82_reg_3233);

assign add_ln55_84_fu_2773_p2 = (trunc_ln55_83_reg_3238 + trunc_ln55_84_reg_3243);

assign add_ln55_85_fu_2777_p2 = (add_ln55_84_fu_2773_p2 + add_ln55_83_fu_2769_p2);

assign add_ln55_86_fu_2783_p2 = (ap_phi_mux_res_5_024_phi_fu_485_p6 + add_ln55_85_fu_2777_p2);

assign add_ln55_87_fu_2789_p2 = (trunc_ln55_85_reg_3248 + trunc_ln55_86_reg_3253);

assign add_ln55_88_fu_2793_p2 = (trunc_ln55_87_reg_3258 + trunc_ln55_88_reg_3263);

assign add_ln55_89_fu_2797_p2 = (add_ln55_88_fu_2793_p2 + add_ln55_87_fu_2789_p2);

assign add_ln55_90_fu_2803_p2 = (ap_phi_mux_res_6_022_phi_fu_499_p6 + add_ln55_89_fu_2797_p2);

assign add_ln55_91_fu_2809_p2 = (trunc_ln55_89_reg_3268 + trunc_ln55_90_reg_3273);

assign add_ln55_92_fu_2813_p2 = (trunc_ln55_91_reg_3278 + trunc_ln55_92_reg_3283);

assign add_ln55_93_fu_2817_p2 = (add_ln55_92_fu_2813_p2 + add_ln55_91_fu_2809_p2);

assign add_ln55_94_fu_2823_p2 = (ap_phi_mux_res_7_020_phi_fu_513_p6 + add_ln55_93_fu_2817_p2);

assign add_ln55_95_fu_2829_p2 = (trunc_ln55_93_reg_3288 + trunc_ln55_94_reg_3293);

assign add_ln55_96_fu_2833_p2 = (trunc_ln55_95_reg_3298 + trunc_ln55_96_reg_3303);

assign add_ln55_97_fu_2837_p2 = (add_ln55_96_fu_2833_p2 + add_ln55_95_fu_2829_p2);

assign add_ln55_98_fu_2843_p2 = (ap_phi_mux_res_8_018_phi_fu_527_p6 + add_ln55_97_fu_2837_p2);

assign add_ln55_99_fu_2849_p2 = (trunc_ln55_97_reg_3308 + trunc_ln55_98_reg_3313);

assign add_ln55_fu_2669_p2 = (trunc_ln_reg_3128 + trunc_ln55_s_reg_3133);

assign add_ln56_1_cast_cast_fu_686_p4 = {{{{2'd2}, {ap_phi_mux_w_index3_phi_fu_388_p6}}}, {4'd0}};

assign add_ln56_2_cast_cast_cast_cast_cast_fu_710_p1 = add_ln56_cast_cast_fu_662_p4;

assign add_ln56_cast_cast_fu_662_p4 = {{{{1'd1}, {ap_phi_mux_w_index3_phi_fu_388_p6}}}, {4'd0}};

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((ap_start_int == 1'b1) & ((ap_done_reg == 1'b1) | ((ap_phi_mux_do_init_phi_fu_360_p6 == 1'd1) & (input_1_ap_vld == 1'b0)))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((ap_start_int == 1'b1) & ((ap_done_reg == 1'b1) | ((ap_phi_mux_do_init_phi_fu_360_p6 == 1'd1) & (input_1_ap_vld == 1'b0)))));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_done_reg == 1'b1) | ((ap_phi_mux_do_init_phi_fu_360_p6 == 1'd1) & (input_1_ap_vld == 1'b0)));
end

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_151 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_phi_reg_pp0_iter0_input_1_load_phi_reg_398 = 'bx;

assign empty_17_fu_652_p2 = ap_phi_mux_input_1_load_phi_phi_fu_402_p4 >> empty_fu_648_p1;

assign empty_18_fu_672_p1 = $unsigned(add_ln56_cast_cast_fu_662_p4);

assign empty_19_fu_676_p2 = ap_phi_mux_input_1_load_phi_phi_fu_402_p4 >> empty_18_fu_672_p1;

assign empty_20_fu_696_p1 = add_ln56_1_cast_cast_fu_686_p4;

assign empty_21_fu_700_p2 = ap_phi_mux_input_1_load_phi_phi_fu_402_p4 >> empty_20_fu_696_p1;

assign empty_22_fu_714_p1 = $unsigned(add_ln56_2_cast_cast_cast_cast_cast_fu_710_p1);

assign empty_23_fu_718_p2 = ap_phi_mux_input_1_load_phi_phi_fu_402_p4 >> empty_22_fu_714_p1;

assign empty_fu_648_p1 = shl_ln_fu_640_p3;

assign icmp_ln43_fu_734_p2 = ((ap_phi_mux_w_index3_phi_fu_388_p6 == 4'd15) ? 1'b1 : 1'b0);

assign mul_ln55_100_fu_1873_p1 = sext_ln73_65_fu_781_p1;

assign mul_ln55_101_fu_1903_p1 = sext_ln73_67_fu_814_p1;

assign mul_ln55_102_fu_1933_p1 = sext_ln73_69_fu_847_p1;

assign mul_ln55_103_fu_1963_p1 = sext_ln73_63_fu_748_p1;

assign mul_ln55_104_fu_1993_p1 = sext_ln73_65_fu_781_p1;

assign mul_ln55_105_fu_2023_p1 = sext_ln73_67_fu_814_p1;

assign mul_ln55_106_fu_2053_p1 = sext_ln73_69_fu_847_p1;

assign mul_ln55_107_fu_2083_p1 = sext_ln73_63_fu_748_p1;

assign mul_ln55_108_fu_2113_p1 = sext_ln73_65_fu_781_p1;

assign mul_ln55_109_fu_2143_p1 = sext_ln73_67_fu_814_p1;

assign mul_ln55_110_fu_2173_p1 = sext_ln73_69_fu_847_p1;

assign mul_ln55_111_fu_2203_p1 = sext_ln73_63_fu_748_p1;

assign mul_ln55_112_fu_2233_p1 = sext_ln73_65_fu_781_p1;

assign mul_ln55_113_fu_2263_p1 = sext_ln73_67_fu_814_p1;

assign mul_ln55_114_fu_2293_p1 = sext_ln73_69_fu_847_p1;

assign mul_ln55_115_fu_2323_p1 = sext_ln73_63_fu_748_p1;

assign mul_ln55_116_fu_2353_p1 = sext_ln73_65_fu_781_p1;

assign mul_ln55_117_fu_2383_p1 = sext_ln73_67_fu_814_p1;

assign mul_ln55_118_fu_2413_p1 = sext_ln73_69_fu_847_p1;

assign mul_ln55_119_fu_2443_p1 = sext_ln73_63_fu_748_p1;

assign mul_ln55_120_fu_2473_p1 = sext_ln73_65_fu_781_p1;

assign mul_ln55_121_fu_2503_p1 = sext_ln73_67_fu_814_p1;

assign mul_ln55_122_fu_2533_p1 = sext_ln73_69_fu_847_p1;

assign mul_ln55_123_fu_2563_p1 = sext_ln73_63_fu_748_p1;

assign mul_ln55_124_fu_2593_p1 = sext_ln73_65_fu_781_p1;

assign mul_ln55_125_fu_2623_p1 = sext_ln73_67_fu_814_p1;

assign mul_ln55_64_fu_784_p1 = sext_ln73_65_fu_781_p1;

assign mul_ln55_65_fu_817_p1 = sext_ln73_67_fu_814_p1;

assign mul_ln55_66_fu_853_p1 = sext_ln73_69_fu_847_p1;

assign mul_ln55_67_fu_883_p1 = sext_ln73_63_fu_748_p1;

assign mul_ln55_68_fu_913_p1 = sext_ln73_65_fu_781_p1;

assign mul_ln55_69_fu_943_p1 = sext_ln73_67_fu_814_p1;

assign mul_ln55_70_fu_973_p1 = sext_ln73_69_fu_847_p1;

assign mul_ln55_71_fu_1003_p1 = sext_ln73_63_fu_748_p1;

assign mul_ln55_72_fu_1033_p1 = sext_ln73_65_fu_781_p1;

assign mul_ln55_73_fu_1063_p1 = sext_ln73_67_fu_814_p1;

assign mul_ln55_74_fu_1093_p1 = sext_ln73_69_fu_847_p1;

assign mul_ln55_75_fu_1123_p1 = sext_ln73_63_fu_748_p1;

assign mul_ln55_76_fu_1153_p1 = sext_ln73_65_fu_781_p1;

assign mul_ln55_77_fu_1183_p1 = sext_ln73_67_fu_814_p1;

assign mul_ln55_78_fu_1213_p1 = sext_ln73_69_fu_847_p1;

assign mul_ln55_79_fu_1243_p1 = sext_ln73_63_fu_748_p1;

assign mul_ln55_80_fu_1273_p1 = sext_ln73_65_fu_781_p1;

assign mul_ln55_81_fu_1303_p1 = sext_ln73_67_fu_814_p1;

assign mul_ln55_82_fu_1333_p1 = sext_ln73_69_fu_847_p1;

assign mul_ln55_83_fu_1363_p1 = sext_ln73_63_fu_748_p1;

assign mul_ln55_84_fu_1393_p1 = sext_ln73_65_fu_781_p1;

assign mul_ln55_85_fu_1423_p1 = sext_ln73_67_fu_814_p1;

assign mul_ln55_86_fu_1453_p1 = sext_ln73_69_fu_847_p1;

assign mul_ln55_87_fu_1483_p1 = sext_ln73_63_fu_748_p1;

assign mul_ln55_88_fu_1513_p1 = sext_ln73_65_fu_781_p1;

assign mul_ln55_89_fu_1543_p1 = sext_ln73_67_fu_814_p1;

assign mul_ln55_90_fu_1573_p1 = sext_ln73_69_fu_847_p1;

assign mul_ln55_91_fu_1603_p1 = sext_ln73_63_fu_748_p1;

assign mul_ln55_92_fu_1633_p1 = sext_ln73_65_fu_781_p1;

assign mul_ln55_93_fu_1663_p1 = sext_ln73_67_fu_814_p1;

assign mul_ln55_94_fu_1693_p1 = sext_ln73_69_fu_847_p1;

assign mul_ln55_95_fu_1723_p1 = sext_ln73_63_fu_748_p1;

assign mul_ln55_96_fu_1753_p1 = sext_ln73_65_fu_781_p1;

assign mul_ln55_97_fu_1783_p1 = sext_ln73_67_fu_814_p1;

assign mul_ln55_98_fu_1813_p1 = sext_ln73_69_fu_847_p1;

assign mul_ln55_99_fu_1843_p1 = sext_ln73_63_fu_748_p1;

assign mul_ln55_fu_751_p1 = sext_ln73_63_fu_748_p1;

assign sext_ln55_3_fu_2969_p1 = $signed(trunc_ln55_124_reg_3443);

assign sext_ln73_63_fu_748_p1 = $signed(a_reg_3093);

assign sext_ln73_65_fu_781_p1 = $signed(a_1_reg_3103);

assign sext_ln73_67_fu_814_p1 = $signed(a_2_reg_3108);

assign sext_ln73_69_fu_847_p1 = a_3_reg_3113;

assign shl_ln_fu_640_p3 = {{ap_phi_mux_w_index3_phi_fu_388_p6}, {4'd0}};

assign tmp_fu_2639_p4 = {{w2_85_q0[1016:1008]}};

assign w2_85_address0 = zext_ln43_fu_635_p1;

assign w_100_fu_1889_p4 = {{w2_85_q0[623:608]}};

assign w_101_fu_1919_p4 = {{w2_85_q0[639:624]}};

assign w_102_fu_1949_p4 = {{w2_85_q0[655:640]}};

assign w_103_fu_1979_p4 = {{w2_85_q0[671:656]}};

assign w_104_fu_2009_p4 = {{w2_85_q0[687:672]}};

assign w_105_fu_2039_p4 = {{w2_85_q0[703:688]}};

assign w_106_fu_2069_p4 = {{w2_85_q0[719:704]}};

assign w_107_fu_2099_p4 = {{w2_85_q0[735:720]}};

assign w_108_fu_2129_p4 = {{w2_85_q0[751:736]}};

assign w_109_fu_2159_p4 = {{w2_85_q0[767:752]}};

assign w_110_fu_2189_p4 = {{w2_85_q0[783:768]}};

assign w_111_fu_2219_p4 = {{w2_85_q0[799:784]}};

assign w_112_fu_2249_p4 = {{w2_85_q0[815:800]}};

assign w_113_fu_2279_p4 = {{w2_85_q0[831:816]}};

assign w_114_fu_2309_p4 = {{w2_85_q0[847:832]}};

assign w_115_fu_2339_p4 = {{w2_85_q0[863:848]}};

assign w_116_fu_2369_p4 = {{w2_85_q0[879:864]}};

assign w_117_fu_2399_p4 = {{w2_85_q0[895:880]}};

assign w_118_fu_2429_p4 = {{w2_85_q0[911:896]}};

assign w_119_fu_2459_p4 = {{w2_85_q0[927:912]}};

assign w_120_fu_2489_p4 = {{w2_85_q0[943:928]}};

assign w_121_fu_2519_p4 = {{w2_85_q0[959:944]}};

assign w_122_fu_2549_p4 = {{w2_85_q0[975:960]}};

assign w_123_fu_2579_p4 = {{w2_85_q0[991:976]}};

assign w_124_fu_2609_p4 = {{w2_85_q0[1007:992]}};

assign w_63_fu_767_p4 = {{w2_85_q0[31:16]}};

assign w_64_fu_800_p4 = {{w2_85_q0[47:32]}};

assign w_65_fu_833_p4 = {{w2_85_q0[63:48]}};

assign w_66_fu_869_p4 = {{w2_85_q0[79:64]}};

assign w_67_fu_899_p4 = {{w2_85_q0[95:80]}};

assign w_68_fu_929_p4 = {{w2_85_q0[111:96]}};

assign w_69_fu_959_p4 = {{w2_85_q0[127:112]}};

assign w_70_fu_989_p4 = {{w2_85_q0[143:128]}};

assign w_71_fu_1019_p4 = {{w2_85_q0[159:144]}};

assign w_72_fu_1049_p4 = {{w2_85_q0[175:160]}};

assign w_73_fu_1079_p4 = {{w2_85_q0[191:176]}};

assign w_74_fu_1109_p4 = {{w2_85_q0[207:192]}};

assign w_75_fu_1139_p4 = {{w2_85_q0[223:208]}};

assign w_76_fu_1169_p4 = {{w2_85_q0[239:224]}};

assign w_77_fu_1199_p4 = {{w2_85_q0[255:240]}};

assign w_78_fu_1229_p4 = {{w2_85_q0[271:256]}};

assign w_79_fu_1259_p4 = {{w2_85_q0[287:272]}};

assign w_80_fu_1289_p4 = {{w2_85_q0[303:288]}};

assign w_81_fu_1319_p4 = {{w2_85_q0[319:304]}};

assign w_82_fu_1349_p4 = {{w2_85_q0[335:320]}};

assign w_83_fu_1379_p4 = {{w2_85_q0[351:336]}};

assign w_84_fu_1409_p4 = {{w2_85_q0[367:352]}};

assign w_85_fu_1439_p4 = {{w2_85_q0[383:368]}};

assign w_86_fu_1469_p4 = {{w2_85_q0[399:384]}};

assign w_87_fu_1499_p4 = {{w2_85_q0[415:400]}};

assign w_88_fu_1529_p4 = {{w2_85_q0[431:416]}};

assign w_89_fu_1559_p4 = {{w2_85_q0[447:432]}};

assign w_90_fu_1589_p4 = {{w2_85_q0[463:448]}};

assign w_91_fu_1619_p4 = {{w2_85_q0[479:464]}};

assign w_92_fu_1649_p4 = {{w2_85_q0[495:480]}};

assign w_93_fu_1679_p4 = {{w2_85_q0[511:496]}};

assign w_94_fu_1709_p4 = {{w2_85_q0[527:512]}};

assign w_95_fu_1739_p4 = {{w2_85_q0[543:528]}};

assign w_96_fu_1769_p4 = {{w2_85_q0[559:544]}};

assign w_97_fu_1799_p4 = {{w2_85_q0[575:560]}};

assign w_98_fu_1829_p4 = {{w2_85_q0[591:576]}};

assign w_99_fu_1859_p4 = {{w2_85_q0[607:592]}};

assign w_fu_740_p1 = w2_85_q0[15:0];

assign w_index_fu_728_p2 = (ap_phi_mux_w_index3_phi_fu_388_p6 + 4'd1);

assign zext_ln43_fu_635_p1 = ap_phi_mux_w_index3_phi_fu_388_p6;

endmodule //myproject_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s
