// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        p_read,
        p_read1,
        p_read2,
        p_read3,
        p_read4,
        p_read5,
        p_read6,
        p_read7,
        p_read8,
        p_read9,
        p_read10,
        p_read11,
        p_read12,
        p_read13,
        p_read14,
        p_read15,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_return_8,
        ap_return_9,
        ap_return_10,
        ap_return_11,
        ap_return_12,
        ap_return_13,
        ap_return_14,
        ap_return_15
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [15:0] p_read;
input  [15:0] p_read1;
input  [15:0] p_read2;
input  [15:0] p_read3;
input  [15:0] p_read4;
input  [15:0] p_read5;
input  [15:0] p_read6;
input  [15:0] p_read7;
input  [15:0] p_read8;
input  [15:0] p_read9;
input  [15:0] p_read10;
input  [15:0] p_read11;
input  [15:0] p_read12;
input  [15:0] p_read13;
input  [15:0] p_read14;
input  [15:0] p_read15;
output  [14:0] ap_return_0;
output  [14:0] ap_return_1;
output  [14:0] ap_return_2;
output  [14:0] ap_return_3;
output  [14:0] ap_return_4;
output  [14:0] ap_return_5;
output  [14:0] ap_return_6;
output  [14:0] ap_return_7;
output  [14:0] ap_return_8;
output  [14:0] ap_return_9;
output  [14:0] ap_return_10;
output  [14:0] ap_return_11;
output  [14:0] ap_return_12;
output  [14:0] ap_return_13;
output  [14:0] ap_return_14;
output  [14:0] ap_return_15;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[14:0] ap_return_0;
reg[14:0] ap_return_1;
reg[14:0] ap_return_2;
reg[14:0] ap_return_3;
reg[14:0] ap_return_4;
reg[14:0] ap_return_5;
reg[14:0] ap_return_6;
reg[14:0] ap_return_7;
reg[14:0] ap_return_8;
reg[14:0] ap_return_9;
reg[14:0] ap_return_10;
reg[14:0] ap_return_11;
reg[14:0] ap_return_12;
reg[14:0] ap_return_13;
reg[14:0] ap_return_14;
reg[14:0] ap_return_15;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1;
wire   [0:0] icmp_ln45_fu_148_p2;
wire   [14:0] trunc_ln42_fu_144_p1;
wire   [0:0] icmp_ln45_1_fu_166_p2;
wire   [14:0] trunc_ln42_1_fu_162_p1;
wire   [0:0] icmp_ln45_2_fu_184_p2;
wire   [14:0] trunc_ln42_2_fu_180_p1;
wire   [0:0] icmp_ln45_3_fu_202_p2;
wire   [14:0] trunc_ln42_3_fu_198_p1;
wire   [0:0] icmp_ln45_4_fu_220_p2;
wire   [14:0] trunc_ln42_4_fu_216_p1;
wire   [0:0] icmp_ln45_5_fu_238_p2;
wire   [14:0] trunc_ln42_5_fu_234_p1;
wire   [0:0] icmp_ln45_6_fu_256_p2;
wire   [14:0] trunc_ln42_6_fu_252_p1;
wire   [0:0] icmp_ln45_7_fu_274_p2;
wire   [14:0] trunc_ln42_7_fu_270_p1;
wire   [0:0] icmp_ln45_8_fu_292_p2;
wire   [14:0] trunc_ln42_8_fu_288_p1;
wire   [0:0] icmp_ln45_9_fu_310_p2;
wire   [14:0] trunc_ln42_9_fu_306_p1;
wire   [0:0] icmp_ln45_10_fu_328_p2;
wire   [14:0] trunc_ln42_10_fu_324_p1;
wire   [0:0] icmp_ln45_11_fu_346_p2;
wire   [14:0] trunc_ln42_11_fu_342_p1;
wire   [0:0] icmp_ln45_12_fu_364_p2;
wire   [14:0] trunc_ln42_12_fu_360_p1;
wire   [0:0] icmp_ln45_13_fu_382_p2;
wire   [14:0] trunc_ln42_13_fu_378_p1;
wire   [0:0] icmp_ln45_14_fu_400_p2;
wire   [14:0] trunc_ln42_14_fu_396_p1;
wire   [0:0] icmp_ln45_15_fu_418_p2;
wire   [14:0] trunc_ln42_15_fu_414_p1;
wire   [14:0] datareg_fu_154_p3;
wire   [14:0] datareg_1_fu_172_p3;
wire   [14:0] datareg_2_fu_190_p3;
wire   [14:0] datareg_3_fu_208_p3;
wire   [14:0] datareg_4_fu_226_p3;
wire   [14:0] datareg_5_fu_244_p3;
wire   [14:0] datareg_6_fu_262_p3;
wire   [14:0] datareg_7_fu_280_p3;
wire   [14:0] datareg_8_fu_298_p3;
wire   [14:0] datareg_9_fu_316_p3;
wire   [14:0] datareg_10_fu_334_p3;
wire   [14:0] datareg_11_fu_352_p3;
wire   [14:0] datareg_12_fu_370_p3;
wire   [14:0] datareg_13_fu_388_p3;
wire   [14:0] datareg_14_fu_406_p3;
wire   [14:0] datareg_15_fu_424_p3;
reg   [14:0] ap_return_0_preg;
reg   [14:0] ap_return_1_preg;
reg   [14:0] ap_return_2_preg;
reg   [14:0] ap_return_3_preg;
reg   [14:0] ap_return_4_preg;
reg   [14:0] ap_return_5_preg;
reg   [14:0] ap_return_6_preg;
reg   [14:0] ap_return_7_preg;
reg   [14:0] ap_return_8_preg;
reg   [14:0] ap_return_9_preg;
reg   [14:0] ap_return_10_preg;
reg   [14:0] ap_return_11_preg;
reg   [14:0] ap_return_12_preg;
reg   [14:0] ap_return_13_preg;
reg   [14:0] ap_return_14_preg;
reg   [14:0] ap_return_15_preg;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
#0 ap_return_0_preg = 15'd0;
#0 ap_return_1_preg = 15'd0;
#0 ap_return_2_preg = 15'd0;
#0 ap_return_3_preg = 15'd0;
#0 ap_return_4_preg = 15'd0;
#0 ap_return_5_preg = 15'd0;
#0 ap_return_6_preg = 15'd0;
#0 ap_return_7_preg = 15'd0;
#0 ap_return_8_preg = 15'd0;
#0 ap_return_9_preg = 15'd0;
#0 ap_return_10_preg = 15'd0;
#0 ap_return_11_preg = 15'd0;
#0 ap_return_12_preg = 15'd0;
#0 ap_return_13_preg = 15'd0;
#0 ap_return_14_preg = 15'd0;
#0 ap_return_15_preg = 15'd0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_0_preg <= 15'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_0_preg <= datareg_fu_154_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_10_preg <= 15'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_10_preg <= datareg_10_fu_334_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_11_preg <= 15'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_11_preg <= datareg_11_fu_352_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_12_preg <= 15'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_12_preg <= datareg_12_fu_370_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_13_preg <= 15'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_13_preg <= datareg_13_fu_388_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_14_preg <= 15'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_14_preg <= datareg_14_fu_406_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_15_preg <= 15'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_15_preg <= datareg_15_fu_424_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_1_preg <= 15'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_1_preg <= datareg_1_fu_172_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_2_preg <= 15'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_2_preg <= datareg_2_fu_190_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_3_preg <= 15'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_3_preg <= datareg_3_fu_208_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_4_preg <= 15'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_4_preg <= datareg_4_fu_226_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_5_preg <= 15'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_5_preg <= datareg_5_fu_244_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_6_preg <= 15'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_6_preg <= datareg_6_fu_262_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_7_preg <= 15'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_7_preg <= datareg_7_fu_280_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_8_preg <= 15'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_8_preg <= datareg_8_fu_298_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_9_preg <= 15'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_9_preg <= datareg_9_fu_316_p3;
        end
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) | (ap_done_reg == 1'b1))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_0 = datareg_fu_154_p3;
    end else begin
        ap_return_0 = ap_return_0_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_1 = datareg_1_fu_172_p3;
    end else begin
        ap_return_1 = ap_return_1_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_10 = datareg_10_fu_334_p3;
    end else begin
        ap_return_10 = ap_return_10_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_11 = datareg_11_fu_352_p3;
    end else begin
        ap_return_11 = ap_return_11_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_12 = datareg_12_fu_370_p3;
    end else begin
        ap_return_12 = ap_return_12_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_13 = datareg_13_fu_388_p3;
    end else begin
        ap_return_13 = ap_return_13_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_14 = datareg_14_fu_406_p3;
    end else begin
        ap_return_14 = ap_return_14_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_15 = datareg_15_fu_424_p3;
    end else begin
        ap_return_15 = ap_return_15_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_2 = datareg_2_fu_190_p3;
    end else begin
        ap_return_2 = ap_return_2_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_3 = datareg_3_fu_208_p3;
    end else begin
        ap_return_3 = ap_return_3_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_4 = datareg_4_fu_226_p3;
    end else begin
        ap_return_4 = ap_return_4_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_5 = datareg_5_fu_244_p3;
    end else begin
        ap_return_5 = ap_return_5_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_6 = datareg_6_fu_262_p3;
    end else begin
        ap_return_6 = ap_return_6_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_7 = datareg_7_fu_280_p3;
    end else begin
        ap_return_7 = ap_return_7_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_8 = datareg_8_fu_298_p3;
    end else begin
        ap_return_8 = ap_return_8_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_9 = datareg_9_fu_316_p3;
    end else begin
        ap_return_9 = ap_return_9_preg;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign datareg_10_fu_334_p3 = ((icmp_ln45_10_fu_328_p2[0:0] == 1'b1) ? trunc_ln42_10_fu_324_p1 : 15'd0);

assign datareg_11_fu_352_p3 = ((icmp_ln45_11_fu_346_p2[0:0] == 1'b1) ? trunc_ln42_11_fu_342_p1 : 15'd0);

assign datareg_12_fu_370_p3 = ((icmp_ln45_12_fu_364_p2[0:0] == 1'b1) ? trunc_ln42_12_fu_360_p1 : 15'd0);

assign datareg_13_fu_388_p3 = ((icmp_ln45_13_fu_382_p2[0:0] == 1'b1) ? trunc_ln42_13_fu_378_p1 : 15'd0);

assign datareg_14_fu_406_p3 = ((icmp_ln45_14_fu_400_p2[0:0] == 1'b1) ? trunc_ln42_14_fu_396_p1 : 15'd0);

assign datareg_15_fu_424_p3 = ((icmp_ln45_15_fu_418_p2[0:0] == 1'b1) ? trunc_ln42_15_fu_414_p1 : 15'd0);

assign datareg_1_fu_172_p3 = ((icmp_ln45_1_fu_166_p2[0:0] == 1'b1) ? trunc_ln42_1_fu_162_p1 : 15'd0);

assign datareg_2_fu_190_p3 = ((icmp_ln45_2_fu_184_p2[0:0] == 1'b1) ? trunc_ln42_2_fu_180_p1 : 15'd0);

assign datareg_3_fu_208_p3 = ((icmp_ln45_3_fu_202_p2[0:0] == 1'b1) ? trunc_ln42_3_fu_198_p1 : 15'd0);

assign datareg_4_fu_226_p3 = ((icmp_ln45_4_fu_220_p2[0:0] == 1'b1) ? trunc_ln42_4_fu_216_p1 : 15'd0);

assign datareg_5_fu_244_p3 = ((icmp_ln45_5_fu_238_p2[0:0] == 1'b1) ? trunc_ln42_5_fu_234_p1 : 15'd0);

assign datareg_6_fu_262_p3 = ((icmp_ln45_6_fu_256_p2[0:0] == 1'b1) ? trunc_ln42_6_fu_252_p1 : 15'd0);

assign datareg_7_fu_280_p3 = ((icmp_ln45_7_fu_274_p2[0:0] == 1'b1) ? trunc_ln42_7_fu_270_p1 : 15'd0);

assign datareg_8_fu_298_p3 = ((icmp_ln45_8_fu_292_p2[0:0] == 1'b1) ? trunc_ln42_8_fu_288_p1 : 15'd0);

assign datareg_9_fu_316_p3 = ((icmp_ln45_9_fu_310_p2[0:0] == 1'b1) ? trunc_ln42_9_fu_306_p1 : 15'd0);

assign datareg_fu_154_p3 = ((icmp_ln45_fu_148_p2[0:0] == 1'b1) ? trunc_ln42_fu_144_p1 : 15'd0);

assign icmp_ln45_10_fu_328_p2 = (($signed(p_read10) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_11_fu_346_p2 = (($signed(p_read11) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_12_fu_364_p2 = (($signed(p_read12) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_13_fu_382_p2 = (($signed(p_read13) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_14_fu_400_p2 = (($signed(p_read14) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_15_fu_418_p2 = (($signed(p_read15) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_1_fu_166_p2 = (($signed(p_read1) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_2_fu_184_p2 = (($signed(p_read2) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_3_fu_202_p2 = (($signed(p_read3) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_4_fu_220_p2 = (($signed(p_read4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_5_fu_238_p2 = (($signed(p_read5) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_6_fu_256_p2 = (($signed(p_read6) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_7_fu_274_p2 = (($signed(p_read7) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_8_fu_292_p2 = (($signed(p_read8) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_9_fu_310_p2 = (($signed(p_read9) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_fu_148_p2 = (($signed(p_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign trunc_ln42_10_fu_324_p1 = p_read10[14:0];

assign trunc_ln42_11_fu_342_p1 = p_read11[14:0];

assign trunc_ln42_12_fu_360_p1 = p_read12[14:0];

assign trunc_ln42_13_fu_378_p1 = p_read13[14:0];

assign trunc_ln42_14_fu_396_p1 = p_read14[14:0];

assign trunc_ln42_15_fu_414_p1 = p_read15[14:0];

assign trunc_ln42_1_fu_162_p1 = p_read1[14:0];

assign trunc_ln42_2_fu_180_p1 = p_read2[14:0];

assign trunc_ln42_3_fu_198_p1 = p_read3[14:0];

assign trunc_ln42_4_fu_216_p1 = p_read4[14:0];

assign trunc_ln42_5_fu_234_p1 = p_read5[14:0];

assign trunc_ln42_6_fu_252_p1 = p_read6[14:0];

assign trunc_ln42_7_fu_270_p1 = p_read7[14:0];

assign trunc_ln42_8_fu_288_p1 = p_read8[14:0];

assign trunc_ln42_9_fu_306_p1 = p_read9[14:0];

assign trunc_ln42_fu_144_p1 = p_read[14:0];

endmodule //myproject_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s
