// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_relu_ap_fixed_32_6_5_3_0_ap_fixed_32_6_5_3_0_relu_config3_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        p_read,
        p_read1,
        p_read2,
        p_read3,
        p_read4,
        p_read5,
        p_read6,
        p_read7,
        p_read8,
        p_read9,
        p_read10,
        p_read11,
        p_read12,
        p_read13,
        p_read14,
        p_read15,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_return_8,
        ap_return_9,
        ap_return_10,
        ap_return_11,
        ap_return_12,
        ap_return_13,
        ap_return_14,
        ap_return_15
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [31:0] p_read;
input  [31:0] p_read1;
input  [31:0] p_read2;
input  [31:0] p_read3;
input  [31:0] p_read4;
input  [31:0] p_read5;
input  [31:0] p_read6;
input  [31:0] p_read7;
input  [31:0] p_read8;
input  [31:0] p_read9;
input  [31:0] p_read10;
input  [31:0] p_read11;
input  [31:0] p_read12;
input  [31:0] p_read13;
input  [31:0] p_read14;
input  [31:0] p_read15;
output  [30:0] ap_return_0;
output  [30:0] ap_return_1;
output  [30:0] ap_return_2;
output  [30:0] ap_return_3;
output  [30:0] ap_return_4;
output  [30:0] ap_return_5;
output  [30:0] ap_return_6;
output  [30:0] ap_return_7;
output  [30:0] ap_return_8;
output  [30:0] ap_return_9;
output  [30:0] ap_return_10;
output  [30:0] ap_return_11;
output  [30:0] ap_return_12;
output  [30:0] ap_return_13;
output  [30:0] ap_return_14;
output  [30:0] ap_return_15;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[30:0] ap_return_0;
reg[30:0] ap_return_1;
reg[30:0] ap_return_2;
reg[30:0] ap_return_3;
reg[30:0] ap_return_4;
reg[30:0] ap_return_5;
reg[30:0] ap_return_6;
reg[30:0] ap_return_7;
reg[30:0] ap_return_8;
reg[30:0] ap_return_9;
reg[30:0] ap_return_10;
reg[30:0] ap_return_11;
reg[30:0] ap_return_12;
reg[30:0] ap_return_13;
reg[30:0] ap_return_14;
reg[30:0] ap_return_15;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_subdone;
reg   [31:0] p_read_65_reg_494;
reg    ap_block_pp0_stage0_11001;
reg   [31:0] p_read_66_reg_499;
reg   [31:0] p_read_67_reg_504;
reg   [31:0] p_read_68_reg_509;
reg   [31:0] p_read_69_reg_514;
reg   [31:0] p_read1026_reg_519;
reg   [31:0] p_read925_reg_524;
reg   [31:0] p_read824_reg_529;
reg   [31:0] p_read723_reg_534;
reg   [31:0] p_read622_reg_539;
reg   [31:0] p_read521_reg_544;
reg   [31:0] p_read420_reg_549;
reg   [31:0] p_read319_reg_554;
reg   [31:0] p_read218_reg_559;
reg   [31:0] p_read117_reg_564;
reg   [31:0] p_read16_reg_569;
wire   [30:0] trunc_ln42_fu_142_p1;
reg   [30:0] trunc_ln42_reg_574;
wire   [30:0] trunc_ln42_1_fu_146_p1;
reg   [30:0] trunc_ln42_1_reg_579;
wire   [30:0] trunc_ln42_2_fu_150_p1;
reg   [30:0] trunc_ln42_2_reg_584;
wire   [30:0] trunc_ln42_3_fu_154_p1;
reg   [30:0] trunc_ln42_3_reg_589;
wire   [30:0] trunc_ln42_4_fu_158_p1;
reg   [30:0] trunc_ln42_4_reg_594;
wire   [30:0] trunc_ln42_5_fu_162_p1;
reg   [30:0] trunc_ln42_5_reg_599;
wire   [30:0] trunc_ln42_6_fu_166_p1;
reg   [30:0] trunc_ln42_6_reg_604;
wire   [30:0] trunc_ln42_7_fu_170_p1;
reg   [30:0] trunc_ln42_7_reg_609;
wire   [30:0] trunc_ln42_8_fu_174_p1;
reg   [30:0] trunc_ln42_8_reg_614;
wire   [30:0] trunc_ln42_9_fu_178_p1;
reg   [30:0] trunc_ln42_9_reg_619;
wire   [30:0] trunc_ln42_10_fu_182_p1;
reg   [30:0] trunc_ln42_10_reg_624;
wire   [30:0] trunc_ln42_11_fu_186_p1;
reg   [30:0] trunc_ln42_11_reg_629;
wire   [30:0] trunc_ln42_12_fu_190_p1;
reg   [30:0] trunc_ln42_12_reg_634;
wire   [30:0] trunc_ln42_13_fu_194_p1;
reg   [30:0] trunc_ln42_13_reg_639;
wire   [30:0] trunc_ln42_14_fu_198_p1;
reg   [30:0] trunc_ln42_14_reg_644;
wire   [30:0] trunc_ln42_15_fu_202_p1;
reg   [30:0] trunc_ln42_15_reg_649;
wire    ap_block_pp0_stage0;
wire   [0:0] icmp_ln45_fu_206_p2;
wire   [0:0] icmp_ln45_1_fu_218_p2;
wire   [0:0] icmp_ln45_2_fu_230_p2;
wire   [0:0] icmp_ln45_3_fu_242_p2;
wire   [0:0] icmp_ln45_4_fu_254_p2;
wire   [0:0] icmp_ln45_5_fu_266_p2;
wire   [0:0] icmp_ln45_6_fu_278_p2;
wire   [0:0] icmp_ln45_7_fu_290_p2;
wire   [0:0] icmp_ln45_8_fu_302_p2;
wire   [0:0] icmp_ln45_9_fu_314_p2;
wire   [0:0] icmp_ln45_10_fu_326_p2;
wire   [0:0] icmp_ln45_11_fu_338_p2;
wire   [0:0] icmp_ln45_12_fu_350_p2;
wire   [0:0] icmp_ln45_13_fu_362_p2;
wire   [0:0] icmp_ln45_14_fu_374_p2;
wire   [0:0] icmp_ln45_15_fu_386_p2;
wire   [30:0] datareg_fu_211_p3;
wire   [30:0] datareg_1_fu_223_p3;
wire   [30:0] datareg_2_fu_235_p3;
wire   [30:0] datareg_3_fu_247_p3;
wire   [30:0] datareg_4_fu_259_p3;
wire   [30:0] datareg_5_fu_271_p3;
wire   [30:0] datareg_6_fu_283_p3;
wire   [30:0] datareg_7_fu_295_p3;
wire   [30:0] datareg_8_fu_307_p3;
wire   [30:0] datareg_9_fu_319_p3;
wire   [30:0] datareg_10_fu_331_p3;
wire   [30:0] datareg_11_fu_343_p3;
wire   [30:0] datareg_12_fu_355_p3;
wire   [30:0] datareg_13_fu_367_p3;
wire   [30:0] datareg_14_fu_379_p3;
wire   [30:0] datareg_15_fu_391_p3;
reg   [30:0] ap_return_0_preg;
reg   [30:0] ap_return_1_preg;
reg   [30:0] ap_return_2_preg;
reg   [30:0] ap_return_3_preg;
reg   [30:0] ap_return_4_preg;
reg   [30:0] ap_return_5_preg;
reg   [30:0] ap_return_6_preg;
reg   [30:0] ap_return_7_preg;
reg   [30:0] ap_return_8_preg;
reg   [30:0] ap_return_9_preg;
reg   [30:0] ap_return_10_preg;
reg   [30:0] ap_return_11_preg;
reg   [30:0] ap_return_12_preg;
reg   [30:0] ap_return_13_preg;
reg   [30:0] ap_return_14_preg;
reg   [30:0] ap_return_15_preg;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to0;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_return_0_preg = 31'd0;
#0 ap_return_1_preg = 31'd0;
#0 ap_return_2_preg = 31'd0;
#0 ap_return_3_preg = 31'd0;
#0 ap_return_4_preg = 31'd0;
#0 ap_return_5_preg = 31'd0;
#0 ap_return_6_preg = 31'd0;
#0 ap_return_7_preg = 31'd0;
#0 ap_return_8_preg = 31'd0;
#0 ap_return_9_preg = 31'd0;
#0 ap_return_10_preg = 31'd0;
#0 ap_return_11_preg = 31'd0;
#0 ap_return_12_preg = 31'd0;
#0 ap_return_13_preg = 31'd0;
#0 ap_return_14_preg = 31'd0;
#0 ap_return_15_preg = 31'd0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_0_preg <= 31'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_return_0_preg <= datareg_fu_211_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_10_preg <= 31'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_return_10_preg <= datareg_10_fu_331_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_11_preg <= 31'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_return_11_preg <= datareg_11_fu_343_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_12_preg <= 31'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_return_12_preg <= datareg_12_fu_355_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_13_preg <= 31'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_return_13_preg <= datareg_13_fu_367_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_14_preg <= 31'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_return_14_preg <= datareg_14_fu_379_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_15_preg <= 31'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_return_15_preg <= datareg_15_fu_391_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_1_preg <= 31'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_return_1_preg <= datareg_1_fu_223_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_2_preg <= 31'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_return_2_preg <= datareg_2_fu_235_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_3_preg <= 31'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_return_3_preg <= datareg_3_fu_247_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_4_preg <= 31'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_return_4_preg <= datareg_4_fu_259_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_5_preg <= 31'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_return_5_preg <= datareg_5_fu_271_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_6_preg <= 31'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_return_6_preg <= datareg_6_fu_283_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_7_preg <= 31'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_return_7_preg <= datareg_7_fu_295_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_8_preg <= 31'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_return_8_preg <= datareg_8_fu_307_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_9_preg <= 31'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_return_9_preg <= datareg_9_fu_319_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_read1026_reg_519 <= p_read10;
        p_read117_reg_564 <= p_read1;
        p_read16_reg_569 <= p_read;
        p_read218_reg_559 <= p_read2;
        p_read319_reg_554 <= p_read3;
        p_read420_reg_549 <= p_read4;
        p_read521_reg_544 <= p_read5;
        p_read622_reg_539 <= p_read6;
        p_read723_reg_534 <= p_read7;
        p_read824_reg_529 <= p_read8;
        p_read925_reg_524 <= p_read9;
        p_read_65_reg_494 <= p_read15;
        p_read_66_reg_499 <= p_read14;
        p_read_67_reg_504 <= p_read13;
        p_read_68_reg_509 <= p_read12;
        p_read_69_reg_514 <= p_read11;
        trunc_ln42_10_reg_624 <= trunc_ln42_10_fu_182_p1;
        trunc_ln42_11_reg_629 <= trunc_ln42_11_fu_186_p1;
        trunc_ln42_12_reg_634 <= trunc_ln42_12_fu_190_p1;
        trunc_ln42_13_reg_639 <= trunc_ln42_13_fu_194_p1;
        trunc_ln42_14_reg_644 <= trunc_ln42_14_fu_198_p1;
        trunc_ln42_15_reg_649 <= trunc_ln42_15_fu_202_p1;
        trunc_ln42_1_reg_579 <= trunc_ln42_1_fu_146_p1;
        trunc_ln42_2_reg_584 <= trunc_ln42_2_fu_150_p1;
        trunc_ln42_3_reg_589 <= trunc_ln42_3_fu_154_p1;
        trunc_ln42_4_reg_594 <= trunc_ln42_4_fu_158_p1;
        trunc_ln42_5_reg_599 <= trunc_ln42_5_fu_162_p1;
        trunc_ln42_6_reg_604 <= trunc_ln42_6_fu_166_p1;
        trunc_ln42_7_reg_609 <= trunc_ln42_7_fu_170_p1;
        trunc_ln42_8_reg_614 <= trunc_ln42_8_fu_174_p1;
        trunc_ln42_9_reg_619 <= trunc_ln42_9_fu_178_p1;
        trunc_ln42_reg_574 <= trunc_ln42_fu_142_p1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b0)) begin
        ap_idle_pp0_0to0 = 1'b1;
    end else begin
        ap_idle_pp0_0to0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_idle_pp0_0to0 == 1'b1) & (ap_start == 1'b0))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_return_0 = datareg_fu_211_p3;
    end else begin
        ap_return_0 = ap_return_0_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_return_1 = datareg_1_fu_223_p3;
    end else begin
        ap_return_1 = ap_return_1_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_return_10 = datareg_10_fu_331_p3;
    end else begin
        ap_return_10 = ap_return_10_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_return_11 = datareg_11_fu_343_p3;
    end else begin
        ap_return_11 = ap_return_11_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_return_12 = datareg_12_fu_355_p3;
    end else begin
        ap_return_12 = ap_return_12_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_return_13 = datareg_13_fu_367_p3;
    end else begin
        ap_return_13 = ap_return_13_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_return_14 = datareg_14_fu_379_p3;
    end else begin
        ap_return_14 = ap_return_14_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_return_15 = datareg_15_fu_391_p3;
    end else begin
        ap_return_15 = ap_return_15_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_return_2 = datareg_2_fu_235_p3;
    end else begin
        ap_return_2 = ap_return_2_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_return_3 = datareg_3_fu_247_p3;
    end else begin
        ap_return_3 = ap_return_3_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_return_4 = datareg_4_fu_259_p3;
    end else begin
        ap_return_4 = ap_return_4_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_return_5 = datareg_5_fu_271_p3;
    end else begin
        ap_return_5 = ap_return_5_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_return_6 = datareg_6_fu_283_p3;
    end else begin
        ap_return_6 = ap_return_6_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_return_7 = datareg_7_fu_295_p3;
    end else begin
        ap_return_7 = ap_return_7_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_return_8 = datareg_8_fu_307_p3;
    end else begin
        ap_return_8 = ap_return_8_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_return_9 = datareg_9_fu_319_p3;
    end else begin
        ap_return_9 = ap_return_9_preg;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((ap_done_reg == 1'b1) & (ap_start == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((ap_done_reg == 1'b1) & (ap_start == 1'b1)));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_done_reg == 1'b1);
end

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign datareg_10_fu_331_p3 = ((icmp_ln45_10_fu_326_p2[0:0] == 1'b1) ? trunc_ln42_10_reg_624 : 31'd0);

assign datareg_11_fu_343_p3 = ((icmp_ln45_11_fu_338_p2[0:0] == 1'b1) ? trunc_ln42_11_reg_629 : 31'd0);

assign datareg_12_fu_355_p3 = ((icmp_ln45_12_fu_350_p2[0:0] == 1'b1) ? trunc_ln42_12_reg_634 : 31'd0);

assign datareg_13_fu_367_p3 = ((icmp_ln45_13_fu_362_p2[0:0] == 1'b1) ? trunc_ln42_13_reg_639 : 31'd0);

assign datareg_14_fu_379_p3 = ((icmp_ln45_14_fu_374_p2[0:0] == 1'b1) ? trunc_ln42_14_reg_644 : 31'd0);

assign datareg_15_fu_391_p3 = ((icmp_ln45_15_fu_386_p2[0:0] == 1'b1) ? trunc_ln42_15_reg_649 : 31'd0);

assign datareg_1_fu_223_p3 = ((icmp_ln45_1_fu_218_p2[0:0] == 1'b1) ? trunc_ln42_1_reg_579 : 31'd0);

assign datareg_2_fu_235_p3 = ((icmp_ln45_2_fu_230_p2[0:0] == 1'b1) ? trunc_ln42_2_reg_584 : 31'd0);

assign datareg_3_fu_247_p3 = ((icmp_ln45_3_fu_242_p2[0:0] == 1'b1) ? trunc_ln42_3_reg_589 : 31'd0);

assign datareg_4_fu_259_p3 = ((icmp_ln45_4_fu_254_p2[0:0] == 1'b1) ? trunc_ln42_4_reg_594 : 31'd0);

assign datareg_5_fu_271_p3 = ((icmp_ln45_5_fu_266_p2[0:0] == 1'b1) ? trunc_ln42_5_reg_599 : 31'd0);

assign datareg_6_fu_283_p3 = ((icmp_ln45_6_fu_278_p2[0:0] == 1'b1) ? trunc_ln42_6_reg_604 : 31'd0);

assign datareg_7_fu_295_p3 = ((icmp_ln45_7_fu_290_p2[0:0] == 1'b1) ? trunc_ln42_7_reg_609 : 31'd0);

assign datareg_8_fu_307_p3 = ((icmp_ln45_8_fu_302_p2[0:0] == 1'b1) ? trunc_ln42_8_reg_614 : 31'd0);

assign datareg_9_fu_319_p3 = ((icmp_ln45_9_fu_314_p2[0:0] == 1'b1) ? trunc_ln42_9_reg_619 : 31'd0);

assign datareg_fu_211_p3 = ((icmp_ln45_fu_206_p2[0:0] == 1'b1) ? trunc_ln42_reg_574 : 31'd0);

assign icmp_ln45_10_fu_326_p2 = (($signed(p_read1026_reg_519) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_11_fu_338_p2 = (($signed(p_read_69_reg_514) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_12_fu_350_p2 = (($signed(p_read_68_reg_509) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_13_fu_362_p2 = (($signed(p_read_67_reg_504) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_14_fu_374_p2 = (($signed(p_read_66_reg_499) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_15_fu_386_p2 = (($signed(p_read_65_reg_494) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_1_fu_218_p2 = (($signed(p_read117_reg_564) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_2_fu_230_p2 = (($signed(p_read218_reg_559) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_3_fu_242_p2 = (($signed(p_read319_reg_554) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_4_fu_254_p2 = (($signed(p_read420_reg_549) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_5_fu_266_p2 = (($signed(p_read521_reg_544) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_6_fu_278_p2 = (($signed(p_read622_reg_539) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_7_fu_290_p2 = (($signed(p_read723_reg_534) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_8_fu_302_p2 = (($signed(p_read824_reg_529) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_9_fu_314_p2 = (($signed(p_read925_reg_524) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_fu_206_p2 = (($signed(p_read16_reg_569) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign trunc_ln42_10_fu_182_p1 = p_read10[30:0];

assign trunc_ln42_11_fu_186_p1 = p_read11[30:0];

assign trunc_ln42_12_fu_190_p1 = p_read12[30:0];

assign trunc_ln42_13_fu_194_p1 = p_read13[30:0];

assign trunc_ln42_14_fu_198_p1 = p_read14[30:0];

assign trunc_ln42_15_fu_202_p1 = p_read15[30:0];

assign trunc_ln42_1_fu_146_p1 = p_read1[30:0];

assign trunc_ln42_2_fu_150_p1 = p_read2[30:0];

assign trunc_ln42_3_fu_154_p1 = p_read3[30:0];

assign trunc_ln42_4_fu_158_p1 = p_read4[30:0];

assign trunc_ln42_5_fu_162_p1 = p_read5[30:0];

assign trunc_ln42_6_fu_166_p1 = p_read6[30:0];

assign trunc_ln42_7_fu_170_p1 = p_read7[30:0];

assign trunc_ln42_8_fu_174_p1 = p_read8[30:0];

assign trunc_ln42_9_fu_178_p1 = p_read9[30:0];

assign trunc_ln42_fu_142_p1 = p_read[30:0];

endmodule //myproject_relu_ap_fixed_32_6_5_3_0_ap_fixed_32_6_5_3_0_relu_config3_s
