// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="tiny_autoencoder_tiny_autoencoder,hls_ip_2025_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=9.628000,HLS_SYN_LAT=45,HLS_SYN_TPT=8,HLS_SYN_MEM=4,HLS_SYN_DSP=0,HLS_SYN_FF=12733,HLS_SYN_LUT=41793,HLS_VERSION=2025_1}" *)

module tiny_autoencoder (
        input_data_0_address0,
        input_data_0_ce0,
        input_data_0_d0,
        input_data_0_q0,
        input_data_0_we0,
        input_data_0_address1,
        input_data_0_ce1,
        input_data_0_d1,
        input_data_0_q1,
        input_data_0_we1,
        input_data_1_address0,
        input_data_1_ce0,
        input_data_1_d0,
        input_data_1_q0,
        input_data_1_we0,
        input_data_1_address1,
        input_data_1_ce1,
        input_data_1_d1,
        input_data_1_q1,
        input_data_1_we1,
        input_data_2_address0,
        input_data_2_ce0,
        input_data_2_d0,
        input_data_2_q0,
        input_data_2_we0,
        input_data_2_address1,
        input_data_2_ce1,
        input_data_2_d1,
        input_data_2_q1,
        input_data_2_we1,
        input_data_3_address0,
        input_data_3_ce0,
        input_data_3_d0,
        input_data_3_q0,
        input_data_3_we0,
        input_data_3_address1,
        input_data_3_ce1,
        input_data_3_d1,
        input_data_3_q1,
        input_data_3_we1,
        input_data_4_address0,
        input_data_4_ce0,
        input_data_4_d0,
        input_data_4_q0,
        input_data_4_we0,
        input_data_4_address1,
        input_data_4_ce1,
        input_data_4_d1,
        input_data_4_q1,
        input_data_4_we1,
        input_data_5_address0,
        input_data_5_ce0,
        input_data_5_d0,
        input_data_5_q0,
        input_data_5_we0,
        input_data_5_address1,
        input_data_5_ce1,
        input_data_5_d1,
        input_data_5_q1,
        input_data_5_we1,
        input_data_6_address0,
        input_data_6_ce0,
        input_data_6_d0,
        input_data_6_q0,
        input_data_6_we0,
        input_data_6_address1,
        input_data_6_ce1,
        input_data_6_d1,
        input_data_6_q1,
        input_data_6_we1,
        input_data_7_address0,
        input_data_7_ce0,
        input_data_7_d0,
        input_data_7_q0,
        input_data_7_we0,
        input_data_7_address1,
        input_data_7_ce1,
        input_data_7_d1,
        input_data_7_q1,
        input_data_7_we1,
        output_data_0_address0,
        output_data_0_ce0,
        output_data_0_d0,
        output_data_0_q0,
        output_data_0_we0,
        output_data_0_address1,
        output_data_0_ce1,
        output_data_0_d1,
        output_data_0_q1,
        output_data_0_we1,
        output_data_1_address0,
        output_data_1_ce0,
        output_data_1_d0,
        output_data_1_q0,
        output_data_1_we0,
        output_data_1_address1,
        output_data_1_ce1,
        output_data_1_d1,
        output_data_1_q1,
        output_data_1_we1,
        output_data_2_address0,
        output_data_2_ce0,
        output_data_2_d0,
        output_data_2_q0,
        output_data_2_we0,
        output_data_2_address1,
        output_data_2_ce1,
        output_data_2_d1,
        output_data_2_q1,
        output_data_2_we1,
        output_data_3_address0,
        output_data_3_ce0,
        output_data_3_d0,
        output_data_3_q0,
        output_data_3_we0,
        output_data_3_address1,
        output_data_3_ce1,
        output_data_3_d1,
        output_data_3_q1,
        output_data_3_we1,
        output_data_4_address0,
        output_data_4_ce0,
        output_data_4_d0,
        output_data_4_q0,
        output_data_4_we0,
        output_data_4_address1,
        output_data_4_ce1,
        output_data_4_d1,
        output_data_4_q1,
        output_data_4_we1,
        output_data_5_address0,
        output_data_5_ce0,
        output_data_5_d0,
        output_data_5_q0,
        output_data_5_we0,
        output_data_5_address1,
        output_data_5_ce1,
        output_data_5_d1,
        output_data_5_q1,
        output_data_5_we1,
        output_data_6_address0,
        output_data_6_ce0,
        output_data_6_d0,
        output_data_6_q0,
        output_data_6_we0,
        output_data_6_address1,
        output_data_6_ce1,
        output_data_6_d1,
        output_data_6_q1,
        output_data_6_we1,
        output_data_7_address0,
        output_data_7_ce0,
        output_data_7_d0,
        output_data_7_q0,
        output_data_7_we0,
        output_data_7_address1,
        output_data_7_ce1,
        output_data_7_d1,
        output_data_7_q1,
        output_data_7_we1,
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_ready,
        ap_idle
);


output  [2:0] input_data_0_address0;
output   input_data_0_ce0;
output  [15:0] input_data_0_d0;
input  [15:0] input_data_0_q0;
output   input_data_0_we0;
output  [2:0] input_data_0_address1;
output   input_data_0_ce1;
output  [15:0] input_data_0_d1;
input  [15:0] input_data_0_q1;
output   input_data_0_we1;
output  [2:0] input_data_1_address0;
output   input_data_1_ce0;
output  [15:0] input_data_1_d0;
input  [15:0] input_data_1_q0;
output   input_data_1_we0;
output  [2:0] input_data_1_address1;
output   input_data_1_ce1;
output  [15:0] input_data_1_d1;
input  [15:0] input_data_1_q1;
output   input_data_1_we1;
output  [2:0] input_data_2_address0;
output   input_data_2_ce0;
output  [15:0] input_data_2_d0;
input  [15:0] input_data_2_q0;
output   input_data_2_we0;
output  [2:0] input_data_2_address1;
output   input_data_2_ce1;
output  [15:0] input_data_2_d1;
input  [15:0] input_data_2_q1;
output   input_data_2_we1;
output  [2:0] input_data_3_address0;
output   input_data_3_ce0;
output  [15:0] input_data_3_d0;
input  [15:0] input_data_3_q0;
output   input_data_3_we0;
output  [2:0] input_data_3_address1;
output   input_data_3_ce1;
output  [15:0] input_data_3_d1;
input  [15:0] input_data_3_q1;
output   input_data_3_we1;
output  [2:0] input_data_4_address0;
output   input_data_4_ce0;
output  [15:0] input_data_4_d0;
input  [15:0] input_data_4_q0;
output   input_data_4_we0;
output  [2:0] input_data_4_address1;
output   input_data_4_ce1;
output  [15:0] input_data_4_d1;
input  [15:0] input_data_4_q1;
output   input_data_4_we1;
output  [2:0] input_data_5_address0;
output   input_data_5_ce0;
output  [15:0] input_data_5_d0;
input  [15:0] input_data_5_q0;
output   input_data_5_we0;
output  [2:0] input_data_5_address1;
output   input_data_5_ce1;
output  [15:0] input_data_5_d1;
input  [15:0] input_data_5_q1;
output   input_data_5_we1;
output  [2:0] input_data_6_address0;
output   input_data_6_ce0;
output  [15:0] input_data_6_d0;
input  [15:0] input_data_6_q0;
output   input_data_6_we0;
output  [2:0] input_data_6_address1;
output   input_data_6_ce1;
output  [15:0] input_data_6_d1;
input  [15:0] input_data_6_q1;
output   input_data_6_we1;
output  [2:0] input_data_7_address0;
output   input_data_7_ce0;
output  [15:0] input_data_7_d0;
input  [15:0] input_data_7_q0;
output   input_data_7_we0;
output  [2:0] input_data_7_address1;
output   input_data_7_ce1;
output  [15:0] input_data_7_d1;
input  [15:0] input_data_7_q1;
output   input_data_7_we1;
output  [2:0] output_data_0_address0;
output   output_data_0_ce0;
output  [15:0] output_data_0_d0;
input  [15:0] output_data_0_q0;
output   output_data_0_we0;
output  [2:0] output_data_0_address1;
output   output_data_0_ce1;
output  [15:0] output_data_0_d1;
input  [15:0] output_data_0_q1;
output   output_data_0_we1;
output  [2:0] output_data_1_address0;
output   output_data_1_ce0;
output  [15:0] output_data_1_d0;
input  [15:0] output_data_1_q0;
output   output_data_1_we0;
output  [2:0] output_data_1_address1;
output   output_data_1_ce1;
output  [15:0] output_data_1_d1;
input  [15:0] output_data_1_q1;
output   output_data_1_we1;
output  [2:0] output_data_2_address0;
output   output_data_2_ce0;
output  [15:0] output_data_2_d0;
input  [15:0] output_data_2_q0;
output   output_data_2_we0;
output  [2:0] output_data_2_address1;
output   output_data_2_ce1;
output  [15:0] output_data_2_d1;
input  [15:0] output_data_2_q1;
output   output_data_2_we1;
output  [2:0] output_data_3_address0;
output   output_data_3_ce0;
output  [15:0] output_data_3_d0;
input  [15:0] output_data_3_q0;
output   output_data_3_we0;
output  [2:0] output_data_3_address1;
output   output_data_3_ce1;
output  [15:0] output_data_3_d1;
input  [15:0] output_data_3_q1;
output   output_data_3_we1;
output  [2:0] output_data_4_address0;
output   output_data_4_ce0;
output  [15:0] output_data_4_d0;
input  [15:0] output_data_4_q0;
output   output_data_4_we0;
output  [2:0] output_data_4_address1;
output   output_data_4_ce1;
output  [15:0] output_data_4_d1;
input  [15:0] output_data_4_q1;
output   output_data_4_we1;
output  [2:0] output_data_5_address0;
output   output_data_5_ce0;
output  [15:0] output_data_5_d0;
input  [15:0] output_data_5_q0;
output   output_data_5_we0;
output  [2:0] output_data_5_address1;
output   output_data_5_ce1;
output  [15:0] output_data_5_d1;
input  [15:0] output_data_5_q1;
output   output_data_5_we1;
output  [2:0] output_data_6_address0;
output   output_data_6_ce0;
output  [15:0] output_data_6_d0;
input  [15:0] output_data_6_q0;
output   output_data_6_we0;
output  [2:0] output_data_6_address1;
output   output_data_6_ce1;
output  [15:0] output_data_6_d1;
input  [15:0] output_data_6_q1;
output   output_data_6_we1;
output  [2:0] output_data_7_address0;
output   output_data_7_ce0;
output  [15:0] output_data_7_d0;
input  [15:0] output_data_7_q0;
output   output_data_7_we0;
output  [2:0] output_data_7_address1;
output   output_data_7_ce1;
output  [15:0] output_data_7_d1;
input  [15:0] output_data_7_q1;
output   output_data_7_we1;
input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_ready;
output   ap_idle;

wire    compute_encoder_U0_ap_start;
wire    compute_encoder_U0_ap_done;
wire    compute_encoder_U0_ap_continue;
wire    compute_encoder_U0_ap_idle;
wire    compute_encoder_U0_ap_ready;
wire   [2:0] compute_encoder_U0_input_data_0_address0;
wire    compute_encoder_U0_input_data_0_ce0;
wire   [2:0] compute_encoder_U0_input_data_1_address0;
wire    compute_encoder_U0_input_data_1_ce0;
wire   [2:0] compute_encoder_U0_input_data_2_address0;
wire    compute_encoder_U0_input_data_2_ce0;
wire   [2:0] compute_encoder_U0_input_data_3_address0;
wire    compute_encoder_U0_input_data_3_ce0;
wire   [2:0] compute_encoder_U0_input_data_4_address0;
wire    compute_encoder_U0_input_data_4_ce0;
wire   [2:0] compute_encoder_U0_input_data_5_address0;
wire    compute_encoder_U0_input_data_5_ce0;
wire   [2:0] compute_encoder_U0_input_data_6_address0;
wire    compute_encoder_U0_input_data_6_ce0;
wire   [2:0] compute_encoder_U0_input_data_7_address0;
wire    compute_encoder_U0_input_data_7_ce0;
wire   [15:0] compute_encoder_U0_ap_return_0;
wire   [15:0] compute_encoder_U0_ap_return_1;
wire   [15:0] compute_encoder_U0_ap_return_2;
wire   [15:0] compute_encoder_U0_ap_return_3;
wire   [15:0] compute_encoder_U0_ap_return_4;
wire   [15:0] compute_encoder_U0_ap_return_5;
wire   [15:0] compute_encoder_U0_ap_return_6;
wire   [15:0] compute_encoder_U0_ap_return_7;
wire   [15:0] compute_encoder_U0_ap_return_8;
wire   [15:0] compute_encoder_U0_ap_return_9;
wire   [15:0] compute_encoder_U0_ap_return_10;
wire   [15:0] compute_encoder_U0_ap_return_11;
wire   [15:0] compute_encoder_U0_ap_return_12;
wire   [15:0] compute_encoder_U0_ap_return_13;
wire   [15:0] compute_encoder_U0_ap_return_14;
wire   [15:0] compute_encoder_U0_ap_return_15;
wire    ap_channel_done_hidden_layer_buf_15;
wire    hidden_layer_buf_15_full_n;
reg    ap_sync_reg_channel_write_hidden_layer_buf_15;
wire    ap_sync_channel_write_hidden_layer_buf_15;
wire    compute_decoder_U0_ap_start;
wire    compute_decoder_U0_ap_done;
wire    compute_decoder_U0_ap_continue;
wire    compute_decoder_U0_ap_idle;
wire    compute_decoder_U0_ap_ready;
wire   [2:0] compute_decoder_U0_output_data_0_address0;
wire    compute_decoder_U0_output_data_0_ce0;
wire    compute_decoder_U0_output_data_0_we0;
wire   [15:0] compute_decoder_U0_output_data_0_d0;
wire   [2:0] compute_decoder_U0_output_data_1_address0;
wire    compute_decoder_U0_output_data_1_ce0;
wire    compute_decoder_U0_output_data_1_we0;
wire   [15:0] compute_decoder_U0_output_data_1_d0;
wire   [2:0] compute_decoder_U0_output_data_2_address0;
wire    compute_decoder_U0_output_data_2_ce0;
wire    compute_decoder_U0_output_data_2_we0;
wire   [15:0] compute_decoder_U0_output_data_2_d0;
wire   [2:0] compute_decoder_U0_output_data_3_address0;
wire    compute_decoder_U0_output_data_3_ce0;
wire    compute_decoder_U0_output_data_3_we0;
wire   [15:0] compute_decoder_U0_output_data_3_d0;
wire   [2:0] compute_decoder_U0_output_data_4_address0;
wire    compute_decoder_U0_output_data_4_ce0;
wire    compute_decoder_U0_output_data_4_we0;
wire   [15:0] compute_decoder_U0_output_data_4_d0;
wire   [2:0] compute_decoder_U0_output_data_5_address0;
wire    compute_decoder_U0_output_data_5_ce0;
wire    compute_decoder_U0_output_data_5_we0;
wire   [15:0] compute_decoder_U0_output_data_5_d0;
wire   [2:0] compute_decoder_U0_output_data_6_address0;
wire    compute_decoder_U0_output_data_6_ce0;
wire    compute_decoder_U0_output_data_6_we0;
wire   [15:0] compute_decoder_U0_output_data_6_d0;
wire   [2:0] compute_decoder_U0_output_data_7_address0;
wire    compute_decoder_U0_output_data_7_ce0;
wire    compute_decoder_U0_output_data_7_we0;
wire   [15:0] compute_decoder_U0_output_data_7_d0;
wire    hidden_layer_buf_full_n;
wire   [15:0] hidden_layer_buf_dout;
wire    hidden_layer_buf_empty_n;
wire   [2:0] hidden_layer_buf_num_data_valid;
wire   [2:0] hidden_layer_buf_fifo_cap;
wire    hidden_layer_buf_1_full_n;
wire   [15:0] hidden_layer_buf_1_dout;
wire    hidden_layer_buf_1_empty_n;
wire   [2:0] hidden_layer_buf_1_num_data_valid;
wire   [2:0] hidden_layer_buf_1_fifo_cap;
wire    hidden_layer_buf_2_full_n;
wire   [15:0] hidden_layer_buf_2_dout;
wire    hidden_layer_buf_2_empty_n;
wire   [2:0] hidden_layer_buf_2_num_data_valid;
wire   [2:0] hidden_layer_buf_2_fifo_cap;
wire    hidden_layer_buf_3_full_n;
wire   [15:0] hidden_layer_buf_3_dout;
wire    hidden_layer_buf_3_empty_n;
wire   [2:0] hidden_layer_buf_3_num_data_valid;
wire   [2:0] hidden_layer_buf_3_fifo_cap;
wire    hidden_layer_buf_4_full_n;
wire   [15:0] hidden_layer_buf_4_dout;
wire    hidden_layer_buf_4_empty_n;
wire   [2:0] hidden_layer_buf_4_num_data_valid;
wire   [2:0] hidden_layer_buf_4_fifo_cap;
wire    hidden_layer_buf_5_full_n;
wire   [15:0] hidden_layer_buf_5_dout;
wire    hidden_layer_buf_5_empty_n;
wire   [2:0] hidden_layer_buf_5_num_data_valid;
wire   [2:0] hidden_layer_buf_5_fifo_cap;
wire    hidden_layer_buf_6_full_n;
wire   [15:0] hidden_layer_buf_6_dout;
wire    hidden_layer_buf_6_empty_n;
wire   [2:0] hidden_layer_buf_6_num_data_valid;
wire   [2:0] hidden_layer_buf_6_fifo_cap;
wire    hidden_layer_buf_7_full_n;
wire   [15:0] hidden_layer_buf_7_dout;
wire    hidden_layer_buf_7_empty_n;
wire   [2:0] hidden_layer_buf_7_num_data_valid;
wire   [2:0] hidden_layer_buf_7_fifo_cap;
wire    hidden_layer_buf_8_full_n;
wire   [15:0] hidden_layer_buf_8_dout;
wire    hidden_layer_buf_8_empty_n;
wire   [2:0] hidden_layer_buf_8_num_data_valid;
wire   [2:0] hidden_layer_buf_8_fifo_cap;
wire    hidden_layer_buf_9_full_n;
wire   [15:0] hidden_layer_buf_9_dout;
wire    hidden_layer_buf_9_empty_n;
wire   [2:0] hidden_layer_buf_9_num_data_valid;
wire   [2:0] hidden_layer_buf_9_fifo_cap;
wire    hidden_layer_buf_10_full_n;
wire   [15:0] hidden_layer_buf_10_dout;
wire    hidden_layer_buf_10_empty_n;
wire   [2:0] hidden_layer_buf_10_num_data_valid;
wire   [2:0] hidden_layer_buf_10_fifo_cap;
wire    hidden_layer_buf_11_full_n;
wire   [15:0] hidden_layer_buf_11_dout;
wire    hidden_layer_buf_11_empty_n;
wire   [2:0] hidden_layer_buf_11_num_data_valid;
wire   [2:0] hidden_layer_buf_11_fifo_cap;
wire    hidden_layer_buf_12_full_n;
wire   [15:0] hidden_layer_buf_12_dout;
wire    hidden_layer_buf_12_empty_n;
wire   [2:0] hidden_layer_buf_12_num_data_valid;
wire   [2:0] hidden_layer_buf_12_fifo_cap;
wire    hidden_layer_buf_13_full_n;
wire   [15:0] hidden_layer_buf_13_dout;
wire    hidden_layer_buf_13_empty_n;
wire   [2:0] hidden_layer_buf_13_num_data_valid;
wire   [2:0] hidden_layer_buf_13_fifo_cap;
wire    hidden_layer_buf_14_full_n;
wire   [15:0] hidden_layer_buf_14_dout;
wire    hidden_layer_buf_14_empty_n;
wire   [2:0] hidden_layer_buf_14_num_data_valid;
wire   [2:0] hidden_layer_buf_14_fifo_cap;
wire   [15:0] hidden_layer_buf_15_dout;
wire    hidden_layer_buf_15_empty_n;
wire   [2:0] hidden_layer_buf_15_num_data_valid;
wire   [2:0] hidden_layer_buf_15_fifo_cap;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_sync_reg_channel_write_hidden_layer_buf_15 = 1'b0;
end

tiny_autoencoder_compute_encoder compute_encoder_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(compute_encoder_U0_ap_start),
    .ap_done(compute_encoder_U0_ap_done),
    .ap_continue(compute_encoder_U0_ap_continue),
    .ap_idle(compute_encoder_U0_ap_idle),
    .ap_ready(compute_encoder_U0_ap_ready),
    .input_data_0_address0(compute_encoder_U0_input_data_0_address0),
    .input_data_0_ce0(compute_encoder_U0_input_data_0_ce0),
    .input_data_0_q0(input_data_0_q0),
    .input_data_1_address0(compute_encoder_U0_input_data_1_address0),
    .input_data_1_ce0(compute_encoder_U0_input_data_1_ce0),
    .input_data_1_q0(input_data_1_q0),
    .input_data_2_address0(compute_encoder_U0_input_data_2_address0),
    .input_data_2_ce0(compute_encoder_U0_input_data_2_ce0),
    .input_data_2_q0(input_data_2_q0),
    .input_data_3_address0(compute_encoder_U0_input_data_3_address0),
    .input_data_3_ce0(compute_encoder_U0_input_data_3_ce0),
    .input_data_3_q0(input_data_3_q0),
    .input_data_4_address0(compute_encoder_U0_input_data_4_address0),
    .input_data_4_ce0(compute_encoder_U0_input_data_4_ce0),
    .input_data_4_q0(input_data_4_q0),
    .input_data_5_address0(compute_encoder_U0_input_data_5_address0),
    .input_data_5_ce0(compute_encoder_U0_input_data_5_ce0),
    .input_data_5_q0(input_data_5_q0),
    .input_data_6_address0(compute_encoder_U0_input_data_6_address0),
    .input_data_6_ce0(compute_encoder_U0_input_data_6_ce0),
    .input_data_6_q0(input_data_6_q0),
    .input_data_7_address0(compute_encoder_U0_input_data_7_address0),
    .input_data_7_ce0(compute_encoder_U0_input_data_7_ce0),
    .input_data_7_q0(input_data_7_q0),
    .ap_return_0(compute_encoder_U0_ap_return_0),
    .ap_return_1(compute_encoder_U0_ap_return_1),
    .ap_return_2(compute_encoder_U0_ap_return_2),
    .ap_return_3(compute_encoder_U0_ap_return_3),
    .ap_return_4(compute_encoder_U0_ap_return_4),
    .ap_return_5(compute_encoder_U0_ap_return_5),
    .ap_return_6(compute_encoder_U0_ap_return_6),
    .ap_return_7(compute_encoder_U0_ap_return_7),
    .ap_return_8(compute_encoder_U0_ap_return_8),
    .ap_return_9(compute_encoder_U0_ap_return_9),
    .ap_return_10(compute_encoder_U0_ap_return_10),
    .ap_return_11(compute_encoder_U0_ap_return_11),
    .ap_return_12(compute_encoder_U0_ap_return_12),
    .ap_return_13(compute_encoder_U0_ap_return_13),
    .ap_return_14(compute_encoder_U0_ap_return_14),
    .ap_return_15(compute_encoder_U0_ap_return_15)
);

tiny_autoencoder_compute_decoder compute_decoder_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(compute_decoder_U0_ap_start),
    .ap_done(compute_decoder_U0_ap_done),
    .ap_continue(compute_decoder_U0_ap_continue),
    .ap_idle(compute_decoder_U0_ap_idle),
    .ap_ready(compute_decoder_U0_ap_ready),
    .p_read(hidden_layer_buf_dout),
    .p_read1(hidden_layer_buf_1_dout),
    .p_read2(hidden_layer_buf_2_dout),
    .p_read3(hidden_layer_buf_3_dout),
    .p_read4(hidden_layer_buf_4_dout),
    .p_read5(hidden_layer_buf_5_dout),
    .p_read6(hidden_layer_buf_6_dout),
    .p_read7(hidden_layer_buf_7_dout),
    .p_read8(hidden_layer_buf_8_dout),
    .p_read9(hidden_layer_buf_9_dout),
    .p_read10(hidden_layer_buf_10_dout),
    .p_read11(hidden_layer_buf_11_dout),
    .p_read12(hidden_layer_buf_12_dout),
    .p_read13(hidden_layer_buf_13_dout),
    .p_read14(hidden_layer_buf_14_dout),
    .p_read15(hidden_layer_buf_15_dout),
    .output_data_0_address0(compute_decoder_U0_output_data_0_address0),
    .output_data_0_ce0(compute_decoder_U0_output_data_0_ce0),
    .output_data_0_we0(compute_decoder_U0_output_data_0_we0),
    .output_data_0_d0(compute_decoder_U0_output_data_0_d0),
    .output_data_1_address0(compute_decoder_U0_output_data_1_address0),
    .output_data_1_ce0(compute_decoder_U0_output_data_1_ce0),
    .output_data_1_we0(compute_decoder_U0_output_data_1_we0),
    .output_data_1_d0(compute_decoder_U0_output_data_1_d0),
    .output_data_2_address0(compute_decoder_U0_output_data_2_address0),
    .output_data_2_ce0(compute_decoder_U0_output_data_2_ce0),
    .output_data_2_we0(compute_decoder_U0_output_data_2_we0),
    .output_data_2_d0(compute_decoder_U0_output_data_2_d0),
    .output_data_3_address0(compute_decoder_U0_output_data_3_address0),
    .output_data_3_ce0(compute_decoder_U0_output_data_3_ce0),
    .output_data_3_we0(compute_decoder_U0_output_data_3_we0),
    .output_data_3_d0(compute_decoder_U0_output_data_3_d0),
    .output_data_4_address0(compute_decoder_U0_output_data_4_address0),
    .output_data_4_ce0(compute_decoder_U0_output_data_4_ce0),
    .output_data_4_we0(compute_decoder_U0_output_data_4_we0),
    .output_data_4_d0(compute_decoder_U0_output_data_4_d0),
    .output_data_5_address0(compute_decoder_U0_output_data_5_address0),
    .output_data_5_ce0(compute_decoder_U0_output_data_5_ce0),
    .output_data_5_we0(compute_decoder_U0_output_data_5_we0),
    .output_data_5_d0(compute_decoder_U0_output_data_5_d0),
    .output_data_6_address0(compute_decoder_U0_output_data_6_address0),
    .output_data_6_ce0(compute_decoder_U0_output_data_6_ce0),
    .output_data_6_we0(compute_decoder_U0_output_data_6_we0),
    .output_data_6_d0(compute_decoder_U0_output_data_6_d0),
    .output_data_7_address0(compute_decoder_U0_output_data_7_address0),
    .output_data_7_ce0(compute_decoder_U0_output_data_7_ce0),
    .output_data_7_we0(compute_decoder_U0_output_data_7_we0),
    .output_data_7_d0(compute_decoder_U0_output_data_7_d0)
);

tiny_autoencoder_fifo_w16_d2_S hidden_layer_buf_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(compute_encoder_U0_ap_return_0),
    .if_full_n(hidden_layer_buf_full_n),
    .if_write(ap_channel_done_hidden_layer_buf_15),
    .if_dout(hidden_layer_buf_dout),
    .if_empty_n(hidden_layer_buf_empty_n),
    .if_read(compute_decoder_U0_ap_ready),
    .if_num_data_valid(hidden_layer_buf_num_data_valid),
    .if_fifo_cap(hidden_layer_buf_fifo_cap)
);

tiny_autoencoder_fifo_w16_d2_S hidden_layer_buf_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(compute_encoder_U0_ap_return_1),
    .if_full_n(hidden_layer_buf_1_full_n),
    .if_write(ap_channel_done_hidden_layer_buf_15),
    .if_dout(hidden_layer_buf_1_dout),
    .if_empty_n(hidden_layer_buf_1_empty_n),
    .if_read(compute_decoder_U0_ap_ready),
    .if_num_data_valid(hidden_layer_buf_1_num_data_valid),
    .if_fifo_cap(hidden_layer_buf_1_fifo_cap)
);

tiny_autoencoder_fifo_w16_d2_S hidden_layer_buf_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(compute_encoder_U0_ap_return_2),
    .if_full_n(hidden_layer_buf_2_full_n),
    .if_write(ap_channel_done_hidden_layer_buf_15),
    .if_dout(hidden_layer_buf_2_dout),
    .if_empty_n(hidden_layer_buf_2_empty_n),
    .if_read(compute_decoder_U0_ap_ready),
    .if_num_data_valid(hidden_layer_buf_2_num_data_valid),
    .if_fifo_cap(hidden_layer_buf_2_fifo_cap)
);

tiny_autoencoder_fifo_w16_d2_S hidden_layer_buf_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(compute_encoder_U0_ap_return_3),
    .if_full_n(hidden_layer_buf_3_full_n),
    .if_write(ap_channel_done_hidden_layer_buf_15),
    .if_dout(hidden_layer_buf_3_dout),
    .if_empty_n(hidden_layer_buf_3_empty_n),
    .if_read(compute_decoder_U0_ap_ready),
    .if_num_data_valid(hidden_layer_buf_3_num_data_valid),
    .if_fifo_cap(hidden_layer_buf_3_fifo_cap)
);

tiny_autoencoder_fifo_w16_d2_S hidden_layer_buf_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(compute_encoder_U0_ap_return_4),
    .if_full_n(hidden_layer_buf_4_full_n),
    .if_write(ap_channel_done_hidden_layer_buf_15),
    .if_dout(hidden_layer_buf_4_dout),
    .if_empty_n(hidden_layer_buf_4_empty_n),
    .if_read(compute_decoder_U0_ap_ready),
    .if_num_data_valid(hidden_layer_buf_4_num_data_valid),
    .if_fifo_cap(hidden_layer_buf_4_fifo_cap)
);

tiny_autoencoder_fifo_w16_d2_S hidden_layer_buf_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(compute_encoder_U0_ap_return_5),
    .if_full_n(hidden_layer_buf_5_full_n),
    .if_write(ap_channel_done_hidden_layer_buf_15),
    .if_dout(hidden_layer_buf_5_dout),
    .if_empty_n(hidden_layer_buf_5_empty_n),
    .if_read(compute_decoder_U0_ap_ready),
    .if_num_data_valid(hidden_layer_buf_5_num_data_valid),
    .if_fifo_cap(hidden_layer_buf_5_fifo_cap)
);

tiny_autoencoder_fifo_w16_d2_S hidden_layer_buf_6_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(compute_encoder_U0_ap_return_6),
    .if_full_n(hidden_layer_buf_6_full_n),
    .if_write(ap_channel_done_hidden_layer_buf_15),
    .if_dout(hidden_layer_buf_6_dout),
    .if_empty_n(hidden_layer_buf_6_empty_n),
    .if_read(compute_decoder_U0_ap_ready),
    .if_num_data_valid(hidden_layer_buf_6_num_data_valid),
    .if_fifo_cap(hidden_layer_buf_6_fifo_cap)
);

tiny_autoencoder_fifo_w16_d2_S hidden_layer_buf_7_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(compute_encoder_U0_ap_return_7),
    .if_full_n(hidden_layer_buf_7_full_n),
    .if_write(ap_channel_done_hidden_layer_buf_15),
    .if_dout(hidden_layer_buf_7_dout),
    .if_empty_n(hidden_layer_buf_7_empty_n),
    .if_read(compute_decoder_U0_ap_ready),
    .if_num_data_valid(hidden_layer_buf_7_num_data_valid),
    .if_fifo_cap(hidden_layer_buf_7_fifo_cap)
);

tiny_autoencoder_fifo_w16_d2_S hidden_layer_buf_8_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(compute_encoder_U0_ap_return_8),
    .if_full_n(hidden_layer_buf_8_full_n),
    .if_write(ap_channel_done_hidden_layer_buf_15),
    .if_dout(hidden_layer_buf_8_dout),
    .if_empty_n(hidden_layer_buf_8_empty_n),
    .if_read(compute_decoder_U0_ap_ready),
    .if_num_data_valid(hidden_layer_buf_8_num_data_valid),
    .if_fifo_cap(hidden_layer_buf_8_fifo_cap)
);

tiny_autoencoder_fifo_w16_d2_S hidden_layer_buf_9_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(compute_encoder_U0_ap_return_9),
    .if_full_n(hidden_layer_buf_9_full_n),
    .if_write(ap_channel_done_hidden_layer_buf_15),
    .if_dout(hidden_layer_buf_9_dout),
    .if_empty_n(hidden_layer_buf_9_empty_n),
    .if_read(compute_decoder_U0_ap_ready),
    .if_num_data_valid(hidden_layer_buf_9_num_data_valid),
    .if_fifo_cap(hidden_layer_buf_9_fifo_cap)
);

tiny_autoencoder_fifo_w16_d2_S hidden_layer_buf_10_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(compute_encoder_U0_ap_return_10),
    .if_full_n(hidden_layer_buf_10_full_n),
    .if_write(ap_channel_done_hidden_layer_buf_15),
    .if_dout(hidden_layer_buf_10_dout),
    .if_empty_n(hidden_layer_buf_10_empty_n),
    .if_read(compute_decoder_U0_ap_ready),
    .if_num_data_valid(hidden_layer_buf_10_num_data_valid),
    .if_fifo_cap(hidden_layer_buf_10_fifo_cap)
);

tiny_autoencoder_fifo_w16_d2_S hidden_layer_buf_11_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(compute_encoder_U0_ap_return_11),
    .if_full_n(hidden_layer_buf_11_full_n),
    .if_write(ap_channel_done_hidden_layer_buf_15),
    .if_dout(hidden_layer_buf_11_dout),
    .if_empty_n(hidden_layer_buf_11_empty_n),
    .if_read(compute_decoder_U0_ap_ready),
    .if_num_data_valid(hidden_layer_buf_11_num_data_valid),
    .if_fifo_cap(hidden_layer_buf_11_fifo_cap)
);

tiny_autoencoder_fifo_w16_d2_S hidden_layer_buf_12_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(compute_encoder_U0_ap_return_12),
    .if_full_n(hidden_layer_buf_12_full_n),
    .if_write(ap_channel_done_hidden_layer_buf_15),
    .if_dout(hidden_layer_buf_12_dout),
    .if_empty_n(hidden_layer_buf_12_empty_n),
    .if_read(compute_decoder_U0_ap_ready),
    .if_num_data_valid(hidden_layer_buf_12_num_data_valid),
    .if_fifo_cap(hidden_layer_buf_12_fifo_cap)
);

tiny_autoencoder_fifo_w16_d2_S hidden_layer_buf_13_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(compute_encoder_U0_ap_return_13),
    .if_full_n(hidden_layer_buf_13_full_n),
    .if_write(ap_channel_done_hidden_layer_buf_15),
    .if_dout(hidden_layer_buf_13_dout),
    .if_empty_n(hidden_layer_buf_13_empty_n),
    .if_read(compute_decoder_U0_ap_ready),
    .if_num_data_valid(hidden_layer_buf_13_num_data_valid),
    .if_fifo_cap(hidden_layer_buf_13_fifo_cap)
);

tiny_autoencoder_fifo_w16_d2_S hidden_layer_buf_14_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(compute_encoder_U0_ap_return_14),
    .if_full_n(hidden_layer_buf_14_full_n),
    .if_write(ap_channel_done_hidden_layer_buf_15),
    .if_dout(hidden_layer_buf_14_dout),
    .if_empty_n(hidden_layer_buf_14_empty_n),
    .if_read(compute_decoder_U0_ap_ready),
    .if_num_data_valid(hidden_layer_buf_14_num_data_valid),
    .if_fifo_cap(hidden_layer_buf_14_fifo_cap)
);

tiny_autoencoder_fifo_w16_d2_S hidden_layer_buf_15_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(compute_encoder_U0_ap_return_15),
    .if_full_n(hidden_layer_buf_15_full_n),
    .if_write(ap_channel_done_hidden_layer_buf_15),
    .if_dout(hidden_layer_buf_15_dout),
    .if_empty_n(hidden_layer_buf_15_empty_n),
    .if_read(compute_decoder_U0_ap_ready),
    .if_num_data_valid(hidden_layer_buf_15_num_data_valid),
    .if_fifo_cap(hidden_layer_buf_15_fifo_cap)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_hidden_layer_buf_15 <= 1'b0;
    end else begin
        if (((compute_encoder_U0_ap_done & compute_encoder_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_hidden_layer_buf_15 <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_hidden_layer_buf_15 <= ap_sync_channel_write_hidden_layer_buf_15;
        end
    end
end

assign ap_channel_done_hidden_layer_buf_15 = ((ap_sync_reg_channel_write_hidden_layer_buf_15 ^ 1'b1) & compute_encoder_U0_ap_done);

assign ap_done = compute_decoder_U0_ap_done;

assign ap_idle = ((hidden_layer_buf_empty_n ^ 1'b1) & compute_encoder_U0_ap_idle & compute_decoder_U0_ap_idle);

assign ap_ready = compute_encoder_U0_ap_ready;

assign ap_sync_channel_write_hidden_layer_buf_15 = ((hidden_layer_buf_15_full_n & ap_channel_done_hidden_layer_buf_15) | ap_sync_reg_channel_write_hidden_layer_buf_15);

assign compute_decoder_U0_ap_continue = 1'b1;

assign compute_decoder_U0_ap_start = hidden_layer_buf_empty_n;

assign compute_encoder_U0_ap_continue = ap_sync_channel_write_hidden_layer_buf_15;

assign compute_encoder_U0_ap_start = ap_start;

assign input_data_0_address0 = compute_encoder_U0_input_data_0_address0;

assign input_data_0_address1 = 3'd0;

assign input_data_0_ce0 = compute_encoder_U0_input_data_0_ce0;

assign input_data_0_ce1 = 1'b0;

assign input_data_0_d0 = 16'd0;

assign input_data_0_d1 = 16'd0;

assign input_data_0_we0 = 1'b0;

assign input_data_0_we1 = 1'b0;

assign input_data_1_address0 = compute_encoder_U0_input_data_1_address0;

assign input_data_1_address1 = 3'd0;

assign input_data_1_ce0 = compute_encoder_U0_input_data_1_ce0;

assign input_data_1_ce1 = 1'b0;

assign input_data_1_d0 = 16'd0;

assign input_data_1_d1 = 16'd0;

assign input_data_1_we0 = 1'b0;

assign input_data_1_we1 = 1'b0;

assign input_data_2_address0 = compute_encoder_U0_input_data_2_address0;

assign input_data_2_address1 = 3'd0;

assign input_data_2_ce0 = compute_encoder_U0_input_data_2_ce0;

assign input_data_2_ce1 = 1'b0;

assign input_data_2_d0 = 16'd0;

assign input_data_2_d1 = 16'd0;

assign input_data_2_we0 = 1'b0;

assign input_data_2_we1 = 1'b0;

assign input_data_3_address0 = compute_encoder_U0_input_data_3_address0;

assign input_data_3_address1 = 3'd0;

assign input_data_3_ce0 = compute_encoder_U0_input_data_3_ce0;

assign input_data_3_ce1 = 1'b0;

assign input_data_3_d0 = 16'd0;

assign input_data_3_d1 = 16'd0;

assign input_data_3_we0 = 1'b0;

assign input_data_3_we1 = 1'b0;

assign input_data_4_address0 = compute_encoder_U0_input_data_4_address0;

assign input_data_4_address1 = 3'd0;

assign input_data_4_ce0 = compute_encoder_U0_input_data_4_ce0;

assign input_data_4_ce1 = 1'b0;

assign input_data_4_d0 = 16'd0;

assign input_data_4_d1 = 16'd0;

assign input_data_4_we0 = 1'b0;

assign input_data_4_we1 = 1'b0;

assign input_data_5_address0 = compute_encoder_U0_input_data_5_address0;

assign input_data_5_address1 = 3'd0;

assign input_data_5_ce0 = compute_encoder_U0_input_data_5_ce0;

assign input_data_5_ce1 = 1'b0;

assign input_data_5_d0 = 16'd0;

assign input_data_5_d1 = 16'd0;

assign input_data_5_we0 = 1'b0;

assign input_data_5_we1 = 1'b0;

assign input_data_6_address0 = compute_encoder_U0_input_data_6_address0;

assign input_data_6_address1 = 3'd0;

assign input_data_6_ce0 = compute_encoder_U0_input_data_6_ce0;

assign input_data_6_ce1 = 1'b0;

assign input_data_6_d0 = 16'd0;

assign input_data_6_d1 = 16'd0;

assign input_data_6_we0 = 1'b0;

assign input_data_6_we1 = 1'b0;

assign input_data_7_address0 = compute_encoder_U0_input_data_7_address0;

assign input_data_7_address1 = 3'd0;

assign input_data_7_ce0 = compute_encoder_U0_input_data_7_ce0;

assign input_data_7_ce1 = 1'b0;

assign input_data_7_d0 = 16'd0;

assign input_data_7_d1 = 16'd0;

assign input_data_7_we0 = 1'b0;

assign input_data_7_we1 = 1'b0;

assign output_data_0_address0 = compute_decoder_U0_output_data_0_address0;

assign output_data_0_address1 = 3'd0;

assign output_data_0_ce0 = compute_decoder_U0_output_data_0_ce0;

assign output_data_0_ce1 = 1'b0;

assign output_data_0_d0 = compute_decoder_U0_output_data_0_d0;

assign output_data_0_d1 = 16'd0;

assign output_data_0_we0 = compute_decoder_U0_output_data_0_we0;

assign output_data_0_we1 = 1'b0;

assign output_data_1_address0 = compute_decoder_U0_output_data_1_address0;

assign output_data_1_address1 = 3'd0;

assign output_data_1_ce0 = compute_decoder_U0_output_data_1_ce0;

assign output_data_1_ce1 = 1'b0;

assign output_data_1_d0 = compute_decoder_U0_output_data_1_d0;

assign output_data_1_d1 = 16'd0;

assign output_data_1_we0 = compute_decoder_U0_output_data_1_we0;

assign output_data_1_we1 = 1'b0;

assign output_data_2_address0 = compute_decoder_U0_output_data_2_address0;

assign output_data_2_address1 = 3'd0;

assign output_data_2_ce0 = compute_decoder_U0_output_data_2_ce0;

assign output_data_2_ce1 = 1'b0;

assign output_data_2_d0 = compute_decoder_U0_output_data_2_d0;

assign output_data_2_d1 = 16'd0;

assign output_data_2_we0 = compute_decoder_U0_output_data_2_we0;

assign output_data_2_we1 = 1'b0;

assign output_data_3_address0 = compute_decoder_U0_output_data_3_address0;

assign output_data_3_address1 = 3'd0;

assign output_data_3_ce0 = compute_decoder_U0_output_data_3_ce0;

assign output_data_3_ce1 = 1'b0;

assign output_data_3_d0 = compute_decoder_U0_output_data_3_d0;

assign output_data_3_d1 = 16'd0;

assign output_data_3_we0 = compute_decoder_U0_output_data_3_we0;

assign output_data_3_we1 = 1'b0;

assign output_data_4_address0 = compute_decoder_U0_output_data_4_address0;

assign output_data_4_address1 = 3'd0;

assign output_data_4_ce0 = compute_decoder_U0_output_data_4_ce0;

assign output_data_4_ce1 = 1'b0;

assign output_data_4_d0 = compute_decoder_U0_output_data_4_d0;

assign output_data_4_d1 = 16'd0;

assign output_data_4_we0 = compute_decoder_U0_output_data_4_we0;

assign output_data_4_we1 = 1'b0;

assign output_data_5_address0 = compute_decoder_U0_output_data_5_address0;

assign output_data_5_address1 = 3'd0;

assign output_data_5_ce0 = compute_decoder_U0_output_data_5_ce0;

assign output_data_5_ce1 = 1'b0;

assign output_data_5_d0 = compute_decoder_U0_output_data_5_d0;

assign output_data_5_d1 = 16'd0;

assign output_data_5_we0 = compute_decoder_U0_output_data_5_we0;

assign output_data_5_we1 = 1'b0;

assign output_data_6_address0 = compute_decoder_U0_output_data_6_address0;

assign output_data_6_address1 = 3'd0;

assign output_data_6_ce0 = compute_decoder_U0_output_data_6_ce0;

assign output_data_6_ce1 = 1'b0;

assign output_data_6_d0 = compute_decoder_U0_output_data_6_d0;

assign output_data_6_d1 = 16'd0;

assign output_data_6_we0 = compute_decoder_U0_output_data_6_we0;

assign output_data_6_we1 = 1'b0;

assign output_data_7_address0 = compute_decoder_U0_output_data_7_address0;

assign output_data_7_address1 = 3'd0;

assign output_data_7_ce0 = compute_decoder_U0_output_data_7_ce0;

assign output_data_7_ce1 = 1'b0;

assign output_data_7_d0 = compute_decoder_U0_output_data_7_d0;

assign output_data_7_d1 = 16'd0;

assign output_data_7_we0 = compute_decoder_U0_output_data_7_we0;

assign output_data_7_we1 = 1'b0;

endmodule //tiny_autoencoder
