-- ==============================================================
-- Generated by Vitis HLS v2023.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    p_read : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read1 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read2 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read3 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read4 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read5 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read6 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read7 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read8 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read9 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read10 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read11 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read12 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read13 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read14 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read15 : IN STD_LOGIC_VECTOR (15 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (14 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (14 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (14 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (14 downto 0);
    ap_return_4 : OUT STD_LOGIC_VECTOR (14 downto 0);
    ap_return_5 : OUT STD_LOGIC_VECTOR (14 downto 0);
    ap_return_6 : OUT STD_LOGIC_VECTOR (14 downto 0);
    ap_return_7 : OUT STD_LOGIC_VECTOR (14 downto 0);
    ap_return_8 : OUT STD_LOGIC_VECTOR (14 downto 0);
    ap_return_9 : OUT STD_LOGIC_VECTOR (14 downto 0);
    ap_return_10 : OUT STD_LOGIC_VECTOR (14 downto 0);
    ap_return_11 : OUT STD_LOGIC_VECTOR (14 downto 0);
    ap_return_12 : OUT STD_LOGIC_VECTOR (14 downto 0);
    ap_return_13 : OUT STD_LOGIC_VECTOR (14 downto 0);
    ap_return_14 : OUT STD_LOGIC_VECTOR (14 downto 0);
    ap_return_15 : OUT STD_LOGIC_VECTOR (14 downto 0) );
end;


architecture behav of myproject_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv15_0 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal trunc_ln42_fu_144_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln42_reg_496 : STD_LOGIC_VECTOR (14 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln45_fu_148_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln45_reg_501 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln42_1_fu_154_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln42_1_reg_506 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_1_fu_158_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln45_1_reg_511 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln42_2_fu_164_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln42_2_reg_516 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_2_fu_168_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln45_2_reg_521 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln42_3_fu_174_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln42_3_reg_526 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_3_fu_178_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln45_3_reg_531 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln42_4_fu_184_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln42_4_reg_536 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_4_fu_188_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln45_4_reg_541 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln42_5_fu_194_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln42_5_reg_546 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_5_fu_198_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln45_5_reg_551 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln42_6_fu_204_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln42_6_reg_556 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_6_fu_208_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln45_6_reg_561 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln42_7_fu_214_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln42_7_reg_566 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_7_fu_218_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln45_7_reg_571 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln42_8_fu_224_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln42_8_reg_576 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_8_fu_228_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln45_8_reg_581 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln42_9_fu_234_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln42_9_reg_586 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_9_fu_238_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln45_9_reg_591 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln42_10_fu_244_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln42_10_reg_596 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_10_fu_248_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln45_10_reg_601 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln42_11_fu_254_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln42_11_reg_606 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_11_fu_258_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln45_11_reg_611 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln42_12_fu_264_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln42_12_reg_616 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_12_fu_268_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln45_12_reg_621 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln42_13_fu_274_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln42_13_reg_626 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_13_fu_278_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln45_13_reg_631 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln42_14_fu_284_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln42_14_reg_636 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_14_fu_288_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln45_14_reg_641 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln42_15_fu_294_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln42_15_reg_646 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_15_fu_298_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln45_15_reg_651 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal datareg_fu_304_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_1_fu_310_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_2_fu_316_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_3_fu_322_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_4_fu_328_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_5_fu_334_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_6_fu_340_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_7_fu_346_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_8_fu_352_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_9_fu_358_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_10_fu_364_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_11_fu_370_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_12_fu_376_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_13_fu_382_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_14_fu_388_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_15_fu_394_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal ap_return_0_preg : STD_LOGIC_VECTOR (14 downto 0) := "000000000000000";
    signal ap_return_1_preg : STD_LOGIC_VECTOR (14 downto 0) := "000000000000000";
    signal ap_return_2_preg : STD_LOGIC_VECTOR (14 downto 0) := "000000000000000";
    signal ap_return_3_preg : STD_LOGIC_VECTOR (14 downto 0) := "000000000000000";
    signal ap_return_4_preg : STD_LOGIC_VECTOR (14 downto 0) := "000000000000000";
    signal ap_return_5_preg : STD_LOGIC_VECTOR (14 downto 0) := "000000000000000";
    signal ap_return_6_preg : STD_LOGIC_VECTOR (14 downto 0) := "000000000000000";
    signal ap_return_7_preg : STD_LOGIC_VECTOR (14 downto 0) := "000000000000000";
    signal ap_return_8_preg : STD_LOGIC_VECTOR (14 downto 0) := "000000000000000";
    signal ap_return_9_preg : STD_LOGIC_VECTOR (14 downto 0) := "000000000000000";
    signal ap_return_10_preg : STD_LOGIC_VECTOR (14 downto 0) := "000000000000000";
    signal ap_return_11_preg : STD_LOGIC_VECTOR (14 downto 0) := "000000000000000";
    signal ap_return_12_preg : STD_LOGIC_VECTOR (14 downto 0) := "000000000000000";
    signal ap_return_13_preg : STD_LOGIC_VECTOR (14 downto 0) := "000000000000000";
    signal ap_return_14_preg : STD_LOGIC_VECTOR (14 downto 0) := "000000000000000";
    signal ap_return_15_preg : STD_LOGIC_VECTOR (14 downto 0) := "000000000000000";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_idle_pp0_0to0 : STD_LOGIC;
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start;
                end if; 
            end if;
        end if;
    end process;


    ap_return_0_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_0_preg <= ap_const_lv15_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_return_0_preg <= datareg_fu_304_p3;
                end if; 
            end if;
        end if;
    end process;


    ap_return_10_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_10_preg <= ap_const_lv15_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_return_10_preg <= datareg_10_fu_364_p3;
                end if; 
            end if;
        end if;
    end process;


    ap_return_11_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_11_preg <= ap_const_lv15_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_return_11_preg <= datareg_11_fu_370_p3;
                end if; 
            end if;
        end if;
    end process;


    ap_return_12_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_12_preg <= ap_const_lv15_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_return_12_preg <= datareg_12_fu_376_p3;
                end if; 
            end if;
        end if;
    end process;


    ap_return_13_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_13_preg <= ap_const_lv15_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_return_13_preg <= datareg_13_fu_382_p3;
                end if; 
            end if;
        end if;
    end process;


    ap_return_14_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_14_preg <= ap_const_lv15_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_return_14_preg <= datareg_14_fu_388_p3;
                end if; 
            end if;
        end if;
    end process;


    ap_return_15_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_15_preg <= ap_const_lv15_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_return_15_preg <= datareg_15_fu_394_p3;
                end if; 
            end if;
        end if;
    end process;


    ap_return_1_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_1_preg <= ap_const_lv15_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_return_1_preg <= datareg_1_fu_310_p3;
                end if; 
            end if;
        end if;
    end process;


    ap_return_2_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_2_preg <= ap_const_lv15_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_return_2_preg <= datareg_2_fu_316_p3;
                end if; 
            end if;
        end if;
    end process;


    ap_return_3_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_3_preg <= ap_const_lv15_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_return_3_preg <= datareg_3_fu_322_p3;
                end if; 
            end if;
        end if;
    end process;


    ap_return_4_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_4_preg <= ap_const_lv15_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_return_4_preg <= datareg_4_fu_328_p3;
                end if; 
            end if;
        end if;
    end process;


    ap_return_5_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_5_preg <= ap_const_lv15_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_return_5_preg <= datareg_5_fu_334_p3;
                end if; 
            end if;
        end if;
    end process;


    ap_return_6_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_6_preg <= ap_const_lv15_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_return_6_preg <= datareg_6_fu_340_p3;
                end if; 
            end if;
        end if;
    end process;


    ap_return_7_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_7_preg <= ap_const_lv15_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_return_7_preg <= datareg_7_fu_346_p3;
                end if; 
            end if;
        end if;
    end process;


    ap_return_8_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_8_preg <= ap_const_lv15_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_return_8_preg <= datareg_8_fu_352_p3;
                end if; 
            end if;
        end if;
    end process;


    ap_return_9_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_9_preg <= ap_const_lv15_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_return_9_preg <= datareg_9_fu_358_p3;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln45_10_reg_601 <= icmp_ln45_10_fu_248_p2;
                icmp_ln45_11_reg_611 <= icmp_ln45_11_fu_258_p2;
                icmp_ln45_12_reg_621 <= icmp_ln45_12_fu_268_p2;
                icmp_ln45_13_reg_631 <= icmp_ln45_13_fu_278_p2;
                icmp_ln45_14_reg_641 <= icmp_ln45_14_fu_288_p2;
                icmp_ln45_15_reg_651 <= icmp_ln45_15_fu_298_p2;
                icmp_ln45_1_reg_511 <= icmp_ln45_1_fu_158_p2;
                icmp_ln45_2_reg_521 <= icmp_ln45_2_fu_168_p2;
                icmp_ln45_3_reg_531 <= icmp_ln45_3_fu_178_p2;
                icmp_ln45_4_reg_541 <= icmp_ln45_4_fu_188_p2;
                icmp_ln45_5_reg_551 <= icmp_ln45_5_fu_198_p2;
                icmp_ln45_6_reg_561 <= icmp_ln45_6_fu_208_p2;
                icmp_ln45_7_reg_571 <= icmp_ln45_7_fu_218_p2;
                icmp_ln45_8_reg_581 <= icmp_ln45_8_fu_228_p2;
                icmp_ln45_9_reg_591 <= icmp_ln45_9_fu_238_p2;
                icmp_ln45_reg_501 <= icmp_ln45_fu_148_p2;
                trunc_ln42_10_reg_596 <= trunc_ln42_10_fu_244_p1;
                trunc_ln42_11_reg_606 <= trunc_ln42_11_fu_254_p1;
                trunc_ln42_12_reg_616 <= trunc_ln42_12_fu_264_p1;
                trunc_ln42_13_reg_626 <= trunc_ln42_13_fu_274_p1;
                trunc_ln42_14_reg_636 <= trunc_ln42_14_fu_284_p1;
                trunc_ln42_15_reg_646 <= trunc_ln42_15_fu_294_p1;
                trunc_ln42_1_reg_506 <= trunc_ln42_1_fu_154_p1;
                trunc_ln42_2_reg_516 <= trunc_ln42_2_fu_164_p1;
                trunc_ln42_3_reg_526 <= trunc_ln42_3_fu_174_p1;
                trunc_ln42_4_reg_536 <= trunc_ln42_4_fu_184_p1;
                trunc_ln42_5_reg_546 <= trunc_ln42_5_fu_194_p1;
                trunc_ln42_6_reg_556 <= trunc_ln42_6_fu_204_p1;
                trunc_ln42_7_reg_566 <= trunc_ln42_7_fu_214_p1;
                trunc_ln42_8_reg_576 <= trunc_ln42_8_fu_224_p1;
                trunc_ln42_9_reg_586 <= trunc_ln42_9_fu_234_p1;
                trunc_ln42_reg_496 <= trunc_ln42_fu_144_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_reset_idle_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_done_reg = ap_const_logic_1) or ((ap_done_reg = ap_const_logic_1) and (ap_start = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_done_reg = ap_const_logic_1) or ((ap_done_reg = ap_const_logic_1) and (ap_start = ap_const_logic_1)));
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_done_reg)
    begin
                ap_block_state1_pp0_stage0_iter0 <= (ap_done_reg = ap_const_logic_1);
    end process;

        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_done_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_done_reg, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start;

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_idle_pp0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to0_assign_proc : process(ap_enable_reg_pp0_iter0)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_0)) then 
            ap_idle_pp0_0to0 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_reset_idle_pp0_assign_proc : process(ap_start, ap_idle_pp0_0to0)
    begin
        if (((ap_idle_pp0_0to0 = ap_const_logic_1) and (ap_start = ap_const_logic_0))) then 
            ap_reset_idle_pp0 <= ap_const_logic_1;
        else 
            ap_reset_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_return_0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, datareg_fu_304_p3, ap_return_0_preg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_return_0 <= datareg_fu_304_p3;
        else 
            ap_return_0 <= ap_return_0_preg;
        end if; 
    end process;


    ap_return_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, datareg_1_fu_310_p3, ap_return_1_preg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_return_1 <= datareg_1_fu_310_p3;
        else 
            ap_return_1 <= ap_return_1_preg;
        end if; 
    end process;


    ap_return_10_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, datareg_10_fu_364_p3, ap_return_10_preg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_return_10 <= datareg_10_fu_364_p3;
        else 
            ap_return_10 <= ap_return_10_preg;
        end if; 
    end process;


    ap_return_11_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, datareg_11_fu_370_p3, ap_return_11_preg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_return_11 <= datareg_11_fu_370_p3;
        else 
            ap_return_11 <= ap_return_11_preg;
        end if; 
    end process;


    ap_return_12_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, datareg_12_fu_376_p3, ap_return_12_preg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_return_12 <= datareg_12_fu_376_p3;
        else 
            ap_return_12 <= ap_return_12_preg;
        end if; 
    end process;


    ap_return_13_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, datareg_13_fu_382_p3, ap_return_13_preg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_return_13 <= datareg_13_fu_382_p3;
        else 
            ap_return_13 <= ap_return_13_preg;
        end if; 
    end process;


    ap_return_14_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, datareg_14_fu_388_p3, ap_return_14_preg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_return_14 <= datareg_14_fu_388_p3;
        else 
            ap_return_14 <= ap_return_14_preg;
        end if; 
    end process;


    ap_return_15_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, datareg_15_fu_394_p3, ap_return_15_preg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_return_15 <= datareg_15_fu_394_p3;
        else 
            ap_return_15 <= ap_return_15_preg;
        end if; 
    end process;


    ap_return_2_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, datareg_2_fu_316_p3, ap_return_2_preg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_return_2 <= datareg_2_fu_316_p3;
        else 
            ap_return_2 <= ap_return_2_preg;
        end if; 
    end process;


    ap_return_3_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, datareg_3_fu_322_p3, ap_return_3_preg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_return_3 <= datareg_3_fu_322_p3;
        else 
            ap_return_3 <= ap_return_3_preg;
        end if; 
    end process;


    ap_return_4_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, datareg_4_fu_328_p3, ap_return_4_preg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_return_4 <= datareg_4_fu_328_p3;
        else 
            ap_return_4 <= ap_return_4_preg;
        end if; 
    end process;


    ap_return_5_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, datareg_5_fu_334_p3, ap_return_5_preg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_return_5 <= datareg_5_fu_334_p3;
        else 
            ap_return_5 <= ap_return_5_preg;
        end if; 
    end process;


    ap_return_6_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, datareg_6_fu_340_p3, ap_return_6_preg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_return_6 <= datareg_6_fu_340_p3;
        else 
            ap_return_6 <= ap_return_6_preg;
        end if; 
    end process;


    ap_return_7_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, datareg_7_fu_346_p3, ap_return_7_preg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_return_7 <= datareg_7_fu_346_p3;
        else 
            ap_return_7 <= ap_return_7_preg;
        end if; 
    end process;


    ap_return_8_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, datareg_8_fu_352_p3, ap_return_8_preg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_return_8 <= datareg_8_fu_352_p3;
        else 
            ap_return_8 <= ap_return_8_preg;
        end if; 
    end process;


    ap_return_9_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, datareg_9_fu_358_p3, ap_return_9_preg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_return_9 <= datareg_9_fu_358_p3;
        else 
            ap_return_9 <= ap_return_9_preg;
        end if; 
    end process;

    datareg_10_fu_364_p3 <= 
        trunc_ln42_10_reg_596 when (icmp_ln45_10_reg_601(0) = '1') else 
        ap_const_lv15_0;
    datareg_11_fu_370_p3 <= 
        trunc_ln42_11_reg_606 when (icmp_ln45_11_reg_611(0) = '1') else 
        ap_const_lv15_0;
    datareg_12_fu_376_p3 <= 
        trunc_ln42_12_reg_616 when (icmp_ln45_12_reg_621(0) = '1') else 
        ap_const_lv15_0;
    datareg_13_fu_382_p3 <= 
        trunc_ln42_13_reg_626 when (icmp_ln45_13_reg_631(0) = '1') else 
        ap_const_lv15_0;
    datareg_14_fu_388_p3 <= 
        trunc_ln42_14_reg_636 when (icmp_ln45_14_reg_641(0) = '1') else 
        ap_const_lv15_0;
    datareg_15_fu_394_p3 <= 
        trunc_ln42_15_reg_646 when (icmp_ln45_15_reg_651(0) = '1') else 
        ap_const_lv15_0;
    datareg_1_fu_310_p3 <= 
        trunc_ln42_1_reg_506 when (icmp_ln45_1_reg_511(0) = '1') else 
        ap_const_lv15_0;
    datareg_2_fu_316_p3 <= 
        trunc_ln42_2_reg_516 when (icmp_ln45_2_reg_521(0) = '1') else 
        ap_const_lv15_0;
    datareg_3_fu_322_p3 <= 
        trunc_ln42_3_reg_526 when (icmp_ln45_3_reg_531(0) = '1') else 
        ap_const_lv15_0;
    datareg_4_fu_328_p3 <= 
        trunc_ln42_4_reg_536 when (icmp_ln45_4_reg_541(0) = '1') else 
        ap_const_lv15_0;
    datareg_5_fu_334_p3 <= 
        trunc_ln42_5_reg_546 when (icmp_ln45_5_reg_551(0) = '1') else 
        ap_const_lv15_0;
    datareg_6_fu_340_p3 <= 
        trunc_ln42_6_reg_556 when (icmp_ln45_6_reg_561(0) = '1') else 
        ap_const_lv15_0;
    datareg_7_fu_346_p3 <= 
        trunc_ln42_7_reg_566 when (icmp_ln45_7_reg_571(0) = '1') else 
        ap_const_lv15_0;
    datareg_8_fu_352_p3 <= 
        trunc_ln42_8_reg_576 when (icmp_ln45_8_reg_581(0) = '1') else 
        ap_const_lv15_0;
    datareg_9_fu_358_p3 <= 
        trunc_ln42_9_reg_586 when (icmp_ln45_9_reg_591(0) = '1') else 
        ap_const_lv15_0;
    datareg_fu_304_p3 <= 
        trunc_ln42_reg_496 when (icmp_ln45_reg_501(0) = '1') else 
        ap_const_lv15_0;
    icmp_ln45_10_fu_248_p2 <= "1" when (signed(p_read10) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_11_fu_258_p2 <= "1" when (signed(p_read11) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_12_fu_268_p2 <= "1" when (signed(p_read12) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_13_fu_278_p2 <= "1" when (signed(p_read13) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_14_fu_288_p2 <= "1" when (signed(p_read14) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_15_fu_298_p2 <= "1" when (signed(p_read15) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_1_fu_158_p2 <= "1" when (signed(p_read1) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_2_fu_168_p2 <= "1" when (signed(p_read2) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_3_fu_178_p2 <= "1" when (signed(p_read3) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_4_fu_188_p2 <= "1" when (signed(p_read4) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_5_fu_198_p2 <= "1" when (signed(p_read5) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_6_fu_208_p2 <= "1" when (signed(p_read6) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_7_fu_218_p2 <= "1" when (signed(p_read7) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_8_fu_228_p2 <= "1" when (signed(p_read8) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_9_fu_238_p2 <= "1" when (signed(p_read9) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_fu_148_p2 <= "1" when (signed(p_read) > signed(ap_const_lv16_0)) else "0";
    trunc_ln42_10_fu_244_p1 <= p_read10(15 - 1 downto 0);
    trunc_ln42_11_fu_254_p1 <= p_read11(15 - 1 downto 0);
    trunc_ln42_12_fu_264_p1 <= p_read12(15 - 1 downto 0);
    trunc_ln42_13_fu_274_p1 <= p_read13(15 - 1 downto 0);
    trunc_ln42_14_fu_284_p1 <= p_read14(15 - 1 downto 0);
    trunc_ln42_15_fu_294_p1 <= p_read15(15 - 1 downto 0);
    trunc_ln42_1_fu_154_p1 <= p_read1(15 - 1 downto 0);
    trunc_ln42_2_fu_164_p1 <= p_read2(15 - 1 downto 0);
    trunc_ln42_3_fu_174_p1 <= p_read3(15 - 1 downto 0);
    trunc_ln42_4_fu_184_p1 <= p_read4(15 - 1 downto 0);
    trunc_ln42_5_fu_194_p1 <= p_read5(15 - 1 downto 0);
    trunc_ln42_6_fu_204_p1 <= p_read6(15 - 1 downto 0);
    trunc_ln42_7_fu_214_p1 <= p_read7(15 - 1 downto 0);
    trunc_ln42_8_fu_224_p1 <= p_read8(15 - 1 downto 0);
    trunc_ln42_9_fu_234_p1 <= p_read9(15 - 1 downto 0);
    trunc_ln42_fu_144_p1 <= p_read(15 - 1 downto 0);
end behav;
