// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_dense_resource_ap_fixed_32_6_5_3_0_ap_fixed_32_6_5_3_0_config2_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        input_1_ap_vld,
        input_1,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_return_8,
        ap_return_9,
        ap_return_10,
        ap_return_11,
        ap_return_12,
        ap_return_13,
        ap_return_14,
        ap_return_15
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input   input_1_ap_vld;
input  [2047:0] input_1;
output  [31:0] ap_return_0;
output  [31:0] ap_return_1;
output  [31:0] ap_return_2;
output  [31:0] ap_return_3;
output  [31:0] ap_return_4;
output  [31:0] ap_return_5;
output  [31:0] ap_return_6;
output  [31:0] ap_return_7;
output  [31:0] ap_return_8;
output  [31:0] ap_return_9;
output  [31:0] ap_return_10;
output  [31:0] ap_return_11;
output  [31:0] ap_return_12;
output  [31:0] ap_return_13;
output  [31:0] ap_return_14;
output  [31:0] ap_return_15;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_idle_pp0;
reg   [0:0] ap_phi_mux_do_init_phi_fu_159_p6;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
wire    ap_block_state9_pp0_stage0_iter8;
wire    ap_block_state10_pp0_stage0_iter9;
wire    ap_block_state11_pp0_stage0_iter10;
wire    ap_block_state12_pp0_stage0_iter11;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln129_fu_554_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [6:0] outidx_1_address0;
reg    outidx_1_ce0;
wire   [0:0] outidx_1_q0;
wire   [6:0] w2_86_address0;
reg    w2_86_ce0;
wire   [251:0] w2_86_q0;
wire    input_1_blk_n;
wire    ap_block_pp0_stage0;
reg   [0:0] do_init_reg_156;
wire    ap_block_pp0_stage0_11001;
reg   [31:0] in_index42_reg_184;
reg   [6:0] w_index41_reg_197;
reg   [6:0] w_index41_reg_197_pp0_iter1_reg;
reg   [6:0] w_index41_reg_197_pp0_iter2_reg;
reg   [6:0] w_index41_reg_197_pp0_iter3_reg;
reg   [2047:0] input_1_load_phi_reg_211;
reg   [31:0] acc40_reg_224;
reg   [31:0] acc_14438_reg_239;
reg   [31:0] acc_14536_reg_254;
reg   [31:0] acc_14634_reg_269;
reg   [31:0] acc_14732_reg_284;
reg   [31:0] acc_14830_reg_299;
reg   [31:0] acc_14928_reg_314;
reg   [31:0] acc_15026_reg_329;
reg   [31:0] acc_15124_reg_344;
reg   [31:0] acc_15222_reg_359;
reg   [31:0] acc_15320_reg_374;
reg   [31:0] acc_15418_reg_389;
reg   [31:0] acc_15516_reg_404;
reg   [31:0] acc_15614_reg_419;
reg   [31:0] acc_15712_reg_434;
reg   [31:0] acc_15810_reg_449;
wire   [31:0] in_index_fu_540_p3;
reg   [31:0] in_index_reg_1456;
wire   [6:0] w_index_fu_548_p2;
reg   [6:0] w_index_reg_1461;
reg   [0:0] icmp_ln129_reg_1466;
reg   [0:0] icmp_ln129_reg_1466_pp0_iter1_reg;
reg   [0:0] icmp_ln129_reg_1466_pp0_iter2_reg;
reg   [0:0] icmp_ln129_reg_1466_pp0_iter3_reg;
reg   [0:0] icmp_ln129_reg_1466_pp0_iter4_reg;
reg   [0:0] icmp_ln129_reg_1466_pp0_iter5_reg;
reg   [0:0] icmp_ln129_reg_1466_pp0_iter6_reg;
reg   [0:0] icmp_ln129_reg_1466_pp0_iter7_reg;
reg   [0:0] icmp_ln129_reg_1466_pp0_iter8_reg;
reg   [0:0] icmp_ln129_reg_1466_pp0_iter9_reg;
reg   [0:0] icmp_ln129_reg_1466_pp0_iter10_reg;
reg   [0:0] out_index_reg_1480;
reg   [0:0] out_index_reg_1480_pp0_iter6_reg;
reg   [0:0] out_index_reg_1480_pp0_iter7_reg;
reg   [0:0] out_index_reg_1480_pp0_iter8_reg;
reg   [0:0] out_index_reg_1480_pp0_iter9_reg;
reg   [0:0] out_index_reg_1480_pp0_iter10_reg;
wire   [31:0] a_fu_566_p1;
reg   [31:0] a_reg_1524;
wire   [31:0] w_fu_570_p1;
reg  signed [31:0] w_reg_1529;
reg  signed [31:0] w_7_reg_1534;
reg  signed [31:0] w_8_reg_1539;
reg  signed [31:0] w_9_reg_1544;
reg  signed [31:0] w_10_reg_1549;
reg  signed [31:0] w_11_reg_1554;
reg  signed [31:0] w_12_reg_1559;
reg  signed [27:0] tmp_reg_1564;
wire  signed [57:0] sext_ln73_fu_644_p1;
reg  signed [31:0] trunc_ln_reg_1621;
wire  signed [31:0] select_ln138_fu_697_p3;
reg  signed [31:0] select_ln138_reg_1627;
wire   [32:0] sub_ln138_fu_708_p2;
reg   [32:0] sub_ln138_reg_1632;
reg  signed [31:0] trunc_ln138_8_reg_1637;
wire  signed [31:0] select_ln138_3_fu_724_p3;
reg  signed [31:0] select_ln138_3_reg_1643;
wire   [32:0] sub_ln138_8_fu_735_p2;
reg   [32:0] sub_ln138_8_reg_1648;
reg  signed [31:0] trunc_ln138_9_reg_1653;
wire  signed [31:0] select_ln138_8_fu_751_p3;
reg  signed [31:0] select_ln138_8_reg_1659;
wire   [32:0] sub_ln138_9_fu_762_p2;
reg   [32:0] sub_ln138_9_reg_1664;
reg  signed [31:0] trunc_ln138_s_reg_1669;
wire  signed [31:0] select_ln138_13_fu_778_p3;
reg  signed [31:0] select_ln138_13_reg_1675;
wire   [32:0] sub_ln138_10_fu_789_p2;
reg   [32:0] sub_ln138_10_reg_1680;
reg  signed [31:0] trunc_ln138_1_reg_1685;
wire  signed [31:0] select_ln138_18_fu_805_p3;
reg  signed [31:0] select_ln138_18_reg_1691;
wire   [32:0] sub_ln138_11_fu_816_p2;
reg   [32:0] sub_ln138_11_reg_1696;
reg  signed [31:0] trunc_ln138_2_reg_1701;
wire  signed [31:0] select_ln138_23_fu_832_p3;
reg  signed [31:0] select_ln138_23_reg_1707;
wire   [32:0] sub_ln138_12_fu_843_p2;
reg   [32:0] sub_ln138_12_reg_1712;
reg  signed [31:0] trunc_ln138_3_reg_1717;
wire  signed [31:0] select_ln138_28_fu_859_p3;
reg  signed [31:0] select_ln138_28_reg_1723;
wire   [32:0] sub_ln138_13_fu_870_p2;
reg   [32:0] sub_ln138_13_reg_1728;
reg  signed [31:0] trunc_ln138_4_reg_1733;
wire  signed [31:0] select_ln138_33_fu_886_p3;
reg  signed [31:0] select_ln138_33_reg_1739;
wire   [32:0] sub_ln138_14_fu_897_p2;
reg   [32:0] sub_ln138_14_reg_1744;
wire   [31:0] acc_182_fu_945_p3;
wire   [31:0] acc_181_fu_952_p3;
wire   [31:0] acc_184_fu_1001_p3;
wire   [31:0] acc_183_fu_1008_p3;
wire   [31:0] acc_186_fu_1057_p3;
wire   [31:0] acc_185_fu_1064_p3;
wire   [31:0] acc_188_fu_1113_p3;
wire   [31:0] acc_187_fu_1120_p3;
wire   [31:0] acc_190_fu_1169_p3;
wire   [31:0] acc_189_fu_1176_p3;
wire   [31:0] acc_192_fu_1225_p3;
wire   [31:0] acc_191_fu_1232_p3;
wire   [31:0] acc_194_fu_1281_p3;
wire   [31:0] acc_193_fu_1288_p3;
wire   [31:0] acc_196_fu_1337_p3;
wire   [31:0] acc_195_fu_1344_p3;
wire    ap_loop_init;
reg   [31:0] ap_phi_mux_in_index42_phi_fu_187_p6;
reg   [6:0] ap_phi_mux_w_index41_phi_fu_200_p6;
reg   [2047:0] ap_phi_mux_input_1_load_phi_phi_fu_215_p4;
wire   [2047:0] ap_phi_reg_pp0_iter0_input_1_load_phi_reg_211;
reg   [31:0] ap_phi_mux_acc40_phi_fu_228_p6;
reg    ap_loop_init_pp0_iter1_reg;
reg    ap_loop_init_pp0_iter2_reg;
reg    ap_loop_init_pp0_iter3_reg;
reg    ap_loop_init_pp0_iter4_reg;
reg    ap_loop_init_pp0_iter5_reg;
reg    ap_loop_init_pp0_iter6_reg;
reg    ap_loop_init_pp0_iter7_reg;
reg    ap_loop_init_pp0_iter8_reg;
reg    ap_loop_init_pp0_iter9_reg;
reg    ap_loop_init_pp0_iter10_reg;
reg   [31:0] ap_phi_mux_acc_14438_phi_fu_243_p6;
reg   [31:0] ap_phi_mux_acc_14536_phi_fu_258_p6;
reg   [31:0] ap_phi_mux_acc_14634_phi_fu_273_p6;
reg   [31:0] ap_phi_mux_acc_14732_phi_fu_288_p6;
reg   [31:0] ap_phi_mux_acc_14830_phi_fu_303_p6;
reg   [31:0] ap_phi_mux_acc_14928_phi_fu_318_p6;
reg   [31:0] ap_phi_mux_acc_15026_phi_fu_333_p6;
reg   [31:0] ap_phi_mux_acc_15124_phi_fu_348_p6;
reg   [31:0] ap_phi_mux_acc_15222_phi_fu_363_p6;
reg   [31:0] ap_phi_mux_acc_15320_phi_fu_378_p6;
reg   [31:0] ap_phi_mux_acc_15418_phi_fu_393_p6;
reg   [31:0] ap_phi_mux_acc_15516_phi_fu_408_p6;
reg   [31:0] ap_phi_mux_acc_15614_phi_fu_423_p6;
reg   [31:0] ap_phi_mux_acc_15712_phi_fu_438_p6;
reg   [31:0] ap_phi_mux_acc_15810_phi_fu_453_p6;
wire   [63:0] zext_ln129_fu_560_p1;
wire  signed [31:0] grp_fu_464_p0;
wire  signed [31:0] grp_fu_468_p1;
wire  signed [31:0] grp_fu_472_p1;
wire  signed [31:0] grp_fu_476_p1;
wire  signed [31:0] grp_fu_480_p1;
wire  signed [31:0] grp_fu_484_p1;
wire  signed [31:0] grp_fu_488_p1;
wire  signed [31:0] grp_fu_492_p1;
wire   [5:0] empty_fu_496_p1;
wire   [10:0] tmp_256_fu_500_p3;
wire   [2047:0] grp_fu_512_p1;
wire   [31:0] in_index_2_fu_518_p2;
wire   [25:0] tmp_257_fu_524_p4;
wire   [0:0] icmp_ln148_fu_534_p2;
wire   [2047:0] grp_fu_512_p2;
wire   [57:0] grp_fu_468_p2;
wire  signed [32:0] sext_ln138_fu_704_p1;
wire   [57:0] grp_fu_472_p2;
wire  signed [32:0] sext_ln138_17_fu_731_p1;
wire   [57:0] grp_fu_476_p2;
wire  signed [32:0] sext_ln138_19_fu_758_p1;
wire   [57:0] grp_fu_480_p2;
wire  signed [32:0] sext_ln138_21_fu_785_p1;
wire   [57:0] grp_fu_484_p2;
wire  signed [32:0] sext_ln138_23_fu_812_p1;
wire   [57:0] grp_fu_488_p2;
wire  signed [32:0] sext_ln138_25_fu_839_p1;
wire   [57:0] grp_fu_492_p2;
wire  signed [32:0] sext_ln138_27_fu_866_p1;
wire   [57:0] grp_fu_464_p2;
wire  signed [32:0] sext_ln138_29_fu_893_p1;
wire  signed [32:0] sext_ln138_16_fu_903_p1;
wire   [0:0] icmp_ln138_fu_906_p2;
wire   [31:0] select_ln138_1_fu_911_p3;
wire   [31:0] select_ln138_2_fu_918_p3;
wire   [31:0] acc_160_fu_941_p2;
wire   [31:0] acc_159_fu_925_p3;
wire   [31:0] acc_158_fu_933_p3;
wire  signed [32:0] sext_ln138_18_fu_959_p1;
wire   [0:0] icmp_ln138_8_fu_962_p2;
wire   [31:0] select_ln138_6_fu_967_p3;
wire   [31:0] select_ln138_7_fu_974_p3;
wire   [31:0] acc_162_fu_997_p2;
wire   [31:0] acc_161_fu_981_p3;
wire   [31:0] acc_fu_989_p3;
wire  signed [32:0] sext_ln138_20_fu_1015_p1;
wire   [0:0] icmp_ln138_9_fu_1018_p2;
wire   [31:0] select_ln138_11_fu_1023_p3;
wire   [31:0] select_ln138_12_fu_1030_p3;
wire   [31:0] acc_165_fu_1053_p2;
wire   [31:0] acc_164_fu_1037_p3;
wire   [31:0] acc_163_fu_1045_p3;
wire  signed [32:0] sext_ln138_22_fu_1071_p1;
wire   [0:0] icmp_ln138_10_fu_1074_p2;
wire   [31:0] select_ln138_16_fu_1079_p3;
wire   [31:0] select_ln138_17_fu_1086_p3;
wire   [31:0] acc_168_fu_1109_p2;
wire   [31:0] acc_167_fu_1093_p3;
wire   [31:0] acc_166_fu_1101_p3;
wire  signed [32:0] sext_ln138_24_fu_1127_p1;
wire   [0:0] icmp_ln138_11_fu_1130_p2;
wire   [31:0] select_ln138_21_fu_1135_p3;
wire   [31:0] select_ln138_22_fu_1142_p3;
wire   [31:0] acc_171_fu_1165_p2;
wire   [31:0] acc_170_fu_1149_p3;
wire   [31:0] acc_169_fu_1157_p3;
wire  signed [32:0] sext_ln138_26_fu_1183_p1;
wire   [0:0] icmp_ln138_12_fu_1186_p2;
wire   [31:0] select_ln138_26_fu_1191_p3;
wire   [31:0] select_ln138_27_fu_1198_p3;
wire   [31:0] acc_174_fu_1221_p2;
wire   [31:0] acc_173_fu_1205_p3;
wire   [31:0] acc_172_fu_1213_p3;
wire  signed [32:0] sext_ln138_28_fu_1239_p1;
wire   [0:0] icmp_ln138_13_fu_1242_p2;
wire   [31:0] select_ln138_31_fu_1247_p3;
wire   [31:0] select_ln138_32_fu_1254_p3;
wire   [31:0] acc_177_fu_1277_p2;
wire   [31:0] acc_176_fu_1261_p3;
wire   [31:0] acc_175_fu_1269_p3;
wire  signed [32:0] sext_ln138_30_fu_1295_p1;
wire   [0:0] icmp_ln138_14_fu_1298_p2;
wire   [31:0] select_ln138_36_fu_1303_p3;
wire   [31:0] select_ln138_37_fu_1310_p3;
wire   [31:0] acc_180_fu_1333_p2;
wire   [31:0] acc_179_fu_1317_p3;
wire   [31:0] acc_178_fu_1325_p3;
reg   [31:0] ap_return_0_preg;
reg   [31:0] ap_return_1_preg;
reg   [31:0] ap_return_2_preg;
reg   [31:0] ap_return_3_preg;
reg   [31:0] ap_return_4_preg;
reg   [31:0] ap_return_5_preg;
reg   [31:0] ap_return_6_preg;
reg   [31:0] ap_return_7_preg;
reg   [31:0] ap_return_8_preg;
reg   [31:0] ap_return_9_preg;
reg   [31:0] ap_return_10_preg;
reg   [31:0] ap_return_11_preg;
reg   [31:0] ap_return_12_preg;
reg   [31:0] ap_return_13_preg;
reg   [31:0] ap_return_14_preg;
reg   [31:0] ap_return_15_preg;
wire    ap_continue_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg    ap_done_int_frp;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to10;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;
wire    ap_start_int;
wire   [11:0] frp_pipeline_valid_U_valid_out;
wire   [4:0] frp_pipeline_valid_U_num_valid_datasets;
wire    pf_data_in_last;
wire   [31:0] pf_ap_return_0_U_data_out;
wire    pf_ap_return_0_U_data_out_vld;
wire    pf_ap_return_0_U_pf_ready;
wire    pf_ap_return_0_U_pf_done;
wire   [31:0] pf_ap_return_1_U_data_out;
wire    pf_ap_return_1_U_data_out_vld;
wire    pf_ap_return_1_U_pf_ready;
wire    pf_ap_return_1_U_pf_done;
wire   [31:0] pf_ap_return_2_U_data_out;
wire    pf_ap_return_2_U_data_out_vld;
wire    pf_ap_return_2_U_pf_ready;
wire    pf_ap_return_2_U_pf_done;
wire   [31:0] pf_ap_return_3_U_data_out;
wire    pf_ap_return_3_U_data_out_vld;
wire    pf_ap_return_3_U_pf_ready;
wire    pf_ap_return_3_U_pf_done;
wire   [31:0] pf_ap_return_4_U_data_out;
wire    pf_ap_return_4_U_data_out_vld;
wire    pf_ap_return_4_U_pf_ready;
wire    pf_ap_return_4_U_pf_done;
wire   [31:0] pf_ap_return_5_U_data_out;
wire    pf_ap_return_5_U_data_out_vld;
wire    pf_ap_return_5_U_pf_ready;
wire    pf_ap_return_5_U_pf_done;
wire   [31:0] pf_ap_return_6_U_data_out;
wire    pf_ap_return_6_U_data_out_vld;
wire    pf_ap_return_6_U_pf_ready;
wire    pf_ap_return_6_U_pf_done;
wire   [31:0] pf_ap_return_7_U_data_out;
wire    pf_ap_return_7_U_data_out_vld;
wire    pf_ap_return_7_U_pf_ready;
wire    pf_ap_return_7_U_pf_done;
wire   [31:0] pf_ap_return_8_U_data_out;
wire    pf_ap_return_8_U_data_out_vld;
wire    pf_ap_return_8_U_pf_ready;
wire    pf_ap_return_8_U_pf_done;
wire   [31:0] pf_ap_return_9_U_data_out;
wire    pf_ap_return_9_U_data_out_vld;
wire    pf_ap_return_9_U_pf_ready;
wire    pf_ap_return_9_U_pf_done;
wire   [31:0] pf_ap_return_10_U_data_out;
wire    pf_ap_return_10_U_data_out_vld;
wire    pf_ap_return_10_U_pf_ready;
wire    pf_ap_return_10_U_pf_done;
wire   [31:0] pf_ap_return_11_U_data_out;
wire    pf_ap_return_11_U_data_out_vld;
wire    pf_ap_return_11_U_pf_ready;
wire    pf_ap_return_11_U_pf_done;
wire   [31:0] pf_ap_return_12_U_data_out;
wire    pf_ap_return_12_U_data_out_vld;
wire    pf_ap_return_12_U_pf_ready;
wire    pf_ap_return_12_U_pf_done;
wire   [31:0] pf_ap_return_13_U_data_out;
wire    pf_ap_return_13_U_data_out_vld;
wire    pf_ap_return_13_U_pf_ready;
wire    pf_ap_return_13_U_pf_done;
wire   [31:0] pf_ap_return_14_U_data_out;
wire    pf_ap_return_14_U_data_out_vld;
wire    pf_ap_return_14_U_pf_ready;
wire    pf_ap_return_14_U_pf_done;
wire   [31:0] pf_ap_return_15_U_data_out;
wire    pf_ap_return_15_U_data_out_vld;
wire    pf_ap_return_15_U_pf_ready;
wire    pf_ap_return_15_U_pf_done;
reg    ap_condition_frp_pvb_no_fwd_prs;
reg    ap_condition_frp_pvb_no_bkwd_prs;
reg    ap_condition_frp_pvb_pf_start;
reg    ap_frp_vld_in;
reg   [31:0] pf_ap_return_0_U_frpsig_data_in;
wire    pf_sync_continue;
wire    pf_all_done;
reg   [31:0] pf_ap_return_1_U_frpsig_data_in;
reg   [31:0] pf_ap_return_2_U_frpsig_data_in;
reg   [31:0] pf_ap_return_3_U_frpsig_data_in;
reg   [31:0] pf_ap_return_4_U_frpsig_data_in;
reg   [31:0] pf_ap_return_5_U_frpsig_data_in;
reg   [31:0] pf_ap_return_6_U_frpsig_data_in;
reg   [31:0] pf_ap_return_7_U_frpsig_data_in;
reg   [31:0] pf_ap_return_8_U_frpsig_data_in;
reg   [31:0] pf_ap_return_9_U_frpsig_data_in;
reg   [31:0] pf_ap_return_10_U_frpsig_data_in;
reg   [31:0] pf_ap_return_11_U_frpsig_data_in;
reg   [31:0] pf_ap_return_12_U_frpsig_data_in;
reg   [31:0] pf_ap_return_13_U_frpsig_data_in;
reg   [31:0] pf_ap_return_14_U_frpsig_data_in;
reg   [31:0] pf_ap_return_15_U_frpsig_data_in;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_done_reg = 1'b0;
#0 ap_return_0_preg = 32'd0;
#0 ap_return_1_preg = 32'd0;
#0 ap_return_2_preg = 32'd0;
#0 ap_return_3_preg = 32'd0;
#0 ap_return_4_preg = 32'd0;
#0 ap_return_5_preg = 32'd0;
#0 ap_return_6_preg = 32'd0;
#0 ap_return_7_preg = 32'd0;
#0 ap_return_8_preg = 32'd0;
#0 ap_return_9_preg = 32'd0;
#0 ap_return_10_preg = 32'd0;
#0 ap_return_11_preg = 32'd0;
#0 ap_return_12_preg = 32'd0;
#0 ap_return_13_preg = 32'd0;
#0 ap_return_14_preg = 32'd0;
#0 ap_return_15_preg = 32'd0;
end

myproject_dense_resource_ap_fixed_32_6_5_3_0_ap_fixed_32_6_5_3_0_config2_s_outidx_1_ROMbkb #(
    .DataWidth( 1 ),
    .AddressRange( 128 ),
    .AddressWidth( 7 ))
outidx_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(outidx_1_address0),
    .ce0(outidx_1_ce0),
    .q0(outidx_1_q0)
);

myproject_dense_resource_ap_fixed_32_6_5_3_0_ap_fixed_32_6_5_3_0_config2_s_w2_86_ROM_AUcud #(
    .DataWidth( 252 ),
    .AddressRange( 128 ),
    .AddressWidth( 7 ))
w2_86_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(w2_86_address0),
    .ce0(w2_86_ce0),
    .q0(w2_86_q0)
);

myproject_mul_32s_28s_58_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 28 ),
    .dout_WIDTH( 58 ))
mul_32s_28s_58_5_1_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_464_p0),
    .din1(tmp_reg_1564),
    .ce(1'b1),
    .dout(grp_fu_464_p2)
);

myproject_mul_32s_32s_58_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 58 ))
mul_32s_32s_58_5_1_U2(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(w_reg_1529),
    .din1(grp_fu_468_p1),
    .ce(1'b1),
    .dout(grp_fu_468_p2)
);

myproject_mul_32s_32s_58_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 58 ))
mul_32s_32s_58_5_1_U3(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(w_7_reg_1534),
    .din1(grp_fu_472_p1),
    .ce(1'b1),
    .dout(grp_fu_472_p2)
);

myproject_mul_32s_32s_58_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 58 ))
mul_32s_32s_58_5_1_U4(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(w_8_reg_1539),
    .din1(grp_fu_476_p1),
    .ce(1'b1),
    .dout(grp_fu_476_p2)
);

myproject_mul_32s_32s_58_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 58 ))
mul_32s_32s_58_5_1_U5(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(w_9_reg_1544),
    .din1(grp_fu_480_p1),
    .ce(1'b1),
    .dout(grp_fu_480_p2)
);

myproject_mul_32s_32s_58_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 58 ))
mul_32s_32s_58_5_1_U6(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(w_10_reg_1549),
    .din1(grp_fu_484_p1),
    .ce(1'b1),
    .dout(grp_fu_484_p2)
);

myproject_mul_32s_32s_58_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 58 ))
mul_32s_32s_58_5_1_U7(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(w_11_reg_1554),
    .din1(grp_fu_488_p1),
    .ce(1'b1),
    .dout(grp_fu_488_p2)
);

myproject_mul_32s_32s_58_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 58 ))
mul_32s_32s_58_5_1_U8(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(w_12_reg_1559),
    .din1(grp_fu_492_p1),
    .ce(1'b1),
    .dout(grp_fu_492_p2)
);

myproject_lshr_2048ns_11ns_2048_6_1 #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .OP( 1 ),
    .din0_WIDTH( 2048 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 2048 ))
lshr_2048ns_11ns_2048_6_1_U9(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(ap_phi_mux_input_1_load_phi_phi_fu_215_p4),
    .din1(grp_fu_512_p1),
    .ce(1'b1),
    .dout(grp_fu_512_p2)
);

myproject_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(pf_all_done),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(pf_all_done),
    .ap_continue(ap_continue)
);

myproject_frp_pipeline_valid #(
    .PipelineLatency( 12 ),
    .PipelineII( 1 ),
    .CeilLog2Stages( 4 ),
    .ExitLatency( -1 ))
frp_pipeline_valid_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .valid_in(ap_frp_vld_in),
    .exitcond(1'b0),
    .valid_out(frp_pipeline_valid_U_valid_out),
    .num_valid_datasets(frp_pipeline_valid_U_num_valid_datasets)
);

myproject_frp_fifoout #(
    .BlockingType( 0 ),
    .PipeLatency( 12 ),
    .PipelineII( 1 ),
    .DataWidth( 32 ),
    .NumWrites( 1 ),
    .CeilLog2Stages( 4 ),
    .CeilLog2FDepth( 4 ),
    .PfAllDoneEnable( 0 ))
pf_ap_return_0_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(pf_ap_return_0_U_frpsig_data_in),
    .data_out(pf_ap_return_0_U_data_out),
    .valid(frp_pipeline_valid_U_valid_out),
    .data_in_vld(ap_done_int_frp),
    .data_out_vld(pf_ap_return_0_U_data_out_vld),
    .data_in_last(ap_done_int_frp),
    .pf_continue(pf_sync_continue),
    .pf_all_done(pf_all_done),
    .pf_ready(pf_ap_return_0_U_pf_ready),
    .pf_done(pf_ap_return_0_U_pf_done),
    .data_out_read(1'b1),
    .ap_start(1'b0),
    .num_valid_datasets(frp_pipeline_valid_U_num_valid_datasets)
);

myproject_frp_fifoout #(
    .BlockingType( 0 ),
    .PipeLatency( 12 ),
    .PipelineII( 1 ),
    .DataWidth( 32 ),
    .NumWrites( 1 ),
    .CeilLog2Stages( 4 ),
    .CeilLog2FDepth( 4 ),
    .PfAllDoneEnable( 0 ))
pf_ap_return_1_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(pf_ap_return_1_U_frpsig_data_in),
    .data_out(pf_ap_return_1_U_data_out),
    .valid(frp_pipeline_valid_U_valid_out),
    .data_in_vld(ap_done_int_frp),
    .data_out_vld(pf_ap_return_1_U_data_out_vld),
    .data_in_last(ap_done_int_frp),
    .pf_continue(pf_sync_continue),
    .pf_all_done(pf_all_done),
    .pf_ready(pf_ap_return_1_U_pf_ready),
    .pf_done(pf_ap_return_1_U_pf_done),
    .data_out_read(1'b1),
    .ap_start(1'b0),
    .num_valid_datasets(frp_pipeline_valid_U_num_valid_datasets)
);

myproject_frp_fifoout #(
    .BlockingType( 0 ),
    .PipeLatency( 12 ),
    .PipelineII( 1 ),
    .DataWidth( 32 ),
    .NumWrites( 1 ),
    .CeilLog2Stages( 4 ),
    .CeilLog2FDepth( 4 ),
    .PfAllDoneEnable( 0 ))
pf_ap_return_2_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(pf_ap_return_2_U_frpsig_data_in),
    .data_out(pf_ap_return_2_U_data_out),
    .valid(frp_pipeline_valid_U_valid_out),
    .data_in_vld(ap_done_int_frp),
    .data_out_vld(pf_ap_return_2_U_data_out_vld),
    .data_in_last(ap_done_int_frp),
    .pf_continue(pf_sync_continue),
    .pf_all_done(pf_all_done),
    .pf_ready(pf_ap_return_2_U_pf_ready),
    .pf_done(pf_ap_return_2_U_pf_done),
    .data_out_read(1'b1),
    .ap_start(1'b0),
    .num_valid_datasets(frp_pipeline_valid_U_num_valid_datasets)
);

myproject_frp_fifoout #(
    .BlockingType( 0 ),
    .PipeLatency( 12 ),
    .PipelineII( 1 ),
    .DataWidth( 32 ),
    .NumWrites( 1 ),
    .CeilLog2Stages( 4 ),
    .CeilLog2FDepth( 4 ),
    .PfAllDoneEnable( 0 ))
pf_ap_return_3_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(pf_ap_return_3_U_frpsig_data_in),
    .data_out(pf_ap_return_3_U_data_out),
    .valid(frp_pipeline_valid_U_valid_out),
    .data_in_vld(ap_done_int_frp),
    .data_out_vld(pf_ap_return_3_U_data_out_vld),
    .data_in_last(ap_done_int_frp),
    .pf_continue(pf_sync_continue),
    .pf_all_done(pf_all_done),
    .pf_ready(pf_ap_return_3_U_pf_ready),
    .pf_done(pf_ap_return_3_U_pf_done),
    .data_out_read(1'b1),
    .ap_start(1'b0),
    .num_valid_datasets(frp_pipeline_valid_U_num_valid_datasets)
);

myproject_frp_fifoout #(
    .BlockingType( 0 ),
    .PipeLatency( 12 ),
    .PipelineII( 1 ),
    .DataWidth( 32 ),
    .NumWrites( 1 ),
    .CeilLog2Stages( 4 ),
    .CeilLog2FDepth( 4 ),
    .PfAllDoneEnable( 0 ))
pf_ap_return_4_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(pf_ap_return_4_U_frpsig_data_in),
    .data_out(pf_ap_return_4_U_data_out),
    .valid(frp_pipeline_valid_U_valid_out),
    .data_in_vld(ap_done_int_frp),
    .data_out_vld(pf_ap_return_4_U_data_out_vld),
    .data_in_last(ap_done_int_frp),
    .pf_continue(pf_sync_continue),
    .pf_all_done(pf_all_done),
    .pf_ready(pf_ap_return_4_U_pf_ready),
    .pf_done(pf_ap_return_4_U_pf_done),
    .data_out_read(1'b1),
    .ap_start(1'b0),
    .num_valid_datasets(frp_pipeline_valid_U_num_valid_datasets)
);

myproject_frp_fifoout #(
    .BlockingType( 0 ),
    .PipeLatency( 12 ),
    .PipelineII( 1 ),
    .DataWidth( 32 ),
    .NumWrites( 1 ),
    .CeilLog2Stages( 4 ),
    .CeilLog2FDepth( 4 ),
    .PfAllDoneEnable( 0 ))
pf_ap_return_5_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(pf_ap_return_5_U_frpsig_data_in),
    .data_out(pf_ap_return_5_U_data_out),
    .valid(frp_pipeline_valid_U_valid_out),
    .data_in_vld(ap_done_int_frp),
    .data_out_vld(pf_ap_return_5_U_data_out_vld),
    .data_in_last(ap_done_int_frp),
    .pf_continue(pf_sync_continue),
    .pf_all_done(pf_all_done),
    .pf_ready(pf_ap_return_5_U_pf_ready),
    .pf_done(pf_ap_return_5_U_pf_done),
    .data_out_read(1'b1),
    .ap_start(1'b0),
    .num_valid_datasets(frp_pipeline_valid_U_num_valid_datasets)
);

myproject_frp_fifoout #(
    .BlockingType( 0 ),
    .PipeLatency( 12 ),
    .PipelineII( 1 ),
    .DataWidth( 32 ),
    .NumWrites( 1 ),
    .CeilLog2Stages( 4 ),
    .CeilLog2FDepth( 4 ),
    .PfAllDoneEnable( 0 ))
pf_ap_return_6_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(pf_ap_return_6_U_frpsig_data_in),
    .data_out(pf_ap_return_6_U_data_out),
    .valid(frp_pipeline_valid_U_valid_out),
    .data_in_vld(ap_done_int_frp),
    .data_out_vld(pf_ap_return_6_U_data_out_vld),
    .data_in_last(ap_done_int_frp),
    .pf_continue(pf_sync_continue),
    .pf_all_done(pf_all_done),
    .pf_ready(pf_ap_return_6_U_pf_ready),
    .pf_done(pf_ap_return_6_U_pf_done),
    .data_out_read(1'b1),
    .ap_start(1'b0),
    .num_valid_datasets(frp_pipeline_valid_U_num_valid_datasets)
);

myproject_frp_fifoout #(
    .BlockingType( 0 ),
    .PipeLatency( 12 ),
    .PipelineII( 1 ),
    .DataWidth( 32 ),
    .NumWrites( 1 ),
    .CeilLog2Stages( 4 ),
    .CeilLog2FDepth( 4 ),
    .PfAllDoneEnable( 0 ))
pf_ap_return_7_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(pf_ap_return_7_U_frpsig_data_in),
    .data_out(pf_ap_return_7_U_data_out),
    .valid(frp_pipeline_valid_U_valid_out),
    .data_in_vld(ap_done_int_frp),
    .data_out_vld(pf_ap_return_7_U_data_out_vld),
    .data_in_last(ap_done_int_frp),
    .pf_continue(pf_sync_continue),
    .pf_all_done(pf_all_done),
    .pf_ready(pf_ap_return_7_U_pf_ready),
    .pf_done(pf_ap_return_7_U_pf_done),
    .data_out_read(1'b1),
    .ap_start(1'b0),
    .num_valid_datasets(frp_pipeline_valid_U_num_valid_datasets)
);

myproject_frp_fifoout #(
    .BlockingType( 0 ),
    .PipeLatency( 12 ),
    .PipelineII( 1 ),
    .DataWidth( 32 ),
    .NumWrites( 1 ),
    .CeilLog2Stages( 4 ),
    .CeilLog2FDepth( 4 ),
    .PfAllDoneEnable( 0 ))
pf_ap_return_8_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(pf_ap_return_8_U_frpsig_data_in),
    .data_out(pf_ap_return_8_U_data_out),
    .valid(frp_pipeline_valid_U_valid_out),
    .data_in_vld(ap_done_int_frp),
    .data_out_vld(pf_ap_return_8_U_data_out_vld),
    .data_in_last(ap_done_int_frp),
    .pf_continue(pf_sync_continue),
    .pf_all_done(pf_all_done),
    .pf_ready(pf_ap_return_8_U_pf_ready),
    .pf_done(pf_ap_return_8_U_pf_done),
    .data_out_read(1'b1),
    .ap_start(1'b0),
    .num_valid_datasets(frp_pipeline_valid_U_num_valid_datasets)
);

myproject_frp_fifoout #(
    .BlockingType( 0 ),
    .PipeLatency( 12 ),
    .PipelineII( 1 ),
    .DataWidth( 32 ),
    .NumWrites( 1 ),
    .CeilLog2Stages( 4 ),
    .CeilLog2FDepth( 4 ),
    .PfAllDoneEnable( 0 ))
pf_ap_return_9_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(pf_ap_return_9_U_frpsig_data_in),
    .data_out(pf_ap_return_9_U_data_out),
    .valid(frp_pipeline_valid_U_valid_out),
    .data_in_vld(ap_done_int_frp),
    .data_out_vld(pf_ap_return_9_U_data_out_vld),
    .data_in_last(ap_done_int_frp),
    .pf_continue(pf_sync_continue),
    .pf_all_done(pf_all_done),
    .pf_ready(pf_ap_return_9_U_pf_ready),
    .pf_done(pf_ap_return_9_U_pf_done),
    .data_out_read(1'b1),
    .ap_start(1'b0),
    .num_valid_datasets(frp_pipeline_valid_U_num_valid_datasets)
);

myproject_frp_fifoout #(
    .BlockingType( 0 ),
    .PipeLatency( 12 ),
    .PipelineII( 1 ),
    .DataWidth( 32 ),
    .NumWrites( 1 ),
    .CeilLog2Stages( 4 ),
    .CeilLog2FDepth( 4 ),
    .PfAllDoneEnable( 0 ))
pf_ap_return_10_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(pf_ap_return_10_U_frpsig_data_in),
    .data_out(pf_ap_return_10_U_data_out),
    .valid(frp_pipeline_valid_U_valid_out),
    .data_in_vld(ap_done_int_frp),
    .data_out_vld(pf_ap_return_10_U_data_out_vld),
    .data_in_last(ap_done_int_frp),
    .pf_continue(pf_sync_continue),
    .pf_all_done(pf_all_done),
    .pf_ready(pf_ap_return_10_U_pf_ready),
    .pf_done(pf_ap_return_10_U_pf_done),
    .data_out_read(1'b1),
    .ap_start(1'b0),
    .num_valid_datasets(frp_pipeline_valid_U_num_valid_datasets)
);

myproject_frp_fifoout #(
    .BlockingType( 0 ),
    .PipeLatency( 12 ),
    .PipelineII( 1 ),
    .DataWidth( 32 ),
    .NumWrites( 1 ),
    .CeilLog2Stages( 4 ),
    .CeilLog2FDepth( 4 ),
    .PfAllDoneEnable( 0 ))
pf_ap_return_11_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(pf_ap_return_11_U_frpsig_data_in),
    .data_out(pf_ap_return_11_U_data_out),
    .valid(frp_pipeline_valid_U_valid_out),
    .data_in_vld(ap_done_int_frp),
    .data_out_vld(pf_ap_return_11_U_data_out_vld),
    .data_in_last(ap_done_int_frp),
    .pf_continue(pf_sync_continue),
    .pf_all_done(pf_all_done),
    .pf_ready(pf_ap_return_11_U_pf_ready),
    .pf_done(pf_ap_return_11_U_pf_done),
    .data_out_read(1'b1),
    .ap_start(1'b0),
    .num_valid_datasets(frp_pipeline_valid_U_num_valid_datasets)
);

myproject_frp_fifoout #(
    .BlockingType( 0 ),
    .PipeLatency( 12 ),
    .PipelineII( 1 ),
    .DataWidth( 32 ),
    .NumWrites( 1 ),
    .CeilLog2Stages( 4 ),
    .CeilLog2FDepth( 4 ),
    .PfAllDoneEnable( 0 ))
pf_ap_return_12_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(pf_ap_return_12_U_frpsig_data_in),
    .data_out(pf_ap_return_12_U_data_out),
    .valid(frp_pipeline_valid_U_valid_out),
    .data_in_vld(ap_done_int_frp),
    .data_out_vld(pf_ap_return_12_U_data_out_vld),
    .data_in_last(ap_done_int_frp),
    .pf_continue(pf_sync_continue),
    .pf_all_done(pf_all_done),
    .pf_ready(pf_ap_return_12_U_pf_ready),
    .pf_done(pf_ap_return_12_U_pf_done),
    .data_out_read(1'b1),
    .ap_start(1'b0),
    .num_valid_datasets(frp_pipeline_valid_U_num_valid_datasets)
);

myproject_frp_fifoout #(
    .BlockingType( 0 ),
    .PipeLatency( 12 ),
    .PipelineII( 1 ),
    .DataWidth( 32 ),
    .NumWrites( 1 ),
    .CeilLog2Stages( 4 ),
    .CeilLog2FDepth( 4 ),
    .PfAllDoneEnable( 0 ))
pf_ap_return_13_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(pf_ap_return_13_U_frpsig_data_in),
    .data_out(pf_ap_return_13_U_data_out),
    .valid(frp_pipeline_valid_U_valid_out),
    .data_in_vld(ap_done_int_frp),
    .data_out_vld(pf_ap_return_13_U_data_out_vld),
    .data_in_last(ap_done_int_frp),
    .pf_continue(pf_sync_continue),
    .pf_all_done(pf_all_done),
    .pf_ready(pf_ap_return_13_U_pf_ready),
    .pf_done(pf_ap_return_13_U_pf_done),
    .data_out_read(1'b1),
    .ap_start(1'b0),
    .num_valid_datasets(frp_pipeline_valid_U_num_valid_datasets)
);

myproject_frp_fifoout #(
    .BlockingType( 0 ),
    .PipeLatency( 12 ),
    .PipelineII( 1 ),
    .DataWidth( 32 ),
    .NumWrites( 1 ),
    .CeilLog2Stages( 4 ),
    .CeilLog2FDepth( 4 ),
    .PfAllDoneEnable( 0 ))
pf_ap_return_14_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(pf_ap_return_14_U_frpsig_data_in),
    .data_out(pf_ap_return_14_U_data_out),
    .valid(frp_pipeline_valid_U_valid_out),
    .data_in_vld(ap_done_int_frp),
    .data_out_vld(pf_ap_return_14_U_data_out_vld),
    .data_in_last(ap_done_int_frp),
    .pf_continue(pf_sync_continue),
    .pf_all_done(pf_all_done),
    .pf_ready(pf_ap_return_14_U_pf_ready),
    .pf_done(pf_ap_return_14_U_pf_done),
    .data_out_read(1'b1),
    .ap_start(1'b0),
    .num_valid_datasets(frp_pipeline_valid_U_num_valid_datasets)
);

myproject_frp_fifoout #(
    .BlockingType( 0 ),
    .PipeLatency( 12 ),
    .PipelineII( 1 ),
    .DataWidth( 32 ),
    .NumWrites( 1 ),
    .CeilLog2Stages( 4 ),
    .CeilLog2FDepth( 4 ),
    .PfAllDoneEnable( 0 ))
pf_ap_return_15_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(pf_ap_return_15_U_frpsig_data_in),
    .data_out(pf_ap_return_15_U_data_out),
    .valid(frp_pipeline_valid_U_valid_out),
    .data_in_vld(ap_done_int_frp),
    .data_out_vld(pf_ap_return_15_U_data_out_vld),
    .data_in_last(ap_done_int_frp),
    .pf_continue(pf_sync_continue),
    .pf_all_done(pf_all_done),
    .pf_ready(pf_ap_return_15_U_pf_ready),
    .pf_done(pf_ap_return_15_U_pf_done),
    .data_out_read(1'b1),
    .ap_start(1'b0),
    .num_valid_datasets(frp_pipeline_valid_U_num_valid_datasets)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter11_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_0_preg <= 32'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln129_reg_1466_pp0_iter10_reg == 1'd1))) begin
            ap_return_0_preg <= acc_181_fu_952_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_10_preg <= 32'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln129_reg_1466_pp0_iter10_reg == 1'd1))) begin
            ap_return_10_preg <= acc_191_fu_1232_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_11_preg <= 32'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln129_reg_1466_pp0_iter10_reg == 1'd1))) begin
            ap_return_11_preg <= acc_192_fu_1225_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_12_preg <= 32'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln129_reg_1466_pp0_iter10_reg == 1'd1))) begin
            ap_return_12_preg <= acc_193_fu_1288_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_13_preg <= 32'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln129_reg_1466_pp0_iter10_reg == 1'd1))) begin
            ap_return_13_preg <= acc_194_fu_1281_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_14_preg <= 32'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln129_reg_1466_pp0_iter10_reg == 1'd1))) begin
            ap_return_14_preg <= acc_195_fu_1344_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_15_preg <= 32'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln129_reg_1466_pp0_iter10_reg == 1'd1))) begin
            ap_return_15_preg <= acc_196_fu_1337_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_1_preg <= 32'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln129_reg_1466_pp0_iter10_reg == 1'd1))) begin
            ap_return_1_preg <= acc_182_fu_945_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_2_preg <= 32'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln129_reg_1466_pp0_iter10_reg == 1'd1))) begin
            ap_return_2_preg <= acc_183_fu_1008_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_3_preg <= 32'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln129_reg_1466_pp0_iter10_reg == 1'd1))) begin
            ap_return_3_preg <= acc_184_fu_1001_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_4_preg <= 32'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln129_reg_1466_pp0_iter10_reg == 1'd1))) begin
            ap_return_4_preg <= acc_185_fu_1064_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_5_preg <= 32'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln129_reg_1466_pp0_iter10_reg == 1'd1))) begin
            ap_return_5_preg <= acc_186_fu_1057_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_6_preg <= 32'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln129_reg_1466_pp0_iter10_reg == 1'd1))) begin
            ap_return_6_preg <= acc_187_fu_1120_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_7_preg <= 32'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln129_reg_1466_pp0_iter10_reg == 1'd1))) begin
            ap_return_7_preg <= acc_188_fu_1113_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_8_preg <= 32'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln129_reg_1466_pp0_iter10_reg == 1'd1))) begin
            ap_return_8_preg <= acc_189_fu_1176_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_9_preg <= 32'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln129_reg_1466_pp0_iter10_reg == 1'd1))) begin
            ap_return_9_preg <= acc_190_fu_1169_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter11 == 1'b1) & (icmp_ln129_reg_1466_pp0_iter10_reg == 1'd0))) begin
        acc40_reg_224 <= acc_181_fu_952_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_init_pp0_iter10_reg == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter11 == 1'b1) & (icmp_ln129_reg_1466_pp0_iter10_reg == 1'd1)))) begin
        acc40_reg_224 <= 32'd79804976;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter11 == 1'b1) & (icmp_ln129_reg_1466_pp0_iter10_reg == 1'd0))) begin
        acc_14438_reg_239 <= acc_182_fu_945_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_init_pp0_iter10_reg == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter11 == 1'b1) & (icmp_ln129_reg_1466_pp0_iter10_reg == 1'd1)))) begin
        acc_14438_reg_239 <= 32'd82054352;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter11 == 1'b1) & (icmp_ln129_reg_1466_pp0_iter10_reg == 1'd0))) begin
        acc_14536_reg_254 <= acc_183_fu_1008_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_init_pp0_iter10_reg == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter11 == 1'b1) & (icmp_ln129_reg_1466_pp0_iter10_reg == 1'd1)))) begin
        acc_14536_reg_254 <= 32'd46805572;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter11 == 1'b1) & (icmp_ln129_reg_1466_pp0_iter10_reg == 1'd0))) begin
        acc_14634_reg_269 <= acc_184_fu_1001_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_init_pp0_iter10_reg == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter11 == 1'b1) & (icmp_ln129_reg_1466_pp0_iter10_reg == 1'd1)))) begin
        acc_14634_reg_269 <= 32'd108430976;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter11 == 1'b1) & (icmp_ln129_reg_1466_pp0_iter10_reg == 1'd0))) begin
        acc_14732_reg_284 <= acc_185_fu_1064_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_init_pp0_iter10_reg == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter11 == 1'b1) & (icmp_ln129_reg_1466_pp0_iter10_reg == 1'd1)))) begin
        acc_14732_reg_284 <= 32'd67839712;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter11 == 1'b1) & (icmp_ln129_reg_1466_pp0_iter10_reg == 1'd0))) begin
        acc_14830_reg_299 <= acc_186_fu_1057_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_init_pp0_iter10_reg == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter11 == 1'b1) & (icmp_ln129_reg_1466_pp0_iter10_reg == 1'd1)))) begin
        acc_14830_reg_299 <= 32'd101503696;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter11 == 1'b1) & (icmp_ln129_reg_1466_pp0_iter10_reg == 1'd0))) begin
        acc_14928_reg_314 <= acc_187_fu_1120_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_init_pp0_iter10_reg == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter11 == 1'b1) & (icmp_ln129_reg_1466_pp0_iter10_reg == 1'd1)))) begin
        acc_14928_reg_314 <= 32'd109891344;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter11 == 1'b1) & (icmp_ln129_reg_1466_pp0_iter10_reg == 1'd0))) begin
        acc_15026_reg_329 <= acc_188_fu_1113_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_init_pp0_iter10_reg == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter11 == 1'b1) & (icmp_ln129_reg_1466_pp0_iter10_reg == 1'd1)))) begin
        acc_15026_reg_329 <= 32'd92863000;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter11 == 1'b1) & (icmp_ln129_reg_1466_pp0_iter10_reg == 1'd0))) begin
        acc_15124_reg_344 <= acc_189_fu_1176_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_init_pp0_iter10_reg == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter11 == 1'b1) & (icmp_ln129_reg_1466_pp0_iter10_reg == 1'd1)))) begin
        acc_15124_reg_344 <= 32'd11457830;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter11 == 1'b1) & (icmp_ln129_reg_1466_pp0_iter10_reg == 1'd0))) begin
        acc_15222_reg_359 <= acc_190_fu_1169_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_init_pp0_iter10_reg == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter11 == 1'b1) & (icmp_ln129_reg_1466_pp0_iter10_reg == 1'd1)))) begin
        acc_15222_reg_359 <= 32'd106089208;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter11 == 1'b1) & (icmp_ln129_reg_1466_pp0_iter10_reg == 1'd0))) begin
        acc_15320_reg_374 <= acc_191_fu_1232_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_init_pp0_iter10_reg == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter11 == 1'b1) & (icmp_ln129_reg_1466_pp0_iter10_reg == 1'd1)))) begin
        acc_15320_reg_374 <= 32'd102826920;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter11 == 1'b1) & (icmp_ln129_reg_1466_pp0_iter10_reg == 1'd0))) begin
        acc_15418_reg_389 <= acc_192_fu_1225_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_init_pp0_iter10_reg == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter11 == 1'b1) & (icmp_ln129_reg_1466_pp0_iter10_reg == 1'd1)))) begin
        acc_15418_reg_389 <= 32'd92101440;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter11 == 1'b1) & (icmp_ln129_reg_1466_pp0_iter10_reg == 1'd0))) begin
        acc_15516_reg_404 <= acc_193_fu_1288_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_init_pp0_iter10_reg == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter11 == 1'b1) & (icmp_ln129_reg_1466_pp0_iter10_reg == 1'd1)))) begin
        acc_15516_reg_404 <= 32'd98554280;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter11 == 1'b1) & (icmp_ln129_reg_1466_pp0_iter10_reg == 1'd0))) begin
        acc_15614_reg_419 <= acc_194_fu_1281_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_init_pp0_iter10_reg == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter11 == 1'b1) & (icmp_ln129_reg_1466_pp0_iter10_reg == 1'd1)))) begin
        acc_15614_reg_419 <= 32'd84158264;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter11 == 1'b1) & (icmp_ln129_reg_1466_pp0_iter10_reg == 1'd0))) begin
        acc_15712_reg_434 <= acc_195_fu_1344_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_init_pp0_iter10_reg == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter11 == 1'b1) & (icmp_ln129_reg_1466_pp0_iter10_reg == 1'd1)))) begin
        acc_15712_reg_434 <= 32'd100940856;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter11 == 1'b1) & (icmp_ln129_reg_1466_pp0_iter10_reg == 1'd0))) begin
        acc_15810_reg_449 <= acc_196_fu_1337_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_init_pp0_iter10_reg == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter11 == 1'b1) & (icmp_ln129_reg_1466_pp0_iter10_reg == 1'd1)))) begin
        acc_15810_reg_449 <= 32'd53044472;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter10_reg == 1'b0))) begin
        ap_loop_exit_ready_pp0_iter11_reg <= 1'b0;
    end else if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[4'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln129_reg_1466 == 1'd0)))) begin
        do_init_reg_156 <= 1'd0;
    end else if ((((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((frp_pipeline_valid_U_valid_out[4'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln129_reg_1466 == 1'd1))))) begin
        do_init_reg_156 <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[4'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln129_reg_1466 == 1'd0)))) begin
        in_index42_reg_184 <= in_index_reg_1456;
    end else if ((((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((frp_pipeline_valid_U_valid_out[4'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln129_reg_1466 == 1'd1))))) begin
        in_index42_reg_184 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((frp_pipeline_valid_U_valid_out[4'd0] == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_phi_mux_do_init_phi_fu_159_p6 == 1'd0))) begin
            input_1_load_phi_reg_211 <= input_1_load_phi_reg_211;
        end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_phi_mux_do_init_phi_fu_159_p6 == 1'd1))) begin
            input_1_load_phi_reg_211 <= input_1;
        end else if ((~(icmp_ln129_fu_554_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
            input_1_load_phi_reg_211 <= ap_phi_reg_pp0_iter0_input_1_load_phi_reg_211;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[4'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln129_reg_1466 == 1'd0)))) begin
        w_index41_reg_197 <= w_index_reg_1461;
    end else if ((((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((frp_pipeline_valid_U_valid_out[4'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln129_reg_1466 == 1'd1))))) begin
        w_index41_reg_197 <= 7'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        a_reg_1524 <= a_fu_566_p1;
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        ap_loop_init_pp0_iter10_reg <= ap_loop_init_pp0_iter9_reg;
        ap_loop_init_pp0_iter3_reg <= ap_loop_init_pp0_iter2_reg;
        ap_loop_init_pp0_iter4_reg <= ap_loop_init_pp0_iter3_reg;
        ap_loop_init_pp0_iter5_reg <= ap_loop_init_pp0_iter4_reg;
        ap_loop_init_pp0_iter6_reg <= ap_loop_init_pp0_iter5_reg;
        ap_loop_init_pp0_iter7_reg <= ap_loop_init_pp0_iter6_reg;
        ap_loop_init_pp0_iter8_reg <= ap_loop_init_pp0_iter7_reg;
        ap_loop_init_pp0_iter9_reg <= ap_loop_init_pp0_iter8_reg;
        icmp_ln129_reg_1466_pp0_iter10_reg <= icmp_ln129_reg_1466_pp0_iter9_reg;
        icmp_ln129_reg_1466_pp0_iter2_reg <= icmp_ln129_reg_1466_pp0_iter1_reg;
        icmp_ln129_reg_1466_pp0_iter3_reg <= icmp_ln129_reg_1466_pp0_iter2_reg;
        icmp_ln129_reg_1466_pp0_iter4_reg <= icmp_ln129_reg_1466_pp0_iter3_reg;
        icmp_ln129_reg_1466_pp0_iter5_reg <= icmp_ln129_reg_1466_pp0_iter4_reg;
        icmp_ln129_reg_1466_pp0_iter6_reg <= icmp_ln129_reg_1466_pp0_iter5_reg;
        icmp_ln129_reg_1466_pp0_iter7_reg <= icmp_ln129_reg_1466_pp0_iter6_reg;
        icmp_ln129_reg_1466_pp0_iter8_reg <= icmp_ln129_reg_1466_pp0_iter7_reg;
        icmp_ln129_reg_1466_pp0_iter9_reg <= icmp_ln129_reg_1466_pp0_iter8_reg;
        out_index_reg_1480 <= outidx_1_q0;
        out_index_reg_1480_pp0_iter10_reg <= out_index_reg_1480_pp0_iter9_reg;
        out_index_reg_1480_pp0_iter6_reg <= out_index_reg_1480;
        out_index_reg_1480_pp0_iter7_reg <= out_index_reg_1480_pp0_iter6_reg;
        out_index_reg_1480_pp0_iter8_reg <= out_index_reg_1480_pp0_iter7_reg;
        out_index_reg_1480_pp0_iter9_reg <= out_index_reg_1480_pp0_iter8_reg;
        select_ln138_13_reg_1675 <= select_ln138_13_fu_778_p3;
        select_ln138_18_reg_1691 <= select_ln138_18_fu_805_p3;
        select_ln138_23_reg_1707 <= select_ln138_23_fu_832_p3;
        select_ln138_28_reg_1723 <= select_ln138_28_fu_859_p3;
        select_ln138_33_reg_1739 <= select_ln138_33_fu_886_p3;
        select_ln138_3_reg_1643 <= select_ln138_3_fu_724_p3;
        select_ln138_8_reg_1659 <= select_ln138_8_fu_751_p3;
        select_ln138_reg_1627 <= select_ln138_fu_697_p3;
        sub_ln138_10_reg_1680 <= sub_ln138_10_fu_789_p2;
        sub_ln138_11_reg_1696 <= sub_ln138_11_fu_816_p2;
        sub_ln138_12_reg_1712 <= sub_ln138_12_fu_843_p2;
        sub_ln138_13_reg_1728 <= sub_ln138_13_fu_870_p2;
        sub_ln138_14_reg_1744 <= sub_ln138_14_fu_897_p2;
        sub_ln138_8_reg_1648 <= sub_ln138_8_fu_735_p2;
        sub_ln138_9_reg_1664 <= sub_ln138_9_fu_762_p2;
        sub_ln138_reg_1632 <= sub_ln138_fu_708_p2;
        tmp_reg_1564 <= {{w2_86_q0[251:224]}};
        trunc_ln138_1_reg_1685 <= {{grp_fu_484_p2[57:26]}};
        trunc_ln138_2_reg_1701 <= {{grp_fu_488_p2[57:26]}};
        trunc_ln138_3_reg_1717 <= {{grp_fu_492_p2[57:26]}};
        trunc_ln138_4_reg_1733 <= {{grp_fu_464_p2[57:26]}};
        trunc_ln138_8_reg_1637 <= {{grp_fu_472_p2[57:26]}};
        trunc_ln138_9_reg_1653 <= {{grp_fu_476_p2[57:26]}};
        trunc_ln138_s_reg_1669 <= {{grp_fu_480_p2[57:26]}};
        trunc_ln_reg_1621 <= {{grp_fu_468_p2[57:26]}};
        w_10_reg_1549 <= {{w2_86_q0[159:128]}};
        w_11_reg_1554 <= {{w2_86_q0[191:160]}};
        w_12_reg_1559 <= {{w2_86_q0[223:192]}};
        w_7_reg_1534 <= {{w2_86_q0[63:32]}};
        w_8_reg_1539 <= {{w2_86_q0[95:64]}};
        w_9_reg_1544 <= {{w2_86_q0[127:96]}};
        w_index41_reg_197_pp0_iter2_reg <= w_index41_reg_197_pp0_iter1_reg;
        w_index41_reg_197_pp0_iter3_reg <= w_index41_reg_197_pp0_iter2_reg;
        w_reg_1529 <= w_fu_570_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        ap_loop_init_pp0_iter1_reg <= ap_loop_init;
        ap_loop_init_pp0_iter2_reg <= ap_loop_init_pp0_iter1_reg;
        icmp_ln129_reg_1466 <= icmp_ln129_fu_554_p2;
        icmp_ln129_reg_1466_pp0_iter1_reg <= icmp_ln129_reg_1466;
        w_index41_reg_197_pp0_iter1_reg <= w_index41_reg_197;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (frp_pipeline_valid_U_valid_out[4'd0] == 1'b1))) begin
        in_index_reg_1456 <= in_index_fu_540_p3;
        w_index_reg_1461 <= w_index_fu_548_p2;
    end
end

always @ (*) begin
    if (((frp_pipeline_valid_U_valid_out[4'd0] == 1'b1) & ((icmp_ln129_fu_554_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone)))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter11_reg == 1'b1))) begin
        ap_done_int_frp = 1'b1;
    end else begin
        ap_done_int_frp = 1'b0;
    end
end

always @ (*) begin
    if ((frp_pipeline_valid_U_valid_out[4'd1] == 1'b1)) begin
        ap_enable_reg_pp0_iter1 = 1'b1;
    end else begin
        ap_enable_reg_pp0_iter1 = 1'b0;
    end
end

always @ (*) begin
    if ((frp_pipeline_valid_U_valid_out[4'd10] == 1'b1)) begin
        ap_enable_reg_pp0_iter10 = 1'b1;
    end else begin
        ap_enable_reg_pp0_iter10 = 1'b0;
    end
end

always @ (*) begin
    if ((frp_pipeline_valid_U_valid_out[4'd11] == 1'b1)) begin
        ap_enable_reg_pp0_iter11 = 1'b1;
    end else begin
        ap_enable_reg_pp0_iter11 = 1'b0;
    end
end

always @ (*) begin
    if ((frp_pipeline_valid_U_valid_out[4'd2] == 1'b1)) begin
        ap_enable_reg_pp0_iter2 = 1'b1;
    end else begin
        ap_enable_reg_pp0_iter2 = 1'b0;
    end
end

always @ (*) begin
    if ((frp_pipeline_valid_U_valid_out[4'd3] == 1'b1)) begin
        ap_enable_reg_pp0_iter3 = 1'b1;
    end else begin
        ap_enable_reg_pp0_iter3 = 1'b0;
    end
end

always @ (*) begin
    if ((frp_pipeline_valid_U_valid_out[4'd4] == 1'b1)) begin
        ap_enable_reg_pp0_iter4 = 1'b1;
    end else begin
        ap_enable_reg_pp0_iter4 = 1'b0;
    end
end

always @ (*) begin
    if ((frp_pipeline_valid_U_valid_out[4'd5] == 1'b1)) begin
        ap_enable_reg_pp0_iter5 = 1'b1;
    end else begin
        ap_enable_reg_pp0_iter5 = 1'b0;
    end
end

always @ (*) begin
    if ((frp_pipeline_valid_U_valid_out[4'd6] == 1'b1)) begin
        ap_enable_reg_pp0_iter6 = 1'b1;
    end else begin
        ap_enable_reg_pp0_iter6 = 1'b0;
    end
end

always @ (*) begin
    if ((frp_pipeline_valid_U_valid_out[4'd7] == 1'b1)) begin
        ap_enable_reg_pp0_iter7 = 1'b1;
    end else begin
        ap_enable_reg_pp0_iter7 = 1'b0;
    end
end

always @ (*) begin
    if ((frp_pipeline_valid_U_valid_out[4'd8] == 1'b1)) begin
        ap_enable_reg_pp0_iter8 = 1'b1;
    end else begin
        ap_enable_reg_pp0_iter8 = 1'b0;
    end
end

always @ (*) begin
    if ((frp_pipeline_valid_U_valid_out[4'd9] == 1'b1)) begin
        ap_enable_reg_pp0_iter9 = 1'b1;
    end else begin
        ap_enable_reg_pp0_iter9 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_condition_frp_pvb_pf_start) & (1'b1 == ap_condition_frp_pvb_no_bkwd_prs) & (1'b1 == ap_condition_frp_pvb_no_fwd_prs))) begin
        ap_frp_vld_in = 1'b1;
    end else begin
        ap_frp_vld_in = 1'b0;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to10 = 1'b1;
    end else begin
        ap_idle_pp0_0to10 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter11 == 1'b1) & (icmp_ln129_reg_1466_pp0_iter10_reg == 1'd0))) begin
        ap_phi_mux_acc40_phi_fu_228_p6 = acc_181_fu_952_p3;
    end else if (((ap_loop_init_pp0_iter10_reg == 1'b1) | ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter11 == 1'b1) & (icmp_ln129_reg_1466_pp0_iter10_reg == 1'd1)))) begin
        ap_phi_mux_acc40_phi_fu_228_p6 = 32'd79804976;
    end else begin
        ap_phi_mux_acc40_phi_fu_228_p6 = acc40_reg_224;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter11 == 1'b1) & (icmp_ln129_reg_1466_pp0_iter10_reg == 1'd0))) begin
        ap_phi_mux_acc_14438_phi_fu_243_p6 = acc_182_fu_945_p3;
    end else if (((ap_loop_init_pp0_iter10_reg == 1'b1) | ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter11 == 1'b1) & (icmp_ln129_reg_1466_pp0_iter10_reg == 1'd1)))) begin
        ap_phi_mux_acc_14438_phi_fu_243_p6 = 32'd82054352;
    end else begin
        ap_phi_mux_acc_14438_phi_fu_243_p6 = acc_14438_reg_239;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter11 == 1'b1) & (icmp_ln129_reg_1466_pp0_iter10_reg == 1'd0))) begin
        ap_phi_mux_acc_14536_phi_fu_258_p6 = acc_183_fu_1008_p3;
    end else if (((ap_loop_init_pp0_iter10_reg == 1'b1) | ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter11 == 1'b1) & (icmp_ln129_reg_1466_pp0_iter10_reg == 1'd1)))) begin
        ap_phi_mux_acc_14536_phi_fu_258_p6 = 32'd46805572;
    end else begin
        ap_phi_mux_acc_14536_phi_fu_258_p6 = acc_14536_reg_254;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter11 == 1'b1) & (icmp_ln129_reg_1466_pp0_iter10_reg == 1'd0))) begin
        ap_phi_mux_acc_14634_phi_fu_273_p6 = acc_184_fu_1001_p3;
    end else if (((ap_loop_init_pp0_iter10_reg == 1'b1) | ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter11 == 1'b1) & (icmp_ln129_reg_1466_pp0_iter10_reg == 1'd1)))) begin
        ap_phi_mux_acc_14634_phi_fu_273_p6 = 32'd108430976;
    end else begin
        ap_phi_mux_acc_14634_phi_fu_273_p6 = acc_14634_reg_269;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter11 == 1'b1) & (icmp_ln129_reg_1466_pp0_iter10_reg == 1'd0))) begin
        ap_phi_mux_acc_14732_phi_fu_288_p6 = acc_185_fu_1064_p3;
    end else if (((ap_loop_init_pp0_iter10_reg == 1'b1) | ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter11 == 1'b1) & (icmp_ln129_reg_1466_pp0_iter10_reg == 1'd1)))) begin
        ap_phi_mux_acc_14732_phi_fu_288_p6 = 32'd67839712;
    end else begin
        ap_phi_mux_acc_14732_phi_fu_288_p6 = acc_14732_reg_284;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter11 == 1'b1) & (icmp_ln129_reg_1466_pp0_iter10_reg == 1'd0))) begin
        ap_phi_mux_acc_14830_phi_fu_303_p6 = acc_186_fu_1057_p3;
    end else if (((ap_loop_init_pp0_iter10_reg == 1'b1) | ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter11 == 1'b1) & (icmp_ln129_reg_1466_pp0_iter10_reg == 1'd1)))) begin
        ap_phi_mux_acc_14830_phi_fu_303_p6 = 32'd101503696;
    end else begin
        ap_phi_mux_acc_14830_phi_fu_303_p6 = acc_14830_reg_299;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter11 == 1'b1) & (icmp_ln129_reg_1466_pp0_iter10_reg == 1'd0))) begin
        ap_phi_mux_acc_14928_phi_fu_318_p6 = acc_187_fu_1120_p3;
    end else if (((ap_loop_init_pp0_iter10_reg == 1'b1) | ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter11 == 1'b1) & (icmp_ln129_reg_1466_pp0_iter10_reg == 1'd1)))) begin
        ap_phi_mux_acc_14928_phi_fu_318_p6 = 32'd109891344;
    end else begin
        ap_phi_mux_acc_14928_phi_fu_318_p6 = acc_14928_reg_314;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter11 == 1'b1) & (icmp_ln129_reg_1466_pp0_iter10_reg == 1'd0))) begin
        ap_phi_mux_acc_15026_phi_fu_333_p6 = acc_188_fu_1113_p3;
    end else if (((ap_loop_init_pp0_iter10_reg == 1'b1) | ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter11 == 1'b1) & (icmp_ln129_reg_1466_pp0_iter10_reg == 1'd1)))) begin
        ap_phi_mux_acc_15026_phi_fu_333_p6 = 32'd92863000;
    end else begin
        ap_phi_mux_acc_15026_phi_fu_333_p6 = acc_15026_reg_329;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter11 == 1'b1) & (icmp_ln129_reg_1466_pp0_iter10_reg == 1'd0))) begin
        ap_phi_mux_acc_15124_phi_fu_348_p6 = acc_189_fu_1176_p3;
    end else if (((ap_loop_init_pp0_iter10_reg == 1'b1) | ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter11 == 1'b1) & (icmp_ln129_reg_1466_pp0_iter10_reg == 1'd1)))) begin
        ap_phi_mux_acc_15124_phi_fu_348_p6 = 32'd11457830;
    end else begin
        ap_phi_mux_acc_15124_phi_fu_348_p6 = acc_15124_reg_344;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter11 == 1'b1) & (icmp_ln129_reg_1466_pp0_iter10_reg == 1'd0))) begin
        ap_phi_mux_acc_15222_phi_fu_363_p6 = acc_190_fu_1169_p3;
    end else if (((ap_loop_init_pp0_iter10_reg == 1'b1) | ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter11 == 1'b1) & (icmp_ln129_reg_1466_pp0_iter10_reg == 1'd1)))) begin
        ap_phi_mux_acc_15222_phi_fu_363_p6 = 32'd106089208;
    end else begin
        ap_phi_mux_acc_15222_phi_fu_363_p6 = acc_15222_reg_359;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter11 == 1'b1) & (icmp_ln129_reg_1466_pp0_iter10_reg == 1'd0))) begin
        ap_phi_mux_acc_15320_phi_fu_378_p6 = acc_191_fu_1232_p3;
    end else if (((ap_loop_init_pp0_iter10_reg == 1'b1) | ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter11 == 1'b1) & (icmp_ln129_reg_1466_pp0_iter10_reg == 1'd1)))) begin
        ap_phi_mux_acc_15320_phi_fu_378_p6 = 32'd102826920;
    end else begin
        ap_phi_mux_acc_15320_phi_fu_378_p6 = acc_15320_reg_374;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter11 == 1'b1) & (icmp_ln129_reg_1466_pp0_iter10_reg == 1'd0))) begin
        ap_phi_mux_acc_15418_phi_fu_393_p6 = acc_192_fu_1225_p3;
    end else if (((ap_loop_init_pp0_iter10_reg == 1'b1) | ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter11 == 1'b1) & (icmp_ln129_reg_1466_pp0_iter10_reg == 1'd1)))) begin
        ap_phi_mux_acc_15418_phi_fu_393_p6 = 32'd92101440;
    end else begin
        ap_phi_mux_acc_15418_phi_fu_393_p6 = acc_15418_reg_389;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter11 == 1'b1) & (icmp_ln129_reg_1466_pp0_iter10_reg == 1'd0))) begin
        ap_phi_mux_acc_15516_phi_fu_408_p6 = acc_193_fu_1288_p3;
    end else if (((ap_loop_init_pp0_iter10_reg == 1'b1) | ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter11 == 1'b1) & (icmp_ln129_reg_1466_pp0_iter10_reg == 1'd1)))) begin
        ap_phi_mux_acc_15516_phi_fu_408_p6 = 32'd98554280;
    end else begin
        ap_phi_mux_acc_15516_phi_fu_408_p6 = acc_15516_reg_404;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter11 == 1'b1) & (icmp_ln129_reg_1466_pp0_iter10_reg == 1'd0))) begin
        ap_phi_mux_acc_15614_phi_fu_423_p6 = acc_194_fu_1281_p3;
    end else if (((ap_loop_init_pp0_iter10_reg == 1'b1) | ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter11 == 1'b1) & (icmp_ln129_reg_1466_pp0_iter10_reg == 1'd1)))) begin
        ap_phi_mux_acc_15614_phi_fu_423_p6 = 32'd84158264;
    end else begin
        ap_phi_mux_acc_15614_phi_fu_423_p6 = acc_15614_reg_419;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter11 == 1'b1) & (icmp_ln129_reg_1466_pp0_iter10_reg == 1'd0))) begin
        ap_phi_mux_acc_15712_phi_fu_438_p6 = acc_195_fu_1344_p3;
    end else if (((ap_loop_init_pp0_iter10_reg == 1'b1) | ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter11 == 1'b1) & (icmp_ln129_reg_1466_pp0_iter10_reg == 1'd1)))) begin
        ap_phi_mux_acc_15712_phi_fu_438_p6 = 32'd100940856;
    end else begin
        ap_phi_mux_acc_15712_phi_fu_438_p6 = acc_15712_reg_434;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter11 == 1'b1) & (icmp_ln129_reg_1466_pp0_iter10_reg == 1'd0))) begin
        ap_phi_mux_acc_15810_phi_fu_453_p6 = acc_196_fu_1337_p3;
    end else if (((ap_loop_init_pp0_iter10_reg == 1'b1) | ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter11 == 1'b1) & (icmp_ln129_reg_1466_pp0_iter10_reg == 1'd1)))) begin
        ap_phi_mux_acc_15810_phi_fu_453_p6 = 32'd53044472;
    end else begin
        ap_phi_mux_acc_15810_phi_fu_453_p6 = acc_15810_reg_449;
    end
end

always @ (*) begin
    if (((frp_pipeline_valid_U_valid_out[4'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0) & (icmp_ln129_reg_1466 == 1'd0)))) begin
        ap_phi_mux_do_init_phi_fu_159_p6 = 1'd0;
    end else if ((((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((frp_pipeline_valid_U_valid_out[4'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0) & (icmp_ln129_reg_1466 == 1'd1))))) begin
        ap_phi_mux_do_init_phi_fu_159_p6 = 1'd1;
    end else begin
        ap_phi_mux_do_init_phi_fu_159_p6 = do_init_reg_156;
    end
end

always @ (*) begin
    if (((frp_pipeline_valid_U_valid_out[4'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0) & (icmp_ln129_reg_1466 == 1'd0)))) begin
        ap_phi_mux_in_index42_phi_fu_187_p6 = in_index_reg_1456;
    end else if ((((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((frp_pipeline_valid_U_valid_out[4'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0) & (icmp_ln129_reg_1466 == 1'd1))))) begin
        ap_phi_mux_in_index42_phi_fu_187_p6 = 32'd0;
    end else begin
        ap_phi_mux_in_index42_phi_fu_187_p6 = in_index42_reg_184;
    end
end

always @ (*) begin
    if ((ap_phi_mux_do_init_phi_fu_159_p6 == 1'd0)) begin
        ap_phi_mux_input_1_load_phi_phi_fu_215_p4 = input_1_load_phi_reg_211;
    end else if ((ap_phi_mux_do_init_phi_fu_159_p6 == 1'd1)) begin
        ap_phi_mux_input_1_load_phi_phi_fu_215_p4 = input_1;
    end else begin
        ap_phi_mux_input_1_load_phi_phi_fu_215_p4 = ap_phi_reg_pp0_iter0_input_1_load_phi_reg_211;
    end
end

always @ (*) begin
    if (((frp_pipeline_valid_U_valid_out[4'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0) & (icmp_ln129_reg_1466 == 1'd0)))) begin
        ap_phi_mux_w_index41_phi_fu_200_p6 = w_index_reg_1461;
    end else if ((((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((frp_pipeline_valid_U_valid_out[4'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0) & (icmp_ln129_reg_1466 == 1'd1))))) begin
        ap_phi_mux_w_index41_phi_fu_200_p6 = 7'd0;
    end else begin
        ap_phi_mux_w_index41_phi_fu_200_p6 = w_index41_reg_197;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (frp_pipeline_valid_U_valid_out[4'd0] == 1'b1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0_0to10 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        outidx_1_ce0 = 1'b1;
    end else begin
        outidx_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln129_reg_1466_pp0_iter10_reg == 1'd1))) begin
        pf_ap_return_0_U_frpsig_data_in = acc_181_fu_952_p3;
    end else begin
        pf_ap_return_0_U_frpsig_data_in = ap_return_0_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln129_reg_1466_pp0_iter10_reg == 1'd1))) begin
        pf_ap_return_10_U_frpsig_data_in = acc_191_fu_1232_p3;
    end else begin
        pf_ap_return_10_U_frpsig_data_in = ap_return_10_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln129_reg_1466_pp0_iter10_reg == 1'd1))) begin
        pf_ap_return_11_U_frpsig_data_in = acc_192_fu_1225_p3;
    end else begin
        pf_ap_return_11_U_frpsig_data_in = ap_return_11_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln129_reg_1466_pp0_iter10_reg == 1'd1))) begin
        pf_ap_return_12_U_frpsig_data_in = acc_193_fu_1288_p3;
    end else begin
        pf_ap_return_12_U_frpsig_data_in = ap_return_12_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln129_reg_1466_pp0_iter10_reg == 1'd1))) begin
        pf_ap_return_13_U_frpsig_data_in = acc_194_fu_1281_p3;
    end else begin
        pf_ap_return_13_U_frpsig_data_in = ap_return_13_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln129_reg_1466_pp0_iter10_reg == 1'd1))) begin
        pf_ap_return_14_U_frpsig_data_in = acc_195_fu_1344_p3;
    end else begin
        pf_ap_return_14_U_frpsig_data_in = ap_return_14_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln129_reg_1466_pp0_iter10_reg == 1'd1))) begin
        pf_ap_return_15_U_frpsig_data_in = acc_196_fu_1337_p3;
    end else begin
        pf_ap_return_15_U_frpsig_data_in = ap_return_15_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln129_reg_1466_pp0_iter10_reg == 1'd1))) begin
        pf_ap_return_1_U_frpsig_data_in = acc_182_fu_945_p3;
    end else begin
        pf_ap_return_1_U_frpsig_data_in = ap_return_1_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln129_reg_1466_pp0_iter10_reg == 1'd1))) begin
        pf_ap_return_2_U_frpsig_data_in = acc_183_fu_1008_p3;
    end else begin
        pf_ap_return_2_U_frpsig_data_in = ap_return_2_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln129_reg_1466_pp0_iter10_reg == 1'd1))) begin
        pf_ap_return_3_U_frpsig_data_in = acc_184_fu_1001_p3;
    end else begin
        pf_ap_return_3_U_frpsig_data_in = ap_return_3_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln129_reg_1466_pp0_iter10_reg == 1'd1))) begin
        pf_ap_return_4_U_frpsig_data_in = acc_185_fu_1064_p3;
    end else begin
        pf_ap_return_4_U_frpsig_data_in = ap_return_4_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln129_reg_1466_pp0_iter10_reg == 1'd1))) begin
        pf_ap_return_5_U_frpsig_data_in = acc_186_fu_1057_p3;
    end else begin
        pf_ap_return_5_U_frpsig_data_in = ap_return_5_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln129_reg_1466_pp0_iter10_reg == 1'd1))) begin
        pf_ap_return_6_U_frpsig_data_in = acc_187_fu_1120_p3;
    end else begin
        pf_ap_return_6_U_frpsig_data_in = ap_return_6_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln129_reg_1466_pp0_iter10_reg == 1'd1))) begin
        pf_ap_return_7_U_frpsig_data_in = acc_188_fu_1113_p3;
    end else begin
        pf_ap_return_7_U_frpsig_data_in = ap_return_7_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln129_reg_1466_pp0_iter10_reg == 1'd1))) begin
        pf_ap_return_8_U_frpsig_data_in = acc_189_fu_1176_p3;
    end else begin
        pf_ap_return_8_U_frpsig_data_in = ap_return_8_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln129_reg_1466_pp0_iter10_reg == 1'd1))) begin
        pf_ap_return_9_U_frpsig_data_in = acc_190_fu_1169_p3;
    end else begin
        pf_ap_return_9_U_frpsig_data_in = ap_return_9_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        w2_86_ce0 = 1'b1;
    end else begin
        w2_86_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign a_fu_566_p1 = grp_fu_512_p2[31:0];

assign acc_158_fu_933_p3 = ((icmp_ln138_fu_906_p2[0:0] == 1'b1) ? select_ln138_2_fu_918_p3 : acc40_reg_224);

assign acc_159_fu_925_p3 = ((icmp_ln138_fu_906_p2[0:0] == 1'b1) ? select_ln138_1_fu_911_p3 : acc_14438_reg_239);

assign acc_160_fu_941_p2 = ($signed(trunc_ln_reg_1621) + $signed(select_ln138_reg_1627));

assign acc_161_fu_981_p3 = ((icmp_ln138_8_fu_962_p2[0:0] == 1'b1) ? select_ln138_6_fu_967_p3 : acc_14634_reg_269);

assign acc_162_fu_997_p2 = ($signed(trunc_ln138_8_reg_1637) + $signed(select_ln138_3_reg_1643));

assign acc_163_fu_1045_p3 = ((icmp_ln138_9_fu_1018_p2[0:0] == 1'b1) ? select_ln138_12_fu_1030_p3 : acc_14732_reg_284);

assign acc_164_fu_1037_p3 = ((icmp_ln138_9_fu_1018_p2[0:0] == 1'b1) ? select_ln138_11_fu_1023_p3 : acc_14830_reg_299);

assign acc_165_fu_1053_p2 = ($signed(trunc_ln138_9_reg_1653) + $signed(select_ln138_8_reg_1659));

assign acc_166_fu_1101_p3 = ((icmp_ln138_10_fu_1074_p2[0:0] == 1'b1) ? select_ln138_17_fu_1086_p3 : acc_14928_reg_314);

assign acc_167_fu_1093_p3 = ((icmp_ln138_10_fu_1074_p2[0:0] == 1'b1) ? select_ln138_16_fu_1079_p3 : acc_15026_reg_329);

assign acc_168_fu_1109_p2 = ($signed(trunc_ln138_s_reg_1669) + $signed(select_ln138_13_reg_1675));

assign acc_169_fu_1157_p3 = ((icmp_ln138_11_fu_1130_p2[0:0] == 1'b1) ? select_ln138_22_fu_1142_p3 : acc_15124_reg_344);

assign acc_170_fu_1149_p3 = ((icmp_ln138_11_fu_1130_p2[0:0] == 1'b1) ? select_ln138_21_fu_1135_p3 : acc_15222_reg_359);

assign acc_171_fu_1165_p2 = ($signed(trunc_ln138_1_reg_1685) + $signed(select_ln138_18_reg_1691));

assign acc_172_fu_1213_p3 = ((icmp_ln138_12_fu_1186_p2[0:0] == 1'b1) ? select_ln138_27_fu_1198_p3 : acc_15320_reg_374);

assign acc_173_fu_1205_p3 = ((icmp_ln138_12_fu_1186_p2[0:0] == 1'b1) ? select_ln138_26_fu_1191_p3 : acc_15418_reg_389);

assign acc_174_fu_1221_p2 = ($signed(trunc_ln138_2_reg_1701) + $signed(select_ln138_23_reg_1707));

assign acc_175_fu_1269_p3 = ((icmp_ln138_13_fu_1242_p2[0:0] == 1'b1) ? select_ln138_32_fu_1254_p3 : acc_15516_reg_404);

assign acc_176_fu_1261_p3 = ((icmp_ln138_13_fu_1242_p2[0:0] == 1'b1) ? select_ln138_31_fu_1247_p3 : acc_15614_reg_419);

assign acc_177_fu_1277_p2 = ($signed(trunc_ln138_3_reg_1717) + $signed(select_ln138_28_reg_1723));

assign acc_178_fu_1325_p3 = ((icmp_ln138_14_fu_1298_p2[0:0] == 1'b1) ? select_ln138_37_fu_1310_p3 : acc_15712_reg_434);

assign acc_179_fu_1317_p3 = ((icmp_ln138_14_fu_1298_p2[0:0] == 1'b1) ? select_ln138_36_fu_1303_p3 : acc_15810_reg_449);

assign acc_180_fu_1333_p2 = ($signed(trunc_ln138_4_reg_1733) + $signed(select_ln138_33_reg_1739));

assign acc_181_fu_952_p3 = ((out_index_reg_1480_pp0_iter10_reg[0:0] == 1'b1) ? acc_158_fu_933_p3 : acc_160_fu_941_p2);

assign acc_182_fu_945_p3 = ((out_index_reg_1480_pp0_iter10_reg[0:0] == 1'b1) ? acc_160_fu_941_p2 : acc_159_fu_925_p3);

assign acc_183_fu_1008_p3 = ((out_index_reg_1480_pp0_iter10_reg[0:0] == 1'b1) ? acc_fu_989_p3 : acc_162_fu_997_p2);

assign acc_184_fu_1001_p3 = ((out_index_reg_1480_pp0_iter10_reg[0:0] == 1'b1) ? acc_162_fu_997_p2 : acc_161_fu_981_p3);

assign acc_185_fu_1064_p3 = ((out_index_reg_1480_pp0_iter10_reg[0:0] == 1'b1) ? acc_163_fu_1045_p3 : acc_165_fu_1053_p2);

assign acc_186_fu_1057_p3 = ((out_index_reg_1480_pp0_iter10_reg[0:0] == 1'b1) ? acc_165_fu_1053_p2 : acc_164_fu_1037_p3);

assign acc_187_fu_1120_p3 = ((out_index_reg_1480_pp0_iter10_reg[0:0] == 1'b1) ? acc_166_fu_1101_p3 : acc_168_fu_1109_p2);

assign acc_188_fu_1113_p3 = ((out_index_reg_1480_pp0_iter10_reg[0:0] == 1'b1) ? acc_168_fu_1109_p2 : acc_167_fu_1093_p3);

assign acc_189_fu_1176_p3 = ((out_index_reg_1480_pp0_iter10_reg[0:0] == 1'b1) ? acc_169_fu_1157_p3 : acc_171_fu_1165_p2);

assign acc_190_fu_1169_p3 = ((out_index_reg_1480_pp0_iter10_reg[0:0] == 1'b1) ? acc_171_fu_1165_p2 : acc_170_fu_1149_p3);

assign acc_191_fu_1232_p3 = ((out_index_reg_1480_pp0_iter10_reg[0:0] == 1'b1) ? acc_172_fu_1213_p3 : acc_174_fu_1221_p2);

assign acc_192_fu_1225_p3 = ((out_index_reg_1480_pp0_iter10_reg[0:0] == 1'b1) ? acc_174_fu_1221_p2 : acc_173_fu_1205_p3);

assign acc_193_fu_1288_p3 = ((out_index_reg_1480_pp0_iter10_reg[0:0] == 1'b1) ? acc_175_fu_1269_p3 : acc_177_fu_1277_p2);

assign acc_194_fu_1281_p3 = ((out_index_reg_1480_pp0_iter10_reg[0:0] == 1'b1) ? acc_177_fu_1277_p2 : acc_176_fu_1261_p3);

assign acc_195_fu_1344_p3 = ((out_index_reg_1480_pp0_iter10_reg[0:0] == 1'b1) ? acc_178_fu_1325_p3 : acc_180_fu_1333_p2);

assign acc_196_fu_1337_p3 = ((out_index_reg_1480_pp0_iter10_reg[0:0] == 1'b1) ? acc_180_fu_1333_p2 : acc_179_fu_1317_p3);

assign acc_fu_989_p3 = ((icmp_ln138_8_fu_962_p2[0:0] == 1'b1) ? select_ln138_7_fu_974_p3 : acc_14536_reg_254);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = 1'b0;

assign ap_block_pp0_stage0_11001 = 1'b0;

assign ap_block_pp0_stage0_subdone = 1'b0;

assign ap_block_state10_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter11 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_done_reg == 1'b1) | ((ap_phi_mux_do_init_phi_fu_159_p6 == 1'd1) & (1'b1 == 1'b0)));
end

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_frp_pvb_no_bkwd_prs = ((pf_ap_return_15_U_pf_ready == 1'b1) & (pf_ap_return_14_U_pf_ready == 1'b1) & (pf_ap_return_13_U_pf_ready == 1'b1) & (pf_ap_return_12_U_pf_ready == 1'b1) & (pf_ap_return_11_U_pf_ready == 1'b1) & (pf_ap_return_10_U_pf_ready == 1'b1) & (pf_ap_return_9_U_pf_ready == 1'b1) & (pf_ap_return_8_U_pf_ready == 1'b1) & (pf_ap_return_7_U_pf_ready == 1'b1) & (pf_ap_return_6_U_pf_ready == 1'b1) & (pf_ap_return_5_U_pf_ready == 1'b1) & (pf_ap_return_4_U_pf_ready == 1'b1) & (pf_ap_return_3_U_pf_ready == 1'b1) & (pf_ap_return_2_U_pf_ready == 1'b1) & (pf_ap_return_1_U_pf_ready == 1'b1) & (pf_ap_return_0_U_pf_ready == 1'b1));
end

always @ (*) begin
    ap_condition_frp_pvb_no_fwd_prs = ~((ap_phi_mux_do_init_phi_fu_159_p6 == 1'd1) & (input_1_ap_vld == 1'b0));
end

always @ (*) begin
    ap_condition_frp_pvb_pf_start = ((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b1));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_phi_reg_pp0_iter0_input_1_load_phi_reg_211 = 'bx;

assign ap_return_0 = pf_ap_return_0_U_data_out;

assign ap_return_1 = pf_ap_return_1_U_data_out;

assign ap_return_10 = pf_ap_return_10_U_data_out;

assign ap_return_11 = pf_ap_return_11_U_data_out;

assign ap_return_12 = pf_ap_return_12_U_data_out;

assign ap_return_13 = pf_ap_return_13_U_data_out;

assign ap_return_14 = pf_ap_return_14_U_data_out;

assign ap_return_15 = pf_ap_return_15_U_data_out;

assign ap_return_2 = pf_ap_return_2_U_data_out;

assign ap_return_3 = pf_ap_return_3_U_data_out;

assign ap_return_4 = pf_ap_return_4_U_data_out;

assign ap_return_5 = pf_ap_return_5_U_data_out;

assign ap_return_6 = pf_ap_return_6_U_data_out;

assign ap_return_7 = pf_ap_return_7_U_data_out;

assign ap_return_8 = pf_ap_return_8_U_data_out;

assign ap_return_9 = pf_ap_return_9_U_data_out;

assign empty_fu_496_p1 = ap_phi_mux_in_index42_phi_fu_187_p6[5:0];

assign grp_fu_464_p0 = sext_ln73_fu_644_p1;

assign grp_fu_468_p1 = sext_ln73_fu_644_p1;

assign grp_fu_472_p1 = sext_ln73_fu_644_p1;

assign grp_fu_476_p1 = sext_ln73_fu_644_p1;

assign grp_fu_480_p1 = sext_ln73_fu_644_p1;

assign grp_fu_484_p1 = sext_ln73_fu_644_p1;

assign grp_fu_488_p1 = sext_ln73_fu_644_p1;

assign grp_fu_492_p1 = sext_ln73_fu_644_p1;

assign grp_fu_512_p1 = tmp_256_fu_500_p3;

assign icmp_ln129_fu_554_p2 = ((ap_phi_mux_w_index41_phi_fu_200_p6 == 7'd127) ? 1'b1 : 1'b0);

assign icmp_ln138_10_fu_1074_p2 = ((sext_ln138_22_fu_1071_p1 == sub_ln138_10_reg_1680) ? 1'b1 : 1'b0);

assign icmp_ln138_11_fu_1130_p2 = ((sext_ln138_24_fu_1127_p1 == sub_ln138_11_reg_1696) ? 1'b1 : 1'b0);

assign icmp_ln138_12_fu_1186_p2 = ((sext_ln138_26_fu_1183_p1 == sub_ln138_12_reg_1712) ? 1'b1 : 1'b0);

assign icmp_ln138_13_fu_1242_p2 = ((sext_ln138_28_fu_1239_p1 == sub_ln138_13_reg_1728) ? 1'b1 : 1'b0);

assign icmp_ln138_14_fu_1298_p2 = ((sext_ln138_30_fu_1295_p1 == sub_ln138_14_reg_1744) ? 1'b1 : 1'b0);

assign icmp_ln138_8_fu_962_p2 = ((sext_ln138_18_fu_959_p1 == sub_ln138_8_reg_1648) ? 1'b1 : 1'b0);

assign icmp_ln138_9_fu_1018_p2 = ((sext_ln138_20_fu_1015_p1 == sub_ln138_9_reg_1664) ? 1'b1 : 1'b0);

assign icmp_ln138_fu_906_p2 = ((sext_ln138_16_fu_903_p1 == sub_ln138_reg_1632) ? 1'b1 : 1'b0);

assign icmp_ln148_fu_534_p2 = (($signed(tmp_257_fu_524_p4) > $signed(26'd0)) ? 1'b1 : 1'b0);

assign in_index_2_fu_518_p2 = (ap_phi_mux_in_index42_phi_fu_187_p6 + 32'd1);

assign in_index_fu_540_p3 = ((icmp_ln148_fu_534_p2[0:0] == 1'b1) ? 32'd0 : in_index_2_fu_518_p2);

assign input_1_blk_n = 1'b1;

assign outidx_1_address0 = zext_ln129_fu_560_p1;

assign pf_all_done = (pf_ap_return_9_U_pf_done & pf_ap_return_8_U_pf_done & pf_ap_return_7_U_pf_done & pf_ap_return_6_U_pf_done & pf_ap_return_5_U_pf_done & pf_ap_return_4_U_pf_done & pf_ap_return_3_U_pf_done & pf_ap_return_2_U_pf_done & pf_ap_return_1_U_pf_done & pf_ap_return_15_U_pf_done & pf_ap_return_14_U_pf_done & pf_ap_return_13_U_pf_done & pf_ap_return_12_U_pf_done & pf_ap_return_11_U_pf_done & pf_ap_return_10_U_pf_done & pf_ap_return_0_U_pf_done);

assign pf_data_in_last = ap_done_int_frp;

assign pf_sync_continue = (pf_all_done & ap_continue_int);

assign select_ln138_11_fu_1023_p3 = ((out_index_reg_1480_pp0_iter10_reg[0:0] == 1'b1) ? 32'd0 : acc_14830_reg_299);

assign select_ln138_12_fu_1030_p3 = ((out_index_reg_1480_pp0_iter10_reg[0:0] == 1'b1) ? acc_14732_reg_284 : 32'd0);

assign select_ln138_13_fu_778_p3 = ((out_index_reg_1480_pp0_iter9_reg[0:0] == 1'b1) ? ap_phi_mux_acc_15026_phi_fu_333_p6 : ap_phi_mux_acc_14928_phi_fu_318_p6);

assign select_ln138_16_fu_1079_p3 = ((out_index_reg_1480_pp0_iter10_reg[0:0] == 1'b1) ? 32'd0 : acc_15026_reg_329);

assign select_ln138_17_fu_1086_p3 = ((out_index_reg_1480_pp0_iter10_reg[0:0] == 1'b1) ? acc_14928_reg_314 : 32'd0);

assign select_ln138_18_fu_805_p3 = ((out_index_reg_1480_pp0_iter9_reg[0:0] == 1'b1) ? ap_phi_mux_acc_15222_phi_fu_363_p6 : ap_phi_mux_acc_15124_phi_fu_348_p6);

assign select_ln138_1_fu_911_p3 = ((out_index_reg_1480_pp0_iter10_reg[0:0] == 1'b1) ? 32'd0 : acc_14438_reg_239);

assign select_ln138_21_fu_1135_p3 = ((out_index_reg_1480_pp0_iter10_reg[0:0] == 1'b1) ? 32'd0 : acc_15222_reg_359);

assign select_ln138_22_fu_1142_p3 = ((out_index_reg_1480_pp0_iter10_reg[0:0] == 1'b1) ? acc_15124_reg_344 : 32'd0);

assign select_ln138_23_fu_832_p3 = ((out_index_reg_1480_pp0_iter9_reg[0:0] == 1'b1) ? ap_phi_mux_acc_15418_phi_fu_393_p6 : ap_phi_mux_acc_15320_phi_fu_378_p6);

assign select_ln138_26_fu_1191_p3 = ((out_index_reg_1480_pp0_iter10_reg[0:0] == 1'b1) ? 32'd0 : acc_15418_reg_389);

assign select_ln138_27_fu_1198_p3 = ((out_index_reg_1480_pp0_iter10_reg[0:0] == 1'b1) ? acc_15320_reg_374 : 32'd0);

assign select_ln138_28_fu_859_p3 = ((out_index_reg_1480_pp0_iter9_reg[0:0] == 1'b1) ? ap_phi_mux_acc_15614_phi_fu_423_p6 : ap_phi_mux_acc_15516_phi_fu_408_p6);

assign select_ln138_2_fu_918_p3 = ((out_index_reg_1480_pp0_iter10_reg[0:0] == 1'b1) ? acc40_reg_224 : 32'd0);

assign select_ln138_31_fu_1247_p3 = ((out_index_reg_1480_pp0_iter10_reg[0:0] == 1'b1) ? 32'd0 : acc_15614_reg_419);

assign select_ln138_32_fu_1254_p3 = ((out_index_reg_1480_pp0_iter10_reg[0:0] == 1'b1) ? acc_15516_reg_404 : 32'd0);

assign select_ln138_33_fu_886_p3 = ((out_index_reg_1480_pp0_iter9_reg[0:0] == 1'b1) ? ap_phi_mux_acc_15810_phi_fu_453_p6 : ap_phi_mux_acc_15712_phi_fu_438_p6);

assign select_ln138_36_fu_1303_p3 = ((out_index_reg_1480_pp0_iter10_reg[0:0] == 1'b1) ? 32'd0 : acc_15810_reg_449);

assign select_ln138_37_fu_1310_p3 = ((out_index_reg_1480_pp0_iter10_reg[0:0] == 1'b1) ? acc_15712_reg_434 : 32'd0);

assign select_ln138_3_fu_724_p3 = ((out_index_reg_1480_pp0_iter9_reg[0:0] == 1'b1) ? ap_phi_mux_acc_14634_phi_fu_273_p6 : ap_phi_mux_acc_14536_phi_fu_258_p6);

assign select_ln138_6_fu_967_p3 = ((out_index_reg_1480_pp0_iter10_reg[0:0] == 1'b1) ? 32'd0 : acc_14634_reg_269);

assign select_ln138_7_fu_974_p3 = ((out_index_reg_1480_pp0_iter10_reg[0:0] == 1'b1) ? acc_14536_reg_254 : 32'd0);

assign select_ln138_8_fu_751_p3 = ((out_index_reg_1480_pp0_iter9_reg[0:0] == 1'b1) ? ap_phi_mux_acc_14830_phi_fu_303_p6 : ap_phi_mux_acc_14732_phi_fu_288_p6);

assign select_ln138_fu_697_p3 = ((out_index_reg_1480_pp0_iter9_reg[0:0] == 1'b1) ? ap_phi_mux_acc_14438_phi_fu_243_p6 : ap_phi_mux_acc40_phi_fu_228_p6);

assign sext_ln138_16_fu_903_p1 = trunc_ln_reg_1621;

assign sext_ln138_17_fu_731_p1 = select_ln138_3_fu_724_p3;

assign sext_ln138_18_fu_959_p1 = trunc_ln138_8_reg_1637;

assign sext_ln138_19_fu_758_p1 = select_ln138_8_fu_751_p3;

assign sext_ln138_20_fu_1015_p1 = trunc_ln138_9_reg_1653;

assign sext_ln138_21_fu_785_p1 = select_ln138_13_fu_778_p3;

assign sext_ln138_22_fu_1071_p1 = trunc_ln138_s_reg_1669;

assign sext_ln138_23_fu_812_p1 = select_ln138_18_fu_805_p3;

assign sext_ln138_24_fu_1127_p1 = trunc_ln138_1_reg_1685;

assign sext_ln138_25_fu_839_p1 = select_ln138_23_fu_832_p3;

assign sext_ln138_26_fu_1183_p1 = trunc_ln138_2_reg_1701;

assign sext_ln138_27_fu_866_p1 = select_ln138_28_fu_859_p3;

assign sext_ln138_28_fu_1239_p1 = trunc_ln138_3_reg_1717;

assign sext_ln138_29_fu_893_p1 = select_ln138_33_fu_886_p3;

assign sext_ln138_30_fu_1295_p1 = trunc_ln138_4_reg_1733;

assign sext_ln138_fu_704_p1 = select_ln138_fu_697_p3;

assign sext_ln73_fu_644_p1 = $signed(a_reg_1524);

assign sub_ln138_10_fu_789_p2 = ($signed(33'd0) - $signed(sext_ln138_21_fu_785_p1));

assign sub_ln138_11_fu_816_p2 = ($signed(33'd0) - $signed(sext_ln138_23_fu_812_p1));

assign sub_ln138_12_fu_843_p2 = ($signed(33'd0) - $signed(sext_ln138_25_fu_839_p1));

assign sub_ln138_13_fu_870_p2 = ($signed(33'd0) - $signed(sext_ln138_27_fu_866_p1));

assign sub_ln138_14_fu_897_p2 = ($signed(33'd0) - $signed(sext_ln138_29_fu_893_p1));

assign sub_ln138_8_fu_735_p2 = ($signed(33'd0) - $signed(sext_ln138_17_fu_731_p1));

assign sub_ln138_9_fu_762_p2 = ($signed(33'd0) - $signed(sext_ln138_19_fu_758_p1));

assign sub_ln138_fu_708_p2 = ($signed(33'd0) - $signed(sext_ln138_fu_704_p1));

assign tmp_256_fu_500_p3 = {{empty_fu_496_p1}, {5'd0}};

assign tmp_257_fu_524_p4 = {{in_index_2_fu_518_p2[31:6]}};

assign w2_86_address0 = zext_ln129_fu_560_p1;

assign w_fu_570_p1 = w2_86_q0[31:0];

assign w_index_fu_548_p2 = (ap_phi_mux_w_index41_phi_fu_200_p6 + 7'd1);

assign zext_ln129_fu_560_p1 = w_index41_reg_197_pp0_iter3_reg;

endmodule //myproject_dense_resource_ap_fixed_32_6_5_3_0_ap_fixed_32_6_5_3_0_config2_s
