-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity tiny_autoencoder is
port (
    input_data_0_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    input_data_0_ce0 : OUT STD_LOGIC;
    input_data_0_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    input_data_0_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    input_data_0_we0 : OUT STD_LOGIC;
    input_data_0_address1 : OUT STD_LOGIC_VECTOR (2 downto 0);
    input_data_0_ce1 : OUT STD_LOGIC;
    input_data_0_d1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    input_data_0_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
    input_data_0_we1 : OUT STD_LOGIC;
    input_data_1_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    input_data_1_ce0 : OUT STD_LOGIC;
    input_data_1_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    input_data_1_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    input_data_1_we0 : OUT STD_LOGIC;
    input_data_1_address1 : OUT STD_LOGIC_VECTOR (2 downto 0);
    input_data_1_ce1 : OUT STD_LOGIC;
    input_data_1_d1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    input_data_1_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
    input_data_1_we1 : OUT STD_LOGIC;
    input_data_2_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    input_data_2_ce0 : OUT STD_LOGIC;
    input_data_2_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    input_data_2_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    input_data_2_we0 : OUT STD_LOGIC;
    input_data_2_address1 : OUT STD_LOGIC_VECTOR (2 downto 0);
    input_data_2_ce1 : OUT STD_LOGIC;
    input_data_2_d1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    input_data_2_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
    input_data_2_we1 : OUT STD_LOGIC;
    input_data_3_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    input_data_3_ce0 : OUT STD_LOGIC;
    input_data_3_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    input_data_3_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    input_data_3_we0 : OUT STD_LOGIC;
    input_data_3_address1 : OUT STD_LOGIC_VECTOR (2 downto 0);
    input_data_3_ce1 : OUT STD_LOGIC;
    input_data_3_d1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    input_data_3_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
    input_data_3_we1 : OUT STD_LOGIC;
    input_data_4_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    input_data_4_ce0 : OUT STD_LOGIC;
    input_data_4_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    input_data_4_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    input_data_4_we0 : OUT STD_LOGIC;
    input_data_4_address1 : OUT STD_LOGIC_VECTOR (2 downto 0);
    input_data_4_ce1 : OUT STD_LOGIC;
    input_data_4_d1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    input_data_4_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
    input_data_4_we1 : OUT STD_LOGIC;
    input_data_5_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    input_data_5_ce0 : OUT STD_LOGIC;
    input_data_5_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    input_data_5_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    input_data_5_we0 : OUT STD_LOGIC;
    input_data_5_address1 : OUT STD_LOGIC_VECTOR (2 downto 0);
    input_data_5_ce1 : OUT STD_LOGIC;
    input_data_5_d1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    input_data_5_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
    input_data_5_we1 : OUT STD_LOGIC;
    input_data_6_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    input_data_6_ce0 : OUT STD_LOGIC;
    input_data_6_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    input_data_6_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    input_data_6_we0 : OUT STD_LOGIC;
    input_data_6_address1 : OUT STD_LOGIC_VECTOR (2 downto 0);
    input_data_6_ce1 : OUT STD_LOGIC;
    input_data_6_d1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    input_data_6_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
    input_data_6_we1 : OUT STD_LOGIC;
    input_data_7_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    input_data_7_ce0 : OUT STD_LOGIC;
    input_data_7_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    input_data_7_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    input_data_7_we0 : OUT STD_LOGIC;
    input_data_7_address1 : OUT STD_LOGIC_VECTOR (2 downto 0);
    input_data_7_ce1 : OUT STD_LOGIC;
    input_data_7_d1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    input_data_7_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
    input_data_7_we1 : OUT STD_LOGIC;
    output_data_0_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    output_data_0_ce0 : OUT STD_LOGIC;
    output_data_0_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    output_data_0_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    output_data_0_we0 : OUT STD_LOGIC;
    output_data_0_address1 : OUT STD_LOGIC_VECTOR (2 downto 0);
    output_data_0_ce1 : OUT STD_LOGIC;
    output_data_0_d1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    output_data_0_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
    output_data_0_we1 : OUT STD_LOGIC;
    output_data_1_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    output_data_1_ce0 : OUT STD_LOGIC;
    output_data_1_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    output_data_1_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    output_data_1_we0 : OUT STD_LOGIC;
    output_data_1_address1 : OUT STD_LOGIC_VECTOR (2 downto 0);
    output_data_1_ce1 : OUT STD_LOGIC;
    output_data_1_d1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    output_data_1_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
    output_data_1_we1 : OUT STD_LOGIC;
    output_data_2_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    output_data_2_ce0 : OUT STD_LOGIC;
    output_data_2_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    output_data_2_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    output_data_2_we0 : OUT STD_LOGIC;
    output_data_2_address1 : OUT STD_LOGIC_VECTOR (2 downto 0);
    output_data_2_ce1 : OUT STD_LOGIC;
    output_data_2_d1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    output_data_2_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
    output_data_2_we1 : OUT STD_LOGIC;
    output_data_3_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    output_data_3_ce0 : OUT STD_LOGIC;
    output_data_3_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    output_data_3_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    output_data_3_we0 : OUT STD_LOGIC;
    output_data_3_address1 : OUT STD_LOGIC_VECTOR (2 downto 0);
    output_data_3_ce1 : OUT STD_LOGIC;
    output_data_3_d1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    output_data_3_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
    output_data_3_we1 : OUT STD_LOGIC;
    output_data_4_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    output_data_4_ce0 : OUT STD_LOGIC;
    output_data_4_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    output_data_4_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    output_data_4_we0 : OUT STD_LOGIC;
    output_data_4_address1 : OUT STD_LOGIC_VECTOR (2 downto 0);
    output_data_4_ce1 : OUT STD_LOGIC;
    output_data_4_d1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    output_data_4_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
    output_data_4_we1 : OUT STD_LOGIC;
    output_data_5_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    output_data_5_ce0 : OUT STD_LOGIC;
    output_data_5_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    output_data_5_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    output_data_5_we0 : OUT STD_LOGIC;
    output_data_5_address1 : OUT STD_LOGIC_VECTOR (2 downto 0);
    output_data_5_ce1 : OUT STD_LOGIC;
    output_data_5_d1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    output_data_5_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
    output_data_5_we1 : OUT STD_LOGIC;
    output_data_6_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    output_data_6_ce0 : OUT STD_LOGIC;
    output_data_6_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    output_data_6_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    output_data_6_we0 : OUT STD_LOGIC;
    output_data_6_address1 : OUT STD_LOGIC_VECTOR (2 downto 0);
    output_data_6_ce1 : OUT STD_LOGIC;
    output_data_6_d1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    output_data_6_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
    output_data_6_we1 : OUT STD_LOGIC;
    output_data_7_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    output_data_7_ce0 : OUT STD_LOGIC;
    output_data_7_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    output_data_7_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    output_data_7_we0 : OUT STD_LOGIC;
    output_data_7_address1 : OUT STD_LOGIC_VECTOR (2 downto 0);
    output_data_7_ce1 : OUT STD_LOGIC;
    output_data_7_d1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    output_data_7_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
    output_data_7_we1 : OUT STD_LOGIC;
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC );
end;


architecture behav of tiny_autoencoder is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "tiny_autoencoder_tiny_autoencoder,hls_ip_2025_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=9.628000,HLS_SYN_LAT=45,HLS_SYN_TPT=8,HLS_SYN_MEM=4,HLS_SYN_DSP=0,HLS_SYN_FF=12733,HLS_SYN_LUT=41793,HLS_VERSION=2025_1}";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal compute_encoder_U0_ap_start : STD_LOGIC;
    signal compute_encoder_U0_ap_done : STD_LOGIC;
    signal compute_encoder_U0_ap_continue : STD_LOGIC;
    signal compute_encoder_U0_ap_idle : STD_LOGIC;
    signal compute_encoder_U0_ap_ready : STD_LOGIC;
    signal compute_encoder_U0_input_data_0_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal compute_encoder_U0_input_data_0_ce0 : STD_LOGIC;
    signal compute_encoder_U0_input_data_1_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal compute_encoder_U0_input_data_1_ce0 : STD_LOGIC;
    signal compute_encoder_U0_input_data_2_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal compute_encoder_U0_input_data_2_ce0 : STD_LOGIC;
    signal compute_encoder_U0_input_data_3_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal compute_encoder_U0_input_data_3_ce0 : STD_LOGIC;
    signal compute_encoder_U0_input_data_4_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal compute_encoder_U0_input_data_4_ce0 : STD_LOGIC;
    signal compute_encoder_U0_input_data_5_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal compute_encoder_U0_input_data_5_ce0 : STD_LOGIC;
    signal compute_encoder_U0_input_data_6_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal compute_encoder_U0_input_data_6_ce0 : STD_LOGIC;
    signal compute_encoder_U0_input_data_7_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal compute_encoder_U0_input_data_7_ce0 : STD_LOGIC;
    signal compute_encoder_U0_ap_return_0 : STD_LOGIC_VECTOR (15 downto 0);
    signal compute_encoder_U0_ap_return_1 : STD_LOGIC_VECTOR (15 downto 0);
    signal compute_encoder_U0_ap_return_2 : STD_LOGIC_VECTOR (15 downto 0);
    signal compute_encoder_U0_ap_return_3 : STD_LOGIC_VECTOR (15 downto 0);
    signal compute_encoder_U0_ap_return_4 : STD_LOGIC_VECTOR (15 downto 0);
    signal compute_encoder_U0_ap_return_5 : STD_LOGIC_VECTOR (15 downto 0);
    signal compute_encoder_U0_ap_return_6 : STD_LOGIC_VECTOR (15 downto 0);
    signal compute_encoder_U0_ap_return_7 : STD_LOGIC_VECTOR (15 downto 0);
    signal compute_encoder_U0_ap_return_8 : STD_LOGIC_VECTOR (15 downto 0);
    signal compute_encoder_U0_ap_return_9 : STD_LOGIC_VECTOR (15 downto 0);
    signal compute_encoder_U0_ap_return_10 : STD_LOGIC_VECTOR (15 downto 0);
    signal compute_encoder_U0_ap_return_11 : STD_LOGIC_VECTOR (15 downto 0);
    signal compute_encoder_U0_ap_return_12 : STD_LOGIC_VECTOR (15 downto 0);
    signal compute_encoder_U0_ap_return_13 : STD_LOGIC_VECTOR (15 downto 0);
    signal compute_encoder_U0_ap_return_14 : STD_LOGIC_VECTOR (15 downto 0);
    signal compute_encoder_U0_ap_return_15 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_channel_done_hidden_layer_buf_15 : STD_LOGIC;
    signal hidden_layer_buf_15_full_n : STD_LOGIC;
    signal ap_sync_reg_channel_write_hidden_layer_buf_15 : STD_LOGIC := '0';
    signal ap_sync_channel_write_hidden_layer_buf_15 : STD_LOGIC;
    signal compute_decoder_U0_ap_start : STD_LOGIC;
    signal compute_decoder_U0_ap_done : STD_LOGIC;
    signal compute_decoder_U0_ap_continue : STD_LOGIC;
    signal compute_decoder_U0_ap_idle : STD_LOGIC;
    signal compute_decoder_U0_ap_ready : STD_LOGIC;
    signal compute_decoder_U0_output_data_0_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal compute_decoder_U0_output_data_0_ce0 : STD_LOGIC;
    signal compute_decoder_U0_output_data_0_we0 : STD_LOGIC;
    signal compute_decoder_U0_output_data_0_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal compute_decoder_U0_output_data_1_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal compute_decoder_U0_output_data_1_ce0 : STD_LOGIC;
    signal compute_decoder_U0_output_data_1_we0 : STD_LOGIC;
    signal compute_decoder_U0_output_data_1_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal compute_decoder_U0_output_data_2_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal compute_decoder_U0_output_data_2_ce0 : STD_LOGIC;
    signal compute_decoder_U0_output_data_2_we0 : STD_LOGIC;
    signal compute_decoder_U0_output_data_2_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal compute_decoder_U0_output_data_3_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal compute_decoder_U0_output_data_3_ce0 : STD_LOGIC;
    signal compute_decoder_U0_output_data_3_we0 : STD_LOGIC;
    signal compute_decoder_U0_output_data_3_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal compute_decoder_U0_output_data_4_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal compute_decoder_U0_output_data_4_ce0 : STD_LOGIC;
    signal compute_decoder_U0_output_data_4_we0 : STD_LOGIC;
    signal compute_decoder_U0_output_data_4_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal compute_decoder_U0_output_data_5_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal compute_decoder_U0_output_data_5_ce0 : STD_LOGIC;
    signal compute_decoder_U0_output_data_5_we0 : STD_LOGIC;
    signal compute_decoder_U0_output_data_5_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal compute_decoder_U0_output_data_6_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal compute_decoder_U0_output_data_6_ce0 : STD_LOGIC;
    signal compute_decoder_U0_output_data_6_we0 : STD_LOGIC;
    signal compute_decoder_U0_output_data_6_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal compute_decoder_U0_output_data_7_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal compute_decoder_U0_output_data_7_ce0 : STD_LOGIC;
    signal compute_decoder_U0_output_data_7_we0 : STD_LOGIC;
    signal compute_decoder_U0_output_data_7_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal hidden_layer_buf_full_n : STD_LOGIC;
    signal hidden_layer_buf_dout : STD_LOGIC_VECTOR (15 downto 0);
    signal hidden_layer_buf_empty_n : STD_LOGIC;
    signal hidden_layer_buf_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal hidden_layer_buf_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal hidden_layer_buf_1_full_n : STD_LOGIC;
    signal hidden_layer_buf_1_dout : STD_LOGIC_VECTOR (15 downto 0);
    signal hidden_layer_buf_1_empty_n : STD_LOGIC;
    signal hidden_layer_buf_1_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal hidden_layer_buf_1_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal hidden_layer_buf_2_full_n : STD_LOGIC;
    signal hidden_layer_buf_2_dout : STD_LOGIC_VECTOR (15 downto 0);
    signal hidden_layer_buf_2_empty_n : STD_LOGIC;
    signal hidden_layer_buf_2_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal hidden_layer_buf_2_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal hidden_layer_buf_3_full_n : STD_LOGIC;
    signal hidden_layer_buf_3_dout : STD_LOGIC_VECTOR (15 downto 0);
    signal hidden_layer_buf_3_empty_n : STD_LOGIC;
    signal hidden_layer_buf_3_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal hidden_layer_buf_3_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal hidden_layer_buf_4_full_n : STD_LOGIC;
    signal hidden_layer_buf_4_dout : STD_LOGIC_VECTOR (15 downto 0);
    signal hidden_layer_buf_4_empty_n : STD_LOGIC;
    signal hidden_layer_buf_4_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal hidden_layer_buf_4_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal hidden_layer_buf_5_full_n : STD_LOGIC;
    signal hidden_layer_buf_5_dout : STD_LOGIC_VECTOR (15 downto 0);
    signal hidden_layer_buf_5_empty_n : STD_LOGIC;
    signal hidden_layer_buf_5_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal hidden_layer_buf_5_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal hidden_layer_buf_6_full_n : STD_LOGIC;
    signal hidden_layer_buf_6_dout : STD_LOGIC_VECTOR (15 downto 0);
    signal hidden_layer_buf_6_empty_n : STD_LOGIC;
    signal hidden_layer_buf_6_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal hidden_layer_buf_6_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal hidden_layer_buf_7_full_n : STD_LOGIC;
    signal hidden_layer_buf_7_dout : STD_LOGIC_VECTOR (15 downto 0);
    signal hidden_layer_buf_7_empty_n : STD_LOGIC;
    signal hidden_layer_buf_7_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal hidden_layer_buf_7_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal hidden_layer_buf_8_full_n : STD_LOGIC;
    signal hidden_layer_buf_8_dout : STD_LOGIC_VECTOR (15 downto 0);
    signal hidden_layer_buf_8_empty_n : STD_LOGIC;
    signal hidden_layer_buf_8_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal hidden_layer_buf_8_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal hidden_layer_buf_9_full_n : STD_LOGIC;
    signal hidden_layer_buf_9_dout : STD_LOGIC_VECTOR (15 downto 0);
    signal hidden_layer_buf_9_empty_n : STD_LOGIC;
    signal hidden_layer_buf_9_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal hidden_layer_buf_9_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal hidden_layer_buf_10_full_n : STD_LOGIC;
    signal hidden_layer_buf_10_dout : STD_LOGIC_VECTOR (15 downto 0);
    signal hidden_layer_buf_10_empty_n : STD_LOGIC;
    signal hidden_layer_buf_10_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal hidden_layer_buf_10_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal hidden_layer_buf_11_full_n : STD_LOGIC;
    signal hidden_layer_buf_11_dout : STD_LOGIC_VECTOR (15 downto 0);
    signal hidden_layer_buf_11_empty_n : STD_LOGIC;
    signal hidden_layer_buf_11_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal hidden_layer_buf_11_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal hidden_layer_buf_12_full_n : STD_LOGIC;
    signal hidden_layer_buf_12_dout : STD_LOGIC_VECTOR (15 downto 0);
    signal hidden_layer_buf_12_empty_n : STD_LOGIC;
    signal hidden_layer_buf_12_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal hidden_layer_buf_12_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal hidden_layer_buf_13_full_n : STD_LOGIC;
    signal hidden_layer_buf_13_dout : STD_LOGIC_VECTOR (15 downto 0);
    signal hidden_layer_buf_13_empty_n : STD_LOGIC;
    signal hidden_layer_buf_13_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal hidden_layer_buf_13_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal hidden_layer_buf_14_full_n : STD_LOGIC;
    signal hidden_layer_buf_14_dout : STD_LOGIC_VECTOR (15 downto 0);
    signal hidden_layer_buf_14_empty_n : STD_LOGIC;
    signal hidden_layer_buf_14_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal hidden_layer_buf_14_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal hidden_layer_buf_15_dout : STD_LOGIC_VECTOR (15 downto 0);
    signal hidden_layer_buf_15_empty_n : STD_LOGIC;
    signal hidden_layer_buf_15_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal hidden_layer_buf_15_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component tiny_autoencoder_compute_encoder IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        input_data_0_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        input_data_0_ce0 : OUT STD_LOGIC;
        input_data_0_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_data_1_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        input_data_1_ce0 : OUT STD_LOGIC;
        input_data_1_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_data_2_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        input_data_2_ce0 : OUT STD_LOGIC;
        input_data_2_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_data_3_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        input_data_3_ce0 : OUT STD_LOGIC;
        input_data_3_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_data_4_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        input_data_4_ce0 : OUT STD_LOGIC;
        input_data_4_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_data_5_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        input_data_5_ce0 : OUT STD_LOGIC;
        input_data_5_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_data_6_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        input_data_6_ce0 : OUT STD_LOGIC;
        input_data_6_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_data_7_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        input_data_7_ce0 : OUT STD_LOGIC;
        input_data_7_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_3 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_4 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_5 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_6 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_7 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_8 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_9 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_10 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_11 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_12 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_13 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_14 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_15 : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component tiny_autoencoder_compute_decoder IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        p_read : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read1 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read2 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read3 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read4 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read5 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read6 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read7 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read8 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read9 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read10 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read11 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read12 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read13 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read14 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read15 : IN STD_LOGIC_VECTOR (15 downto 0);
        output_data_0_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        output_data_0_ce0 : OUT STD_LOGIC;
        output_data_0_we0 : OUT STD_LOGIC;
        output_data_0_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        output_data_1_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        output_data_1_ce0 : OUT STD_LOGIC;
        output_data_1_we0 : OUT STD_LOGIC;
        output_data_1_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        output_data_2_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        output_data_2_ce0 : OUT STD_LOGIC;
        output_data_2_we0 : OUT STD_LOGIC;
        output_data_2_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        output_data_3_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        output_data_3_ce0 : OUT STD_LOGIC;
        output_data_3_we0 : OUT STD_LOGIC;
        output_data_3_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        output_data_4_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        output_data_4_ce0 : OUT STD_LOGIC;
        output_data_4_we0 : OUT STD_LOGIC;
        output_data_4_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        output_data_5_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        output_data_5_ce0 : OUT STD_LOGIC;
        output_data_5_we0 : OUT STD_LOGIC;
        output_data_5_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        output_data_6_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        output_data_6_ce0 : OUT STD_LOGIC;
        output_data_6_we0 : OUT STD_LOGIC;
        output_data_6_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        output_data_7_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        output_data_7_ce0 : OUT STD_LOGIC;
        output_data_7_we0 : OUT STD_LOGIC;
        output_data_7_d0 : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component tiny_autoencoder_fifo_w16_d2_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (15 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (15 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC;
        if_num_data_valid : OUT STD_LOGIC_VECTOR (2 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (2 downto 0) );
    end component;



begin
    compute_encoder_U0 : component tiny_autoencoder_compute_encoder
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => compute_encoder_U0_ap_start,
        ap_done => compute_encoder_U0_ap_done,
        ap_continue => compute_encoder_U0_ap_continue,
        ap_idle => compute_encoder_U0_ap_idle,
        ap_ready => compute_encoder_U0_ap_ready,
        input_data_0_address0 => compute_encoder_U0_input_data_0_address0,
        input_data_0_ce0 => compute_encoder_U0_input_data_0_ce0,
        input_data_0_q0 => input_data_0_q0,
        input_data_1_address0 => compute_encoder_U0_input_data_1_address0,
        input_data_1_ce0 => compute_encoder_U0_input_data_1_ce0,
        input_data_1_q0 => input_data_1_q0,
        input_data_2_address0 => compute_encoder_U0_input_data_2_address0,
        input_data_2_ce0 => compute_encoder_U0_input_data_2_ce0,
        input_data_2_q0 => input_data_2_q0,
        input_data_3_address0 => compute_encoder_U0_input_data_3_address0,
        input_data_3_ce0 => compute_encoder_U0_input_data_3_ce0,
        input_data_3_q0 => input_data_3_q0,
        input_data_4_address0 => compute_encoder_U0_input_data_4_address0,
        input_data_4_ce0 => compute_encoder_U0_input_data_4_ce0,
        input_data_4_q0 => input_data_4_q0,
        input_data_5_address0 => compute_encoder_U0_input_data_5_address0,
        input_data_5_ce0 => compute_encoder_U0_input_data_5_ce0,
        input_data_5_q0 => input_data_5_q0,
        input_data_6_address0 => compute_encoder_U0_input_data_6_address0,
        input_data_6_ce0 => compute_encoder_U0_input_data_6_ce0,
        input_data_6_q0 => input_data_6_q0,
        input_data_7_address0 => compute_encoder_U0_input_data_7_address0,
        input_data_7_ce0 => compute_encoder_U0_input_data_7_ce0,
        input_data_7_q0 => input_data_7_q0,
        ap_return_0 => compute_encoder_U0_ap_return_0,
        ap_return_1 => compute_encoder_U0_ap_return_1,
        ap_return_2 => compute_encoder_U0_ap_return_2,
        ap_return_3 => compute_encoder_U0_ap_return_3,
        ap_return_4 => compute_encoder_U0_ap_return_4,
        ap_return_5 => compute_encoder_U0_ap_return_5,
        ap_return_6 => compute_encoder_U0_ap_return_6,
        ap_return_7 => compute_encoder_U0_ap_return_7,
        ap_return_8 => compute_encoder_U0_ap_return_8,
        ap_return_9 => compute_encoder_U0_ap_return_9,
        ap_return_10 => compute_encoder_U0_ap_return_10,
        ap_return_11 => compute_encoder_U0_ap_return_11,
        ap_return_12 => compute_encoder_U0_ap_return_12,
        ap_return_13 => compute_encoder_U0_ap_return_13,
        ap_return_14 => compute_encoder_U0_ap_return_14,
        ap_return_15 => compute_encoder_U0_ap_return_15);

    compute_decoder_U0 : component tiny_autoencoder_compute_decoder
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => compute_decoder_U0_ap_start,
        ap_done => compute_decoder_U0_ap_done,
        ap_continue => compute_decoder_U0_ap_continue,
        ap_idle => compute_decoder_U0_ap_idle,
        ap_ready => compute_decoder_U0_ap_ready,
        p_read => hidden_layer_buf_dout,
        p_read1 => hidden_layer_buf_1_dout,
        p_read2 => hidden_layer_buf_2_dout,
        p_read3 => hidden_layer_buf_3_dout,
        p_read4 => hidden_layer_buf_4_dout,
        p_read5 => hidden_layer_buf_5_dout,
        p_read6 => hidden_layer_buf_6_dout,
        p_read7 => hidden_layer_buf_7_dout,
        p_read8 => hidden_layer_buf_8_dout,
        p_read9 => hidden_layer_buf_9_dout,
        p_read10 => hidden_layer_buf_10_dout,
        p_read11 => hidden_layer_buf_11_dout,
        p_read12 => hidden_layer_buf_12_dout,
        p_read13 => hidden_layer_buf_13_dout,
        p_read14 => hidden_layer_buf_14_dout,
        p_read15 => hidden_layer_buf_15_dout,
        output_data_0_address0 => compute_decoder_U0_output_data_0_address0,
        output_data_0_ce0 => compute_decoder_U0_output_data_0_ce0,
        output_data_0_we0 => compute_decoder_U0_output_data_0_we0,
        output_data_0_d0 => compute_decoder_U0_output_data_0_d0,
        output_data_1_address0 => compute_decoder_U0_output_data_1_address0,
        output_data_1_ce0 => compute_decoder_U0_output_data_1_ce0,
        output_data_1_we0 => compute_decoder_U0_output_data_1_we0,
        output_data_1_d0 => compute_decoder_U0_output_data_1_d0,
        output_data_2_address0 => compute_decoder_U0_output_data_2_address0,
        output_data_2_ce0 => compute_decoder_U0_output_data_2_ce0,
        output_data_2_we0 => compute_decoder_U0_output_data_2_we0,
        output_data_2_d0 => compute_decoder_U0_output_data_2_d0,
        output_data_3_address0 => compute_decoder_U0_output_data_3_address0,
        output_data_3_ce0 => compute_decoder_U0_output_data_3_ce0,
        output_data_3_we0 => compute_decoder_U0_output_data_3_we0,
        output_data_3_d0 => compute_decoder_U0_output_data_3_d0,
        output_data_4_address0 => compute_decoder_U0_output_data_4_address0,
        output_data_4_ce0 => compute_decoder_U0_output_data_4_ce0,
        output_data_4_we0 => compute_decoder_U0_output_data_4_we0,
        output_data_4_d0 => compute_decoder_U0_output_data_4_d0,
        output_data_5_address0 => compute_decoder_U0_output_data_5_address0,
        output_data_5_ce0 => compute_decoder_U0_output_data_5_ce0,
        output_data_5_we0 => compute_decoder_U0_output_data_5_we0,
        output_data_5_d0 => compute_decoder_U0_output_data_5_d0,
        output_data_6_address0 => compute_decoder_U0_output_data_6_address0,
        output_data_6_ce0 => compute_decoder_U0_output_data_6_ce0,
        output_data_6_we0 => compute_decoder_U0_output_data_6_we0,
        output_data_6_d0 => compute_decoder_U0_output_data_6_d0,
        output_data_7_address0 => compute_decoder_U0_output_data_7_address0,
        output_data_7_ce0 => compute_decoder_U0_output_data_7_ce0,
        output_data_7_we0 => compute_decoder_U0_output_data_7_we0,
        output_data_7_d0 => compute_decoder_U0_output_data_7_d0);

    hidden_layer_buf_U : component tiny_autoencoder_fifo_w16_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => compute_encoder_U0_ap_return_0,
        if_full_n => hidden_layer_buf_full_n,
        if_write => ap_channel_done_hidden_layer_buf_15,
        if_dout => hidden_layer_buf_dout,
        if_empty_n => hidden_layer_buf_empty_n,
        if_read => compute_decoder_U0_ap_ready,
        if_num_data_valid => hidden_layer_buf_num_data_valid,
        if_fifo_cap => hidden_layer_buf_fifo_cap);

    hidden_layer_buf_1_U : component tiny_autoencoder_fifo_w16_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => compute_encoder_U0_ap_return_1,
        if_full_n => hidden_layer_buf_1_full_n,
        if_write => ap_channel_done_hidden_layer_buf_15,
        if_dout => hidden_layer_buf_1_dout,
        if_empty_n => hidden_layer_buf_1_empty_n,
        if_read => compute_decoder_U0_ap_ready,
        if_num_data_valid => hidden_layer_buf_1_num_data_valid,
        if_fifo_cap => hidden_layer_buf_1_fifo_cap);

    hidden_layer_buf_2_U : component tiny_autoencoder_fifo_w16_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => compute_encoder_U0_ap_return_2,
        if_full_n => hidden_layer_buf_2_full_n,
        if_write => ap_channel_done_hidden_layer_buf_15,
        if_dout => hidden_layer_buf_2_dout,
        if_empty_n => hidden_layer_buf_2_empty_n,
        if_read => compute_decoder_U0_ap_ready,
        if_num_data_valid => hidden_layer_buf_2_num_data_valid,
        if_fifo_cap => hidden_layer_buf_2_fifo_cap);

    hidden_layer_buf_3_U : component tiny_autoencoder_fifo_w16_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => compute_encoder_U0_ap_return_3,
        if_full_n => hidden_layer_buf_3_full_n,
        if_write => ap_channel_done_hidden_layer_buf_15,
        if_dout => hidden_layer_buf_3_dout,
        if_empty_n => hidden_layer_buf_3_empty_n,
        if_read => compute_decoder_U0_ap_ready,
        if_num_data_valid => hidden_layer_buf_3_num_data_valid,
        if_fifo_cap => hidden_layer_buf_3_fifo_cap);

    hidden_layer_buf_4_U : component tiny_autoencoder_fifo_w16_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => compute_encoder_U0_ap_return_4,
        if_full_n => hidden_layer_buf_4_full_n,
        if_write => ap_channel_done_hidden_layer_buf_15,
        if_dout => hidden_layer_buf_4_dout,
        if_empty_n => hidden_layer_buf_4_empty_n,
        if_read => compute_decoder_U0_ap_ready,
        if_num_data_valid => hidden_layer_buf_4_num_data_valid,
        if_fifo_cap => hidden_layer_buf_4_fifo_cap);

    hidden_layer_buf_5_U : component tiny_autoencoder_fifo_w16_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => compute_encoder_U0_ap_return_5,
        if_full_n => hidden_layer_buf_5_full_n,
        if_write => ap_channel_done_hidden_layer_buf_15,
        if_dout => hidden_layer_buf_5_dout,
        if_empty_n => hidden_layer_buf_5_empty_n,
        if_read => compute_decoder_U0_ap_ready,
        if_num_data_valid => hidden_layer_buf_5_num_data_valid,
        if_fifo_cap => hidden_layer_buf_5_fifo_cap);

    hidden_layer_buf_6_U : component tiny_autoencoder_fifo_w16_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => compute_encoder_U0_ap_return_6,
        if_full_n => hidden_layer_buf_6_full_n,
        if_write => ap_channel_done_hidden_layer_buf_15,
        if_dout => hidden_layer_buf_6_dout,
        if_empty_n => hidden_layer_buf_6_empty_n,
        if_read => compute_decoder_U0_ap_ready,
        if_num_data_valid => hidden_layer_buf_6_num_data_valid,
        if_fifo_cap => hidden_layer_buf_6_fifo_cap);

    hidden_layer_buf_7_U : component tiny_autoencoder_fifo_w16_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => compute_encoder_U0_ap_return_7,
        if_full_n => hidden_layer_buf_7_full_n,
        if_write => ap_channel_done_hidden_layer_buf_15,
        if_dout => hidden_layer_buf_7_dout,
        if_empty_n => hidden_layer_buf_7_empty_n,
        if_read => compute_decoder_U0_ap_ready,
        if_num_data_valid => hidden_layer_buf_7_num_data_valid,
        if_fifo_cap => hidden_layer_buf_7_fifo_cap);

    hidden_layer_buf_8_U : component tiny_autoencoder_fifo_w16_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => compute_encoder_U0_ap_return_8,
        if_full_n => hidden_layer_buf_8_full_n,
        if_write => ap_channel_done_hidden_layer_buf_15,
        if_dout => hidden_layer_buf_8_dout,
        if_empty_n => hidden_layer_buf_8_empty_n,
        if_read => compute_decoder_U0_ap_ready,
        if_num_data_valid => hidden_layer_buf_8_num_data_valid,
        if_fifo_cap => hidden_layer_buf_8_fifo_cap);

    hidden_layer_buf_9_U : component tiny_autoencoder_fifo_w16_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => compute_encoder_U0_ap_return_9,
        if_full_n => hidden_layer_buf_9_full_n,
        if_write => ap_channel_done_hidden_layer_buf_15,
        if_dout => hidden_layer_buf_9_dout,
        if_empty_n => hidden_layer_buf_9_empty_n,
        if_read => compute_decoder_U0_ap_ready,
        if_num_data_valid => hidden_layer_buf_9_num_data_valid,
        if_fifo_cap => hidden_layer_buf_9_fifo_cap);

    hidden_layer_buf_10_U : component tiny_autoencoder_fifo_w16_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => compute_encoder_U0_ap_return_10,
        if_full_n => hidden_layer_buf_10_full_n,
        if_write => ap_channel_done_hidden_layer_buf_15,
        if_dout => hidden_layer_buf_10_dout,
        if_empty_n => hidden_layer_buf_10_empty_n,
        if_read => compute_decoder_U0_ap_ready,
        if_num_data_valid => hidden_layer_buf_10_num_data_valid,
        if_fifo_cap => hidden_layer_buf_10_fifo_cap);

    hidden_layer_buf_11_U : component tiny_autoencoder_fifo_w16_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => compute_encoder_U0_ap_return_11,
        if_full_n => hidden_layer_buf_11_full_n,
        if_write => ap_channel_done_hidden_layer_buf_15,
        if_dout => hidden_layer_buf_11_dout,
        if_empty_n => hidden_layer_buf_11_empty_n,
        if_read => compute_decoder_U0_ap_ready,
        if_num_data_valid => hidden_layer_buf_11_num_data_valid,
        if_fifo_cap => hidden_layer_buf_11_fifo_cap);

    hidden_layer_buf_12_U : component tiny_autoencoder_fifo_w16_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => compute_encoder_U0_ap_return_12,
        if_full_n => hidden_layer_buf_12_full_n,
        if_write => ap_channel_done_hidden_layer_buf_15,
        if_dout => hidden_layer_buf_12_dout,
        if_empty_n => hidden_layer_buf_12_empty_n,
        if_read => compute_decoder_U0_ap_ready,
        if_num_data_valid => hidden_layer_buf_12_num_data_valid,
        if_fifo_cap => hidden_layer_buf_12_fifo_cap);

    hidden_layer_buf_13_U : component tiny_autoencoder_fifo_w16_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => compute_encoder_U0_ap_return_13,
        if_full_n => hidden_layer_buf_13_full_n,
        if_write => ap_channel_done_hidden_layer_buf_15,
        if_dout => hidden_layer_buf_13_dout,
        if_empty_n => hidden_layer_buf_13_empty_n,
        if_read => compute_decoder_U0_ap_ready,
        if_num_data_valid => hidden_layer_buf_13_num_data_valid,
        if_fifo_cap => hidden_layer_buf_13_fifo_cap);

    hidden_layer_buf_14_U : component tiny_autoencoder_fifo_w16_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => compute_encoder_U0_ap_return_14,
        if_full_n => hidden_layer_buf_14_full_n,
        if_write => ap_channel_done_hidden_layer_buf_15,
        if_dout => hidden_layer_buf_14_dout,
        if_empty_n => hidden_layer_buf_14_empty_n,
        if_read => compute_decoder_U0_ap_ready,
        if_num_data_valid => hidden_layer_buf_14_num_data_valid,
        if_fifo_cap => hidden_layer_buf_14_fifo_cap);

    hidden_layer_buf_15_U : component tiny_autoencoder_fifo_w16_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => compute_encoder_U0_ap_return_15,
        if_full_n => hidden_layer_buf_15_full_n,
        if_write => ap_channel_done_hidden_layer_buf_15,
        if_dout => hidden_layer_buf_15_dout,
        if_empty_n => hidden_layer_buf_15_empty_n,
        if_read => compute_decoder_U0_ap_ready,
        if_num_data_valid => hidden_layer_buf_15_num_data_valid,
        if_fifo_cap => hidden_layer_buf_15_fifo_cap);





    ap_sync_reg_channel_write_hidden_layer_buf_15_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_channel_write_hidden_layer_buf_15 <= ap_const_logic_0;
            else
                if (((compute_encoder_U0_ap_done and compute_encoder_U0_ap_continue) = ap_const_logic_1)) then 
                    ap_sync_reg_channel_write_hidden_layer_buf_15 <= ap_const_logic_0;
                else 
                    ap_sync_reg_channel_write_hidden_layer_buf_15 <= ap_sync_channel_write_hidden_layer_buf_15;
                end if; 
            end if;
        end if;
    end process;

    ap_channel_done_hidden_layer_buf_15 <= ((ap_sync_reg_channel_write_hidden_layer_buf_15 xor ap_const_logic_1) and compute_encoder_U0_ap_done);
    ap_done <= compute_decoder_U0_ap_done;
    ap_idle <= ((hidden_layer_buf_empty_n xor ap_const_logic_1) and compute_encoder_U0_ap_idle and compute_decoder_U0_ap_idle);
    ap_ready <= compute_encoder_U0_ap_ready;
    ap_sync_channel_write_hidden_layer_buf_15 <= ((hidden_layer_buf_15_full_n and ap_channel_done_hidden_layer_buf_15) or ap_sync_reg_channel_write_hidden_layer_buf_15);
    compute_decoder_U0_ap_continue <= ap_const_logic_1;
    compute_decoder_U0_ap_start <= hidden_layer_buf_empty_n;
    compute_encoder_U0_ap_continue <= ap_sync_channel_write_hidden_layer_buf_15;
    compute_encoder_U0_ap_start <= ap_start;
    input_data_0_address0 <= compute_encoder_U0_input_data_0_address0;
    input_data_0_address1 <= ap_const_lv3_0;
    input_data_0_ce0 <= compute_encoder_U0_input_data_0_ce0;
    input_data_0_ce1 <= ap_const_logic_0;
    input_data_0_d0 <= ap_const_lv16_0;
    input_data_0_d1 <= ap_const_lv16_0;
    input_data_0_we0 <= ap_const_logic_0;
    input_data_0_we1 <= ap_const_logic_0;
    input_data_1_address0 <= compute_encoder_U0_input_data_1_address0;
    input_data_1_address1 <= ap_const_lv3_0;
    input_data_1_ce0 <= compute_encoder_U0_input_data_1_ce0;
    input_data_1_ce1 <= ap_const_logic_0;
    input_data_1_d0 <= ap_const_lv16_0;
    input_data_1_d1 <= ap_const_lv16_0;
    input_data_1_we0 <= ap_const_logic_0;
    input_data_1_we1 <= ap_const_logic_0;
    input_data_2_address0 <= compute_encoder_U0_input_data_2_address0;
    input_data_2_address1 <= ap_const_lv3_0;
    input_data_2_ce0 <= compute_encoder_U0_input_data_2_ce0;
    input_data_2_ce1 <= ap_const_logic_0;
    input_data_2_d0 <= ap_const_lv16_0;
    input_data_2_d1 <= ap_const_lv16_0;
    input_data_2_we0 <= ap_const_logic_0;
    input_data_2_we1 <= ap_const_logic_0;
    input_data_3_address0 <= compute_encoder_U0_input_data_3_address0;
    input_data_3_address1 <= ap_const_lv3_0;
    input_data_3_ce0 <= compute_encoder_U0_input_data_3_ce0;
    input_data_3_ce1 <= ap_const_logic_0;
    input_data_3_d0 <= ap_const_lv16_0;
    input_data_3_d1 <= ap_const_lv16_0;
    input_data_3_we0 <= ap_const_logic_0;
    input_data_3_we1 <= ap_const_logic_0;
    input_data_4_address0 <= compute_encoder_U0_input_data_4_address0;
    input_data_4_address1 <= ap_const_lv3_0;
    input_data_4_ce0 <= compute_encoder_U0_input_data_4_ce0;
    input_data_4_ce1 <= ap_const_logic_0;
    input_data_4_d0 <= ap_const_lv16_0;
    input_data_4_d1 <= ap_const_lv16_0;
    input_data_4_we0 <= ap_const_logic_0;
    input_data_4_we1 <= ap_const_logic_0;
    input_data_5_address0 <= compute_encoder_U0_input_data_5_address0;
    input_data_5_address1 <= ap_const_lv3_0;
    input_data_5_ce0 <= compute_encoder_U0_input_data_5_ce0;
    input_data_5_ce1 <= ap_const_logic_0;
    input_data_5_d0 <= ap_const_lv16_0;
    input_data_5_d1 <= ap_const_lv16_0;
    input_data_5_we0 <= ap_const_logic_0;
    input_data_5_we1 <= ap_const_logic_0;
    input_data_6_address0 <= compute_encoder_U0_input_data_6_address0;
    input_data_6_address1 <= ap_const_lv3_0;
    input_data_6_ce0 <= compute_encoder_U0_input_data_6_ce0;
    input_data_6_ce1 <= ap_const_logic_0;
    input_data_6_d0 <= ap_const_lv16_0;
    input_data_6_d1 <= ap_const_lv16_0;
    input_data_6_we0 <= ap_const_logic_0;
    input_data_6_we1 <= ap_const_logic_0;
    input_data_7_address0 <= compute_encoder_U0_input_data_7_address0;
    input_data_7_address1 <= ap_const_lv3_0;
    input_data_7_ce0 <= compute_encoder_U0_input_data_7_ce0;
    input_data_7_ce1 <= ap_const_logic_0;
    input_data_7_d0 <= ap_const_lv16_0;
    input_data_7_d1 <= ap_const_lv16_0;
    input_data_7_we0 <= ap_const_logic_0;
    input_data_7_we1 <= ap_const_logic_0;
    output_data_0_address0 <= compute_decoder_U0_output_data_0_address0;
    output_data_0_address1 <= ap_const_lv3_0;
    output_data_0_ce0 <= compute_decoder_U0_output_data_0_ce0;
    output_data_0_ce1 <= ap_const_logic_0;
    output_data_0_d0 <= compute_decoder_U0_output_data_0_d0;
    output_data_0_d1 <= ap_const_lv16_0;
    output_data_0_we0 <= compute_decoder_U0_output_data_0_we0;
    output_data_0_we1 <= ap_const_logic_0;
    output_data_1_address0 <= compute_decoder_U0_output_data_1_address0;
    output_data_1_address1 <= ap_const_lv3_0;
    output_data_1_ce0 <= compute_decoder_U0_output_data_1_ce0;
    output_data_1_ce1 <= ap_const_logic_0;
    output_data_1_d0 <= compute_decoder_U0_output_data_1_d0;
    output_data_1_d1 <= ap_const_lv16_0;
    output_data_1_we0 <= compute_decoder_U0_output_data_1_we0;
    output_data_1_we1 <= ap_const_logic_0;
    output_data_2_address0 <= compute_decoder_U0_output_data_2_address0;
    output_data_2_address1 <= ap_const_lv3_0;
    output_data_2_ce0 <= compute_decoder_U0_output_data_2_ce0;
    output_data_2_ce1 <= ap_const_logic_0;
    output_data_2_d0 <= compute_decoder_U0_output_data_2_d0;
    output_data_2_d1 <= ap_const_lv16_0;
    output_data_2_we0 <= compute_decoder_U0_output_data_2_we0;
    output_data_2_we1 <= ap_const_logic_0;
    output_data_3_address0 <= compute_decoder_U0_output_data_3_address0;
    output_data_3_address1 <= ap_const_lv3_0;
    output_data_3_ce0 <= compute_decoder_U0_output_data_3_ce0;
    output_data_3_ce1 <= ap_const_logic_0;
    output_data_3_d0 <= compute_decoder_U0_output_data_3_d0;
    output_data_3_d1 <= ap_const_lv16_0;
    output_data_3_we0 <= compute_decoder_U0_output_data_3_we0;
    output_data_3_we1 <= ap_const_logic_0;
    output_data_4_address0 <= compute_decoder_U0_output_data_4_address0;
    output_data_4_address1 <= ap_const_lv3_0;
    output_data_4_ce0 <= compute_decoder_U0_output_data_4_ce0;
    output_data_4_ce1 <= ap_const_logic_0;
    output_data_4_d0 <= compute_decoder_U0_output_data_4_d0;
    output_data_4_d1 <= ap_const_lv16_0;
    output_data_4_we0 <= compute_decoder_U0_output_data_4_we0;
    output_data_4_we1 <= ap_const_logic_0;
    output_data_5_address0 <= compute_decoder_U0_output_data_5_address0;
    output_data_5_address1 <= ap_const_lv3_0;
    output_data_5_ce0 <= compute_decoder_U0_output_data_5_ce0;
    output_data_5_ce1 <= ap_const_logic_0;
    output_data_5_d0 <= compute_decoder_U0_output_data_5_d0;
    output_data_5_d1 <= ap_const_lv16_0;
    output_data_5_we0 <= compute_decoder_U0_output_data_5_we0;
    output_data_5_we1 <= ap_const_logic_0;
    output_data_6_address0 <= compute_decoder_U0_output_data_6_address0;
    output_data_6_address1 <= ap_const_lv3_0;
    output_data_6_ce0 <= compute_decoder_U0_output_data_6_ce0;
    output_data_6_ce1 <= ap_const_logic_0;
    output_data_6_d0 <= compute_decoder_U0_output_data_6_d0;
    output_data_6_d1 <= ap_const_lv16_0;
    output_data_6_we0 <= compute_decoder_U0_output_data_6_we0;
    output_data_6_we1 <= ap_const_logic_0;
    output_data_7_address0 <= compute_decoder_U0_output_data_7_address0;
    output_data_7_address1 <= ap_const_lv3_0;
    output_data_7_ce0 <= compute_decoder_U0_output_data_7_ce0;
    output_data_7_ce1 <= ap_const_logic_0;
    output_data_7_d0 <= compute_decoder_U0_output_data_7_d0;
    output_data_7_d1 <= ap_const_lv16_0;
    output_data_7_we0 <= compute_decoder_U0_output_data_7_we0;
    output_data_7_we1 <= ap_const_logic_0;
end behav;
